---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  values:
    controllers:
      open-webui:
        containers:
          app:
            env:
              ENABLE_OLLAMA_API: 'false'
              OLLAMA_BASE_URL: null
              ENABLE_OPENAI_API: 'true'
              OPENAI_API_BASE_URL: http://litellm.ai.svc.cluster.local:4000/v1
              OPENAI_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: cluster-open-webui-litellm-secrets
                    key: OPENAI_API_KEY
              DEFAULT_MODELS: qwen3-local
              RAG_EMBEDDING_ENGINE: openai
              RAG_EMBEDDING_MODEL: qwen3-embedding-0.6b
              RAG_EMBEDDING_BATCH_SIZE: '4'
              RAG_OPENAI_API_BASE_URL: http://litellm.ai.svc.cluster.local:4000/v1
              RAG_OPENAI_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: cluster-open-webui-litellm-secrets
                    key: OPENAI_API_KEY
              ENABLE_WEBSOCKET_SUPPORT: 'true'
              WEBSOCKET_REDIS_URL: redis://dragonfly.storage.svc.cluster.local:6379/4
