apiVersion: v1
kind: Secret
metadata:
  name: cluster-vaultwarden-secrets
  namespace: default
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:Jzmu3AZSbP/BUfbfT7FXEuyOX0A71frQZZeVVDO2p1Q0bvPDE+pUS3TxuLHDq+rQ9f2C/O2fQCae0moe40fWC5kZ75y1621ouDcPZ5hLu5/B6l4rBFR4fzVHGGNHTPNFLMaWNSSMjfsj,iv:oxt2KWv3NSkTao98n92WsB8srccZ42F37p5QiXoKY7g=,tag:P5AxiG8Di4NJiVbmu5HGwA==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:lW+Fp6YQcG0UEyBL4KvoonffGTrxdmxiox+Y7NnJx7NunJWVZQfQPPyuWhPeYLOd+IQJZkEENQS9NFQhLU1xzGXJ66Uy3UWDCKkEqaH+4gzafqUOh7oCclpK0FUCG9N0z4wPEh+kgRcnzmHCwmac3P318Fxw4lvpbEsBpqjNySRmMyizq2o=,iv:fzEAUnxV4LzczOyPxGAf9KzJzCpTjBSYlMMY7P0Xy3k=,tag:q912o/32jrAVAwp4PFFuLQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:1xEguRwtEcogQqU=,iv:BCeI6rvUNV7tC0l9+bCCkB5DRN6kNMrz1F5kmrDXjV4=,tag:gDtlv68ifAUCT1AibS/gGQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:QpHEKkkzjkkIxxtvGmk6NWCAKKSRsnjIUA3+xb9W4Y+Izrfxbg==,iv:RoSsi1lgqVzXwLXKnKKDZ0xLt9r0MfnVZAXFSPva3I4=,tag:THCAxZMeAR62VrNEFIN0Rg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:zwv4wYXlK3ey7mw=,iv:c6RxLjlHZTsPLGOMnO6btLqeLdBn6vzrcx8ama0ZfQY=,tag:/+lxd3zK/DV9EwMT7dZeZg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:YeG0Qfs5S+YHGo6+zsVaE2pxpWWd9eY7aQ==,iv:sJzr5a/F5IZKtpPoWDWtrNYE0aUGjHfFnqBOCqqi2IE=,tag:/nwnO168Gtuj+R4rHoqHaA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:MFwBauojeJ32mz4QpBpc1Q==,iv:5dLZ1UbXTzkTot34IzzPACT31PMhRiPo8Bl7CIIT7UU=,tag:bukRbL+nbn2u/zwSfQhA4w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSDVpUzU2YkRNampCZEhX
        LytQZ094dXpnbTdQTEM3b2w2NVhBU2xOWTJVCjRnVjZDYXdncDZEaWJCZkdybWtD
        V2hzcXc4SDNNM2VJSFZYT3dqWTRISk0KLS0tIEhycXkwT0Q0ZmZDbVIrcDRnQnlS
        NENFaGZZdG5TYm1ZNXkxaGxKajNDRnMK+VwvoXoOZQd38F+7MmFnvikLw/waIXhY
        9s5cwQKUht2sIMoIWLG1LBaAEW5+6OVBzN23cwS1NSkYbfo36OuWAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T16:53:42Z"
  mac: ENC[AES256_GCM,data:QqJCRZVMvFHcJcaluH6BWgxxKPAOUJv9tjsAT5srN5jdu4nidJUqXG93/Xpn1boprs282Iz/3EWdgCTvT/WNgwATMh0OFTDxkMpqcCeo6zMSPCBT0QtWvDB2hYWrCd96hWVOkK6kkTLCk2xgLYKkYFttSpw6UFtcHesRq5iLUoM=,iv:lMA5JQQGu+m8nnaUDQbn3JBPqc5Lc1TgP8WniUm53Uc=,tag:pxYbFu5aGQ7g7XK7/eu12A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
