apiVersion: v1
kind: Secret
metadata:
  name: cluster-vaultwarden-secrets
  namespace: default
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:t+Zc4BUUrpOhcmCX+L4LHJSU2VJ51EEH8oPFPUjx/gWrIal65YP31KObjhjwunLHZVQHtNhX+15qev9G2nZd85ndrhGEOYuFsR3/LipJRb4ryMdvSkcWm4OSO5dlMUL7vtZQFI1U+e5E,iv:UW/O7xKsOwnzP1unvx4UeWqA9NzAkzMpEv8solBRUsE=,tag:QC1o3KceW6I1oX83SANBvQ==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:of1hi0I+BcHKSAtEPTn2JXhfLd0qJUEskqRZVts3tX2vlYJ9EBkVvqHMfPcdQ2NhTSeYU747Cw2mm+YLZcHkpHL8sMClRHVpXmxH/eSH0NLbx4wF19xTk4OnMW8ILdXTYjg3dUxwmQMLN4qAr4Nqqk1M2ySH6hPaJjCbmjwMQaIc+Fkyzms=,iv:1aW1OMbKZw/LFkKbFsTwaiLUV0wCPMKw1KhgrXlT4mc=,tag:fjqKvqEP6PkJzMGxKG2BSA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bnpHCsbb4EzesC8=,iv:wo7hhqtrQmgFydLApltfvGrVVeMbwAZzvfMNmub+tow=,tag:tcU3D2IyV2RhGEjE2kqE4A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:MpvOhV+nXKkYo6r7HrFlqniTXgYBFYIvfeQZ0eQ/fximDdjrWg==,iv:6kXs37haBLy4bNrv2O5k+pm+eIkZeCUKwFS8yiSHS8M=,tag:pk2TzpZH3WxbWo2lc7K0BA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:wgPSoJcKR3Z0GE4=,iv:bfh+4As1tX2cgZFIHQ2VKxpeZ/P9yrGH5VAW+a1vLUc=,tag:tB63C9GmrKR1elJZlNoccw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:VHMPOwdSCGUYqF1JVDg/TTTGSoMw/mbbiQ==,iv:jxr4PEUzrGzkS376MGSpS/irLlmNIG0YLfvY00sFtGk=,tag:1n47HK7BQU8otHOrbLTXkg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:yIza7PRMiOBF/lyjKfBqlw==,iv:TYwzbTcAU/bTcw9FFOy+zXNjvIuSeft925gcicsXpjY=,tag:D49kCg34sUovrpasdVP+wQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdmpkSDdaQU5uZ3c0MHc4
        VzMwVkx1eVhMdnU0eE5aU3FiZndhcDRnc0FnCnI5Ky90Z3RvNS9oQ3l4eEFJUVVn
        c2tPSTVhUzBCKzJWUmRKTkJobkxCdGMKLS0tIEllcG5MTEFhcEE4d29DTFRndVl6
        Qk9BbHV3UlJiMGFlekEzeGZKaGxFcDgKCza1VL0mAyJLAf6DHfzVMp1oe7HMur3R
        UeqKuVQqMxgHRqdzaw1X+csITF34UI4Bc40Th+dymzAlWO00zQbjBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:42:48Z"
  mac: ENC[AES256_GCM,data:jiUP0XEH6KFoen+QXmwhF2hm2qifuE1mat3GtBLlKhceX8eL//wqzxW1TaMcGFoa3EaynnPU1cxewC3IyWA1q8oO2Mv1f9kOv4hQxxRtWKt+WfAqWJXaAUXyKlU0kw9SSf8LKTwZKlivLv4fFSqnhZlJGoNDlgxeXyH/YTP8W7E=,iv:cY5VbZ6yUg3dI/CnATHOgMBwhaOwJozC3L9WQdFt1YQ=,tag:P8aaOJNlRtVV3OMkag8gBA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
