apiVersion: v1
kind: Secret
metadata:
  name: cluster-vaultwarden-secrets
  namespace: default
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:PpK1i6EF44sdEAkZyWFmhDFqMeHtJYoCXfhupWXWqb0O30cV65mmfH9wp+typHXCjFaVG7qBhYYxsW8rpJAPaYPu6ttD6Mpck0RDhnav/W+OdmFMbFaCNch900svfjusxxEOCllUoLxN,iv:wJZATP0g6YDVO4fxNN8IeKlL2gswce/lQ8jdb98UYSE=,tag:8Qd79sHEEGsDH1lOrr2Luw==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:UmIJGDCnbsIGsaWZ02axusBARV3YQGFFwcgLRMVuzuDSfmV263qH228SJL1GaVjupmLi/C/UmTtgKyshCKrIoZETi0gREqBUU31hxnF0AOXw/fX13U2hJpQF3t1S9OrR1UZHWCkCyURCWqBTKTAXcGYoQxWSz736nByff4BzEODW0ZUd4U4=,iv:FsgUsaSPlzoL/QmrEq9thBJh+ZTBgfTWRQMTG5OQ+jc=,tag:I29D6bxna0MamMu2PmJPUg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:nd00hoSoxcpOGuQ=,iv:YBJk8zd+vkEy0DdELv2kGIXx1lePDOrnAzlclZuF8U8=,tag:kh6yOrirp71rcG05+GWpgw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Ft+jqLAhOzTyE0Vx1uW4/WK3Fp+bfSS4LJSOByARwK9jIw23mQ==,iv:sW1Gn3fVWV9k+gkENd+RHa5felXt51k+X3eRX40BhnM=,tag:pSMN+6s5M7iL526FHAhRvw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:8T8o1hlk8ofDrTw=,iv:gsK8E/qyh/j38FCD7w8P4S+YCC0Ogf+HKFLZwDe0Ono=,tag:MTlKTW2s5dGwmDuF2pPUSQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FGHLjJP51Xu3krZsD5P1QKAX+Lhh7MLGWg==,iv:PDNDn5wHwxeHUpKUrAI3JD1zsULHBnWOQ0WdV8gEZnE=,tag:WH91vcrHOmqKdFcEFCBKRg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:yEwL1U44w9/zlW8YMCpUBA==,iv:TSZS7thRelyW59bz381/CrbkCMTom6gh7q2Ct+Y9A5Q=,tag:OT4nkdKo/FACidLCkccPJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRHpCWnpmY1ArRTRoRlJ4
        QzZUWStMay9ZQjdRYjY1eXkwY3RDM05pb0FJCm44WGVjT2o1a294dVVaQW5lQThC
        dzZ4YmNwbVN6ODlRMHRRVTh5NmdMUFEKLS0tIFFKem1vb1llQmxtVVhFMDhDSE11
        VG1IOTZBTmdodm82bnFSTTBVMUFLR1EKS9uqwcyt9k+tufmPZX0SIA6SttvvAru5
        0opXKoslaBr6jOdriN/VbrZSG8wj0VM6JApd5OkqkYBVQNFr0T5hTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T09:43:48Z"
  mac: ENC[AES256_GCM,data:VayqV/M36WGv5HUKrqkv+5qUx8bh2HroCPnw4JFRmsihOGce3twpidJwNbkgcmbEZWolnMBW+MSof2FQsMlBSTU26kJ3PxBFkHKld9nJq9CbAod3VfmQLysspdiHLC1jvSHVn9EZ8KHbyEnD7WyqnmdINmTQ/wRqxGOvCq8zzdc=,iv:m8SN+ZH3jsuzJMMSH8YVUgILCz50lWtKXMFu4t48p1Y=,tag:9upSvvfW5tYg/8v8t1qF9w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
