apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: storage
stringData:
  config_local.py: ENC[AES256_GCM,data:4PpUcJ52lB0aZx/gfoP5cSsk84BIkeQbmF2pj6GbloTgNN/wz+zBQunglE/KccaDD9azx3I28JSJTOKTVmt0PJ+EoQz8jAwT7YXaGOlvg1vEnv/9HtzbRE/nZMJS5rQi33lyIaIbXP9dsJrn7erFkz2NVCrkOVNaTC4X6boSb64Eid8laTINNA7n/BIudcce9e3cODLZTSesdghY8UIbaV9MpV8FyizuRohlOveP/omVHo1duCfmxQp3jdD57qQDdlhmSBJZUd+Z+W30E+Eqp5dw/DkmfL7OmiOEuWUHEhH1D+/4RvwHRwINmzbUIBYjHoJR6uSV6a1wQOa5D1WomEzBA9qBJ5GgiQDuv5Gyxg6ngIJ/yqSJ1q5XsmMIPGcQFMJJtBUGa6Gg9h6ykWFPBpBZ7QFa2pLQc9iO83P6UkdtaeL02Bgj1DO7qZ/CZV56tWzH5SbgpnDz0+eV5Aq09xs5l20LJvPPceAAjZf/DxWAjJ+8m0bZa9V0oWQTk5FTSCqGERWfhsi7i8p4jBc9Oz5NVUv+pTjTgLMre3tN76Mt+JTsPzkkadJ+HDhJhblxntXrLvzlB1uWwBC2o+xm1rhKVnqzomaGpIPB5KmaRGPkC+hc3su0FSXzujhs32txh39W/b3CQkQJqivpf+gucG1tmlmV4qfSTNgA0k4P5KeitlyFcYpFnaHPMO8clCR+qzXIwVixZZ+JKZvTDF+SJikW4Hw2SWfveRf81ErQ7IlHGY4ZdZyZ2WVvQ7jj33+9EXbfkWaMdkaNn86hY6RAiVGTSrHzD9dmcicXIThB2PbLfI+RAm0xbwMoUO9O98OfGbMYeEiJxOjYEXAse/dj1Jsj6i1gju+oAw9CHBpx4jKWJtI8SnrwVppMY2+GsHMSEqLwhhTkU2MnL1U1UAqqcRd29oNpNhOe/XXpa+Trkkgd1PnrAXDBA08jGoeDU4INAQ==,iv:ebgdBlcdGbO5rPPcazvmq8+vwsdeIv++riDURsUWkv4=,tag:VQy/9Zfdvc66fzmvioSN3w==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVExYUzM4SXZkd1RZNldK
        QTMxV3lMcEVhb3RCMGh5L0hIRnBoS0ZOMFJrCnZCMWtmUW0zejRsTnFSQStzM3Fi
        ZHMvYmRKU2xEV29oMFkraktJR0o1UXcKLS0tIFNDM2M3ME1LWXptMUEybFNhNEhR
        aVRXdFNCa290RXlmeERKSk1tOUNGdWMKHw6/9Emt+jfoJEka3i/ey2J69/Db/GP1
        FifZ41Ai5c4EjFCZRWbo+BXnDvsjXhY6Zw93RWKaGrpWPDMM0XfOFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T18:14:18Z"
  mac: ENC[AES256_GCM,data:k/QgDVwZPrrEt7XpeH9+a8++gzg9NOgEiQGji/3wKlzRiQz2+s0yJuHipKBKUPVSLeG5pg8aTVOccnQjLkxPnUVGAl6e6sj+TgPUnc0gx8UkQmvBK+5Onn6dOcg9amQfYsLP2RtweJ+KPj0RydIWfsfwpmYjSOGM0J/oTjKSjXU=,iv:XFdPmLwcSyqVvNjiSdvIQKCKkEZpmKHre4vzy8eKlT8=,tag:7mhgIAQZIhVxcnV/9uPygA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
