apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: storage
stringData:
  config_local.py: ENC[AES256_GCM,data:6Er0azgsu4LwkTcNq8a2N61OAIYP1h2elRX2ijTZgsiodmE1Pp69ChoKpWlLvPUqcgDP8oZlnGa+cQ+oL+sUsWgYMTSO5ckPGf/nr+C1+FKEUdrTPGcvKsxm0V25hselJcEVUO8PLAyMs6sR59idXFK07cmzyc/uh16lbVzl+t1CS2IEn7Rh9el/O005GjtOM7wQgS9HBOsvEe06tgGdwflgf2EUPCYLsrVxNxljDSMYlSoFLUdlNEXuLniHwExikrxIFWi/2KIFoTlNiS9usvGOxiHqQts9XaGFmLD7EtzGwc5U2ZviGgn0+YOZbnU+VuLOCAkHlb7iGzVgjBtHT5S+gtZ0ebXgaDZKoOgM0U5wNCNEYsTt28keLo5LcCJochhTPCW7U9GRBUi+48y8L/DxRvbeir0BGr4GGfeejctlKtL3RYCf+Rrnhz6B2RgyWSmvoLD3fuwiFJC5lhgJ3sI181ymz/x40P2SoJ+bJFXv5NI8ZeUJ8q45uCgeLZJLJ+Cq3oEWN+9sEcXFbTdrAUg5fK9frqpRwc+bglRcMo7sIVBXgaBLKk4RSAbbNa2O9PHxnkDqMWEJZotC7BF3ipUrwQ0IRBJ4APnA3WPYym8mznVyVnAz7J1ztGlZix6sQp+/6nfcq4dAIEzImn5km+9fN8SSLUiZYV2dNBCPJPJe4ETNA1pB5rsuD+3iVOLWXPHn4N6S3TN47wORyzWjfu3VIhM72zd9Ec8USrTu/S5LmFwcitJNI4udCZoW5vsZrEBwS3BD+TcXfpD1pwc5iK896/awENXqY6dPsLScPXQ/Ps+a3LGAeBoMiXUjzf7XaMB2C+0NegL/5ajCfC4DVCXJzTH6GJZAGBpSvnqemj3iMreDLGLGqAgI9dYJZjtetMrrXuifKwL6wiSs/UhCj9P7PzVcgIrLudXqIRvgm8vGdgY9dzLoOg2EzyzfS0hUOQ==,iv:tNqgpPk6HHPDQvk4WXkZ9UwPuF/zRItuJ9vyfec2K40=,tag:VoS+mt/yUkWdCDIUtuiYRg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybHptNGtZR2xHamsvNDNG
        MHptVnRkdUpBQ3BOYzVTV1JXTDdDK0ZJMGowClVNaWdMVXJrV1Y3QzQ2aEVsRURS
        L3VMa2lEenJNKytmNzJ2dmpGamlpODAKLS0tIHlXSHV1aGZ4MkRNd05FKzNKRE5s
        empjRGpQcUV0WFo2a2cxY3Q2VjFyTjQKCrrIQYudzg+AQ2YxCgOPGBa2pz3g/A1A
        D/auDgIXLylWRgqwMleQfifaU95g++fsOO2VAK7ctERdSm4gWpmRoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T13:04:59Z"
  mac: ENC[AES256_GCM,data:Ejjd9oHG3JbpWunnTXWRKTHMOikPLJ4yP6+XiN/BP2Hdo+vnUHGSUIaz16gQm4kKmAGHLVWFzP0kGY+6NqxkQSgZxQzHzG8Hi5zgsPvftmv5be3EXS1xuga+ykPIYi6Uv0/HYV3HNO0oiu1rZVpIt+cTm3WA0vrf8N2i9Vuew0w=,iv:pvmv5ZBb6wwG3VmvH2ketSj/ghPdLfBFz0zvGoB0ECw=,tag:LLS5nwti2xu0nScf4GQwmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
