apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: storage
stringData:
  config_local.py: ENC[AES256_GCM,data:XOxKYgbkIjxVQuNwxNwg6Yyvfo5EMZVKgSHMK/7EE0mUcSrH54uOdb6iTE8pDOg9OhJGjv4bWII2gzFIAV7iYYgYKwdjFFyLB87M6PfD1wqALZDFNQIjJ2Ad0qi4zkIySlVt7YuyCGKluEqAvkxJ4fIxgToBl2qcHEE/sTWvkOncG6cK2VLwadV71iXX2QPwVIO/PgumhXLc+wYaRL6bXlXmU13juP0Lmd57Qykq7Aw/8HCO9xuOazQdH5OQRBx2sBh8NCvPlaEumJybFL3Hu+DFtCD8Wjk2QkmTEvVRGSLgqY6IK1ULBLbw6GkKRgXp1HmaFFNgk9SMivqvwiKb1dFrc8lgekKBklmn+yQ6O3aD6uLGbMj6inPan5VPkTRu/4wlmi2QjP/QtNKtGBubKkmTq/3WvcE/gl1j0W3kwRHZvCM5Pc9YBCjOJR5JXW3oVctCnEBfRwYPrq2fueVYqaujxKHKZxFnYlZNFI89BO10gvGN4+j+WUeG7KFDEaP40xNKMFzGSFrxnu2dB84+GH/MM95Z7QlbYJmNG13RrifmdiEG0BKT94JV0/wWUQBvGs20sDI0jsSa0BEyk+mA3jtbT18PfXkKuIvt4LX+mKtZLTvUNLAM37Dlutp7wTeO6LDvYQCuakaLGtk5bzutcjitaT1EvAVRdQIle8MiErpss3WcS1+ifjHCvzkBLpYPQzfYng7DiCrgwktFpe0x1rn0Q0bYrqVJKXcVqZS1Y5R1mHg9BDSy8bIj2lb7n910l6unAN5vOgC1zP0CqU9n/GFLRDrncosKbv6MEaGT57+FQjbdCLk16joGiI+Yrxp88Vv4Zl2CbdWE5h3LZyo5OjFz77y7r8bleS/45UM6b9t7QJCwtHgivbZwDjbgaKqjWurMUDbftDJLuLb7z0a1xdjkXyw6dxc58M+rqpL1kC8lE1m75zI1ThOl4bwh8B9q2Q==,iv:et+mLOKIMukbWwikAc24L3rHnp5o4cxdod6LS4ZkjOI=,tag:hBFC3ub/nRJMr3t5VD0JEQ==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQjVPTFVDeGVYYUhaTWFG
        UExsT1NJVWtwd1huR25HK3I2OUd1VkJ1SkZFCnlybHM4WE8yc3ZyYVA3N0RDSk5a
        WU9BUFRtMndQR2l0N1ZjSDVsR21waEkKLS0tIE5RMSttZnY2TVVVanpOU3FFeWtD
        Wnd2c2lEek1RYnp5eHZTMjVLT1pQdDAKq7y7ghx+nQQVsjR3kPkWBTWDaeG2OOLm
        vtWiec6lJFUvf8ZxKXCRTOQGy6mYMRoHRH8dShkyYmZWyRjwvLk3ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T00:22:01Z"
  mac: ENC[AES256_GCM,data:z5Gb0iq1ZH4ZxZAb48HU5oAe30ZKun8mtgJIsLKyU/kbbRwuM5JrrslCO2Q2/TT34oN9Bx7peGaDkr/N6wB2+T2In2rTWrvHzvvUmVmhi5hg+qEl1m3vii+5yTeezbn6EE13FABbem865jXXgTCgAKu5+kohLq30OfAyD/XWOIg=,iv:irRMHJXTa5246jnUZFnN6M/DYyxRX/MEMZq5ne9Kok0=,tag:ztkASjuc5SxgEOx4JPtbIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
