# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-litellm-secrets
  namespace: ai
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:Udn0jCuP1Q==,iv:oyI9oiZhbRwkqK02EHtPlJiIq500m6u351gqIKy3JVA=,tag:6g4eEbKQxQUy6r4e5kQzoA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:CWf0e4qP5Osx21Y4XqaYBRTO5jKGJlkGY2ajOqGdt6KP5E1kjkajvLTfHAJV2pktqy3voG6rscMLnqCR79OY2g==,iv:Ur7KjBwdD+DRw+Hj2FTR1PxsCCvJsipS4vsIL6hUkOc=,tag:/1qFCPMn40ylqkPQpUg82w==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:MxoikjzwKQ5Utj4nzvy+cAFc3qPEo6iBhghNAmbJJ8ikCpo704RcXu1Es9+RhLvZWIFayc84tPtKr7vqhgk5cezoF7Q9DgyqLc7HZDgfgHKLkDlHyvriCyvOocLMw+7uel6Rvu46aZic09bll0kSr1QSRV8T7FSOrC/OF3u9368uBOG+FKPghg==,iv:UEetkF+G4gO/lbHCwKz8jc6e/ldjxhQve+nhOsNW+VM=,tag:ZgCgpNFNT1Y+mNpuB8uDQQ==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:cA0U8dXZjtTXqvf+/7i3qZY18ExIZkqGPVoBpp94rQHufiJFOZVPG+tdICs5O5jkcgtoIlTr59upLXbmZDtgvfegNg==,iv:+deYPoVkERC7u7EiG41wL/nEl5FnOLhuHsmtCj0MGcU=,tag:ssIb5g+wm8JyThdaywRYzw==,type:str]
  LITELLM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:2v2SxNYP/AjTczT7l43bjG9I26H6ML3FNnxIcCC5khFmYQW3v0B+WPBGCGF2Fx+Z5tHZNmB5WdV5NjQ4t/92Ew==,iv:D4oluOrjCfhRjhZSHjSXEo1cWQFEofJIweYsx/1UWPc=,tag:FwFHH4aZcEN66dnrQuDoBg==,type:str]
  PROXY_ADMIN_ID: ENC[AES256_GCM,data:cVGbUW6NgMTUcKsv9w2Tp16c0A==,iv:ADUOo8WNt8qyABUV152lIseda6JIGe7W3FB7iD13sRs=,tag:Rib6BN4u4KiDJxCXuw+f/w==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:/Mm05gF4UguhLmWYAE4js4SyMteDtkOOsLd30irSjBhcFGCeZbPyUwF3YoUl4V0NL3OwL/bLnMU3zPJdvyGpBpsihqiyk4JETyorT75mwKvWn08/lWMJ102awk+RUXYfZBbyQ2y9AG7ktvOQpaF8/1zI2fiDcYEECA+tC+UdnoIWZALHnakWhqyYU5qygMxEldLor4Pz5Kf6mf8jmIhPQI1isHw=,iv:a431hqQzg+tNBtBLTwfvKtmdzF1YFvZ1kjG1Z9GKFPE=,tag:ZYbxi4+qpzde8dfAi4H+mA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS3hsQ0RPWVM0QmNtd1M1
        TTRhNFZDQnY3NDMzZEdwa0RuV2EyenlyTVY4CitCbXF2SWo1akdQRnlpMUtRbVU5
        TUF5SExkUmRrZGRHbjhMUitnVkg5cVUKLS0tIFpISjJtRWp3eWhicXB5SmZSdW1y
        Q3MwZFRvYW81SmIvczFkN2U3bytQbEUKE1twyuebQF4yPIYorEywQRHagtyOQfO1
        PIQ5DFWW9op/KGnjXN+qTc6fRgDvM9piPYq4l1AzC1IbayGizQkNgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T23:16:42Z"
  mac: ENC[AES256_GCM,data:YRsWc+ObuK7+SL4AJkkbfQFugP+h2EWJo9lza7dQwEJpqVye52xh8FfShiWqi9+hbUIOjTtwU7tNK48S+w8MPI55xkuBSVgEtgZmoYK7KLRJlMHzUpTLAF/XQXSAhpr9cgLgxltIRIcqEC31KBGkAE/uULdk/O4aScPwio0rg9A=,iv:hTVunm0Jg1O61gjL4n8I8HsLZgRiPqrJ8b0HF1y15cQ=,tag:D+iy5iySTNvE4iLcQxeZ4w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
