---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      tdarr:
        containers:
          app:
            image:
              repository: haveagitgat/tdarr
              tag: 2.80.01@sha256:43e0808409011a14a0f8c89d649ef9caebf0a1e7120624ba6d9dbad517f53d98
            env:
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
              serverBindIP: true
              serverIP: 0.0.0.0
              serverPort: &serverPort 8266
              webUIPort: &port 8265
              internalNode: "true"
              inContainer: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
      server:
        controller: *app
        ports:
          server:
            port: *serverPort

    route:
      main:
        hostnames:
          - "tdarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
          enabled: true
          existingClaim: tdarr-jericho
          globalMounts:
            - subPath: tdarr

      movies:
        enabled: true
        existingClaim: tdarr-lordcommander
        globalMounts:
          - path: /mnt/storage/video/movies
            subPath: movies
      tv:
        enabled: true
        existingClaim: tdarr-lordcommander
        globalMounts:
          - path: /mnt/storage/video/tv
            subPath: series
      shared:
        enabled: true
        existingClaim: tdarr-lordcommander
        globalMounts:
          - path: /mnt/cache
            subPath: .tdarr
