---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      frigate:
        annotations:
          configmap.reloader.stakater.com/reload: frigate-config
        pod:
          resourceClaims:
           - name: gpu
             resourceClaimTemplateName: frigate
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.17.1@sha256:1724960349dad0bd2ae8ec884171a6fd5755a4dc242a0e66cadbda9c0e85c99b
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 120
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 4Gi
                squat.ai/coral: 1
              claims:
                - name: gpu
    service:
      app:
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "Home Automation"
          hajimari.io/icon: "streamline-cyber:origami-paper-bird"
          hajimari.io/appName: "Frigate NVR"
        hosts:
          - host: frigate.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: nfs
        server: ${NFS_SERVER}
        path: /volume1/apps/home-automation
        globalMounts:
          - path: /data
            subPath: frigate
      config:
        type: configMap
        name: frigate-config
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /tmp/cache
      shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /dev/shm
      usb:
        type: hostPath
        hostPath: /dev/bus/usb
        globalMounts:
          - path: /dev/bus/usb
            readOnly: false
      media:
        type: nfs
        server: ${NFS_SERVER}
        path: /volume1/media/cameras
        globalMounts:
          - path: /media/frigate