apiVersion: v1
kind: Secret
metadata:
  name: cluster-vscode-secrets
  namespace: default
stringData:
  OPENAI_API_KEY: null
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcU5ZRk9yd1E0SG9LaGk1
        VHMwS2J5NkZuaU1XQnpnTUlJeHg1cDVhTndBCmZ4elFUdWczZlVKTGdjbk5ENXdX
        VnJ4WGY5dVh6SGZJcFJDYWxvV2JyYWsKLS0tIFRPR1BLeXUrQ3RIZlBzZUFSK3RO
        VkVKRkVkZmZEaEFLY0QwU2tpNnYvNlUKGVDF7SsKG3eiFaTZJwORZrsXJMK9j1z/
        7F6JGQzNAvuNWhMhQprqt3dCJB1sLt7MpROujCTHYwzlg/Dlmk5nEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T22:04:49Z"
  mac: ENC[AES256_GCM,data:GxtK6LPUOszkW1+Nk2gKiAjkevJyILi63+Dd+c9MqpeGX4+C6Nh91i0UDRsrSIWZg0Sewu9CXlEC3CHw4zDGAbqbWSybXcycE68Hl9uzKjBrlTLn5rBbobLHaFPdHtyMjfTMWdqr/gHiom4OjEoZdPJ3kBTnU/a2qbqHRQlriFo=,iv:eazn8GfzAvODgzvohiEph94aoR1Aid6mQqRtqWV6Ahc=,tag:j+5/9t7I24nHMMTUi5Zeag==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
