apiVersion: v1
kind: Secret
metadata:
  name: cluster-vscode-secrets
  namespace: default
stringData:
  OPENAI_API_KEY: null
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMDM2bjBudkxjdFF5UWll
        cE5TUFdvYU03cHZlY3dIRFllQURxYS9pT0JJCnpMcG1JTE5XUGNTWWhtbjdXYzFP
        N3ZseUtUYUJvRzZiQi9mOUY5TFRtUmMKLS0tIFRJdDBSMkN4cnA3VGN3SjE5TEJS
        dEppV1dJOTNJbG9KYnFjOGNwVGFmcUEKN5+mtB/7NP9OovX7yxNMhNh3RfiQvZU/
        BWuBKLyg/6oLu4h6A9EsdKz4oV6g1LF10H+UQU0w3B4Lg8a1FORzHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T11:15:43Z"
  mac: ENC[AES256_GCM,data:Pg3ijYyQ6qazCSpvyciV0yPRQugucP7HofItgPaeMHS8fIT/6YbZKBxZTbjfyPlmtOwjFeDYPY5OaItEFLy8cx0DQfTBYG2I1YQDwQGFX3kCQP3fG49etvxUPLtJzNbUECORzoWHL2CAxj6JPL2OuY0ZxovB4lB42alr3JFVDzg=,iv:vb0PPI+yYKC3R/t6TvpPeUyhik/NzcwV3H6zFqmjTWg=,tag:cM/JkO+GCkhIO7Rf9HmNVA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
