apiVersion: v1
kind: Secret
metadata:
  name: cluster-vscode-secrets
  namespace: default
stringData:
  OPENAI_API_KEY: null
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeGpIZXU4ekRNa1NZdSs1
        cVFyeS9Wd3V1WDJWZkJobnRJRXlmS09jWXc4ClZHR1l6ZWRTUnZ1cEYza1V5WVBq
        UGtsbTltMUJQSldnWkk0REZoYWw2UVEKLS0tIHNDTU9wOEdSbVN2OEkyQXVmdFZB
        RG13dlJpdFZ3MmZuWEpXcVNEK1RWaWsK0yz8IbBnj2MHe+Zo9HciL2mHYAuJ2f71
        pckjlayoQ7ce3uxuZMhjQtL1bjctyEldXQfYNqn5dONyqgYXe5OI4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T23:45:56Z"
  mac: ENC[AES256_GCM,data:+rerkLcUxCzZ5GtcI7ejcYxBwxaGHi+6Uz4apGyfR345ZxZDgIwW0LzKxXtHuIGwVdK2BMDwYylEwuwiFajEon7/iBJKhaEQpJrNefz/eT4F6YbesThtNX6osErlxAJ4/TTIpH287YQk5WJ7UmPv3hKSKOlo8u9w+8pc11JyU0o=,iv:TntAYQPfi9G1R6AKaNyL/SSIIUNpKUIjK9bdTPx6aaw=,tag:z6KfxjD3jnuRPYtKGDCigA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
