---
auth:
  enabled: false
mqtt:
  host: mosquitto.storage.svc.cluster.local
database:
  path: /data/frigate.db
detectors:
  coral:
    type: edgetpu
    device: usb
face_recognition:
  enabled: true
audio:
  enabled: true
  listen:
    - speech
ffmpeg:
  input_args: preset-rtsp-restream
  hwaccel_args: preset-intel-qsv-h264
birdseye:
  enabled: true
  mode: continuous
record:
  enabled: true
  motion:
    days: 7
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
snapshots:
  enabled: true
  retain:
    default: 5
    objects:
      person: 30
review:
  alerts:
    labels:
      - hat
      - umbrella
      - person
      - speech
  detections:
    labels:
      - person
      - dog
      - cat
      - car
objects:
  track:
    - person
    - dog
    - cat
    - car
    - hat
    - umbrella
go2rtc:
  streams:
    entrance:
      - rtsp://go2rtc.home-automation.svc.cluster.local:554/entrance_hq

cameras:
  entrance:
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/entrance_lq
          roles:
            - detect
        - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/entrance_hq
          roles:
            - record
            - audio
