apiVersion: v1
kind: Secret
metadata:
  name: cluster-media-secrets
  namespace: media
stringData:
  SONARR_0_API_KEY: ENC[AES256_GCM,data:kaCng/5v+/Wg5ENxalBY5OdntjCc2bjdHA2Pq5fZtEg=,iv:IF5DjZBE68+6sYyjenvMSI4XrnHXufY4+bapVX4XgpQ=,tag:Rw6OH+0dvx4guyZ8DiTRLA==,type:str]
  SONARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:g1mEHLF82mbJKDGjvMx8nBYrjGCdzA==,iv:8mMqLYnbwv3LZKzGlYyl8KW+QDqQ6OzTjkSAhVQ6lts=,tag:LSWvPoB7uJ28XVsvptDDnw==,type:str]
  SONARR_0_POSTGRES_USER: ENC[AES256_GCM,data:fmKd+LoH,iv:WwPytdY/Y8+oZYyi5TJNctC1bA+Eyq6zlCsxFCHeA7o=,tag:jCaozyVjyFlp+BIfgSSueQ==,type:str]
  RADARR_0_API_KEY: ENC[AES256_GCM,data:mIRB1rcIM395wBmahMMdmzJsFClHPVXpy15itLc1XEg=,iv:eMoxC9mnZUnP143g3bLIP1cA9U/L6iIwpF3Vuvfq7VI=,tag:05xKQ9cN2F1WRMERbehcEw==,type:str]
  RADARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:WcHYqWEsuCFRSJ2NtpjjFYu/sHEvGg==,iv:kEVRUj22GKodcx7JQLjJXJdTNxQyA7ieswDBLWRRdyQ=,tag:mafPur2RZiDiNl2fl9IVsA==,type:str]
  RADARR_0_POSTGRES_USER: ENC[AES256_GCM,data:/UGSFl8q,iv:bY3XMMF+XLqiexLrTQUtKeXtHo7H6K4z7d+6ot8yhgU=,tag:uAXlD8KjO/2wBs0rooz45Q==,type:str]
  AUTOBRR_0_API_KEY: ENC[AES256_GCM,data:MFuzTISg3xefkP07WpBdhhpv70gNTShxaAFVR3IS5Gc=,iv:Rou9EkU/uYnPlrDBmHmCYwIfPWoHUkPzyOeDQrKLjSk=,tag:sl6RCtRAu+Y7IZL1PaOZ/w==,type:str]
  AUTOBRR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:wUG4eJs5ZSOcfCB0omUvrbn6ilj7,iv:pUNi7Tl+/cSbzkaUcpITjJU7FR45TixAj8Lb3Z4b94k=,tag:ThKxHRJLObjmxZtREbj9rA==,type:str]
  AUTOBRR_0_POSTGRES_USER: ENC[AES256_GCM,data:zBTJIj3Drw==,iv:h4t8V4KpR57ZhnA4c4jLFsQD2qK2C5D6EgFnES4XXDo=,tag:2OZy0/tVZFWiWyPc0hqo9w==,type:str]
  PROWLARR_0_API_KEY: ENC[AES256_GCM,data:IHAKQyp0K6i97PjxOUs5Vd4XUt0/csZ96U0adUvPI/g=,iv:iikGK2lX1oIbPyGtqboLiIehfqNM+Y58jvT7uRQHo84=,tag:PIs85JLRTogCWfrrHyglJQ==,type:str]
  PROWLARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:fLtlwiYsM7YMm1Ys9ZusQfr+DmnlKl3o,iv:+7T2ozUog/2tJnKKOnvDu53OMw38tc9Shx8KEzqoXdg=,tag:yN2mFX7M40XINTL1sGxI+A==,type:str]
  PROWLARR_0_POSTGRES_USER: ENC[AES256_GCM,data:WBaHdQqvqjA=,iv:3zVWmDJfKS6/4rD0SxU6O8SyCBoDR9/hbzhFQ4eLm2U=,tag:09mgvC+w/SBxCSMEZ6pWtQ==,type:str]
  READARR_0_API_KEY: ENC[AES256_GCM,data:WhlsXxr2MSR+HqKNqZzeVlbI+IWadGRfjFtHQBZE83Y=,iv:7cJh93utqd8QX14Ol0B+syGjLaBS3n0pttR8StR9Qn4=,tag:R8HWvoD9DABJYyAuPH9KUw==,type:str]
  READARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZLCeA7adG1nWVqHk5mytwPPPxoMOJHM=,iv:GV+9YZ72GOv5vTyw1Sk5LDWaaKWGlRIP3wAZeZXtgYU=,tag:onSPBU9vJ7bkDv1FRk9rVA==,type:str]
  READARR_0_POSTGRES_USER: ENC[AES256_GCM,data:l5KezS9ZhA==,iv:WUFAncRrrOkGvSB0HJMBVNLP9rSeyn7GD0h2Ep/+MDU=,tag:2P+6vg91U8a9cgE6sO3aYA==,type:str]
  JELLYSTAT_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:0YyYsZ7VdxfTB4g9DNtxqBHkRqmOqaf0,iv:bW2ATAkN3Z7e5bB7Ms1jll/EsUgMpu00/9DcqEgkssI=,tag:VVVB2UI8kUQGO+OUyZfuDg==,type:str]
  JELLYSTAT_0_POSTGRES_USER: ENC[AES256_GCM,data:821IeJTNsY2p,iv:OR7c34ZI6RvUza8GkVl7gF+InsnpYOuDJNx6zpYw3EI=,tag:W15xq1NOpmP1pZDYmTyQ5w==,type:str]
  JELLYSTAT_0_JWT_SECRET: ENC[AES256_GCM,data:O4L8zKxBm8Dd0TYioLtY4Tn1qS1I12uuxhUPawwViqZZQy81PNyMRMOF4Sxo41ly,iv:IZfDUYUvrOky9TexJJSMHwlPaL7iI5abRNqARAijZTY=,tag:4WoUu9QvdnZyPsNWQDAEzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTVluQVRxQ1U1eENZV0dy
        UXlSK1hrZktDdytCQndGZWhWWmt3YkhML0dJCnlxN0xZR3h2N2swemdmQ0JNcEpH
        SlhjY24wekdFWFRyODBGVzcwWCtnejQKLS0tIDRRWUJNWm5lSW9RMXErR0VWS3Fy
        M2pyaW56YWY2OTBVWnFJSVJwL0VMMTgKoyXSMerVqZ03HN6b94Bag4KH91Fxbc9D
        vMvVIZcUVXRNHLolVNTbaFBmd7tSGFAqBOuLjhxj/0stbaOGje3vmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T22:45:53Z"
  mac: ENC[AES256_GCM,data:zWndKGb54i+mrH21SZfSwBDxl+pNQFh58WdAx9oyM6erXSailvMnfu0c56Zf1hmh+9G0IMtbPJ7Vrq41MV/ayPPy38lftvy9ZKOWTNalTM/cLkNvLUhYloN3Cxb4L6MHHc1KkHXvEPIkWBkS7I9KLbOswJb7sZ+JspXYBGAlfJ8=,iv:xgxfOVHK9PWaiHS3k/UpwGLdZMKrF3k1xXymnyWGne4=,tag:kuMEMkL3tfi5DCY7FKehlw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
