apiVersion: v1
kind: Secret
metadata:
  name: cluster-media-secrets
  namespace: media
stringData:
  SONARR_0_API_KEY: ENC[AES256_GCM,data:UqKeJja3jX38lr2D58Cr/9ON+BuWqUBqR51ipJymn3A=,iv:dfkQYgu8kNYRkFv2zo2hV4Tx82bHG0u6RsS90zmCN4s=,tag:m7dhv8VwBkS+Wq7P8sGkmQ==,type:str]
  SONARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:oe0LWQBYzwFJhJCVPt7qUcyTqPwkvA==,iv:lJ9pqio5rQ/nE/MpDQ58sbFAgXaO7WhYKcBRvBgcz2U=,tag:mswJKIKESkD63nFpsvn3NA==,type:str]
  SONARR_0_POSTGRES_USER: ENC[AES256_GCM,data:o4wnlRd4,iv:vWA5QZpxBe4UOpEs0MWcI1ftwk8Vh9yly48qeBwG26M=,tag:uDpNItcwUUeSI9CO6xLImg==,type:str]
  RADARR_0_API_KEY: ENC[AES256_GCM,data:RmgrYa1HUXyIV6ai8+Jsxs7RsjZ6l0ZQOPFU/MXQUkQ=,iv:t34rrpI4Qb12ZrS6fLdAjM30g2ahofFtQDW6Dk+o6Gk=,tag:F3JDtJCMPwmgVtTjrK6USg==,type:str]
  RADARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:k1bE/AnauVJhz04XAr3WVztF1AaBIQ==,iv:hHTulTfONSfW1GK9iCFmey2UH0Xz6qsaqmge8G+XW8k=,tag:GP5VvXlA1Laxznk+dT1NSg==,type:str]
  RADARR_0_POSTGRES_USER: ENC[AES256_GCM,data:bFSyfTNL,iv:FpZXLMrL+NTxyxlCMQDI053zAmU4/D2aC9aQvjLp1TQ=,tag:z/CkE1OXNEP6cCBFKfaz5w==,type:str]
  AUTOBRR_0_API_KEY: ENC[AES256_GCM,data:4CWZKOpSCWmqA23Mm9ledy1EAc6dudOOKciu6iXkN5Q=,iv:S/P8ysHbYyw0lNcOpeE5qQwqoiSL2GikZAbTKyc7LP0=,tag:VFz3uC4zB7671txykMKXPg==,type:str]
  AUTOBRR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:n/3BjGkGTY1smh3+25KlrwJ7lJhr,iv:O175F470AR6BO5Fzloll9nUJgSkXuu4NbWydg8vapTs=,tag:NiVJoVfFJzVykItq5MAWEg==,type:str]
  AUTOBRR_0_POSTGRES_USER: ENC[AES256_GCM,data:f2IOB3K5pw==,iv:exA2Nxi9Q5V2vz8DjpzYaWdxs2dItJPGBhtG0+e2Z/k=,tag:3U/RMZVUhB0V1uTe278tYw==,type:str]
  PROWLARR_0_API_KEY: ENC[AES256_GCM,data:uTOwWlvOxQzExOpc/W/3CXBxuT9ZQio583EgABDAhoE=,iv:62gwNIO0A8iuFBo0Va9kkrRUONAJuoXfJ4CN4IyvpEo=,tag:D607fsIJKpS+CStrei7veA==,type:str]
  PROWLARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:d/ZyY4MFalONnGrq/H93dgrdnOV4R6IJ,iv:zto8EhB/ixHeH3JB/CacEN0SDrmAr0Hi+qFVzYXvWiA=,tag:C7B/u9+rjOWV6Kh0Lzg2FQ==,type:str]
  PROWLARR_0_POSTGRES_USER: ENC[AES256_GCM,data:8RBWr5NhHGQ=,iv:PQguEVCkv5rRaIyZjIJYj+3s1kAH5I/a4HTXJiHnZME=,tag:LtU3nBozUIqzVLvFsPsRrw==,type:str]
  READARR_0_API_KEY: ENC[AES256_GCM,data:k5kxiYQvB8o2LpBQGYKviRXUudW+CDVQ8501yNGAqHU=,iv:AcijkNurfh5olv/IevN78z3GZ+8S2pqx+vjZESWjW7M=,tag:0NutmNB/22J/I1sNf2h72Q==,type:str]
  READARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:I27ry1iuVSNArerAv2T9tVX8zITSD+M=,iv:5aia9zuhTNlENVxJ6IgaXwp/rMwU2hwvsL+JXiT6s4c=,tag:cSCWRVxVFx7hLGVfcpDU5w==,type:str]
  READARR_0_POSTGRES_USER: ENC[AES256_GCM,data:yxvpNVaXfQ==,iv:qjXsQ9vFJc6enHDktlX+YAIW8BdGkgfg468CwqPcnEs=,tag:2t5W6MQJrLdq0FleHdf7JQ==,type:str]
  JELLYSTAT_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:bwksG1Z/KYAKdLqNxMjJNCCFZJMtSnUO,iv:FrM00tDql7UMVH9Czhm5CsMbKrC3LpCw/7ej+Q4bLI8=,tag:ruqOoCyrY+XnyYipmxVAvQ==,type:str]
  JELLYSTAT_0_POSTGRES_USER: ENC[AES256_GCM,data:y1M+UneGCtIk,iv:L+41VE8w5ZkuylM+9+/PeLDubQ3MATnofj6Ma0eUbPY=,tag:GZaqUJSPpvm2YTR6JHl43A==,type:str]
  JELLYSTAT_0_JWT_SECRET: ENC[AES256_GCM,data:PrSdtHYqF4uLAbp4u1y5207AdILPu8xbvXK5cxctPv0h31KHMxBWKcH7sxtMHyt+,iv:xzboMdsSjGsLJkuUaWCY0tcZ0AEZThR7a12FSYmVV1I=,tag:UKtEajeJ3Iel3a9O12B0Og==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWnlmRlpQY1IyZlZZeHVN
        cE02V01RMXlYb2RJb1doRU5RWDhFNnVkVm1VCkFIOGZFaWNmWnk4SytsbEdNbkht
        RDZFWE84dUU0SHdWMUxpbUhsQUp0L0UKLS0tIDFpaVZ5TDZBMWt6MG1JcUIxSVl6
        V1IyalZLZVVpWkxBMjYvUkxnMnowNk0KwQ/RT92eM4NiikyAxVQb7XkQ4U+Dkw92
        sQtWFaUqSm5hkEbctW+9isqH98Kev6TsysDbPd6j1g9aOre7vxPaLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T00:43:43Z"
  mac: ENC[AES256_GCM,data:Q9mNmqAL4fTndKIv/kYpTD8XBkYhBcDfvz2IlCCKtMGBFlP1VR8nVnGojHMxbrhYst39sw9yFfekZbqC7j7U7VBw7PKN5QVR+Uxrve5y3q9S0lnIzep7tYJq3XC2wzL96fqVtJW5IMbDdYsd2ZTedy47C0DQAualOLvwA6zxdiI=,iv:cpfVFq2MivQhrtuYOwnMwVEvOyBzeG5MkXtmCjybExY=,tag:pvQP+Lr9LIC7rxkU8TA8tQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
