apiVersion: v1
kind: Secret
metadata:
  name: cluster-media-secrets
  namespace: media
stringData:
  SONARR_0_API_KEY: ENC[AES256_GCM,data:VLbVzYGClFtCOOSeMQWiPesPL/geZMHKUmPKhIx2Zws=,iv:ozWNysO9QYkj3w0dm9QnVRLTEIWAc/jyWCsylgIy84M=,tag:gzUEr1MTeQKGEvIKA+BW1g==,type:str]
  SONARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:w9wdFCAjihHZ3A7ekC0oJXEJ8wMO7w==,iv:uFyufoCap8gBVmfDxaDjiawx1hCSzXQ4XGWeri7bb8E=,tag:bAWzOCpuLWscBlKIo022lg==,type:str]
  SONARR_0_POSTGRES_USER: ENC[AES256_GCM,data:eOVgGDZZ,iv:hqXX4HPMX9zwZMHDlzn7lRkwIKBwtN3CVpuF99hMCik=,tag:OsJT8WkkvIIRDBxBRSWOqw==,type:str]
  RADARR_0_API_KEY: ENC[AES256_GCM,data:gjetNa5QkMEQCcsn6Elm1bZLH+D8PymUY+trwutkSyw=,iv:NDwv7WfBWVPaKEVZygzFwnVyFalRlHkWsmnGrXyBh6I=,tag:IHqclCCPKJgJmm6nCRKjaQ==,type:str]
  RADARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:zNerhCXerNwzy7W+0xQ6fOQ5qjn4Sg==,iv:BpQCO+KwlTPUxehG5qnJcP4BtDpWuGg29sp8KIRp77g=,tag:NYgLsKqG4lkkEtl9lc+YwA==,type:str]
  RADARR_0_POSTGRES_USER: ENC[AES256_GCM,data:SOsNtDEw,iv:zxD7lZk3UL2cECGmAW4hLEUE6nbzLEM7pnUggQbiwjE=,tag:xuizeG9HUl5LnOkC0MlOLQ==,type:str]
  AUTOBRR_0_API_KEY: ENC[AES256_GCM,data:5PGoa/HMB+Tpt8mgvD53AhqTDFsdqgzXp0w4sZ/iIPI=,iv:Yx8xSJUZzlwJMAgxCsvo8HIsF3IRUw852xFy7G1rK7o=,tag:PzpsBiR9X+yEu0mQ0vXblg==,type:str]
  AUTOBRR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:3XJwrorOsmsD9gLrdFMJKbQgERhe,iv:2Fm8yVWUZVjCDAJcocaN37qyTcDpM5rvIgM0XOX7AAI=,tag:cxFlyI01KHZfEOkP1xwknw==,type:str]
  AUTOBRR_0_POSTGRES_USER: ENC[AES256_GCM,data:AJH8C9BkLg==,iv:k40PopfEhk2/lwbDmPlFuitNsmurfRjEFfAA1rfHLQ8=,tag:Y5z7piI7/VCLwaWZ8AkTEw==,type:str]
  PROWLARR_0_API_KEY: ENC[AES256_GCM,data:nPIypTTN1/hAE4hptGtdjtBpNfz+2Dya8EtvjZfuXHk=,iv:bUUFW7lu0uQt8X301eosIcxLgTj7FF3aDtc9BVsIiz4=,tag:/Gg00g0TAcpkrier2pRn/w==,type:str]
  PROWLARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:wAawg/lnzEMwLMUwJEO6T46LKIIOrJr2,iv:5XGYfYSFVK2nSCz/V0iRZt/cau2VkncLtYFps2Trnio=,tag:/z271L6uAofear5aSBiozA==,type:str]
  PROWLARR_0_POSTGRES_USER: ENC[AES256_GCM,data:ixW9hSbzUTw=,iv:apXsR0rl7tujBxxY2vWfZxBxVDYlZSz6fdJiLm9Vmzo=,tag:+gQA95KpPRiAWjc7uuzKKg==,type:str]
  READARR_0_API_KEY: ENC[AES256_GCM,data:gQ5F1pHNUr60NkTJb4WSiZX6G0XSaAFkkvj8TeOUCdk=,iv:htwMwvK2JAofznJmduuIm6dOioIKc91DyHLQbnVXNLE=,tag:InZ/ttjDFv+dILIjWW2lLw==,type:str]
  READARR_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:dNCI+Ymqp0Ki9cka5YmUCf3I2b9bhTs=,iv:E0k8RlwVjIUO2Zxxg4NZnLa4v/yzC5dzLjKVpolaFqg=,tag:Be+EC5bolC1KT3FmPyMWtw==,type:str]
  READARR_0_POSTGRES_USER: ENC[AES256_GCM,data:x781bhQUzA==,iv:7/yccVD+l1kzPDi0GsicWyos6tAGvmsa9vf5SqiDslA=,tag:vtrAyT1HYDJ6HtEaoNngrg==,type:str]
  JELLYSTAT_0_POSTGRES_PASSWORD: ENC[AES256_GCM,data:g1qR1qAgNRQiI6cahjAi5n6uGflgcB2O,iv:jyqgjZgzywCq8ZBR8L8FQNZ3vruZYUGNcMpTWebj94I=,tag:b5s1cpftgyY4Y9PmPXIvEg==,type:str]
  JELLYSTAT_0_POSTGRES_USER: ENC[AES256_GCM,data:Wk4HeNKsiy0q,iv:wdgHAI1RE49+pLs0G68URpTcVkvbNYEkSJFfGql0w38=,tag:EGzeuzY1TqqRP3hAUmJgQA==,type:str]
  JELLYSTAT_0_JWT_SECRET: ENC[AES256_GCM,data:mTJ6WZgYngbCKcLnmLaBwKnhbm5J9HYsW7fYGxVZUiTbtjBFHW5Rdw+rNnG2qV/K,iv:UusqOrWENdMhu+aucqJ9N0UZPRaKi3LJ6AaqY7egrrA=,tag:u9Q/vgcseiiDnC8v5657LA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY0ZLcnJ5YXdNckRwUjB5
        NHNmUVV0Q2JKaVVsVVBuR0VHeW1LV2xYOENJCkJGZG5sc2hrSDErWHhvWktPUmlR
        Q0s2V1JRSS9PQ3k3ZENzbS9ZMU11R1kKLS0tIHNsNlVqaG95QmlQQ29WM0w0Vzh1
        MXR1QlNtTEFSUjhvV3dSQm84S3U3RzAKtUARLTdvwtWbONMyiaaCCyYYWy4UdmPX
        hhZbmx3A5lWeJd7mdwel+i/Bv1GSdnWPpmJLz6YcYAsap5iAYIKhxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:48:42Z"
  mac: ENC[AES256_GCM,data:pDDgqMrfPFZpd8wWk66P9Z88dD7HKulmwbHxizej4kjTGuTmo3bjkr7HQcx7hDL3GPKtAtCPri/KSjoPEXhr6HlauSQmGdtE0nOMaSD8CEZONN51c0IqoUSl8u88bVG7fIF7syrPYVpHMX5Uel0OCyebVAAzI5/nWcjouiR7lR8=,iv:82nxLuPpDq0jglA48JEp4Io1PWzbsKp0Bvg8JiL5WJY=,tag:MHy83ZkMQ3eSiYulWYh2Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
