apiVersion: v1
kind: Secret
metadata:
  name: cluster-minio-secrets
  namespace: storage
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:0ks7Fq637aCDwZPQ+OkXG78KcSU=,iv:K9xt8LPTziwEKA+pvAleQEbc3z0y9F/TXd17b2Hdhec=,tag:AkbtHun+bGK4TmSmreXx0w==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Z7xkruqd8AmVSkR3nb7ESunERF6eDmd3IGHZhWuiM8hCLa15ZOg7LLuOSfbxHcaRph44xEg9G7MvS03iWs1O0A==,iv:+4Sn30mdOd0GSxtjC40YD0zdIKdx/eFQKVIIgl7yAMI=,tag:B8jcr6Ggl6P8Yq0Kl06Xbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeFhWNVhJMWp0cUs4aVVQ
        Nm9EeXE3VGtVTm9zb2pxVyt0eUtsY2MrQlcwCnBSWUlFdU91SE50UlZWN1NWQjIw
        RGVDWlVBclVXTXg1N2RsWTdKRy9VTzQKLS0tIHNYNllBcy9qSGtUaHBMZGlFYkYw
        YlVJc3pUcGFsVklLNWY5Nk4vRWdRRDAKgOXNQnBcLlTq1uh0OHW06y7e2qq6mXA9
        YDC4tOVXRLq6CLcSZwSIomInUqLuVZWCb2OB6bwGiDcDJpKAnaq75Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T22:29:55Z"
  mac: ENC[AES256_GCM,data:PgfwFrzRBE1BCPn/11oJbmU1HnPDVq1yxnbL4jH41wrKbHXBG24UUzOAKj7j7yoyzVzs2fZOaxJEP2dbloSzaxraNJxW5ddMTUFiCth2iKnvRHC2tiMtRtm4bmOqk6huY4SDKbwilShTyQ7CeO39xT6KTbgn24K3Xt2xhYP6PwY=,iv:exAO1+uoWuVjGkkYev6HPeyZOAilKmf9fkFLsFzG8mw=,tag:UapsZv63ZveqVJtVWzGaBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
