apiVersion: v1
kind: Secret
metadata:
  name: cluster-renovate-secrets
  namespace: devtools
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:/DMRxHWIUlMQVaglXIogJcMfSGSNlyHD8O9+He6g3jdYC6VRJpw7lg==,iv:bmPQKx0st+CZ/8U+oKjS3P/asnzasP5AzxgG2FjX6j0=,tag:d9OiAuqBSYFQhRV3g5pkuQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZDVreS9ERksyZlI1ZmV2
        dWxwbDg2TEtDcUxsOGRBaWRqbTNkMDROOVdNCmpUTitVOWh5S1Y0USs5blhGWDE5
        VDNoVnh5aTVjUHpRUWE3UWpISVBOVzAKLS0tIFZ0ZDhJMEhWUkVJalljQ1RmVkI2
        bDJieUFXTWFBOHhZZ3BPQmtydTZwTG8KMZ50A0FvTJgwEBuFFQVy3AgpoIv5+7wO
        +7e42UfEHrPEjELtdGcY63+R4l5bPuLXWSfrTNHLkw3U3//On7LwGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:bWDGdfhjKSFw9nkoKyI2BF3uQ97PJ6A93QAJfCpxEKX3xwQzeIkqRaq0fZtvf+i3/3a6HAndwsOfsdHSDrjPppjcpEQr6+gfH/vpov+SY0uuUXz9B6QKQxaB4b+tBj+e8+bj9nJbUqdADVm4cIkXU6x3DWi/f8fQcj5RSKp99nM=,iv:2I/8Y0kvG0JC++9MVe8qUirjVersxKdAeZgRCoCvMDM=,tag:WPMYtZNKk9RIbGvbHI5rFA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
