apiVersion: v1
kind: Secret
metadata:
  name: cluster-renovate-secrets
  namespace: devtools
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:dAbEg9frPm07shM2ZL6Wd9whVTA4/V67NO6sSRFDmjXn3FoFmymKhw==,iv:w98FResDlkh/6iIUdtaDNAwfcjcVSdiPRFWKKSFM9SI=,tag:3FFw1LTbvDsCVxfHt4Qqng==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRmE0MFBXcXhuT0RsVU0w
        Y29NUFRSSWZUaW9neG9WUzBsZlhvSW9FZ2k0Ck9nbklCRXEvclVuY2M1WmsvUUlF
        WVo0VXQ1L3BETTJNM3k3emVGVE92L28KLS0tIHRXRjRpSlJOOWFReTd3Y3R6TTdr
        WFl1RWhoWDhkSU00SDl2V2Y4Q2JUZHMKaC4bXbhCTTTcjGJz+O4JPZTqXmhFhKIC
        VmbKdXxTBOcvk0z6I5r/7pRb97o0GQjZeLFAFbl6Xy/Eq0UgsmuC4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T16:53:42Z"
  mac: ENC[AES256_GCM,data:hj5Up6ucKWyW8CvmEXFuK0g1jb56IailsBy5g3qt8XUgH/jbHeDoCfmT3KF2BIqjLD/9T83ESetpNN/ZQc+/sRwNgmj1cCd88iYq04V3B96oJuokEyHzXZQUi7W7ngIjaUG9SB0zOk/t3Of7voa9Ir3kAtm/jV3AcWfc31izJ10=,iv:C3zZDS64fqcTZQvSZkjo99/x8QPiPNE6mwrEmN7RZVI=,tag:NyVS1j29Ty7MDJOru4gK6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
