apiVersion: v1
kind: Secret
metadata:
    name: cluster-renovate-secrets
    namespace: devtools
stringData:
    RENOVATE_TOKEN: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbnp4ZjlJUGhuclNuVzZo
            aDZ0MmliTHRjUFlzTmZCUFBLLzJMZHRadEVZCmhLajV3TStIcm9PdUVjYWVicTdu
            VTNEOEFQSmVsemVKc0xCRUpkL1hsNncKLS0tIE5nbkNmV2EyYlhiQlNQbjYrZlJn
            YlZaT0pZNlNDdGFtTnFROUt1ZFdvcFUKR+8/1eQaNDjqx3IFt9lJNUnXoeHu/MqH
            ag1bQrFY0nzumhtsIBeMT/HJM4c065DBHaU5iPwRwYKZ5RFf3gmloA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T15:14:07Z"
    mac: ENC[AES256_GCM,data:LfUcD107thV3uTffKBF90MfilajpBY2KlByUzjkkQKZRWBT7uMl1AmxzHbCdK9n+/Bq1QXND4dPksFzeAp9Z9ieqHWv6R5306daz/cDi4MeyydN+QB6utYVYwgQUFoAjhxAY6LCdfSpooLKjA/BUYvPmFeuF22P0qHv87PowpDU=,iv:Ys009EOHT7U5uAVMHgpxasnI2XD3B5iK4Tn/qGVryx8=,tag:L7rH5/9ha2rP55WtlkbTPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
