apiVersion: v1
kind: Secret
metadata:
  name: netbird-peers-secrets
  namespace: networking
stringData:
  NB_SETUP_KEY: ENC[AES256_GCM,data:sCpYti3x2mpxaW6HlJIqZh4x1WJVFvZuOm0gNWJfHJOaQlUV,iv:1ueFWV8ZJ+40NLQlNk99UIjC4auMiuWWWDLDk8OHhMQ=,tag:k39C8Lc3Btgxxk+T6yJ9UQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RlVnVm9UUTZjTjErNGl1
        NEJTUGwzTVJrbGNMU0l5YllCZ2k3VUNjaTBrCm1TY1NyOGNCam1JK1VGV2h5dTl2
        aEY0cWtteG9pNWpWSEUvL2FIVk5LY28KLS0tIHZ0SXBFWmhqN0pZUkJQR2hJVFpH
        VWhPNFNRMVpQVWVibVBnV0ExSW5hMUkKMGHBdSLqnYY8GAP6cf6eVbeD78xlnJ7S
        Ps0TGhAE2+mgbglKA/cJ1VOgRPesn5LDN5n8K/Q9lxQlRX3micd6rA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T09:12:42Z"
  mac: ENC[AES256_GCM,data:Iai33eXiWdbvWWZRxPLm4J/fXIfQhiEy26NqeuE9WurVpZKlzTLhqBSiYN9YRiJopTVK2ErXN62uoLu0SUeZ9DVvMU7Q75oR9j0HZouhO7Yaofb/my6HOCIrsoB9Hm/vjr44gFIQGYHv+AVau/6q34D6pqj4ifb3FOHdXlq3hP8=,iv:mgyUTLAZA1qHPkIjxSJGng6vMP6WWeIPb/U6SHcJ2/0=,tag:fsYxq8fRjScSNqD6kiaFXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
