apiVersion: v1
kind: Secret
metadata:
  name: netbird-peers-secrets
  namespace: networking
stringData:
  NB_SETUP_KEY: ENC[AES256_GCM,data:Hca3f4favUWu+tV2gh18OFrHWAamEwlsWs/R9WzwCFVfSsFM,iv:OBg8Czt4XB4NxSa2NL3XCV2ynbY5Cd+VLXCbtQtI0wE=,tag:rTGTvLUhYyBEjaEFRMFMIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNDV0U0lmTUx5SmFDNEtH
        bUZweEFxSFc5a3BRdDNZbks2M2xScWV5ZkNNCjFTQnZjZ0xvU3U1UzFhRytEU2JD
        K2xwaEs2Z1RmcXRmTnYrZ1hrMXJsbmMKLS0tIFJVRDV4YW5rdWtQNXlFS01tNVpt
        c3dKRm1EWU9ERmk0VVZqYjY1VGlRczAKYlv5hbDctcGsDQjfXP0gdu6vpCiWlpU4
        Vb0zZUo6L4KylEzrex2AVvgsEpRXzpyH7OiA9XJ/dOQgKjcvS402Kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T22:45:53Z"
  mac: ENC[AES256_GCM,data:XdFBSZG2COW+E/05Caz1SjBwEDcEJ0W0NM8mDS2VMyXO3192ZiMamH6I+MB0DXilG5bgIKFaAEcFipw3QokwClo+Lxob5mLG5MmPmgC5fDVrRymheAToRu6D3Kg/pT5zQCN172wZxPX1a1fEqqluA+DOXwp7cUAvORpEeRZDhyo=,iv:R7fEOeRwZzphTXUMhVWIotokq775VWC+SXWSfXFUGwg=,tag:nLgGJbokkCNAg+/SIRVIgA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
