apiVersion: v1
kind: Secret
metadata:
  name: netbird-peers-secrets
  namespace: networking
stringData:
  NB_SETUP_KEY: ENC[AES256_GCM,data:WxuByDg7o8Cmzz1tptcVGOOS5JqodHU7jB4N+5qY2d3eFBh/,iv:Gjr+3+6ldDbwK7XxEcfpSDKYy+nI+lMZlIKu3FkmCMw=,tag:QzsInr5JmqyueZT1q5fiAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TDVXV0hGYnZRUFUzaENv
        TWptbjd0SVdubW51TmtjVEM3eFBkUGVzaUNJCnF0L1dLSUlsZTRvandXNlpCYkwx
        Y0RIS0c4cU8rN1huVHROZC9xVlNlNzAKLS0tIHdPR0JxYjE2LytpWjRmeXplcVpx
        ZTZDSHpiaEhzamRyUm40bDc2SkE2Vk0KPXKq0hpHtXjkWigF2b5MuC3TJu96k0GM
        PR93rLTt+CHB8xIv7vXO8PzV2c8UOGa1RxRCfWXgxfiHRlkGuLqZDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T23:19:00Z"
  mac: ENC[AES256_GCM,data:/yJRlYoiup5qXWgZzd15yZVi9gUCkJKTt+yZBFEDAlMdeEh/5QF3b4z5SB2VO2XgKOZzYNgZIPTXV+itsqNlr47lg1w1fCqbjRE7nBr5godtuDHK6EBtGIagy1z28huVFv8QpL+hcueBOKaEj0zgMSb34SszwbfIm3RMyU4H8yg=,iv:k4uub6mVRfA8FMj9pcA/UuzrykznJKd+MVlxNQdVFJM=,tag:9rEWHjjP8mDtSAgCKllciA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
