apiVersion: v1
kind: Secret
metadata:
  name: cluster-n8n-secrets
  namespace: default
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:rEzxjiWHQKtHyt2gdxRVNaIX0o4nJkn942s=,iv:V+l2eS4XyaLGKl2103o3AvJEcJbJxc5sL5sXjxgj8A8=,tag:Yd6SejJ490pugTm4WTBfUg==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:vEXA,iv:s2PypJHbCFxqUq9OqcpSK7MkaRFgcKvGIclnCI5daS0=,tag:y0qFnwn1EZ0Ew01AfVzc2w==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:ExzQMGXU0JSeqsdELyW+6X6rHIFgLQP+HIc=,iv:blu8CtD4w07R2/OkvdH2R/69oz+DTuyu4wfQtMSpT2U=,tag:gufiARsSi+MOoWEVydh1Ug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc21rRjBNSVFuLzIrWXhx
        N3hNYUx0SlkweHMvczlMSzQ0eStMNlhjVTJ3CitjZkNxMmRLK3MwZ3NMaldzRzlD
        RjVwWlRBRmJXTnRpamZJZ0hjTmVYNWcKLS0tIFpobUtNWnhQVWVhS05YRmw2c3FH
        WDl5VFlWNHpiM0dWakM2alJYejEwSm8KgbuhzSgh6Xug11TFKmqMX/kaDQEvFitv
        ZrA7nHg3atMJmpVwQrxpnaTUy4YK/mHqep3wrXgb29s24vCdkHni8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T21:54:21Z"
  mac: ENC[AES256_GCM,data:lcUov5q7it8AwHUULWjskzkK2qRSYfOw8ZQOBaiymgRdaq31uUtTa+lDa6BAfAZZWTtLg2Z7jleZTkei3LuhyDQSL/zn9X7tJao2Zni9/DO0uj2Otkz2h9ywqbZIHwNP8QTFUtcmQJ9GjuKF6pIKdVX4HGqWOR7NRCbMm7bb2PQ=,iv:RwWWN5He6D/4Sg7z5Ib8uJ/9MG4kNlolKAK3PZy8HQg=,tag:j2kkR1KvmdWLn2AHhPzxTg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
