apiVersion: v1
kind: Secret
metadata:
  name: cluster-n8n-secrets
  namespace: default
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:pQPTJRBSj+0JmIrEV1ECXgUsxwcK9n6uBYk=,iv:XDf2OiZacl90YqHR8KKEGl13d5UEsU45BaOYAIw3CZ0=,tag:KH+WZM591wzYmuldUx1XfA==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:ycAW,iv:fSVG627xgYAI388uwhejoslMxBm0dq2bFkPjel/NNLI=,tag:k//7mnukhH/EXFro6YKRaA==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:Ocrfzr5ZL/yF2C2gPP6zERoLxx5RTvssZ5Q=,iv:cq99isYx4t17P5dpI3Qqrshf9KpTezsU+RDSDxNgdVI=,tag:9DvoNkjxCk74hJ9U8xQotg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWUFxN2dRV1NWckN2d3dh
        UXVNRDhtdnppczVjWHBnbDBtVmoyaTZ3R1dVCmI1dUFXOFNqY1pxMlJXY0o4REJB
        Qi9FdjhubGlSNjFJbVJZQXBSQld0RzAKLS0tIDlJVW9MOXlBMEFGT3Jpcjh3bFpC
        Ym1JbURwMXBaemc1aGRldG1nemdEb3cKICI1Q2Uas/1wBBSKNO1pdJHmZ3BwmZHs
        GT3UAJJiDOqQTTnwGT2ttIhYNI5fC0QkgPJLEJ60tJNXX2jSuH7HKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T18:22:26Z"
  mac: ENC[AES256_GCM,data:2CL221M5px8l6DTnLJ93V2rw/2mTQfd7YDikcBZAmzSGuawH4frdS3AgWqC57Y3uOQOyXHjxltsF3l0GeWlQiJVPqYMhsvEoCYDc6gIF3dH5Yk2e0WljkZxg6Ps/WbKOPodRrgX+qcVnlhISd0s25CaOnG6H8KIpzqQ2dueOH2k=,iv:0gQjosKTb96pFkiSQKNFoxOdm3TjjHyTX/uh6B9Fh70=,tag:/R/mg8hcDd2P3erG3y4+ww==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
