apiVersion: v1
kind: Secret
metadata:
  name: cluster-n8n-secrets
  namespace: default
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:S7IzGJ7bOF4OXLDNCaXDAIO+pDqzQdtJ/qc=,iv:431Hj3mJhhNlSsiV8h2AHwq314QcE2KqXjmDA4oBx50=,tag:ktyZDQckt83Ajk4+pZvrUg==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:j1UP,iv:DzBOgP+/ZdnGCiLrAyBfq4GXx5bQq21T1Q0CRpvwIVc=,tag:liqoKDcEXeP7Q5+lTRA+UQ==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:pIooFIPG7euEVqtlw/QZwqlL+s8Jcl6Lxq0=,iv:/KRANNglBuMASdfwag+ERbJFjnuwwCgX5NqKBmBO/2s=,tag:7NftHNtd4yDOenhHSVfyRQ==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMnB6QWxKMFk5cUZSTG9u
        MzUxNlB0Qy9CMDcrNE5WL3Q5VGN1aEFySWc0Clp2ZWR1cEp4dkZjdVJFNVBMalNS
        T2ZjZWd5WHY4WlVObnpPc0VUTGFJVEEKLS0tIHNkT2l5SGFnMEJwTUVIK0RHOUg2
        dXBOSGVuVnNnM0Jxa2ZaekxuQUgxY0kKefguKvDSo5wTa6JU39Cc0Q8RQg29LGQW
        OfiKIFR8RTC9ytlX3gZqFsuuiqqlPn8TWbZjIcYFJMJMLdtgnTEmeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:57:51Z"
  mac: ENC[AES256_GCM,data:M7fUMf1XZSgBFI6qN03rwPS82gS52brJBOTZWkz3QjgBznSdnPHBatrXxgeMvnJOJmKkGfsZwMoIoVoUDLlDB6FGYjwyunsJar0HYmgNe/PBNMo51oVXgW3xgZTcEWCW2jzPcE89TV64Et0yc+i/1sWzmL8vZunUE0aGl3M7M2A=,iv:UfcHnfkLV/Y0M3xQATXRAEZGuMhVcEUr529QBAAuMAA=,tag:gaF7BVexTy/qgqDQUn0kDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
