# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Wh44lUwQJxa5zLJTTluMvGywmEq0nUbYezlSBQ==,iv:Cpq7ADQKg7y4z5247K7RftEnw0Eb30wAnEQ6cK2Cuk8=,tag:U4CRi5FQclhmZAfIqnGkng==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:xzI79w9WAjE5KGHx+JSs76tASF+ygF+kOjo7lvwQaHBCU1kk/g==,iv:17pUMdazHWlt3M42kGTJRbdFK55Ckldr42c6a0XgGCs=,tag:pqIk4EjgGw6O+q5eyKuC2Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Pni+4Y5TClwfpizMY2+YJmhCRNZ7OvzADv38,iv:7HyhD+7c1F1z92Oi2UulpnKMCAFOV4MHq96Q1g+b65w=,tag:tSgN7WLz0gjZmNCPkGlOKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdGJMUXI1dHlIM3A3SGlt
            R0FyWitSRWJ0SlpvT2xpNkQ0eHlCbkFmekh3CjNFRFZCZUgzcHNjMHZVL3FGMXJv
            YVF1QkFlYkQ1N3pCMWNrQWJCYUNTQ3MKLS0tIDROOGl6RHYwUFRhQWZiMFVidWpR
            YXYxRVhQM0FBeDd6S2hCdlZTQytzTFEKxALnRjIPRQUHka/04srVpkUnLKzGrWWe
            Xr0mo0qYZ6g3vdr7kVFogavPtACLsb+TnUOyeAl/IS/06UqojOy0GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-03T12:41:54Z"
    mac: ENC[AES256_GCM,data:kX+wCZQCJ8H5o2dx0r89qYG+qBhUU9rXheKWxi17NEI89BNvipm7my6KvSy4nGMYOLNtjJZl3A/ptT3T7VuKI2QUqtxdPp92vCbb9aWtpCBsn5njnEImghMbRo6iNMf2i0bYQgQJgcvoh7NOB9eNOJQJtdbVxMcNvLjAJglJyO8=,iv:OeNgF11C6gde+7K5rvqxa2/xyjemTYUqVJdELMnFLvA=,tag:wESld8uztj6Q0dyTff5kXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
