# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6yJg4lWVjGPJ4xiPDOy3lMXBUVkbb0Cgjj0ugg==,iv:XC2wctIW5Unqi3D0aT7F891OR2Xb/sNqMucWpRCvH2Y=,tag:2dxp0l96Gez9wyyMIGel5w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:kaVSUEe8vmTqbFZA/k0SQX4GLxoxwugfMhDuAKc20GLVM6S0jg==,iv:k7V7xyzzNWWFHaZrzxJaY89UtFB0eVUp/kU/2rClKzk=,tag:blwMp+bLK+78VXcO/PVfkA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:viABNIfroamXwqM/Er6xnM8TAbtcWjKRqLv5,iv:OwlH8KiDfyklAFp6WJ2NeBbl0vPDPi95+w/MZJGBAlk=,tag:5Vh/OKVyePoJXmxvVJJgZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeUY5Y2FNd0Z3T0VZVWxJ
            WUtGM0tjMmd0ZWt6a09FMGROaWFaTzQ4NlFNClZDTzJYM1dadGZVdk1RZTMwMU0y
            T0gyWkpFSkxYNE1JME0za0hBcURlQ3MKLS0tIEZoUVVpM3FqOW5WeHlvdENzdzlN
            QUFzc2hrSDNqZUwvY1pvZVAvbElVNUkKGgB0wpyzMBtHrXplKvA3qUsLRhm6GRo5
            S5qdamKdHCPfo3qGDvJASLXvu2X5feKiLZfcF2JFeAwdm8LJgvTvlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T22:41:23Z"
    mac: ENC[AES256_GCM,data:SYGyDVt5KBViTJyr8+N0hChnmdiKnIFk/VdpfMl6sBscMwFWgb6Obfl9erIDLj0eF3H5xFJrVuZpFSrwnQmkt/4Vy1suV3WYJk831bUSgX10yqZkksNMPViqFc5h9AJ44FYw5DVuEXILR6oTNmCkgLDsV3MkES96SEHS8CIsaCM=,iv:/fp2f1JbUHGXRWejN7BYCxwtW2Q7oUPgwirYVvYXfgE=,tag:hMh+e3z5NXLqRPXNUzlmLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
