# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:1xPh42uF/nThP097pRiSPNWIxeS0KKv7jTIwgQ==,iv:XYWrOLGQpLYnv+lP6qzydU/eMb1i1rXdgwUUbxB+6RE=,tag:A9jql56w7da/sbw593iQiQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:De10BYegSNXaO/O548mg9YXNvTvsV6YuyI3ljPwWp164FCojow==,iv:EXzE37WeH5+S4KQaAk4bfCMk1tyzTE2bUdlCDjG8X4M=,tag:AsDsMOKo8OmKdb2WBXOkXA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:O0d3B177u8GaFaaahVbqDJWtZx/Rb8O/GgTr,iv:pDtI+Z2U+vttuKWU9MdLFudJlVhX3Ciq71gGlHFJtMs=,tag:11WSHa36flLAdP4bfJp7Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcnJ6Y0dUZy96QnVsUmVt
            aTlFb2FpSjlkNWRaSklxeUR3SnJ0akJpdFdVCmlHQUlOUVZVYjlhdTFrL09heEtj
            T3B6elFDU09Cd2FMZXFnNERYb0ljdTQKLS0tIG93Z1hqTjA5RXp2aXZaNkJlQ0hN
            NE1JOFlodExkVm1VMkFPc2M0V3VkVkEKtnEu8d85KDszSf2iqIAawlJ/GTRognPf
            EDCoTG/tljvdxSKOuri6ZtGzeXnb6w8FL5n7s3rAc4SjpOgu6kj1CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-03T23:21:27Z"
    mac: ENC[AES256_GCM,data:p3VGZi8j+VGWc3BTfFuozkTAUFDMopY8DXxSwmvUxl1Qy4ihnpshF76t48lD2wuMs1Jbk8QLilB1tv5TSIBe/z91LPyL0OuT6kBakgrby/Y8C+E0PwKw7j13z7YWJmzr51bF1WDwXNfyqjHYIebodIIM3Wfj9D4a94FxfjMjec0=,iv:AjYUF+jMiasTKtthmCgMT5UbZiTrwgJevWsnPLlVhMY=,tag:YUNUyGh/pBKYA3H341KrJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
