apiVersion: v1
kind: Secret
metadata:
  name: cluster-actual-secrets
  namespace: default
stringData:
  GENERIC_TIMEZONE: ENC[AES256_GCM,data:TgsVSzBDJIrvxdUN9Q==,iv:8rrS8HyXEVB9o7izYrz7lbV1zMHevrszD2W7AnA72kY=,tag:bevBxVHQ7stIvPFRjV9y5g==,type:str]
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:nS+hDXDE,iv:Vpygy7/rZiCWEqfDqKSEKCr1C+DWVlPUSs2GOS266PI=,tag:ViftV26HnJIPpVwQICnyQw==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:+7hKSVCvc07VQSoIlFziJKG62JCkoDum7htpodL0TTYjYZ4/cb8lyJ4j1LIPMXI=,iv:4sySAER7LTQVCXM/wTTPK9Cs7Fp/nSidvhqO5SiFrXo=,tag:UmBlTd5elbGT4KAYZzQIuw==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTUdNNEFJMGRRZTdqemg1
        RFBtSXV5dzdINnYzaG56bnVjNit0RUpQTlFZCmtYWVBjS09zYVlVWUZXSnVxTUJK
        eE9td3hUOHZhL3VrbE92ZG04WlNNZDQKLS0tIHQwRWc3bmEvaEFRR0NUZTFQMEVR
        Z2VmWnc4S0hHaDBMQzRlaSs1b2hrNjgKOR1KFaMdajMQ32h+2sZt2jc7OUtT7zhF
        iyPtg12Z31PCpV7y3PU8sCpts3MyDRCgpPEvtVVRrpfVka5FbqmyXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:40:56Z"
  mac: ENC[AES256_GCM,data:NSmAPMHTM4T6P9aBnEsrUt4nRXklhWnkhBZ72M3uL3D1sjR/Ru6c/Zs2ebYqAmvxW2u5tabXfKzn1w0rYnUauDtO8X0x3LXHJSDtJsS6wlL0HC+Wj95s77A1tZr7JefBQJIyUxU0tL1r3yaJKVxkiwrijiMKumI/tZtIC3O69jc=,iv:tPMyZgMQRA60D+K1N0PH0LsBmw0cCAtjxTxnWWnQmaY=,tag:FHJRzcArh98XRaDTF+RhAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
