apiVersion: v1
kind: Secret
metadata:
  name: cluster-actual-secrets
  namespace: default
stringData:
  GENERIC_TIMEZONE: ENC[AES256_GCM,data:+rF2BLbeueY5INVA5g==,iv:Zc5hjd6GOugfeGWmkdkGYzuXCRXXSe0y/7B4TeA5XqQ=,tag:zVaUh2hK1EZNT5SehX42VA==,type:str]
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:+MUulpF1,iv:OyuvyyA3//3QXMVk/ekEuT7KcayckWOmgplJroC1HBg=,tag:DBx84vC17xdFk5hZA7ThPg==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:Vy6FTG7+XpprUMWv3E59nVmDl+nurez4j3DdPVdIgrND3nZQVk2lHaoOZnWlZLU=,iv:yGE6Pnb+OkeaDa9wxj05N88Iyyoe85Yf6WjwBzTTsIM=,tag:QjXtPKio8C6JiawbrJuNfg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTmszSllvMWdTTkUrU0VJ
        eTBVMEREMkZjSTdsOTVCZFBBUTd1eGJMYUMwCldsVVNKRTEzVm5zYlFCZmlCRU5H
        TjhLTy96Y2ZTQ1FlSnpyL2I5em5qUVkKLS0tIG5JdVBHTUxqekJnVmFzYS85aThn
        dHY0S2RZbklSK1NobjIzdnYweUFQN2MKIFYMuR0cqbXDa7egcp7MRfjAVIZDBKkn
        ADModKGd954EpaX8ekhCpTZTPR1TM5NpcPbV9GYdB6FPAnL3O2xIzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T18:14:18Z"
  mac: ENC[AES256_GCM,data:nb6EYzc40VG6xSDWvZ1Bdp3ePy/wlokipl6dJE4XlQx9bZgfvBg4uXs6fLUWo7SaqebRXEj46Bk7fXchOl0MVTpV5ZsH35Bl9p3r11Md9eV4q5Y/UYtCcQANcJWT/gGYWBT+fmyjmtyOayUypAziiu2aGW0jWRWJKDTkIXpyI1I=,iv:eD78AXWNLANWKhx5eUWwDEDaMoDZPSL1uZCSdEpciIc=,tag:lYsIUYfHEHFoJ0/TFyRAfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
