apiVersion: v1
kind: Secret
metadata:
  name: cluster-actual-secrets
  namespace: default
stringData:
  GENERIC_TIMEZONE: ENC[AES256_GCM,data:Zezpa8a6kRYDBftmOA==,iv:+J9QmXenqspBRzAdBw89hg5hix7HVOFtvNG6SMIPquk=,tag:1O2grhoVidukvr0ZGamILw==,type:str]
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:2q2uHIAs,iv:WoIwP/ljSY4AsnaHV5wJfG8Y7hhRMgG4Q7vBigeoe+k=,tag:Kjm63NXxdHBe1yj/LdfxSw==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:AeN7POYG+C7A+cIi0L29+heINiaTCejTbGlNZHgP1bY7yY3VPLMx2k5BfA/qYEs=,iv:Pefo58I0AhPYcN1Wd29Tox2C9WP0MUBYwQE8a+1NrJo=,tag:X2M+/r9LinTlcjbAG1S2pA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWmNDZVVoMWR5cGErczh6
        YnVjYyt5QzJjRTI2U3ZzQXFqbWJJY1FZd2owCll0bm9lNVRtNlMxVkhpVENIMEFy
        eGxWK3Qydk1aQk8welBqbmY5WUlTS1EKLS0tIDIzY2ZUSGpya1kwYWF5U2N1WVNs
        dVJvNHlUTXVOQ05vamt5VUw0Q0ZIcEEKX0EI7mFpDVYcR/fufyYM1A6NJsEZIBAn
        EAh5F4oCHcOobRyUbmoliwqmRsezpIlTKtivrFFgmlUJFqhalU6a6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T16:49:29Z"
  mac: ENC[AES256_GCM,data:4vr5hg85MF4AWozu6criI8qKxzWwpEaNXr63UPQjxf1HiONiO2DhX0aYd0KR50yzBU2gSQMTf5u6wg/kiRLB8UhDTvbRyYilDllv6vDGKj1hXUuvSiAeRj9Iv81B9OUsmCeQC5XcKqp+P+cjuKDv0tzHOdDE0Dqn0Xv/Iqb+Kk8=,iv:fh8YBtY4b4gqt9ncOhG4ofzIafzlP1PRuYK4EWJwE1g=,tag:oEKqFv4OseBs9MKmgEkwrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
