---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama
  namespace: flux-system
spec:
  components:
    - ../../../../components/persistence/jericho-nfs
    - ../../../../components/persistence/lordcommander-nfs
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/ai/ollama/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: ollama
      JERICHO_PATH: /volume1/apps/ai
      LORDCOMMANDER_PATH: /volume1/media/ai
  targetNamespace: ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: ollama
      namespace: ai
  interval: 30m
  retryInterval: 1m
  timeout: 3m
