apiVersion: v1
kind: Secret
metadata:
  name: letibeafrica-secret
  namespace: default
stringData:
  wordpress-password: ENC[AES256_GCM,data:e5w0R7KJXFzYlLU/rDmf+AIEdSdC,iv:NpCp4wwQWuL0lgMPo4sZ5HOZjYs25hZw0TAmxlJtdHg=,tag:MGIjmQ7MIk7gI90FlX0Rzg==,type:str]
  mariadb-password: ENC[AES256_GCM,data:2gpME0kKCkTjoVUkACZOBvG7K4f/,iv:9Q6E6EA4bd5x8c+Sbk3hKyueHLxATQzzcvVnNk47bos=,tag:UOS+SkzEeNxH+msuOyH+Qg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVzhxazhVZTBJUVhFeTVQ
        U0txMytBcmhobVZSREpRemRnZ0tNRmpDTTNNCkVJMU5YVjBPUE1PbE8xN0xxN015
        ekU0T3VoZXQ2N1ltSnF6TDNOR0x4ZlEKLS0tIExuMXRPakpucGJlT0s1cHE3NTBz
        bWFGUzQwS2tla3dVdnYvRENJZUtwZ1EKqj64+UumXBdaj7VB++fbAiHYaUydTfMZ
        C0wrM9L29IxYwtHnrYkhVER86PBry6iCcjGC7r6NquAmdcHn79sJ9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:59:39Z"
  mac: ENC[AES256_GCM,data:HDwAn3FSM48FOkcZk07//f2jL++cRLbgXoKgrYfD5F0+XlyDqntQxB93vlZyTRuf4Xtix16zWW7YNJ7hY84nWUo+Cgcc2V6Yh4eOBTgIYtKIXi//lQpaPzmXDx61TryxZUU4/y6tq7DMFQCg7RTTQxZsMNgYPnJVgxtXRbpyqIU=,iv:eF58zU9vxR81Cefj6/qjtdn88sfVE1GSgp0sTgDM4jA=,tag:co2RQ6Mriz5FPFkbBDtTCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
