apiVersion: v1
kind: Secret
metadata:
  name: letibeafrica-secret
  namespace: default
stringData:
  wordpress-password: ENC[AES256_GCM,data:6IKP7P9dFluaiEznkuBWZE0Ubbw0,iv:7lUvfp2MNSSZ18GjLy2QdB5cKN5ZQXwgTKC8zqWO5K8=,tag:vSbdCtM6G+cLzmJV6ckvhg==,type:str]
  mariadb-password: ENC[AES256_GCM,data:J7KNvO26xnDr9AQY1v5CC7AKqwup,iv:A4M/5I/BLqnbr6aoxbmeUjmoDEVIB6vF0kBGb1QjIW4=,tag:gSG5pD5v7wdN8VPSqqRaWQ==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM1RNWlI0SVg1Z3FETVFu
        c2t6eksvWlpnSFdUZVU1YW1KS3lFcGIwYUZrCjNDaEs0OFZiTStYNVJoY0M0dnFT
        c2FZcDlIK0RRNnRxY0hNWXJBSGxmd2MKLS0tIGN4S1FlOG05aGRqTUZ0SU1jTUNG
        Y0l2UEhJK3lPZFFXaGtLdk9WUXcvK1kK9xNmCUfd76Wn1JSnw+mhmSJ3EUSlCHdl
        j6OibbBl5kz7DbEVTyRXf8VU72O0Q8lXvj6ecFe/KYlsA06HloaEOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T00:09:12Z"
  mac: ENC[AES256_GCM,data:N+pvSxaN+ec6FtG95lc4dRMfTdWuE/r6rti4W1HV+hmrq+YEAyPWEioCPiTfgnafA553MuOBIvD4cwf97uQ9/XfDBrivsVGuR7EyOwMHG7dlRBgOVV+boBIT5UpU8D6Jtm/nk+ksanntMyzcy3/IQ0SO87wNkVlf9LWhtrnP5gc=,iv:7xDcT2SIlt1N+2/KJRQT5h3Q0msxrciJ/Ob4Bgiz+TE=,tag:pptnSACHKTFbACZAFCeeIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
