apiVersion: v1
kind: Secret
metadata:
  name: letibeafrica-secret
  namespace: default
stringData:
  wordpress-password: ENC[AES256_GCM,data:4sZi131e4wdPpCs4a9AKY9DwSUsz,iv:sAiXU5HHcKHkA9jNh8McboMwA9rYuU570xeIspZI0ag=,tag:4NBGjElgsZxVVkEd/8xSvg==,type:str]
  mariadb-password: ENC[AES256_GCM,data:6OT5H6cttgSIlJsjlFHOt+jcRd8w,iv:vhLic9/dsSylcq5GoPdSQ/p0ilnskQl/gmawMVN7txk=,tag:7OL2Unv5wg2hJgEhopxvTA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cTZYOU4yZzk0YmkrWW1u
        VmJaaE9sQ2VrN0xzT25zbk44R2FSMDVsT1F3CkhsbE5DbGFlOGZhNndPSWNEdmd1
        YWp6R3hKU1BCcHlxVGx5bit6Y29hOXcKLS0tIG1hZkxLQVZZTnhuUjY0eEt1K0t1
        Ymk2a3VZaHlMZlFLRVI2dU1UK3ErYkkKhSauZCUJcnD9ijNEdIJcWW29HZMln5Ps
        9qN5k9F1scRuVP9Zwl24N8KHru2EM38PsuvnhRk/j2o89AIqDFlNHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T13:04:59Z"
  mac: ENC[AES256_GCM,data:EblS1ybNHKxDXTSynIADCQlUCBhj+DJSvYn80zYKbqQ5qs0slxSLdLWusCy2dFCO2AaiejUHUx+stLX/hTkYhRmO+KyFZvBn486tW72hQlC1W5QQ97BSYWfeooZgkeL004jCGbIYRUH8kZksZmNfWfJVS/xYY7BYlj3Z5mrQdxw=,iv:RTUZf0OjhMjzI+Sov0ZUABLDxooWnl0yu5QOS5XtcFc=,tag:DqUWIKbidh5zJAm/fTWTYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
