---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: gpu-operator
      version: v26.3.1
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: kube-system
  maxHistory: 2
  install:
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 3
  rollback:
    disableWait: true
  uninstall:
    keepHistory: false
  values:
    ccManager:
      enabled: false
    cdi:
      enabled: false
    dcgmExporter:
      enabled: false
    validator:
      repository: nvcr.io/nvidia
      image: gpu-operator
      version: v26.3.1@sha256:327518e7157e9634eab9aeb51abfba816845fad47177ca985e1b34d202a1f51e
      imagePullPolicy: IfNotPresent
    operator:
      repository: nvcr.io/nvidia
      image: gpu-operator
      version: v26.3.1@sha256:327518e7157e9634eab9aeb51abfba816845fad47177ca985e1b34d202a1f51e
      imagePullPolicy: IfNotPresent
    driver:
      enabled: false
      manager:
        repository: nvcr.io/nvidia/cloud-native
        image: k8s-driver-manager
        version: v0.10.0@sha256:6677437faff2c45506484dd9f0f04ad3b4880aa65b26d11f76d169e65497fade
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_LABEL_FOR_GPU_POD_EVICTION
            value: feature.node.kubernetes.io/pci-10de.present
    hostPaths:
      driverInstallDir: /usr/local
    nfd:
      enabled: false
    gfd:
      enabled: true
    kataSandboxDevicePlugin:
      enabled: false
    migManager:
      enabled: false
    sandboxDevicePlugin:
      enabled: false
    toolkit:
      enabled: false
    vfioManager:
      enabled: false
    vgpuDeviceManager:
      enabled: false
    devicePlugin:
      enabled: true
      config:
        name: nvidia-time-slicing
        default: any
