# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-searxng-secrets
  namespace: default
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:AXpE5bbenM4EOTI+3vjwyvJQmFCf0rHlIRZQBt+Euys8or8ASKR80CL/reIifd8MShYiyprYWlENYJsPv/UqoQ==,iv:Khv9vkqxJrdWFwnv2dBE5vvPgpCvvpltSTLmzbYklNI=,tag:LrGRbbSUl+KChfkALa4HVg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaFJiK2JjeW90SnJUUzdV
        N0lTVENkT1lPTGFhUGNyeTNLNHdJZVVRang0CitxNTVaK0lNcHRUYWN1Y0FBYmNP
        TXAwOGhLaGV0WFY5YUI3WnhFY1MyOFkKLS0tIEZsR0d5T09RUDB3Y0VNcG5qcU9k
        blVYQ1JuaThOWFhTNG01dlRRRHdyZ0UKp0tpNSGaWlXOUFY2xb2hkvfX1VjeTQga
        a6PD1BZGPazm9SCP2WbAOcylJoMRiOdTj4jvpHP1kkENUgGsvNBAeg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:18Z"
  mac: ENC[AES256_GCM,data:AROuCxohyijmpL+7nmtYkcCWjWUecEZUn45dsQ7U8LSZLElWR560bn5aIPR0rO7aapTm6FHgQAjY01BLn3USlTZamHYaLKqzO1tW8mvgag836uTZlLbiGWoeVgAWiwC39A/17/IjORp6XeueGS8foptfk14kd5GTD+aleSg13QY=,iv:0DfWp+cnKxixs9Q5sRIBeuconbYMRqH1xJy2rG7qtYc=,tag:1EEcf4KPAYglQ3KaGgr2bQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
