# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-searxng-secrets
  namespace: default
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:+NK+T42dW7r+OD9xkILomxF5E2hkknRD296gBtwL5EC24regmGUAsd9DfvwxoJZPwRelrpi/Cv5KJUrpT9Ujpw==,iv:YA83sKZYZpfxRirAwDJ+9seDkeiKuaQEI4kUUJomivQ=,tag:GQdjddcSBWVSbLbVO2ZCoQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZHJKdXhIVlRzSlBydGJr
        cGlEZHlJeWtlUnlTWG5MMVY1Y3hJc3JCYVg0Ci85TU5RQTlmY3JJaENyYTNxUnNo
        N2FLN3AxUXBOMis4bE5FeWZacFJxMkUKLS0tICs2TGNRd0NjSDUxTFM1bkdEQzVW
        WUdIcFd4RmFyREQ0K2d4SGVhdURSVDgK3gjHjKQBP+dPmvN8e+pWEhBzo08cslLv
        Hktx9GY/Rqy1fVNdwYAkP57pm8WDuAlVjhC2nm0jTDAo0Vtd8sFuDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T00:05:04Z"
  mac: ENC[AES256_GCM,data:cKeDNYcfRTC3L89uxrBcBCYjc7KxM+/ts6MPnMbtUAmk/z6iyACGVP3BazcPy2IdYYZK5R56NhZfIMdsm+TnAE59luxRO28xqojZ9Lz+DgEcJUpv/m1+NoSdPZK8Nd+dI+wRfFPe1V+nI2b7ssUpI20SVZogkW0xG5oefZijD4s=,iv:EHeD6zAQJgxj9e4iI8chljLQSiN3qLfl77gkZT1UgpY=,tag:GoxV4nNTub0oADk6odbw6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
