apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: default
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:vp28QXqjb7r3,iv:FAQVoYY6D2cvsMqxfnVTlOnSHQ2Qc5Atl5uBu4VgQWI=,tag:un7oKq0Xn8KnFPn97XMfXw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5Lu/N3XTUeflRvjdLHwOBoqDcteO,iv:VcTVLntkFH+WWquEW0fu5+kSptZX4vEWt2PMBVF++4w=,tag:hzwEGuvwXtnqfLPNtf0W7g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:QiwBIWROKu3CEilhLmHrWjMn2J2wF/khQYNfAGpsNsSyylNeIw==,iv:CwhLNRL8H5m9mpA6AmY/paw2E9fbwbo8O6NV6V/rJ98=,tag:P7hITrROlmjdcyeVpGCXjQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zMFtnGwhBCRg,iv:gfmfmSG1zLu077r7DgJNeI7cV/3x59hqlAeyiZp8Pb0=,tag:BqQDVL+dTj9af+HGA8aYCw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:azb6ETS6DMe/lPCAF9hhmQ==,iv:bM51zntJhaHfnxCERDYHg8c15vUV0HlB4Hf2mIfYtww=,tag:BYMXacl5MWYLHYTQ8BackQ==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:UReGtgXQ/aRw,iv:pcpQOkYY8qOjW/L9ez3zjbi4Lk5tIYvWyF9zgQLxk40=,tag:AzYQT2C8Y9UGIajEIluPcA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:c62Vfo3GWaQtR7VeVwuAXKIFmnR5vO4cESElXqH0f5Qe6a1W7zjvv9Kp7jWKoqD/NPONHAQ4WfSrHJWJxZjFnGePAVxXtUTFWg==,iv:Xp29igLAkp3GlCJjog6H5RcONP55LT2V6uC8OE+kJaE=,tag:MwcPm8UacvWS31BxaOjxAQ==,type:str]
  nextcloud-username: ENC[AES256_GCM,data:MU7uhHWCdfYJpGU=,iv:pVf6Xtp+qVv7L5DrFelNxCrChC/5wKFxvhuYPbW39eg=,tag:U4m18C9AQQU5QqWTS8ARaw==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:tPex1IFv05R3IDTNG9/Fpbee76S8,iv:ahTSEu4KfNghGPEBWdi5RCfXoY0OMeeMfmSUeqcHCZc=,tag:5vc6eRaod0yLGQehvHjrqg==,type:str]
  smtp-host: ENC[AES256_GCM,data:nsaEPmA3ki1dYgDmMHQbIY8/r98CHgpDKAVQ2fD4i2bZZ1Bk87tL,iv:kxsVZkwWlwqdhIVc5XF6VAcJPz9oAKoHuyD7xwKrhIU=,tag:eM8tEFOUgioI6UjxRg0ByA==,type:str]
  smtp-username: ""
  smtp-password: ""
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:giRkxpBcniqHTa7iXh7X0UzgFQE=,iv:SKOIZSrI9ifiOmjttyb7Cbom3RXbAhtXEYO3KH87mdE=,tag:62tdySBxDUrJYJs4pLmxLA==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:5cRdqAZIyolS6jVAXoNZG9dGTHiq4mZ/+3lwXu2dN2xl4dcZ5x4g4w==,iv:MzY4aS+T0COxZgj0zANx0pynKIhKLySpn5v8u2KPQpw=,tag:I5uOxRAprFuO2E64iC5+XA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMHhaMjhtMisrYWJJS2lx
        d0d6VUR5QzlYVVZSemtaVW54ZnRVY05DRXh3Ck5WcDA0OXFFTXNXTzl5WVBYZjdp
        YWRxYm0rclBtR09JUWdHZDJtT1JqWTQKLS0tIENkNkFNMlgyQ1BqalhkK2ExM1d2
        dEFoelNWTWYvZkNRaEtCci9FTFJmcW8Kfd3RroxluIwWlUZwW1cqAzES2dLOSgDW
        w1jWjXrKuXX8JlnexGt8PAirEAoO25oUfqTN5VdWU1re+choac9HfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T09:12:42Z"
  mac: ENC[AES256_GCM,data:66Y/Sda6zSsieM+9VW1letwYrKUsyV2zx0AykspdXUSb4UnURLYusqbOZRxiNsQ5MSHcGcqPFOLlubAG31vOZ7VY0Yb10oUqt7lzyLvDED6NoMQxdZtv37rANrq5uzPk9lwZXGQbOcfdT9OI84cCODpFzijyBrhZK7msCO4Caew=,iv:bmeclE9p4TmQIjxVv2peZAvuyor2aur6s1BCV6uD+JM=,tag:P8R21ZMYCopPecQv0zO3hQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
