apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: default
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:5zif91q2Qf6F,iv:XsTajnUDZBcVfg93rWd1ld/hMI5Tu8cthwGZsD0MPR0=,tag:YQlxrs3SLRS6O4Q6aVT9SQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:B/keTsRYeV2kCrd1hMs/acAQAdm+,iv:QZFIoxM3HpZcqISNjUNwN+qsj1ojd8g5HBveQGM+eTs=,tag:xBS00b7hR9UUMCn4nfezLw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:7+SW20YZdvlp97l+emYmw6MUT1JUEYgWFKK+tUFSGOPrJ8U5vQ==,iv:cwUukuFx5Gg3MsRGRZBpukULY3pJnLn0HyR8cxPFJGU=,tag:WFVKeGvtHxf667TjVD8LuA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bRI0xT3XBh8Y,iv:UtZKd/ablEH9PzRl026Xp2DaxuBOycWxx5R4k138diU=,tag:l4m3WvbLH5FzpgQwFaI9YQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Pbt4ZSMHNBHhBbBmoK+tEw==,iv:kfy91KeVwnafRVbs+mzCG/2KrbVJegjJNU2U32LFIuc=,tag:klhT+OD92Fa5mCj9kZsN8Q==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:yu6+APLrhTfA,iv:67OsfElN9nPzBE0X2V5fMN+L4vSPGmFx6WymVV9jsvk=,tag:iqdZrqlJKOM963JW3/N4bw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:a4qIC0axQ+AbWfL3TmBtLGT+lm2/+KjhNxGG9vFP6eNLtcAyq/+A/hpL6DqyXUbBdmGaV2lACE3q/ypNBPCfvpRQw0hg7CrkwQ==,iv:QJQln2k1DCyfuvq6za3oNOlXvzdyBvp/ybvU4lF9QOI=,tag:HooiPg7yp6VMyCN33Kn0pA==,type:str]
  nextcloud-username: ENC[AES256_GCM,data:4EwE5yqPUjV3XlM=,iv:cpux2iJmgJWBwcfhTIGNvjDfKQ7P4FRLYIGExwmCBnQ=,tag:5U7MSH8U6/IF5N6z36QoiQ==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:e3yLvbl35pw9Kvh/KU5gFQPY6fhs,iv:usRuEFgfLAWclkoTOyOILFToahllsb8LlMSJuza3r04=,tag:PgURcgTthBhFP3pZ1b+uiQ==,type:str]
  smtp-username: ""
  smtp-password: ""
  smtp-host: ENC[AES256_GCM,data:riT9EtxuLOjMC4tvOx+qd6c8cOm96AeGLs8qXa47FUn6DXcICI6g,iv:/fOMmxdrpqLvLKK057kYzcKmguBVVsFCEjsVAZdum+I=,tag:q9pDhTMHuEn8XeW/nr/3zw==,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:qsrAjzNWXMD+81xp8goEs26x3n0=,iv:LetgG+AZTOBd7N6kahw7jjDaKB0V1Jup9bOcKmBKnQ8=,tag:CEcWQ2KXOmFWfe3aAaVkdQ==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:ZLAH9ouHknOMASj8DaAMQQk9S5eTsaWHMqQPLi1XFofODeJZILnrWA==,iv:ml4VtdxHum+xorJZ4zvEkCQDO0Jj/L0speyycOqTuMY=,tag:QzTn7k57ko8/ZkqiDO/V3g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MGdBd3d4b1FianhsaUp1
        UHJUZUZMR0VaZVNMYUFXY3l4L0pYWjE3MkJJCm1CelNhWWlYNitWRFVZTGIxcEhy
        MmlydTAyWXNKTnNSYW9oS29Wem45QW8KLS0tIEREWGlUN0NpWTB6U0s3aEFOcnVm
        WFo3ZzB5U1NhbWp0K2xBTGhVcDhjOTQKpXng8IxpDWlhExT/phOPx//93C4oVHhB
        b9WW+zvFCurYy8z5syHYK+tfjGODUke0pNFOmdD8bPztzF3QJaYpRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T23:19:00Z"
  mac: ENC[AES256_GCM,data:u8lcJcye1AGmSwpwAbXUHONEfjfRJuPEgEF42XO8awZnEEMWAePw3HeV7oEg0yvgwmtc/t1lPC9P1HkBxB3noK/dOVHOogc81rZivKfXzsIvYlKWBI2NbY0paDmimAIDeeyHakbL4L1YYLeFjN1dI2R+sniwuywkIH/kjjYocLs=,iv:529Davwv6frHOTryz+mn6zFVbooTzrEjC7A0rj4QJZ4=,tag:s3SOhYFx3HeKz6o7AcbqFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
