apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: default
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:D6u9c0X5bJB5,iv:ZnGC/BgfNW0G3ouBYuNWRKGRpH1GwzeFqai1ND257sA=,tag:/EjDzl45hP/QzGhWirrXPg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:a8yNvxLKJI04jEpOJl+hPWPZ8Y2C,iv:dRJogl+B3+lKJIUYOqUMCUVDpn957AN9elF2vMqDEII=,tag:61V54VOZY0Jj7UcWEnqcdA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:yUrXsr2I4YSGEUq6FgsNZ/wEo+tp+HsTRXnPepIQG9FLp4kQWA==,iv:femJTBOpQs4tSK+TMW6BcEQlhCXnduehnwyJnOp/rSY=,tag:xoMB9ltAzYK4z5JexUPasQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:g/SNwmAyuDFM,iv:0UEKpE9X1DXreuCDbHkQFR0JNm6P/Yjp8QA/4rt5XmU=,tag:3igzIIxtTNyyMTIwluGrtA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:a6xcTNg9ggAZ3bFCyti3HQ==,iv:NUhgr/jEclovzmLOMWXOv5feKOfgBL/SBaSs+ZrQGXI=,tag:5x+4kPC+BZv0blYYlXtvBw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:6eAZjam+9RYz,iv:2YhSABGCF8FJAPOOjQjEC/cpmxR1UVeUyRtXF5OSXkA=,tag:lYbXiLHiIpbD6wz+EbtW6g==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:oQe1j7SjgGvXN/ivR+4RvfQoXNbeYRjZcplQx/jB7SvlJfDwHElzzSHpIq54qOMhjt9Hfs9aGBQj2hVKOgAy/OZegMa7NHkLJA==,iv:29PLHk+PstDb3zWmPRaHI2BLvUeL9ND/+x1Ag/GnOfQ=,tag:vtS1LTYj90avS816tXTppw==,type:str]
  nextcloud-username: ENC[AES256_GCM,data:wo6m6iVZwUnjNVI=,iv:QP4euOJzJHIJIFEAG8czGlnxRsmCy+vQl4sn4BPTmQA=,tag:vn6silQ4LYxnsnsqj8neZQ==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:p0rvnd5LevZKjsqvBOfXNmjd9H/c,iv:R5Cg8p134aipX0yh2m+39j15mNZyYp5T33IRwGQdT/M=,tag:EaoXDRjBzaLWVuCUmgH1xg==,type:str]
  smtp-username: ""
  smtp-password: ""
  smtp-host: ENC[AES256_GCM,data:MKK8x7p3MwztQHyssdgB+2H2IlCSjeHcsFTOxlMjhZcjLbIeQcrm,iv:admmdvpvU1LHoQfmYVfQWnAoLkIdRnPw7NmX7DQk02U=,tag:mNnNHvH4IKOdg0dTvz70Kw==,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:SAFsaoT5CkFCW+8+mm8G3fbSbiw=,iv:SDZijp8z0Yfs4R32LEGJA7TMdAcuiSiTqLB8vu4Bwpg=,tag:BC8zWQKZkhTTjsA4oy5Ksg==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:5lLU4CNoGTdPT+5LswxSaKZuIYqlvr2DvMLKoGKn/h2HJNhVvxbesw==,iv:vGoX3jMScAQ9EQSdrg9OtRCKi9YLhMpx6dlbbw4J7r4=,tag:xrhQTHnoo2VCrRUWg/W83Q==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Nys1dGtBNENReFRQc3lj
        MHovbDZyRTNOVmtRU1hDbDQ5SzU2WHUvOFdVCi9peVZFMFNISnBoTUpwc0hVV0tW
        dzFnUUE5S1RaaGkwbXJ4VS9QR1ZRbTQKLS0tIFQyZzJTOUJOV3pab3h1TDVZb2Fa
        WXp0d2I5MzIwMkUyUjAzMnBZVE12bHcKhZBCG+2GGhT670s/9UJ4PUMiNcSbkWhY
        GGQ5Je6eHcsR7v3o7fjT5zJ/JLyUbHWMO8PkK/iWkUeNrH3LDDGaXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T16:49:29Z"
  mac: ENC[AES256_GCM,data:I6GN0zaKxFMYC/lDb9Cv9/04T5slKnnrn0FRuTRPAH9Ohwdja/icfS3l9OTaeuAj4Xpncb21V/VnU6I9Ca8FVDspcomAwsECiyX7cSXP95DnvYO1U1DdGCXllNGyyJTBv45/NShPnqn8fNBUO2dXs8XFcXSF8U1hPrITH8OI12Q=,iv:6be241bnVikb9bHd+1DbZOJbjG/MUD1hS9pZOQjExQ0=,tag:6etFRhV20xIhf3rsFi+03w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
