---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm-database
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: litellm-database
  path: ./kubernetes/apps/ai/litellm/database
  targetNamespace: ai
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  force: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: litellm
  path: ./kubernetes/apps/ai/litellm/app
  targetNamespace: ai
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  dependsOn:
    - name: litellm-operator
      namespace: flux-system
    - name: litellm-database
      namespace: flux-system
    - name: dragonfly-cluster
      namespace: flux-system
    - name: ollama-models
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: litellm
      namespace: ai
