# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-context7-mcp-secrets
  namespace: ai
stringData:
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:ON0h0NkXPexIbNUWpRy/Vd40E2j4vshZvSUhZhQzdUQ5BcK86NF8Hk2osg==,iv:T2laaQN/9flewaSVWPGp8R2KgUBjLTzfRG5h8CYyQD0=,tag:XQS4qKJlGeOgirJekS9WMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRTJFTlV1Uk85VURqZmFn
        OU1EVTdTc3hwN010Z3hpbDJjUndiMXJsclZNCnZUZFJKeXlUUm5WQ0QxUVFZblNN
        QzIwcFhycUg0Tkw5NkpOZ003R2xSUlUKLS0tIGdKUm9GMFBJalNtaHlKQm1Hd0Vh
        ZlNaVjdQczNpbXpZNDB5eldLT3MyU2cK8ZXIWFcfp8K96WaTpN3BcLu4A+1j36Ln
        dsHKbJDdUsOPkB9to8BE+XvBpb6ASRIaeY2nUF/3aW3dPm/Wm/vHxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:18Z"
  mac: ENC[AES256_GCM,data:dZuaV0M1emNzpTXKcasnnQFYPNOsis1za2Wc/1jcsyri8JoHx0FTrLXOTRi7/DFGfxHcUInyPCnCFggqGHrIuZ0nq9aGYlgs6SpPCnor2G9ucBqYCpWiiQRdaCiHeJ2bvmaMEEgdSFOS5t4M/cA+WqdJrXB+tX7EsxhHt9FdelQ=,iv:uJR4yNh96SdS7vb9po267TV8AzvsATzzcRKzU6U6uTg=,tag:0C1y7fvmKO1YYASw1pRS+A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
