# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-context7-mcp-secrets
  namespace: ai
stringData:
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:YrfaCqS6tN8wAa63hzhYrSLjUCXShupKbmBPYdc9lCeko/F9/JEOZHyTqA==,iv:P0eWF2TUG1vcxzD+O0Tof8d5soThjg1PqYseITH0CVY=,tag:zelr5c62rpnjYTPwy5cFmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMzlUZjFsUUJIM0hyZDB6
        eDFyVnZXeUdpaldGTDBrVHZ1QmhYUWJTYWgwCkNvYWtqcCtRU2RDSEtMbHNieFMz
        alN3YXdxSkpPSmRpVFhqdk80L2NUcjgKLS0tIDNNeWY3a21Xa2tDWU1jY3BqNGJH
        VCtvYWRpaDNiNG12anpVVVdJdGo1RE0KylYr9yUUSDd3AuSDc8t81a4HRdBI6tmx
        3V2SEijCmSju3RxRMlukcGq+xcJ6/Vq9VmJZcBCEFn7ZiHx5D/YsSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T23:16:42Z"
  mac: ENC[AES256_GCM,data:7vN+8l9H4iA4AH+lNDXXUYlJ9p9iZLyn1iqlvuIVwpmxWHVyEGyuG6wLjD/NBMH40IXrFKS4HCc2GqLohCulrULvDRrbmla5kt0wtbtne803fbp6HULw2Bqw8xnrWPPWG+kWqGcUQ0NOIguxxzjTpW/uvGyg5tllL910Udgouq0=,iv:bF/UWF0/q1cwozkecT1KQfB0xOH0HMcFXVuioXAZmfk=,tag:IM7jeCRn/2+2MhUxyJFp7A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
