apiVersion: v1
kind: Secret
metadata:
  name: cluster-grafana-secrets
  namespace: monitoring
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YlcOWFCttA==,iv:+BVFBgi2IxgK+MG5JhGt2BKkLvCi2eay+eM09TSG80s=,tag:gGsXkRt0FwFBAooUK4n9Lg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2jXSQxJDJwvnD1skEkLnT7TKKo6AfJHX6bziBlZSMf04Fu61uA==,iv:bJW8tQiBkDdI0EhxDZj2Hbi18XezctQ+c9oZqyR/TDo=,tag:qrII1uZSRoblvdRPYGUsYg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:dQKStX0r6w==,iv:ImxxJ+Kj7RfoadGyft6m5IIyft/TIgZv773xmmtExbU=,tag:2dSRR6Fd4rhsFSCWtp7/xg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:4BqhfRb2pyIeyeGHeH9KLb2dQ0Sa6ljn,iv:xqlf1cNmrVyzCnDD/7DC9w2GUQo06OledNFmSt552zc=,tag:vdsFeLBEDVN9f/M9qb5zqQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VF5I4H6IfIbdaVzVyqsARg==,iv:p6b+8G5PrzFT00VoP6DYKo4HHXW7IBbf7eWThsQSrBs=,tag:py7c+caHcJkrFN0Fbm+c9g==,type:str]
  GF_DATABASE_NAME: ENC[AES256_GCM,data:3WSPwh0eOQ==,iv:CIUfzkrQJ9Lb9MnrpYBlMqBkvu/OHBVq0Amg7uHgOxs=,tag:RIf8DHG3hXoJT+KtS2ioEA==,type:str]
  GF_DATABASE_HOST: ENC[AES256_GCM,data:m9h4VygXrMGv+UTqmqBVWv+wHWq4YHe/9hEA6Ia7j0MExXB8xY1nH6ab,iv:+Cr59WLzrJgdhork0B+9kEhZj0t8K4FhGdPO/mZJ0Kk=,tag:C+/GVLHWcCMG0Mhx6w87Vg==,type:str]
  GF_DATABASE_USER: ENC[AES256_GCM,data:d/mhglhysw==,iv:uo+MyIs/ODRsySMI95DkGhh6811ghBzc58cNPg9eg9Y=,tag:87CyBRApoMmB1A6aPTxRSg==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:aLiUsuzPHS67UjR1vu49BYWfjxH4bOtA,iv:vlksTRjeMiRN/sey/XJPTtgq4J2glql0gFiOpQ8rOns=,tag:awiYSGroiGjYfmyBkV99Qg==,type:str]
  GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:l8tcM2LQKQ==,iv:B2AZXAnKKyqFhbUEQA+8sf/3XyUkQ7eSoov+mPY5pVI=,tag:8+pF3ABECsT/X7aw/efbOw==,type:str]
  GF_DATABASE_TYPE: ENC[AES256_GCM,data:rSyX+WerELM=,iv:SnGDwWpAeWSrBPPFoRSEblra6E4iiAn3iZ4IbQQH4OE=,tag:AkYYYIPl2RVavcamZ4G+Yw==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:EHeJlzI1a/5G+YicqywbT8i55v9ogoT2OOdH51OL0j8=,iv:TWD7Hseg5zlSvIWbd77TCVfjeWAy1cAtGmWv97gX50Q=,tag:NgcoCzxXoMoh8RD9DN0D9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WlhnUW9GK3NJNmhxNTRQ
        L2UwQ2wzRFliM2hVNUo4SFprNzFLOStTM2c4CnUwdDNIU1h0SE5aR0JLWjAwOU9Y
        TWIyaWJlRkJ6WEVLakpYREVFTWpPY0EKLS0tIG1UWUxtQUlacWtWYVg5Z3R0cUhT
        a0dMNklOZSt2YkVLVWJzdjdDQzRyYnMKA7HNRR9HAxjlP55EiUsk3yCQhmud8px2
        KuxeNFRL5mymfhNz+v5g0O0fBx6QlM3HvnLlPnT5Dg5SsLq4RKN6EA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-22T12:36:45Z"
  mac: ENC[AES256_GCM,data:Z8SkNALCmjsWh3nSyI2xbNeq4nLbKT3b/e9y0K2I63H1sbNv2a1XAqgIJAV/jyUwbak2eg7AmxPvIbfs/VXgi7nG20wObDZvqiZ2XoaK6W9pfkmBeAEwIQWAfCxpMnMsUC3ixrfAt9kFJIFECarMTlPPcdncgT0007cnWdswCQc=,iv:VpFQ6rYpveMcPmYZZYsaijF8QSRhYi+d/Pzoe1I6dzQ=,tag:/OObgord+T7+q2vdT9mydg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
