apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
stringData:
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:U1J3RTdaNM3UCaU=,iv:OUNjFaCSYQExwJK8VJnugUIZIia+9cW5wtST0bOe4G4=,tag:OU3PvjHzUPq/AMn+WpuqUQ==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Q+CpTIxRSFIDCD18BJ6ypg==,iv:blu3Yp8HfhfRymkqN7UoTk08mwdbD4ba1f23JA36S5E=,tag:mO8yXQPS0ABBZfNRa4JTVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYmNVcUZ5V3EwZGI1VDN2
        N0k4YWVVL0pkcWhweWxQOGdtNitnaXBDOW1jCkNNL21KSEt3U0U1dlkvVzd3dllO
        NjZBY2ZSWU11SXpHZWtaTlZGMjVxc0kKLS0tIElFejFRcnlNZWNjTUNSYzd4Ynk0
        RkxtdkZaaXZPM29Lem5XUGRBUTVNRnMK/JfA5S5hPZXOMaPS+NdWTowDBgxvYT6X
        CTi/Uz7OhNOZK5aHKi1ral0TzW3xUaz5J0OD6CiwSt2Wy9mjVj+qnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:42:48Z"
  mac: ENC[AES256_GCM,data:MCuUqZP/800fpvOrAzjCIvIeKXAysqETxQjSn0kcb7Qh4bNDiC3RjGGMgIjWatdOxP7SQD/N8i6w+86gSPccu/vAL5JpdJGLij4UeW0mh4xW/1y96ncHfPCy8GJjaZzvA4mO5ASzPHWRqxIoemqr+dvKOsDal21vXEkYyWgBQeU=,iv:914fVaUKVjb+9+N19wxbBeuq7ytNyPy5bxVz0ZfMdSI=,tag:tN/XFj06eb2mtFF9NrxIVA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-grafana-secrets
  namespace: monitoring
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:JUEIkTNMbA==,iv:6wLUOwGHmjj/KByh+MRtVmwkafolD14jeiNhwi4x2Pc=,tag:bYMr7jNWKN9WFffmvTdX+Q==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lSEN84UO8cS6mh2MIWIvpsp1PU+7l4/juSem2pFprG4=,iv:fCLliYzMRfpEBwMZ2QzAGEZumU5TC3eecX9YAsaLXuk=,tag:hq/hDl01Mq5HP4rGnaYFwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYmNVcUZ5V3EwZGI1VDN2
        N0k4YWVVL0pkcWhweWxQOGdtNitnaXBDOW1jCkNNL21KSEt3U0U1dlkvVzd3dllO
        NjZBY2ZSWU11SXpHZWtaTlZGMjVxc0kKLS0tIElFejFRcnlNZWNjTUNSYzd4Ynk0
        RkxtdkZaaXZPM29Lem5XUGRBUTVNRnMK/JfA5S5hPZXOMaPS+NdWTowDBgxvYT6X
        CTi/Uz7OhNOZK5aHKi1ral0TzW3xUaz5J0OD6CiwSt2Wy9mjVj+qnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:42:48Z"
  mac: ENC[AES256_GCM,data:MCuUqZP/800fpvOrAzjCIvIeKXAysqETxQjSn0kcb7Qh4bNDiC3RjGGMgIjWatdOxP7SQD/N8i6w+86gSPccu/vAL5JpdJGLij4UeW0mh4xW/1y96ncHfPCy8GJjaZzvA4mO5ASzPHWRqxIoemqr+dvKOsDal21vXEkYyWgBQeU=,iv:914fVaUKVjb+9+N19wxbBeuq7ytNyPy5bxVz0ZfMdSI=,tag:tN/XFj06eb2mtFF9NrxIVA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
