apiVersion: v1
kind: Secret
metadata:
  name: cluster-grafana-secrets
  namespace: monitoring
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zn7eJX/r7w==,iv:yfWu9EnQt7T/1ZM9D6jht0lt/O8AJjryLKBy1OLhlHE=,tag:TDunYdVYcp6q8+uYWkuEyg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:lPQayh0GnYuCgst9LTjc4T21FpiIO04Bn6NEqfMPLDTRMg7FXQ==,iv:11vO3EAHJxu8JcV/D3TMNhwr5ZyntwZTWj2fkNiZTlw=,tag:gGem2mswhvDM9/iOl/20zg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:qQqVFVXABQ==,iv:5vewshOWdkw7IPwOzntvWmhlALTGHYAhx8RD1RP6LH0=,tag:tWS4+FmUe3vmwqKsnoQd/w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:pggXK+MSKO++0rjAzPrY/gUnoQTyvYZk,iv:jaWs0kNofve4CWxBAE5w3V7dg2zt2DgP6ghTYf+an1k=,tag:BXQH9OT3ZgLPl6lWP4tnLQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:96JbB409sTs1TkacUNnBww==,iv:RHGFsqiQjMmL4rc4YBCTh9lriEu5ImaoFQb8APt6nOg=,tag:sgeIyCe2MsiJt7Djr2FcnA==,type:str]
  GF_DATABASE_NAME: ENC[AES256_GCM,data:lFG7azkNpw==,iv:Wj0gaumJywp9Cqdpd8aq8bsvGvEfNh2yk1ACB8m/3aI=,tag:lRbRZ6CafbQy2ZZups/u/Q==,type:str]
  GF_DATABASE_HOST: ENC[AES256_GCM,data:ENsYdo0vnQYJK6baCHiQAT0Qt6a/ZRMPp4qbDd85TkUNwT2oB7ZCYi4i,iv:ZLgtyeb/E/Rcha28s/cHRHqThTqtYvUyxp+9FPODxOc=,tag:5sf8JTNltIZXYbLk2Typmg==,type:str]
  GF_DATABASE_USER: ENC[AES256_GCM,data:C9YmK6SQiQ==,iv:t9bfV+7cNGkS1LufY6n6Ik99ZDcH8BZXQB1aSJbAHhw=,tag:tzz6V2pznCUBq9FPM882kw==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:6uEfCabOYxf8JxVCasUK5z4xB2Q41BeA,iv:2dDjghWOrF3JxtvVaOrDBYOuZfo1AhYDqpYAeYvpVEA=,tag:ow2woUod/1jTSNjjbA1QXg==,type:str]
  GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:kuuT6IpEnA==,iv:QdIqC3zQPaImKMyjvZ7dBGD1pfzU3xnpi/yqXOz5b/c=,tag:CP8lApPuT0N1KykzJACj3Q==,type:str]
  GF_DATABASE_TYPE: ENC[AES256_GCM,data:G5fPzwBPVTg=,iv:nnzVnZoDH+tkZejnHgUh6tJkMvw15ZeJM59oNxGZCVg=,tag:NGrMgq7P3rmil9F154beKA==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:86HFPjCuaZfTXJEWd9nxvxn0/Rk/i1/Wf5Id1hQsBPA=,iv:lb6owAAg/dZtJsWEXHYVGjikVvyC0iULIPVDS712HlQ=,tag:+Zx7UBpzGOKzzV7IvtaRXA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTXNFalk1MkRJYSthRUN5
        OWFhUWF1T2xtdzk0UzljSDNyTVFaWk9IcG5JCk9rRDNwZVMxTS8vWDZLQTgwdEx1
        Y3EraldHc0dlZzVScFRwbkNkRVV5QTAKLS0tIE1yUE4yY3JhaTdVLzNLMG5NR2N5
        TmN1RTJyRjZWTXFVTUpMUmxnRzUvenMKc+PeqXh+8daKA+QwXKY26rE+adGK3bP3
        nPltUyiKxBd1zuuPM2uxPCKvhnS2t8KjVtaUOlHvx5L07ROIuXcbUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:40:55Z"
  mac: ENC[AES256_GCM,data:do5UblhU4/bHsfQr6Hur0sqiJ3Wba4+rAAYvflhXF2VL+4Dw7b1MOajl2IX/9qMtN1+qfWwgsN+bxBFjguW4Yd2RPqBU8a1+AhK/Rrq3/itXHFKv3Qc+XOljB3EtfqQuwx+w917QEIolLPqAeVRJHxxLVPmieJgXOPii+yWzaPg=,iv:1F3Sbr3KBWXM7ZiT/QkMApKPj4B2U/8C+Oq/M2paQq0=,tag:gjLg0TwG3SoK1nVsZnjQHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
