---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP}-lordcommander
spec:
  storageClassName: ${APP}-lordcommander
  accessModes:
    - ${LORDCOMMANDER_ACCESS_MODE:=ReadWriteMany}
  capacity:
    storage: ${LORDCOMMANDER_CAPACITY:=1Mi}
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER_MEDIA}"
    path: "${LORDCOMMANDER_PATH}"
