---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      jellyfin:
        pod:
          runtimeClassName: nvidia
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: Unconfined }
            supplementalGroups:
              - 44 # video
              - 109 # render
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
            env:
              JELLYFIN_PublishedServerUrl: https://jellyfin.${SECRET_DOMAIN}
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
              LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/nvidia/lib
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 100m
                memory: 8Gi
              limits:
                memory: 16Gi
                "nvidia.com/gpu.shared": 1
    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${JELLYFIN_IP}"
        ports:
          http:
            port: 8096
    route:
      app:
        hostnames:
          - "jellyfin.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
        enabled: true
        type: nfs
        server: ${NFS_SERVER_APPS}
        path: /volume1/apps/media
        globalMounts:
          - subPath: jellyfin
      media:
        enabled: true
        type: nfs
        server: ${NFS_SERVER_MEDIA}
        path: /volume1/media
        globalMounts:
          - path: /media
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /config/log
                subPath: log
              - path: /transcode
                subPath: transcode
              - path: /tmp
                subPath: tmp
