apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: storage
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:JqaLN8P43/ThQFgOkUlJKZl1ge4=,iv:G9pLI4o0JU2lszGyA6LANfpYTVjnMxtzRpNqai8oV5I=,tag:3hAYgUww6ajBXn05d01DMw==,type:str]
  MYSQL_USER: ENC[AES256_GCM,data:XJ3IfpUijttfHHI=,iv:Diec7Juu/iPRFrMTGoChZEuQQ3ynbNDLcGwfWUZ6Y1U=,tag:tFU8EupIpSokSHyc+T6H4w==,type:str]
  MYSQL_DATABASE: ENC[AES256_GCM,data:GIVRR+iE0w==,iv:h+4epN7XxMEEhTajWysf6nCvyyT/xLcQNWzhvS6ppDg=,tag:y+bHr/SJfq4Hs0GVWfcOaA==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:Px59EGizAxsvUcK0K1KbsuCnHjQ=,iv:y3KupmGvQetclvSjUQZLeFrcS2PMMQoG2vJLwkkQ/AQ=,tag:OVeQphcDrgvBwM0Zdcdr0g==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRmcwZFZJcFk1dWtubTlO
        WVBXTEgwOWlmYlIwLzgrZVJLRlFJQk1Hc2o0CkdxVnEwOU9CdjlENHNuSmdRQ2s5
        Uk5odFVOc0U1V1piQU8weG54emZNVU0KLS0tIDEvaXV0L0lrQm10OTZBY1ArUStS
        b0tGajNVZGFKYXBvckFwbzZtTXZpVGMKJInA6tDMESTyf6/PCLqPYo8FXD1XZwUG
        vKWaXZmboWren/EIizifHzghMBYMcVisO1r1GrgK5p6uNky6KwjxgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T00:43:43Z"
  mac: ENC[AES256_GCM,data:d+20ryrRetAvRRYYUZsU9uSWml75xbd5KdggsTLCb/At8kwLa8zNXPS77hdHxpcuUgcWdOzsbXJbNYRNMY/fVmHszD5KE+Yz9Xe6J7/dW90HPg8CQ/EfEVHxm6Gq+Re2hQ7Rkm5LmVp7z+finTj8/8KL0z/YaLAzRTQOHJT79bM=,iv:QbSXBaDTz2asQpdCQtDzNKTdxZ+5awql+WpEUQ4RSOY=,tag:P+T6dw49DvhjtuaGcVqasA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
