apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: storage
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:yQSMhSLt4uI7KbjN/aO8Jjmk9DU=,iv:TayelPItIniiDkiVc34o34OP3J51f2kMtxTDHr6tvus=,tag:vCYLKNXuK2hgeUjFmv3ftQ==,type:str]
  MYSQL_USER: ENC[AES256_GCM,data:h/1+5k7zLjuwLN8=,iv:jg1+nyvBVcnsmSEE2FCjDy1tEvlKFLu/pxWoj5KYRRY=,tag:xVt/c2UCxAC2rZXy81+jzw==,type:str]
  MYSQL_DATABASE: ENC[AES256_GCM,data:LhkBan36Kw==,iv:5vUT3puem66F9EZzu1h//Efo5VtI0C5XD/xQJfBB2gM=,tag:nwdfGCUt4wiyNbKzNS5G+g==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:229p5SHhYcTKE3Nghm/RLDT81es=,iv:ARnX30smWqebAnnVQ1/w+krGX+Iw9VLsPQSO0dQuoZ8=,tag:PFIsFiE/y2M6M4KQJZBx8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVzRNdHB3YzEwQ01kekdl
        OTVhMHlvdmVZU3M4azd6OFZaTXlNK2V3VVFNCkVhZ2pScExXQUZ6SnFHRUVjcjhh
        S2cralFPcjRiZGFGVjhBMWhvMWpOOVkKLS0tIHlkZDZyY3Bxbm5XRDQ0K2JxZXNP
        YWZiZm9QUnRIcDFuQTRidmhVSVlXUG8KCx8SciR3Lj1Z7bLj0FrZJtpJ8gbqqXrK
        hVVovRwbWkntAOyweRId2CQKLTAf/vxzdL75n73n0PnyZyx/73O1jA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T21:54:22Z"
  mac: ENC[AES256_GCM,data:xGw9ig7Nm4xLDsgRuTPLjuVvd7ne3vbNZbXKTId/5PqtvBTLyCVq7E7i3konZxjq9lEhxs2I8Ln36Zts0sTGGtrLjyTEzduaeuWaFigc5P58mErW9gTIYYyWSBy3bN7d4s93udEBj5a0BLA0sdyiKCbcZCnb6DjLofLDke2r/lY=,iv:EyZj9uZa9/iENXjMi+JmaJBiQDhZpgGCfACdx7CTpZ0=,tag:tJW2fyOWuS0gEclA3dhUZQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
