apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: storage
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:mycbN3fkEYW0OjIZMWJ4swtm9is=,iv:E+VWHWLRWJHzTmWiTz3buKRS7r7q4AgIXcYXGFmJouM=,tag:a8YKlb+SNU5N+a0bmMmekg==,type:str]
  MYSQL_USER: ENC[AES256_GCM,data:X5pjmwqUIu7+dGE=,iv:kAggW3fVtuZDjBdE0rQRASOxHwIaMyyvXFF1ZnW5nGk=,tag:wgpziIZs4C7jg9H8jKs+pQ==,type:str]
  MYSQL_DATABASE: ENC[AES256_GCM,data:nyVNo45EYg==,iv:+4xyPLE595vwOc9TEMXWcsguutbQ1Q+n+HMvtTvv3ws=,tag:VpRipNClp2j5M45sD8Zu8g==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:ZfC/kWkD2xP36HatRQH331zTlA4=,iv:OM7IRoLrbks+r41A8GALjpuyRFjEsG5ub73Jnup4gUE=,tag:vjE3qp18Wtup8kmsd2D+Eg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTi9lTHhuQ1RJczdEeTly
        UkdZY2R3VU8xdG9MeWxGK05IZDBmREJCa0cwCnNMWlpxZk84bk9Gd2xmcXhDWHhS
        enJEdyt3a0gvL0FKNHVtOXBqdlBPaEkKLS0tIG5sYTllZlY2MW9rYXhRN0NEMXdK
        VkdWMzBPS3BvZFpJN2VMTVBPM2JDS28KoE4/m5MqFCE6cOYjwtuV+SiAuij0b4G8
        guh9rzPhD4sCbBs/tsJfFW98286aO85FbyUy08dJva4err7a6Q4w6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T17:17:15Z"
  mac: ENC[AES256_GCM,data:WEeEuCuKZFyNsE5D+GC3IrBS9aAoXOkMv1Ep+xBM5ByAEO7m00KSCYkJzrQvk7VLlg+Od4md6uOdikL4OsgwXiwWXUjaI/GX400epBkLSaYJLVB1bJxkrGyL12pyn1yWBh4XiKKcUSSTSGyuTuUdpLQ+vf9EaIMd4N4TnHqGTo8=,iv:NTh3U0etQephuqaHetV0IXxE6yXWXabO59n8VeZc8Ck=,tag:itifwM1AIJiE6JOcWoCZrA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
