# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-litellm-secrets
  namespace: ai
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:M5+CfkGLJt6SzdSyE1UyI/lYkhRIYtigbVTANOyHvg0XvUbN+gGFmrwto8F4Y+vLQG7/UfsSBmhpkVxx5lmU7VLtIY7EijC+jYiBwhJsIr50MgL1F4QcF7hNFhSfP46YlYbXAa+aEvInDeJuuBb8vJf2lBnswvgrAmAcUifAQm/Byo87CkmQCw==,iv:Co1rNwe7SQ2tRSisjrKBRUXln6qG5J3Iti+G1wbRgEk=,tag:KuO06DbejOeNNe7cQHgsZQ==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:jCrQt39XEN52RqYqCcdvjYf7x+tmo+yRm+ovbvlat3Iz+r439t8FaXpzJXKUoHeIKwDInoNIwEzEGIjYf4GOLf7opQ==,iv:UR+DeORbqlTygZlVh7ZvEqphTx5gQItajD63cogEEuU=,tag:KsqO7G84n7VFTFpO71XwEA==,type:str]
  LITELLM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:X5rQXzBWK07Tg/QTYH+H1PGUOKr0poe32P/BWwcK01O4Y40Co3COylKc3RGxHrbTnkRZp5U+RGle1J6ihrbRpA==,iv:ENJrfLEfK3IaQv4ynq8CWvZLM7O/zgVXlljiqUwSnz4=,tag:nRLWHCbIFFeiwIDJAoDWDg==,type:str]
  PROXY_ADMIN_ID: ENC[AES256_GCM,data:9H/8L8YbhGLwIh2uP3xwxnYeLw==,iv:uMVFyoIcXYWk+JahKbaN6Qgxti7PrttytHN2WxfkuKk=,tag:iOOQfTNcpLYGHgFz4pbpFQ==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:6F75rGNEYAycRYz9++7Cg6j+HbP/T9VOB7UQgMrNJWOytK27GWlC4TS64hTp8fFCm+2O/7p2O7sHpnS/F+oZSbIbvKdvbB7HyqlzNDYa/EQBlFXm04GAf5P1wK6XP+IpnWMGQKudcwLeg2tf95QEG/BiJnEymlYOcaD7Qibl0dDWN4vNC+X1FtPI561328W4dGgeFRZZBqVZdl0ucMc6JpX7t+0=,iv:bVsj3CM62hsUCPVkePajoa/ISYCCIzrkG+8KSfPncJo=,tag:LP1S+E6fo+re3Skgdg+DEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRGZROWZFMDZldTFKNk1Y
        QlE3UlBvak9IU0tnaWRiT2pRc3JqKzRreWdFCitJREFpdC82VC9VcGtDYlJ0WjFu
        QlZBVmFvanpJZGZUM0Q0eUhpbEloVHMKLS0tIGVDd1RnYjZ5endDK1ZyL1NPM1NU
        aFF1VlllbC84VkNXMjE4QlVZNE4yMncKyW/lyRd/aG6MZjZw5nihyzyAIF6gW9R0
        cyAGchzXKlj3qOFde68U6rYRfvmmi4NOz5HJ7Gvi+EldKlKnyjxdog==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T23:31:26Z"
  mac: ENC[AES256_GCM,data:kAKApymOYVfvXEBn7vy0dy5MtsXJyufuuBC2wFkHHDH6cCWpP/Dy0tLpmEgYH0nSCu+9PHag6+D5au6O+aOXqA7CR0m8THeFmh0Gi2a1/i3XPKOi7ny4jkRuWzIbJr/35pPQw3hJ+22VoG/BTqd0qWNMlizryjG1nGiNRriO1Og=,iv:vQPmJZvcnp1RXJl9+xerkkuELTsiV8BHrCgknIymqaU=,tag:tsAH7BCwkaYk451aehlOAQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
