# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-litellm-secrets
  namespace: ai
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:fhHSJOPYtQR1kwOA34owIUz9siOgheayTLPU8lq/Rb77Q2ovKEJvAhqChCqy2Br9YMAxJlJqyAuUpmTqP4Ke6l5UkZB+Q0SQLENFX61U2SvWkskEeLRTahdxklmU3ClEn/jIW+c/70Lk7OKifSu7fYseMQ9jdKB41aIhpGYrVPNO+kQRnwimfw==,iv:xt91AswQk0vm+Av/I1DRsxWhWaxgcm+pm3naRYHLpCQ=,tag:dfTkCN/NzrIToIDJ5IupIA==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:5S17lvSZrciqu2J7kCCaOmm4gA+vU2ArTpHWBCUHjL6egsfbQ1XEb6cMjVpPBKZILiqQshkBPAwLRv67B/oJq2mCbA==,iv:GvJkWPCLNR3MlPsgtVW94BnUh9xetFxITbRUXu9GMbE=,tag:Kbkz3CtzvFvjd5XHhi568Q==,type:str]
  LITELLM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:RdQVOHy3TE2QIbvqKeG9J50wLJXb1ylMCttR6Yx/5mF9UquF2pUvDTMDcJ56x1daiJPdE4bHrwd4gcuI/Zz2JA==,iv:BC3HOv0QKh4fvmxvtOwTEk+6RAuu9KaJ43ourjpiees=,tag:nWvZwfR617Z+0+scuOcmJw==,type:str]
  PROXY_ADMIN_ID: ENC[AES256_GCM,data:dzpWWp1lltv2HdogBdRmktlwtA==,iv:HRD+qenDWN/+5oFY82ACcV7g+eEETflRnI2aAvwyMVA=,tag:AC/rhz/pyYXDEfed67l3tQ==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:thohJSgo2jNNL7FqX7h03ABlfP1DZYOZovIhostiIwAHEH7tcZtp62K18u9SqKEwOpghozPtGfr9S25iWWhktvSGsKGaMTbieHw0tbpp+MIGjvjQRcPKsp3ulbvRwuwBkDN9si7yuwEolXcOSWBQjcKt653FC67H4g6YewS5udMzgMXDljhBQQpqHSxMg8xXR/vD3SnDSSa3AxzMmcLgPH4LH4U=,iv:NCDfPK6uNOKODwl6GK3dogRT3yOo10EkxbmuLmb04QY=,tag:bPYtAFWMZX4xPLTCoZEH0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVDJSVU91L0prNG4vdTky
        MklTNkNwZXFrWml6OTJNQ1o4ZUNDN250ZkMwClBiY05DQldjRXBzNWxoMWVJQXhD
        emxPZlZJZTVVUHNiUHRmOVRpaU5DRFkKLS0tIGVZU1dkSGNacjM1aFkyQmVxN1FR
        dnRwQ2xCV3ArNmFFdnFlU1Y5OEpqZGcKozu8Bq2pWiprrOXchdISntBRAps5qNIh
        MXoewtYDTsvF61gdAu47OAwhqT1oZkch76/JiWG5WMKJJdhwWOpaxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:18Z"
  mac: ENC[AES256_GCM,data:Q1jK8Ehq6HPGkZuYXbJ4OKP4w0BioUxM0Lz+jPmDhPyzqVqgVsnNA7bDRAECBe9ZiiXiYw/PXX7niF421Nxx9mcNb1N/doWWkUaSrHvFAn57IYhwYHU5Es2iY7AXLQxUbhtGyx+5YtmBkYSQfKK963iCjPzlQb9e94z5G+pEppg=,iv:g8ZCr3IWXk6rVsaZ31WQeKAYUCs6ky4g0WmEWAvQX3E=,tag:5nj/b5bwWa5EYRrXj19Lug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
