# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:eYQamxpiPSwSl/WZwlHqWmkRGskvkiw2H3XNxg==,iv:Wd9HQ2Q7omIAmZKDBpFGUbo3qiSycRB6p9usclZBH/Y=,tag:jPwt4KItLaX4PSxIUffg6g==,type:str]
    api-key: ENC[AES256_GCM,data:dwQOX+ZoZLgLZYaxfLV1QGUwefRm6dtwG4mq7Vw8jzTXqbebFw==,iv:3p/q55KmsRw/1X6BU1Q4N09z4Al3uhR3pKp9gjYT/Cc=,tag:2AGEyuKNgCq6YOfHRfX1CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OGo1N1JmNTUvMzk2Ky83
            NWNidTBpOG9uODBRUVRTT1VTbXFGMXkwWXhrCkxEMnFHa2xpeEN3SlBQNzF2Nm4r
            L2dZb3ZaSVIyOU9ST2F6K2RuVWxwV1kKLS0tIC9yenovbWlQSnJ5TEtHNmM1YlRs
            K1JQUE5rejVjclYzdGQwMk1vNXVyQ00KP9/aaRQz4LUaiKfZcEwJgEWivbC991v5
            Q4uHnPaWCbZKemXwA+5j+ybKiinTXNPwCtY81CPienI1kAG9oZ6/pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-03T12:41:54Z"
    mac: ENC[AES256_GCM,data:pe1qgUZ6mgACfI7YynU0fSCH+nzArt83hrn7WfSLOcDPh/SvdWWR9izXnf20nh3JwEmauhJDAp7EEKLUMulqoNE76dokF231K9XtKJ+39CMjstGoc0/hn4hNfBio4z1TxvrCaKb0Yor/zAxeSXjUWY/UUoboe5JW9q1A00e9FNI=,iv:eE4rFtUaccACOgdAaKD29Wagi6YphfpElvhIpUYKeUM=,tag:rnrRP1z/KzVU8VGeJF2EXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
