# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:U0OE1tIL/OnqS3oyAn6roiNGCnCII+UcT7BApQ==,iv:wmu9s5RnXi7vgz7VeN5RS2oqaheVdRkHJYO1+pImcgY=,tag:uamCWsuHNlKdndkn0GMG+g==,type:str]
    api-key: ENC[AES256_GCM,data:f21ajIl1+wuuMd+7SimFix4OX6k94NswbBtSQd0KE2F7BijVOA==,iv:1V/mIDKqtbMN3QdWASDy2opkzCytD563HZVfD0zlksw=,tag:Yacd6qcWzfHWdf6nVa8C9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aXRsRnJhR3M2SWk0cXZI
            dUxVMjhlUEtWd0gxT052Tm1lRXdwaFl3TFQ4ClZnOXBPWHlmR2toWjRWYkpCMVd4
            TThTbXphSDMrWERoUmdKWVhCTzUrYTQKLS0tIG96MktFdTBzRnFHMm5FdU5PckJB
            Sy9lM3RLZkZIeFdhZkE5QzJ2eVBaQXcKIGK6qkTsYw7LNXd+vU4tTW2W2PDFd0GH
            7Hi6OUZmw/EyAXvSI4UQ2YXU4OjzkdmpUGlKq+3Wv0Cwt1KzVCU3ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-03T16:06:44Z"
    mac: ENC[AES256_GCM,data:00GOkb61Mvt7CC8TbzFbxy1+npdIHDxihsNwRHmcMpHe9Y2BiSfw7HX0TBK580Cub1P6u0R9bhjp99Q6eXDvQyuRxjWDfEaSJ0wqIj/0BSHlfx/kfv+WVdYsv2ibgxazqOz2lxCmu3fjReak6eqBglaBHUs1m5ijGzVv8DmVRQ0=,iv:yKyQ3AE3zhcOBFaTO09DxIjQffNHp+7ng5FgBXpPUzE=,tag:GFzBcROHkl8zssJDdrNt3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
