# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:T5Y9/hvqhrAArY+fHWcOKqI06f6QxgyYL0sr2A==,iv:VFfgVGDzD+Q54j7TITJgI5fupEI+nue0mwAbHj+POG4=,tag:w9jX7hXUGUcqzYom0pLQXQ==,type:str]
    api-key: ENC[AES256_GCM,data:eylVopGKsV1b1l30eLeyD2KJEP0uThEGNSEGFmCdTUrc7zZcAA==,iv:minY6cqgK5hgMuRPvNf7d+5ubxZn+iu4I0V8rlMX31M=,tag:KdaMb5p7Pu13MT50Cdgxww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ1lSU1VqR1JGUmtsUFFO
            bTBFUS9VeE9pZ21SUDBsWStnT00yeDhiV3c4CnhWL09ERFQ4Rjk1eHBHa0RRa2J1
            aHM0SXRKRFFNaGZPazNnLzBjWk5ZZ0EKLS0tIGJmeVVoZ1h3YUlOZUJuOThndEM3
            dWxybnBiRTZtU1pZOEY1bjBIaEZRdW8K/lbazI7j8V582akvA1jvo1FcrsIir3Mw
            Uh/nZMT/9Xi5fIfUq6YBdIBrE6iX0tjRgRxUqdFpcdEQkZk7VE56Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T09:05:31Z"
    mac: ENC[AES256_GCM,data:OWAjpSn8HSbAv9UDIncCjS8P8w+kQ4/4lViXsM6J5IXQRTXR3KBdpVtrrBEFtZQD7OqgcicWbJOsuutC3bna3UcVhnyO6Ooy3RjKZKRiIHaiUtismOumEVcsw+2cklqy2P3KFF6mHYuIkO2gDIqPBcrwsjNPH4ru7fY87QpNiz8=,iv:DoZpgbAs4BINXe1aeKAaB1p14spR0kLtDQbz2MfWnHg=,tag:1ZCCo+MAStlRbBaUYJqvjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
