# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZhPaKnDGf0raANZ+JokC2aI1tj/dys6yBy6mvG2dzTg=,iv:XYO413WUMKGtTm2SCZHrIpAWXCmpapAj8hYNfWBrSSM=,tag:3JCReG8F1BaGabwvlL0tHw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSHNaSEd4cTgyK1FJbWxp
        ZFo0eUVSMzB5N2tSQVZhVGdRbi9Tc2VqVmdvCnhSbkhPdjQxeVdEWEtaV3FGM2Qr
        U0x1UnFtbjgxRHExODNUTllJVlVMbUkKLS0tIEx0YUYvUmMrVHRIQm02V1AvMXBs
        cTZsY01kN05pWUQ4WXRmcytjZmM5c2MKSjDGmj33FUiwv3JZ5nh6zl78Y8GeHgsk
        dsQd8/+5Z5xT91s6daoSn+24TfUlpA7K36F19Gv3LaAAx/A2ob1huQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T20:31:13Z"
  mac: ENC[AES256_GCM,data:fs9jGpIuC/R9rz6nBWhBnbDioTFdRJycPzsVjjKZobtNMwhqYjyYaabaUaFqfy+51xOlK5ILK7nvgxZsorNtfNEEC9p1x661dqnmMNs/f3k8Lpa71FNtGbmdGoG90Fxq+lzQ1HNlZnpI4xEioH/4SdtnzW1WwDeZszESWVXHqCM=,iv:OJ5ev/vvIrbBzNOOfHW4kNB3Nm8lTzrsNLQK4t3HTcc=,tag:p4fJz0JzGdNwMmDmg5gNyQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
