# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:65dbscWpOD+LRDDXZG+wdYawedfKNp5ZoBXDzri22sM=,iv:pnmbO/TUwRl97YK1zHnvoZmVRQeRkBtAVDlfTqEpckE=,tag:zosy8qRnNpNLG5EEiqdm+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ2xMRTNRd2pIcS9nN1BT
        OERPUWJDT05RbUJGZ2IweFE2bGtFQXBSc1JrCmFxUE1oOFFlWGRHcDdqYVA2YjBM
        V3lsWGNDZ2s1azBVb05mZ2JMbVFweEkKLS0tIElrT1kvbFVnM3NXeUVJdG1tZW9z
        L050clIzcTZ3Zjd6TzNtc0xTZHNBSEUKVqFs7kk9fQBwqQhPCoduR7JYZ8kOv2Xs
        Mebc6qVwHqCjkvJedULLChjNksNBe9mMrM22EKqNKrrgoD1elbW+Gw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:42:47Z"
  mac: ENC[AES256_GCM,data:sXeh74cXTseP6a6rEZHjiX+Izeo2OgQN9NBReDP4CqXmgBbN5pJT1EkpfyM87L9g2bbRlYknceC2RVFyiTd1xbXqJ/MuOIyGz2HwphsBVdNP0ZyUGP83axS79Xg7lGi+RORaBn+6xkPBqqRIDOLQ/7M6JbyTXRYWIVbAKmJhpMw=,iv:qgp1sqOYqUzY5+SfXojxzXhm/V3d0Q8Ywy5JgEHmAeA=,tag:lVF+LR4SjX9wDs9Iv+roog==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
