# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wfiHi/jJoGnt3WmcMU/dpWmdi79uXnjWH5FqwfttDzU=,iv:VB5ndXTAiKqezURuzkYO27N4ZCkyat8wyPgO34r0Vgo=,tag:Feykqyn/TDbx5sJ4mkEu6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdkhnbHBEZGgwMTYyN2RQ
        THZmWWhyYVFjK1IreHZwWW9RM0pkeXpMSkdnCkxlbjkveHhOallUQ2Fxa0ZxZGhv
        cUMwZ3MyaFZpTDFSY1J2eFczbmVhcTQKLS0tIE9yRUh6cGRubzUxcngyOUVOWWdE
        cCtMVVM3Zk94bGNkU3luZHVXNTdoaU0KVhQ8XQ+hEaa/B8NN49nFknS0XyMo0Sx/
        0vE741ZqT3rGRXcfNQz4683bws1PQSoJfMYOwLH3QlbX2Poa4xTG4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:17:19Z"
  mac: ENC[AES256_GCM,data:Cdmcc7whloIqlcNksHHY+R0/hz7jcY2MC2vhN0v/umQ0co2lkiED84U+Ub71GMiBNLPDyozKWgUTiv03Eu+99Ed+BPrLUpIBzyujF+CGaYTRq5x/7L3el6KXtK9VvDFVbxVeBU/NtHiaPqWp0pgQxALe46BAvXAmQ8eUgDFu3RI=,iv:21MUa58uPwvNhCu0cqE9vXv2D7urIxtfz0TlbjiIqSI=,tag:mrvLN9mnETYZ5fu5zq7D4Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
