apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: devtools
stringData:
  config_local.py: ENC[AES256_GCM,data:Cidsmv7KZoFlGO4phJWyVd0NJwULFesn2Ti9VEJIfqN3tfD/REgxzo+66ihm7/TAZfJhv9Q4kOIbvRgM+k+SLPyoM7QQ90QVrxA6G6diyuZR7Ie1JznB66E6xLLS1wVEJtDzmMSeKK7ulcTH7gfyDIzbneZkWNJGXqpbPkl8raXSubQnxVzMNyfn8Xhr9Px+5uElaf5m4zSJEpEPUbbQZEdQBE9evkGRv6T4l05+Y7LtYOrEKZOcfQgfKbjFAHB9Wo00Y8WsjZFCCLBd32M0/+5uVQmgbRKQdj0wlQBpOW1KB3G3S0r7JZI39nVqv88CoJ7jgYivcZHfwVUYJmiVVYI12WC1nVS8rtGSFnSgx/zSuUWt5GGOlGZivo74sHnv1q7dUX3B0y9zvWpsk1TLlwPnTntUo2+2VAQ+EjH6iMxMqQErNc+rfp1z+/MbNr5EMfXcvvJnhP1ig7twChU2FxqXqocHbOzTSKrWZTOH5MVU8/eOEN/SMu66Tmkf+DFIEXbWUcNxnMa7+PZsUfelYaYsHSwaMEq7SI+RPchQa/l99sm33y8W8vZhRbo4D7zKirdXgerEXwtx0NhmgOufBlwWjObsDIg7BFKNhUujw2hqpA9EMYpIkAdmeniWpdAFriSInl1GU7317ZglwI2ed+FQrKwyFPaLphNHMw03ib/lKLlDy1148isnNJVJZmM0dXCSjiFqcKyFa6P/WRHAslHpSrzdKWlopx6axCH5YWAEm9X6zc5TXyrFSkHsJSNSIjR+ynpRq/AhlO4/x90CxvTswS0NUyjbidYeMQvVkGnG64GwVS4jWok8Q33nBSIixiBvP9zSnoU/gKU25Az8a4ExtIW/jbjMO9SnI8kX60or2Ul7/toW0+PXhbj4H1eXWkhp95/oJ6TOau7HiPBBNJWFd9uth0Vwtr4yFR8xc1CfD/oIv4iBcR75DgOy90vlpjI=,iv:WDFFbdXp34HtdIyC/fzQTIEzLqWDhX3s92Of0SnlmsQ=,tag:WpWUYOZiAlR9rz1TpcFrCQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSi9oUVJQU05kYVJ5R0tz
        NjZrb2x6TnI0emRQSW1FRDV3T2xBUFZhRjBBCjZ1c09BQ3h3aTR6MmoyT2l5S2Ix
        R3dTRmtkWnFBNWxSSk1zVDBiRWNZajgKLS0tIG9jWXFTcVNMSm5tc3hOeVREZXJQ
        bGVwU213c1ppNWxHVGRpWXNGU2NHTlkKuF5iwHGOG0Vboq0sUhffX1Pz1Cb0XxiM
        KEjlYbEPFVNKat7NO0Teo6oOnDt1FkJCcFdq4AWkyNyKzMkFVRJz1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T09:43:48Z"
  mac: ENC[AES256_GCM,data:942rqV4vo+EX+PwvCyaabBbb6NFWffObd14BYjLNQB5E9fq02BsYCd9U221zR3cETlQmcGf14ya94rDGsKmZ2KHvLgFJ84wm98hng9NTloAOrZ45chIza9v1zS4JBwqrno2KK/zfGcVfd9CVE8uzGx3+ul1ke+R5VoXGEpZ+9/Y=,iv:nqwfMh7zXFVjSXPEQsQ5IrtXmHRYNVaKYdq4GUbjW+4=,tag:C+xw+KXLVRYR25vdKmbsBw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
