apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: devtools
stringData:
  config_local.py: ENC[AES256_GCM,data:8/AT0GVrUyBA8n31B2Ytju8tBBFyMztlPGPS7eMPoQ6Nqdaiuo8X9UL7wKRMGWHBQV0in8eLWlA7BI4v29A4OIh7YuRXAfxtgqTQBhJ9WaPquI4vDvHzAnLwPDbSwbfyTLDU7mehhe0v1YL0s213kadqBQ3Rbl7iFFbk5UCGuqrlwRip9P/dCeLuEQE8N/ToXcgxtptisOl8cOiNkaJVzViDsMWzcpbQlaBGv3JtxXgQdTfg/+VY80nQ4ZkzCXfZ4Qg0SBf8gCJbLAtwNpUbDihFT8IvwDZJdozwWi0XInx/33u/oJ9b7w9yFp5z8ahkAYB7gwWt85GxXUWd4e1hVmRlZXwXn2zV1IIjyNt5ibRbYQqSo0hOJCf/BXih4Jtq1BP4fpgnP4qgNrx8JyauahPM9yvjXh/DltD9caAzTaXZovJcPZSYaNuAQoi2OamHpx3av6UMgShu6GOlEpkC2x4EFog0XNsLzz3iIKvzCPuXsHWvaCpgiUrhLNLxFPE4N6sKQzg99bIdtSdeWWxTRrHM30xhvsKZ5Tn1GyUe3ULCiDiZrWTsGXb0rYhcL2VFcTO3ZcVTTjlFRXK4C+cP4hgxIbaWm2CCcVZdws9uWNmjXCPDASfpX1aQjU8mlVjhCLNAUrrezKaP+Oxk4MIRcxZpeVFA87GJZNfqNn+rpBsdwbqFJkSpxcblBzuoHwYFw0mF67mWQBHo/9ntE1y9XY1jYFDtVUxJ+QwWSrmboUz7VpX5GdlbxeX3op2DSzPkl/lhvOzwOMtJc5U23Vl8YHt2Ep5o1z3bcCQ9DZPr6411xuEeQqWCiAQXVBPAE1Znez2391kXHevMAPJfg+Z2uFke/7CxXCJgUfLQsRWq8RoMZTf6+zqpsRy5lx8/vItmeDjLaWBEgHJfYKDSmGT8ooi1NcSXx9eiBVhvucEVeRBK5g2hMMA3TBw9Mj/mtUsv1MY=,iv:I4TiNa65yjweGS9TSW0UkPe8tOjNXp3K8CIUD0ZI1Ls=,tag:Lf342Bgkwfe/m3Uypf3lJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZXRkY0dGRWRWSDEzUmNE
        Vk5IRFpSOFdTNEp1bkNXOTQ3ak1rejFNVm0wClh3Ym5KSlhvL25FWEJ6S1hqTEN3
        a2JueG5JQjA4bERzRHFTZ2p6dC9NQ0kKLS0tIE1TZ3dpOG92VlNFbXVFTmRacG1U
        TC9LQ0c5YmM2bzgxbUlCSFpmbld1aVkK47GMVitO1NXX+xp3sR9iAvgJHybIP7Z2
        UazStAgpP6i8yQxR7roGhB9Mw9ASJqLP0wTTlMoo8zr8ISc0KPEZAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T23:03:45Z"
  mac: ENC[AES256_GCM,data:gkU6pizNrCqHn+gS1rMxWmOOXqjpdIbKqVCdeV1KSOpJQ68yc5q2ropqmltCLZ8npHNo3KBJQTDiw/3U+56brmDpYNOay9d/xFwxF0ybmVX02Gu0gJOQekxsxo9po0dq1St2KRcUSfH60sK421CX9NYJhx2gehQdKrZdx/KK7n8=,iv:qV2BpHvJzCaXA6cPBcYmHcOxBsdSQ1t2pG9q1nt/y5A=,tag:bZW4IrS6bhiJYKh53ZT7QQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
