apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: devtools
stringData:
  config_local.py: ENC[AES256_GCM,data:xYhx+0l8qH/VxV7MnocwM6j98GzOWuqdMxDoDy2+YaLV1jCU2gD/aeKhF3CBNYdTf8duZVSKRH3Eyn68rCOZ91hWiowpl1xvAVHSwmsXgI+0T1lYgolxHY28gL+5eW++vmls69Ib2nLI2ecmeJanvgNeXFL/GISrK22FhbuknYs/WJAsJC1n45EY80j4hi+/Obr4IpOXuBbTCBuJRIfhK98chYQ1lLbEY5nD0FpAQ4BAHdscf5wx87jOvEJRvkYEb1SCvkvrUONzY8Z5B9G1gvWEjAVzpkfEDipPphc9RkOsjudTilsU5lyTr0k3t2nv97arLDIT4ic2UD7cBkPwKm8+oQzdgN4+Y+4ixLGpozM0PaDS76Q3zNQchyZCXtEKXfWRHuxP9u8XcU8WGjb9xfZbsEIqZr2DANgrYwrGL9tq4wz3sxx0oXhCTwZ7/ogD/WV2g0nGMYJCGC+GU5HNmU9b7290rLsnU0sKjxdWepJhIso4GcqU3Yzr2Kw9BzlXM/m5HrsbM1NwdAbTSuU26z/fWJd2/fSU2Y9eIhqkmpykDp5UDuP3MVsvzCN/g8ICa7Zd1MjP5VePYCcLU/ZQyIGAONRZ/YSFVZJ4PNMVONgPBHKBrw7jiDwwWsn/CdFtA24Iy0t0KYw+h/R7YUV+fDD+PRZWLek1ErCIjxwA9A/rnHCvjpCcvbZ+kusHCMWV87TWd/w2fZYq2ZbHAP6JFb0Up1CqYQwAKEzU2/nAqdKwrT+faW/RtWSzwvVAwMo0Wg2jp8F/+EK6/nzaxp14Y60nQe4iDjg3C3T+vd+GlwA9cthBdIEvKXWg5otJaYVW3FIUKhloBs40c8WIgQbNvyLL/PEliA1ZXRaFtJ61w6K2arlY9wx2lHuTAbVWzV7683ybhTbe6/q5iJZhSr0t7avzfgxa+kLn4huZed2ehUSza6veEUlUZe43aT02DwYjce8=,iv:nfuSC5DVJ7vlbuqZXcfVajI4+CN4RYgDC4XmWLEzDAE=,tag:RMU1nrKsyCgXVD1qSLn0qw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIald5d2w1anloaEpadGo4
        ZE5KUVR2OWtabjhBb3NrYXdHckF4VzlxYkI0CnJSdW1FY1NKVU52eFA0RXdPbG1x
        bVVKak5ITmxKWlJrSWhXcmQ5M1NtT00KLS0tIHRGNU0yWlAyc0FwSVQxTkNiZkl1
        YmFIV25DYmJFdElWNURaZjZLSEd5RWcKHKCVFCDwS+HwMovolLol7p5dfRtA/ywg
        bAL+g34ZWRfBgZQ7QKWBRbQrt+WYbXFsLkOxFELfatnvrDB9WVfshw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T17:17:15Z"
  mac: ENC[AES256_GCM,data:7XZ2Ypu2u33nvYQTueifvpZAjuHbmcAorK+ZCYIcGNUSJlTl7USqHl+wmE5jOD1981wqawpyJK4yAeINBmwhonpMHJk9HaId2Y0mi8aG2GtxgEwzNDA8rOIBvi7jGxSTRR+5tijzuSLtVKCvrGGperkQN4lc/XZVShgxmlGr/0w=,iv:c+9k5kTJgf+IihyqolC5+RilwGlA8R/+OPRZk2SOJSk=,tag:rE4T4Ts0GISBHGWjrBjXpw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
