---
ingress:
  # Add other hostnames that require the dedicated HTTP/2 tunnel above the fallback rule.
  - hostname: netbird.${SECRET_DOMAIN}
    originRequest:
      http2Origin: true
      originServerName: ipv4.${SECRET_DOMAIN}
    service: https://envoy-external.networking.svc.cluster.local:443

  - service: http_status:404
