apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
  namespace: home-automation
stringData:
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: ENC[AES256_GCM,data:c8U+orQv0cM/KOsyKj180kq/t+cZ4tU=,iv:95ZTBpVcIhjqVM1bjsqn71y9Bsved7vCtrm678KUxyo=,tag:TSDYIyVHKGzgBBlpUNeuoQ==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:8zb1pIIH7uyg1Q==,iv:ElaoGM71viD830++xEsxQ4uCIpgD+K/b4gyT+SRqLOk=,tag:RmLKQc9rohGXVBQWv9xapA==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:c4BveCL+0KcYDpo7Ew/ZthpFGhcK+oos,iv:cQG+AhGzFHA6CdE13GbVL0zP3vDA6yWNBCPLKBKEMEc=,tag:y4JbZxlEVnt+ScTjAohHAQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:XqrryJc=,iv:lXYqkXX3LnDs09cmKccUUAhaLNVp0TAt6taTe15+lVc=,tag:5vzt39aE3gLnIaw+ywjmeg==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:dMG5GOB6VsrDU+GHrKig0WpzdPFDHQh5A+uj4NIktnN6WVSj,iv:Q37kWK6htjrnEuMn3b83Zzn0Ak/q68A52VbV1p+fPsY=,tag:x0iPMCqrEs7MKXcbfygafw==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:55f9zWapFAFW+73kdj1tkA/iT23E32EJVI4DNvY+2FEDPMITOXwpdwgBktDNbFRLD+wgqg2jeXrw7POcLoAtDHwiYFeJZlqbzd4=,iv:dtbY27I/f0wFXmRXuoPcxrhg2guHDGke3KxDOSmyL2s=,tag:7guXjdgZCZmeXJkSWqS28A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaWdiOThTVXlnOVNiNDhp
        MVl1S3FmMDE2Rlc1NUZBbmhqZ0dOZzZDM2pNCkg5Sit4b1Yyci93c1EweHJZY0VX
        aVRjR3lBN2MxWXpRMlFkZFZGL1ZNekEKLS0tIHhUZk5DeXdmdEw1Qk5kbWtwMytz
        dkhIOHFWOFlPUE5ONmlLbFI2cDlvbk0KyjSYbsxV1+Wn/xvdpo707PBBg3hhYP7Y
        5pYq0lt9pIbGOiad3UgOm0LSatmDgzuFEDgVZnzkC61kXh9F6PQ44w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T09:33:30Z"
  mac: ENC[AES256_GCM,data:hE2xQMKIyC4PEPOqJZIYxC66j21ccgG+/K3UfFRl5yM3Q/Y1xmsDycCzXsDQh4sFGGBgPX8l56TA3O2zgR4WHcIiU/HZrgkHEGXZ3blDGTks3f1oJYcS6Y8cW06oYcKS+Wb7Kh8JM//9WXLm8uw7c3xR9A13squBuCXgOg8/s8M=,iv:vCLhGPrHJ9gkwtZ1/fgHBJXXn0Rz+lNO7IMAsxdlRIw=,tag:xCRWqIByOi4XCjUJA2tLMQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
