apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
  namespace: home-automation
stringData:
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: ENC[AES256_GCM,data:2PtnHfGezkPMCydD5tigj+CQvTw5UB0=,iv:H+8wv+MtuFexCcVEINiFHvQohe+tNOFUS8b0lBWbkI4=,tag:FAFSmi74+sOjpupvLVgxgQ==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:prXdf/YriFVBlQ==,iv:H2aTiDckzQ0RcE/X2ujWexbycEF+wGBF3coPnsq62jc=,tag:BTpfcFLetGEBfMpNHX487w==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:i/WvwPZBTbY9p8sgy/N9sAqi3r2N6CeZ,iv:FYtLn6ZPPhE7yjGAtcmmu1UDAfaxvrvfBxIyW3JB0R0=,tag:BhUZyY4HbA4KONC6zKSBfA==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:P1AQeY8=,iv:Tx4mxgbl+3Uk0eXlzu36elBviiABUgPjnx4q412FY7Q=,tag:SgkIKslgFYntc/IDBySuzw==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:+cNN7ZN9e1fcAEjB42amLBkZ1WRu6vf619nSdtpTMisu/5Ho,iv:80/TAuFB2Y3OvmVNm64c8cdj0r2eKZ4QbcI7/r7nKU4=,tag:ED6uCKToeioT542NlI6JgQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:1Y/EnoIie+P6BCNRBsH0RZxEUcpxq85WGLVohjXadCmmiUuxFkNUuI11po1otTj0V5artUubvRScXQ5ecrFKeoBCGMW5f3syq8M=,iv:756W/IGViSyORjGc7OzatBNA3wgr743P0wGyw0wLyQY=,tag:5QjRR46Nz9ynMG+n/MHFHw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQi9Dc3c3c0IyZWlMblN2
        SXJHTFJoVVQ4S0FOazRzVkhWdzc1em5ldlRBCkdkejlyQjc5dmpjWm1QSWZSdDBs
        Y0d0MnlRbTVSQmZrVDh1ZHFsMVE3S3cKLS0tIFo2UXpUdVFGK2NQSktzZWk2Zm5I
        Y2pPRklLTmpDN3M1bTVOZmZueHZoaDQKZo697ablqOsfKxrq590w3d0G5gBXet38
        SU4oL7dJT+GgAkbLnbbHFac8g1jvK16fVJTyuEV1lmyw23AB5Pkjxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T20:49:06Z"
  mac: ENC[AES256_GCM,data:xn+7jP2l0q1D7UEthT4850dUgrvmmmYOTfUPY+TyiKsvq8j4K+SUiXBWACIFm6CGSG6sxRPBUMqbB2dVFdpURAwE/4PBbmkuVuSzT67zRSJInYPWGTtRO9IVvH7Dc0I0MtcIP1JmC4YuSJJ8U/3obLToV7dTPLgps+X464XfHO8=,iv:XpGWaoKsPvtYNzyY2PJPyHkFgEVF/bTL5cq2IGjFifQ=,tag:U1hlP+6GWv8Jn7yXWtVbSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
