apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
  namespace: home-automation
stringData:
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: ENC[AES256_GCM,data:p8Jwc4i0TTnEjm08E/EBYAtZrt4zPoY=,iv:tn6wEi2l/YU0iWpM1BXBi+YihttOocG6/oKSJLAS0k4=,tag:a11vDsa595TAZu/fPEaGXg==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:fQykKOMUDxpi/g==,iv:SU6oqCTtfwRG8XAOIZs7RTSm6lbkPBiaPowkE8i9wIw=,tag:V0xjbwV3RDdw4yAz4Ik76Q==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:2UUSe4iHmD7sOGs92WYLDhHNNDfRLpex,iv:VzXsQO6/bXnL/N+DAmpNDlzWGnTmvH8gstaA83rQ76U=,tag:tHSNoUBUSsqdEu5EMDNjtQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:GOXoK9M=,iv:C5ypEHvx0S09+QjTDI4iztTNi0O0bGof5g0EJzsPSF8=,tag:22OmnGqTcMnLi2vL3F7ecQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:2+Wib5IuexBoHTLS2xcHzJCStO4sRK01DwSBiaqmZWctGbbc,iv:pf4kNfl52EfkdvAImfc/9nmg/Ue/Bq25LN5ZUQYnkvs=,tag:mG0kmxIrFQUazv6oMDeYiw==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:avYRCUPHpTE/SzW+Ss3IfVEFo+emg+Blwu2OAq+Po2Qyart/9R5MOEFlQ9bZHFS43OK1868sU4Qa/fxL7Cudpba7HI4kmQ5tawI=,iv:wepH7Q2HcQI9oDsOQDIh32KK1zYvrGMz/Dx0Prmk4X4=,tag:IS53YAyis7ijmnIuJY80Pg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa25TdnlqUlVScm1yWVM4
        Wk1ROWNIREdDb3BuNHBSK0MrTlBJdHd4L0JVCkFKMnBRSnVFSHltYU1ORUZUblNj
        Z3FxSVExbFlHUS9DRjA4bmRVbjU3RHcKLS0tIGxEN0NKT3NHaHp5c1ZLU3c5V050
        OEUzMVBFNW5mVmE2YXdVOTMyVG1DencK7UCwXcVINK2olkBwMZKoNoGJJFe24zVY
        //bjOaBSY28vZaw6QoJ2c1kCLg6jLypq0bke7SxBdiGFqxh7cednxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T01:08:28Z"
  mac: ENC[AES256_GCM,data:kdS2dOtvzocvekVhJdDORTD2Wf0QExgNQuXrTJM+USzp/qq9f8ZK8wCchkL4lHtn55tyzLqQq9g8Ofut5Vx91nv3CoDmf5jQE6Wx8SpMiShDtuuiH7T5UYVA0e6a6dXBaiXXE32RE6t1fMgLlWmDcPHoJbtQ8drU7MBkD7qxYhU=,iv:ubvIlU2nbk5GM0gX9hyx8lue7MzgjtjQUlkFsU+lWNE=,tag:bPxSSzS92E4saNc1pAF2tg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
