# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-memini-secrets
  namespace: ai
stringData:
  MEMINI_API_KEY: ENC[AES256_GCM,data:3J0/avSSXHx6ZdHNFCpITWi2ZKB6rRGoK3gKuEkco6ZFwP+LBaYaL3JtJLwL03JwqGqxjJwF+rEuAh1qkIjYvQ==,iv:DLnsWTarXAXSSgCNIy2Rc8+XSbSR3hPPgh0vqE+Zf/k=,tag:F289WF3vLgoQG97AgfQO4A==,type:str]
  LITELLM_API_KEY: ENC[AES256_GCM,data:uRCfSQ87PtPXA4Rpcm6pBo4iVinxA2erzA==,iv:7qI20lcSFVM5reUz7hmYGIjOxN7qy8yZHKEFtGfoXUE=,tag:zQ4/cbbWlkXKthY0Zbd3Xw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeGxTZkU1a0d0dWk0RVdB
        cVFhanVoRG8xTkluZ20wRThLL2JDWTA4YWhjCjU3SkhlclpaN0s5ck1XOTQ1bzBt
        OURFZ05OMnA1WDBWVzNGL2dTT3FLOGcKLS0tIEZFdG5zZ1hHTTloa2o4bzZmTTZO
        cmVOZC9IcnZsY2wvV2hRQTJlWHByc1kKgSC8Qo6V3ROgk5T9vYjz7TXkLKSX1GgL
        ugxYMqC6pvYZbuGZCbNSPyVSx8HHnXUxrjNEgj5yoHfisYAKoH9fPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T00:55:44Z"
  mac: ENC[AES256_GCM,data:PrHdvXdhRclhYnzPudxjNCONICJSGm6OSllCgnN5BQprddqOPScigyCV2y6yVFlnUfvNB+ECP/LWzn71zOjr2Pxpyd3p/6nqyE9Wv0ZGy+uHcW4sj/b3leFHFs73KAKNLl5rFIBBstSDpeaMEIx6TJjB95z2p6GR9jy/QIqKxYM=,iv:mWiFnB0bb8CHCtNXOb8FevNw8mmus0cgNBFSMQdLcdY=,tag:vXnaqOOeCxIZ+rYm1CuOSA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
