# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-memini-secrets
  namespace: ai
stringData:
  MEMINI_API_KEY: ENC[AES256_GCM,data:1Fz4bdJeGevfX7MDZL+xVEO9DjeUzPBIZ/wDMpLrAzq+jnqQ79xudMgpObX9Q2a7yb/lIHLqcv6vKsmsyNHCwA==,iv:OOAusqtKUAJ7KUPlCHxbExTHG3cC1hIaRa+E/5ObObs=,tag:TtuFbECXH7sNgyMufqKsfg==,type:str]
  LITELLM_API_KEY: ENC[AES256_GCM,data:1YnGtLzLe9xi2Ag1FgmlAaha4RuJSyuShw==,iv:s/MrnQAYVRhlCvBDzhN+WcEjZ4mSjE2z3qmylsXtVbw=,tag:6fZXKI+EJjrsBs4nl17dbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZGNwSm15ZmduUDlBVlpu
        TS8zSnNRSVRaQm1xMHZkMlJ0bnJwMmJzQ1RNCjlvelBzQVJVQXFmTnIwOUxmSzln
        TVV5dm5oc3k1eEZlczdHWnJzQnN2WG8KLS0tIFhsS29KUithWEF1b2tDbFBuSGZZ
        OFlQRVFXdGx3SEY0N2FDLzFTL2p4NDgKQ8QjWzTt6t03Ks0OganifPFsvUiB/xvk
        7sYpw+a6h0VeEmsKlGWTlMEhoj4nUCSfaqlsOWhwpexLxU+8/S7tNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:18Z"
  mac: ENC[AES256_GCM,data:hj5m8nJKPgWhim2xEqDdmA1cXCbKQO1spWsBC/tNQ1CgNmBGS/0RAWg/R9blVPezPBJOTN8vsY5Q68Zo8CGJy1oTeX39GRAcI9xKOWXKOgkg6fh0BDyN8KVI8Lo2uYUWk74RIC6i8win9PM2N24Zxnx9x5BBBHhpIXgQsvd5Rok=,iv:RZUjpx5FchYoU2iUPZv1vKFwKImCE4UTzwsq6cr771A=,tag:TnaU0f+mvgEiWBNWE8noNw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
