---
gitea:
  admin:
    username: ""
  additionalConfigFromEnvs:
    - name: FORGEJO__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__DATABASE__USER
    - name: FORGEJO__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__DATABASE__PASSWD
    - name: FORGEJO__SECURITY__INTERNAL_TOKEN
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__SECURITY__INTERNAL_TOKEN
    - name: FORGEJO__SECURITY__SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__SECURITY__SECRET_KEY
    - name: FORGEJO__SERVER__LFS_JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__SERVER__LFS_JWT_SECRET
    - name: FORGEJO__STORAGE__MINIO_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__STORAGE__MINIO_ENDPOINT
    - name: FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID
    - name: FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY
    - name: FORGEJO__STORAGE__MINIO_BUCKET
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__STORAGE__MINIO_BUCKET
    - name: FORGEJO__STORAGE__MINIO_LOCATION
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__STORAGE__MINIO_LOCATION
    - name: FORGEJO__STORAGE__MINIO_USE_SSL
      valueFrom:
        secretKeyRef:
          name: cluster-forgejo-secrets
          key: FORGEJO__STORAGE__MINIO_USE_SSL
  config:
    actions:
      ENABLED: true
      DEFAULT_ACTIONS_URL: https://data.forgejo.org
    cache:
      ENABLED: true
      ADAPTER: redis
      HOST: redis://dragonfly.storage.svc.cluster.local:6379/5?pool_size=100&idle_timeout=180s
    cron.archive_cleanup:
      ENABLED: true
      RUN_AT_START: true
      SCHEDULE: "@every 1h"
      OLDER_THAN: 2h
    database:
      DB_TYPE: postgres
      HOST: postgres-lb.storage.svc.cluster.local:5432
      NAME: forgejo
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    mailer:
      ENABLED: true
      FROM: "Forgejo <noreply@${SECRET_DOMAIN}>"
      PROTOCOL: smtp
      SMTP_ADDR: smtp-relay.networking.svc.cluster.local
      SMTP_PORT: "${SMTP_RELAY_PORT}"
    oauth2_client:
      ENABLE_AUTO_REGISTRATION: true
      OPENID_CONNECT_SCOPES: profile email groups
      USERNAME: nickname
    openid:
      ENABLE_OPENID_SIGNIN: false
      ENABLE_OPENID_SIGNUP: false
    queue:
      TYPE: redis
      CONN_STR: redis://dragonfly.storage.svc.cluster.local:6379/7?pool_size=100&idle_timeout=180s
    repository:
      DEFAULT_PRIVATE: private
      DEFAULT_PUSH_CREATE_PRIVATE: true
      DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.actions
      DISABLED_REPO_UNITS: repo.ext_wiki,repo.ext_issues
      ROOT: /data/git/repositories
    repository.pull-request:
      DEFAULT_MERGE_STYLE: rebase
    repository.signing:
      FORMAT: ssh
      SIGNING_KEY: /data/signing/ed25519.pub
      SIGNING_NAME: Forgejo
      SIGNING_EMAIL: "noreply@${SECRET_DOMAIN}"
      INITIAL_COMMIT: always
      WIKI: pubkey,twofa,parentsigned
      CRUD_ACTIONS: pubkey,twofa,parentsigned
      MERGES: pubkey,twofa,basesigned,headsigned,commitssigned,approved
    security:
      INSTALL_LOCK: true
      REVERSE_PROXY_TRUSTED_PROXIES: "${K8S_CLUSTER_CIDR},${K8S_SERVICE_CIDR}"
    server:
      APP_DATA_PATH: /data/gitea
      DOMAIN: forgejo.${SECRET_DOMAIN}
      LFS_START_SERVER: true
      ROOT_URL: https://forgejo.${SECRET_DOMAIN}/
      SSH_DOMAIN: git.${SECRET_DOMAIN}
      SSH_PORT: 22
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      DISABLE_REGISTRATION: false
      ENABLE_INTERNAL_SIGNIN: false
      ENABLE_NOTIFY_MAIL: true
      ENABLE_PASSWORD_SIGNIN_FORM: false
      REQUIRE_SIGNIN_VIEW: true
      SHOW_REGISTRATION_BUTTON: false
    service.explore:
      DISABLE_CODE_PAGE: false
      DISABLE_ORGANIZATIONS_PAGE: true
      DISABLE_USERS_PAGE: true
      REQUIRE_SIGNIN_VIEW: false
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: redis://dragonfly.storage.svc.cluster.local:6379/6?pool_size=100&idle_timeout=180s
      SESSION_LIFE_TIME: "1209600"
    storage:
      STORAGE_TYPE: minio
      SERVE_DIRECT: false
    webhook:
      ALLOWED_HOST_LIST: "*"
  oauth:
    - name: authelia
      adminGroup: admin
      autoDiscoverUrl: https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration
      existingSecret: cluster-forgejo-secrets
      groupClaimName: groups
      provider: openidConnect
      requiredClaimName: groups
      requiredClaimValue: "${FORGEJO_OIDC_REQUIRED_GROUP}"
      scopes: profile email groups
