---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mooncake
  namespace: flux-system
spec:
  components:
    - ../../../../../components/zeroscaler
    - ../../../../../components/persistence/jericho-nfs
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./kubernetes/apps/networking/netbird-peers/mooncake/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: mooncake
      JERICHO_PATH: /volume1/apps/networking/netbird-peers/mooncake
  targetNamespace: networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
