---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-logs
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-stack
    - name: grafana-operator
  components:
    - ../../../../components/persistence/openebs-pvc
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/monitoring/victoria-logs/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: victoria-logs
      OPENEBS_CAPACITY: 50Gi
  targetNamespace: monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-logs
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-logs-collector
  namespace: flux-system
spec:
  dependsOn:
    - name: victoria-logs
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/monitoring/victoria-logs/collector
  targetNamespace: monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-logs-collector
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: true
