---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-internal-ca
spec:
  isCA: true
  commonName: LLDAP Internal CA
  secretName: lldap-internal-ca
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Always
  issuerRef:
    name: lldap-internal-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
