apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-key: ENC[AES256_GCM,data:ifqxNwy4w17unVx+C53Hkw3kMHflL3dd5ijKiYfnWgqM+wiEZw==,iv:s1y+3ssO80xJLqDFsxVnOWgJzH+8r69SioFwxO9px9o=,tag:v8dZJBORbpKMFo71sA3E2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0dQSnlmalhjNlloczQ2
        NDRHWlF6UEFRWDMreWgwMGttUFUrbDVOYzBNClU2bjRkWktTTHJVNno4R2pnZmFn
        NzZGck1FdU83bnVkQ3BvVm1lMmxHcFEKLS0tIHA4VmdVSG5LWUliT3FBV1FLU2Nv
        U3VwamVXb0NpSDF0WVorNlhzZWdzbFEKR+AApFDKtcbAvO0d2spzlhQjzKRJJILl
        gFPrtf99YiyeCZ9RVS/4n0xOpbCu0IQXlDr6Bh8XNSlcmrQ2p7cV1g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:18Z"
  mac: ENC[AES256_GCM,data:waXvgBGR0P4+1Mhwe7fYpXFEYe4IOvsKiG9N42L0WyngT1J7lXdiZWYCh7yZjaLW4bzGC0tbnHVeQpcdFdw2wXbxEuErmdwwfCVXwrwRjlrgdiPeEyrJheqPUgYhhsdpFLRE33A/EZNLqX2ZYldebvePo7GtYUVJw+rL8eTMZQI=,iv:hyIlKIFcjko9UME3x/SdXCLsnr6HVJYefiPPy7QO/WU=,tag:W0H0uivWIAATAbDs/i1hxA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
