apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-key: ENC[AES256_GCM,data:Q7sVHopJJWV/a+o4dwYn4IJgleuOqvW5ptgsRk6q/hVtJLW/BA==,iv:hDJ+wz6AuIo8sD4u/Ua0+ZqU0PBt41BOTxjAMQRp1yk=,tag:kypeRpaAozHJ4TrpdHiRkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUllWUEpPZmJyeC9Pa0Vm
        S1JJVTJDZWtCYUtuSXlkYmxmWERSMlhLbDJJCklvdERaVzNPbUhrOC9uSCtraXVE
        MGRPUzhLMEIxRHpnSVJlNEtpRUJQdTQKLS0tIFErQlZHK1pHNTVVZ3JtSHVuOWFI
        VGFrWjJidmR2MHZJR2pJSWFUemFxQzAKWLduB87zJVY8Cpe1LADHc0F7WALt3A6z
        1hFqV7qqn8w29j5BHL9iODtOgRh6IGpztwKD+vnpePcvhi6mcby1Rw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T09:12:41Z"
  mac: ENC[AES256_GCM,data:O9Tg43qf+2829+PB5zhAFiSI1ZyTx2faFBs5cH/pysfnDOvS6ocaBL6Xkg30NWo4RZfvrVM+u9iEzfWvX6DrKx+/Asbr3EJOoGcoJqIAMk+6aF/f6BCtVtOiSK9amNABY5qH63fH3wY8zjcLY4tCB6XPinGqhaX9qi5s68mdiWo=,iv:DQqvlVSRHaBj0PtC7iUOEyOosC85X2nKz/Vn8JmH6A8=,tag:/jvhUxc6XNVQ4BrRByDNhg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
