apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-key: ENC[AES256_GCM,data:3hFqBGw3WX95HkioLfs3+39VGXbHNSq6hMkhXola+7U8slXUSA==,iv:xJ2Bs8AaKtKRbD7nXJHhk1Cb+bMJCicbBGIVRtcRlvU=,tag:VzxaBLQmvHVTztxd1f4BSw==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWWxmUExiTXUvWmx4aE1y
        aU9ud1VGL3hjZlhUSktabXd6R29xQWJWenhrCnZ2bHliZFJTZzNLWm9mTVNVQkIx
        T1V3NDY0bVJ3S21WK0pPTUtxVW42QU0KLS0tIGNGNkxtSjBjdkUxejhQMjVNSllY
        RlplN3BOYVdOdEZ2NDRDcXM1YmxhSlkKWBDvSUeP3MJAntQ0JN807e72rl3c5a7S
        Xrm+7NqYSGrMCiTPUNk+y5V+rgjs6C78Luc1u7kyfSpo9R2EyoILeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:29:32Z"
  mac: ENC[AES256_GCM,data:U/X327xHspEbchUDolHiG8B0MTMKmJrZ6CkIuXQ3E2B1WYuMpisgDWB4JuIeLQPlxBESGcYwFJxKTAJZtP/TWGr5mBZn9Uid4J9XBNmABeVGj+9dYVYLZ1k7HiyaC5iopAOwGb/9gMDv03+jDkfZ0OZLeLVduymNkfgpjFN1XcM=,iv:i6wY4lgTguZJTMoEwDM7fLdJJJ4H3tUm8SHcOURTMZA=,tag:jwynv/RjaqYTwAFedNNFqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
