---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-server
spec:
  secretName: lldap-server-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: lldap-internal-ca
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - lldap
    - lldap.identity
    - lldap.identity.svc
    - lldap.identity.svc.cluster.local
