kind: Secret
ansible_user: ENC[AES256_GCM,data:/XL4dlhu,iv:FhO4Kj6jIE7SEfwhgpKFGPyEYq830CZhsFGWIF1skWg=,tag:bxZD7CEpR7k0DFB95SC7DQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8hMm+4u+WDzk,iv:gemqCtbFGBX78LwcjKqnQ4C2kCq4IHKPW7/K5I8M8+E=,tag:XjMpM8Lgbb8LVpY+p5cNSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndEJDSUdNRnM5TTR4RU9m
            bDdSNG5wMUhiNGxwNE9VRlFjdjNIWUdKMW5vCnJFZ3lzdEs3cy9hZ0N2WitaclYx
            alY3TzhkSUJ5U3dPcjJ5Qkx0bmJldDgKLS0tIHNGQTI3RFBBalZCdUJRQlhKazlq
            NFcwNkJPUXQrZGlXU2hweWJKeEhwb00KQG4KnaTuStuW8QEs0eSiu+V72c9FLoY9
            kjicL6hJArKy+mMZs74w37U8kk1CUIqxcS9bKbJF7aXu0FT8TMp5Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T09:05:31Z"
    mac: ENC[AES256_GCM,data:WQH+vxxoCYdq3ZkDZhHDPQX7+37590pe7pbPhx+eXK0EJGMsXlX+SzYzA1ap7WTLAFf+hBsSKZjr5R9eaYEKqyvuSbSFJr7DdvQ+9szMoAbK+q4oONywTfHBxrmuOIF/fiJZTBvUExE/sdCBWlHAi4Vrz1Phc2C4kcWjnfqTadQ=,iv:p23LvODh7j5LDl1Um3xfBebxfQAAWKGJrI8N7wnOKgk=,tag:mrWCinggthzb9shX+SIu3g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
