kind: Secret
ansible_user: ENC[AES256_GCM,data:rwJ+Ibc2,iv:/djW8c/6rH4xrxx1WdE/CzNXrxd7rVpwZN1glnCjuXk=,tag:0blumJHrP+EWlH1MijcxgQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Io+y1dJaBQeQ,iv:qx8HTqiWh6aL54K27+MwqJwxu6SUp1FtXZfd1Lq9V8s=,tag:k277wzp9DEOaMCGjGgT75A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YXpseGYyang4cGNYZzM3
            czBUSDU3SzBNYTdYUXpqVmk4YXM4Y002ZVFFCit0OTlwUXFjakhHSEp1ZUJOelpj
            WjRmc3A1azZjcC9wb0pPTVY1ekZTT2cKLS0tIDhyNC91eUJvajlXU0Jwc1R0UFMr
            Rzgyd2J3SmwyOHNib2lHVFB1anlaZkEKjM7TRNzKvhK9UHgX7cFJm0PEgEQY76+O
            vaV92oak6+++u8iSBcABdW8nLOo6J71AQHmCrkzvFxz1LmbQwY0TGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-03T16:06:44Z"
    mac: ENC[AES256_GCM,data:xBK+nV7I5zbFcqvRj2jSaycPjbx1O2Qi+IbwgLFoPgzCydGA+/BlazV1JAgewyayBGH5b/za42iYZa22sRHvu4pjk7pgx3ZxIb0olTa5wvtsXPJGDEOw0S3sndWTqi5XPuvJTJNHC6YZCvwLwBzLawsf/aADrVD/thxL+YEC+/E=,iv:A2FQukXmwCtjfnGSpwsZgZFeOVB2fkbwi5ywAoc86fA=,tag:p318jFp2bAsClC6+gB8Yxg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
