kind: Secret
ansible_user: ENC[AES256_GCM,data:gkA=,iv:1tlwldjkr/tp51bu0uv3YGNeKbEJgrL0M7LbGJ/Xv/c=,tag:P4P8FseYJevgehiOedh0+Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AC5QDw==,iv:sfGLNj+kWbfUrKfufGVMUMFIfWMl+10tvUQ50j/6De8=,tag:LajYPzo6Dh7f/yOEymEAsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cERWamVrbEs5NjlrRWNL
            U3FyTVBvdWxsOXk0ZVpCems5YW1LMWVVWkEwCjNEaWNoVk5XbFQ0MmM2Z3ZpUWl1
            U1I4SCtOd2szMnVvSEtzQktuZHp6dzgKLS0tIERsVUNoc2RzQjZsaERTcThXVjB2
            aGhKZEY1M05XVlU3OWg4Mk1mY1lPWjAK5OS4LSU9BiJurptlR3LF9N9yyoz9eCuF
            tq3b7nwNIPh1Pz6LnygrS4PDKzAL065a8bwLmhH7ICfRUkC8/D5MjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T22:41:23Z"
    mac: ENC[AES256_GCM,data:uIyYKWJoaNc8aHt8kAP84S9wfR9jO9rHFgJgTnpo5xSbkwWVyzozltOGmje3RjVkDsd9otR0NkTVAajFAxAJVAGS3BQW9MXS3gxUlAOQJC8bFFJjDbwpPxNrUnKnJPKGUNd9s282xCYC7w/Xd0/4mE0ZH7rZuDKo9DPqY4UIFZw=,iv:PKeoOtQXnNfHhCWePDjT9YuVfCEN0i9cYp3Td4NIa1E=,tag:rPjy1qnnlYoPSFHxv674qQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
