kind: Secret
ansible_user: ENC[AES256_GCM,data:8Nc=,iv:rdFDvXTJ/ozo4kUi+LIYMJnfFii+t2bbCyeujFJsgNY=,tag:tHDDBqklQJib6JGzL1GZPw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U21O4A==,iv:0yMn9ApeghSh2tlYvxsN325wC4jL/aQQFiBoosxoSh0=,tag:Sb1SSiE9YiD+eIq2SSfIIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZmZscFlxQXpVeUVrQUpP
            U1E4Q2dUcFlqMHYyQjZ2MFNSKzMvMi8vYjFNCnNNT3AyeVlSKzFFSGlmL2dza1da
            MGxibGltL2d1SDNvVXJ5TjFncis1WkEKLS0tIHB2Qk1NVG5meWZ5YUR4elMvYm5J
            WWpBcHFydk0vQWFHWFFRMWg3a0NOQkUKnptrM01zNxgvZNRlPK25fT3JLMGHaQCN
            b9iBpOM61eO3z3Hsrhuvdz8Vq9aPOSwg+6vp6fxNfieH+kuDk5YehQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-12T01:57:58Z"
    mac: ENC[AES256_GCM,data:4HliVucxPvwwC4PPcewprsP6B5nFLDYXSe7KCKAfR8t/lzFxma4y4bdYsKVIROQMimUVd81RUuk63XHcpMRjpaHUe2loZ/xJskgoK0fqil8mlbIMULjCpFUTqGsD2VHfc1CqWcTGx0N/NJjaDv7fa8qc/0FgDUTc+0Kydf7RFtc=,iv:j5sX/5Cr9w/Issp/k+amFpGwWXCwhD7uyWPTb7c/9xE=,tag:sTVC/NDkWVXKvN3+M0HUXA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
