kind: Secret
ansible_user: ENC[AES256_GCM,data:sEhSrDXl,iv:olhsMAu4US9qAGMQQgkax+3TXdD+exfSaoq/o1l+UKU=,tag:lQaigA5x/AtzYqtqwLbq3g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LNNsWaPMGOkh,iv:+SPN0gy3y7+e5/iqLkCIeiY+rmXQtRZwHYe6RapHdSk=,tag:9PipZSkB2BsKLlpibv96uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SVlWLythd2czUS83eVhP
            enIxekZ5M2MydVo0eXZRaUdXajk2OVN3d2pnCkYrekxkbmN5dHF0YmFXTGtlczk2
            THA5NEIweWtoZDJHTnJqZkxtNVZHVFUKLS0tIFdIdGptU0N5WHphcXhtc1RQWUd0
            eE9udGFJN3JXN0t6RjY5alhsZ2NPTE0KDSdLXZw2q9I0GKOPmxXk3oCnDOICPTWN
            Fo5Fypgf9hDV6jMO20JoYiBoavekMm0R9yGHJ5a8X4rK2CscoNPPtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-03T12:41:54Z"
    mac: ENC[AES256_GCM,data:nnllXiM/Ls2V6z4TvzlSaoPzfrg9uT5PCAmynLfy0hW3EkZbPvFANOxefWGqynTIw4YSkKSzLiSkMFygjMOw4b1+DvkvvQ9p4g3pNvSTNIsy/cF/T+Np6q3NKX00hcn5/SCqXUYDcBy6XebunCluT+KpMeAV3CFrVCTi5aG8dro=,iv:pW5XD6z8DnAv9Xj4h8Io65RI/eJ6DkMvHEUZ/pD4vC8=,tag:D4ZCNeoRD6vC5TArH8WeXA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
