kind: Secret
ansible_user: ENC[AES256_GCM,data:ges=,iv:1itvUEHsdnadtkYUDhkLZPUfv7f/8ZSl2bsd9Y6wWRI=,tag:L2BwOXgSegxK3h0CzlXedQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WZR8cA==,iv:B1sLofLDIrhk7PY6ihV+NSSgR1A5fz1ToNbZYSMj0TI=,tag:dQQ2s/HWKh442sWXBPoJrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-18T01:09:28Z"
    mac: ENC[AES256_GCM,data:X2LUGnBPbMaJlpSYRXJjAWveOcdQhqce1MkckoE0Pj2910v1/0SN3CbUdEtghOhLfB2qD6XYOEYgij6YK+CBnN7IZpN1xdnevaTVHM9MnbgCdgU6wcAovSoLWT9ucA3jfLzbtUWJnIMUMRKJwCFhDZVAmGse6sH2XN9Dlaxbgvc=,iv:8sTqNBW5QpxJDV6GiwMj1ej8IWI4BR4CU+WnSBWdo4Y=,tag:CX49StW4JCuKiHHhPwPUeQ==,type:str]
    pgp:
        - created_at: "2021-11-18T01:09:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4Qq/qt7q+z/AQ//fS/tl64489HU3pXocUmhp3ALU02rfF55bQOGQPSxMnkw
            X+ex3Zs6CxQaYKv1TpuhuJtlcJ7ZCQpBQXNAYDhOwLsWE2y4SvVObLsG/ea6hAZr
            nAhbJZigQqCfRtB8V5ekJoJtdHVrYcCMrW6ihXi8HwT4sLozqfxaoFBk0cgI5UIz
            6NNfuT6RDqBO2iIv+kIskCtbUmp0lc6TVnkPZeCxVOouwhDJ9rOzccFRV3zNaku3
            NDr061PwCfzQktXDLHMIlcPssEHgmAjaQ4jEwN1yktJ8asp+BBmls9ypVCkS/H/z
            zkh2TIBk1JzmSYhNsjKlMoSc3t272Nfbbc2WijWGrSZZakB5pTWVNCMFMOg65THk
            KlkQOp3G5DuGExhE0UDo+cbbWzWgUjEV4pumtTw14AuRFK4kMcEEGrcRS9RQ4joM
            72FH8HrdYVtERzIqD66M+kWAaz0hd07SUXVPWL0nlSYr0/XQ/+IdL06ojFdZbZXS
            snQ/iIS/kGeICGAFUhy6hhFrVGOfr3GErlsNsIr1b/7nnoir+e7axq15RBVvkCvS
            hr0nc1Ksd/W1NSUHAkR0XEHBb4iB7CtR4scNVadowEAP9LwRVVgYi8xEXAz2EDaz
            goA/7gs25rYiv2BCXmk0LjZ3PNyOKQ+wkGxJFHqXOJLlKCdNeq1DpSQ3qRaIdsHS
            XgE0ipOnlOxXUuyhH4MvHD/t1OIOgl8oHuqL+YJRhhFYDFgwhNnLsMXMp2jaUdhV
            ZkD5YkDwt0BDFgcDA8J2UmAT404S32ByHXkYRDghLxYBb+ADfuE1dsp4trq1i8Q=
            =IfLd
            -----END PGP MESSAGE-----
          fp: 4F27D7B953202EE9D30FC9E8C165E321C5A55006
    unencrypted_regex: ^(kind)$
    version: 3.7.1
