kind: Secret
ansible_user: ENC[AES256_GCM,data:ubM=,iv:ZGRZt0R3meFpfaiqEq8z7gySqRjHN5XqxfRUeGFu/a4=,tag:IrCLqYVUBYTefxYXpj7Gmw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Pk5YSg==,iv:hDahEGljqG25g6Mqw6D4vqyOQZy0z5gzUhTMxZGATlM=,tag:8hGM1xn5cpy7JsjWP4T0QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweHBjS25FSTVCSmdHdTRy
            S295MzBkcHZrUEhRWERtSnFITVZsdkc5Y1cwCnVDcHRFdHcrZzYwK0Qyam5Ba0t0
            OW1oYTJvSGY2TmRQbzdaVm1QQUsxaEUKLS0tIERLakRucnY3b2pWZGRrTEorNXpE
            NWc5elpEaGdIZ3BmdU4yN2I1UmtnMk0K0mv7L1ot7fyE06js+aAZ2maDwDVQsRlm
            v/2oIurGlZK058VIzd+yPgwNpHuWRsqXuCAJCaQA56sksIfbEAgaDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-03T18:59:54Z"
    mac: ENC[AES256_GCM,data:IxZxF5AdX+Co0oQuVuploV3CBgX3mxL+pvIcHjrFU6pBjQ8sNusb0X3LfyUmXJ+eZkfqF7FGY4IExgjl0TJ+U9alIAM1Lb3QTubcjrhL46r6Ya1GZsZv/RntItUl57Nl0OEULV/lMjEDWrSNmzCkRqA21nrdeG4yHPBLVaiNG1o=,iv:2s39xZZroDIFtgiQ1XZfk998+XOsn5m0vxoQwZoO8Pw=,tag:AsIbIVjxEqHeJyuahOC0HQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
