kind: Secret
ansible_user: ENC[AES256_GCM,data:xAs=,iv:fXVLkL12/e8lHAmdfULcqyUb4BCI66beP4BxWPHIkRE=,tag:aB9R7Iai4Fn3MAqbkQkRKg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:lH8Vww==,iv:xrXrMJGI1ICe+erPWRkz6em8rYt3muEwcB9zuxl9q9o=,tag:mFwodHrRhWDGvnkSw2JQVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TmxPeEFBSGVlT1NLK21j
            NEFLVTZHVTAwVTUrV3greWxsc1RHSjFxMnpnCmVoNXpjUFY2bUxiNDRsaVFJdXZK
            dUo3YkhsY0JXcmlxZ0RkR3p5b2VDdk0KLS0tIDh1c3FVSXFJejhhVkpzdzZuZGN5
            YWJjSTZlMTJPczV4OUpuM1hGWHBTWncKhzK7FNwWByKeTRIJ62ETx8EmWuvVCQxq
            04fBnz3PBuMJIvwmwqcZZvHUx1xs+ks+HVL+TWFgU+ZaUWHr460MEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T22:41:23Z"
    mac: ENC[AES256_GCM,data:C2qENaqD176czGL6kUIll01JGAfpz6ds8k7u+F/2OZnXrHc0kCG+JGHmyzjN+scHksobRmwxHZScqbHlL0YHz8Yx6JiSBitHtXWQiCae8WXfi20Jr6TfosJX8ij0477/TMtIU3UZF9p5FEywY5CZIe/6641XWlP85oYrTbbK1q0=,iv:Dbf5cw78Mwakf329L4EfvzDQOjOKJDQm41UOdoFw8jU=,tag:5qEHdU8+hiDnCmdqd1KgYw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
