kind: Secret
ansible_user: ENC[AES256_GCM,data:3z4=,iv:6VDrjV6XcNifGppKsrvbRpavGnFEk4iY5aQiBadaZIw=,tag:98itw3btkcWEogokEvbKpA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:fFoLcA==,iv:egtnAtu8l7jXPxRVauaNF4/0lMY/1F16RVdORNgyRy8=,tag:4vTtGR2V84aBylijMQPrBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSHdzVlQ2bDQ1Tml1eVRJ
            c1FYRDVEbjRrYkhnUUVnMlJRQzlKeXArNUEwCk1QUWplMVp2TzBNK0hiVTRJYW9q
            ekRPdFV5Wmo3S05sN3hkSEFReXR5Z3cKLS0tIExwVGpUSWZPd2x2bVI4Z2VlR0RD
            V2JSVmtJYUJGcVc3TTc5S3o5TWswUGsKf+NVytdV/blG6o+Zh65fSbvZZTQtHYPQ
            duMuF4kMMzMhdDzUtrSWlkgzj9I+/mSp83OiUGb5p8sVD8YC+jHmJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-02T22:54:42Z"
    mac: ENC[AES256_GCM,data:oxcvY9YiSQqAC9AmrFvVewYU+ElWRfB2SYxk6SpyxzYhqbctpwh7+pnAmT++Z/2us+b15SLljYWTRiQxd5izu1e4pelQ1jfQPKmU23+zVW91XQM83fyQkAEqvQV7LlhwrQvAu+hx5zGR7ib05fQgihTzMzJNTUsJfMq70OgY3dg=,iv:jCrV/jM2Do1XZb5EHfGc1cUWPoKmjRrk0TvwpPxfqHQ=,tag:Osv+DNPXHdXOXTR0NmYqiw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
