kind: Secret
ansible_user: ENC[AES256_GCM,data:U+X2ArXo,iv:vjP1Dktx9HPlU9YXwDLlig7QOsTFFTxQhAD3VsbICis=,tag:aP+car0o76i3XmQkpDmfYA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:N+ZE+w61c5D0,iv:+W9+SiMihASRiDJxMeLBUzrl7SEgsVo959p2pHxNd1s=,tag:ekjvPmj9UCmWZqm4BkgLrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldmJxbjN0aUFEc1lpSUxK
            NXZmd2RNYWhlSFR1aVZjQVRNeEtFdCtqY2pvCllNZHl0dVVUTUZseTd3N2RrSk5l
            aUR2OTRlMnB2S1M4KzVnbDZuYjF0dW8KLS0tIHg2VGptV3RFYjRaUWduMWhQbG00
            VjRsSjhlOFFFeEE0cXQ2VFE2VERRZHcKED4A7TLhHUWMPcyn8AL6w/gqV6iDGCvo
            gBiSilNxtE+UOrCDfRB8pXePwFouMM1qnXNMNk3+8KNXY3fsULrXkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-03T12:41:54Z"
    mac: ENC[AES256_GCM,data:PkhgIqvzZlfwnhGqGWrpIOMZUieY8cm2S5HasegvP/yPBuNDQLh6SVPn7fP9XSp6+D2evyPLvNc3CNkiOiGdGDgQZvUs1phG3+0f5B0kjBkV84DFvEn+bEwHKw5rMdaj8c4nbMLwvYwVQeVP9oqLB0CIMxYLhLHpPzTgowbwdbg=,iv:Bj1vnXcO0GABl87DOyUQhSLePP+cuJqZDUQVTZe2Gy4=,tag:81+Pxc1SAQeqsy/CuVbLNg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
