kind: Secret
ansible_user: ENC[AES256_GCM,data:eEA=,iv:gjmnZbLW8+AaZtbPlxh50OstK8G1xhRdm6rUo6ldbjk=,tag:IwXvJ6jKVxNeykObGSFr6g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VBY4sA==,iv:xc5cDz6wZ/Id98NvpWdxjH7wHB1QVTkYvMOytUH39LE=,tag:3h3kvETGl2Jsb7xPeEAPyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1hTRjlRSEEvaUdYWTNB
            VVdxaEFQTDZucTVNT1Jzd3NiN1JVVlgxZkdNCjV1Q3p3RE85YzFieUo0TVlzNksw
            NXpaQ21ZOXB3T09DUDBhMFUxN0dqL28KLS0tIFpxS1ZibW5SejByYTAxcExCNWpi
            RnRjT2FwZlFGL3ROeFNSQ0RWRGNqaWMKcGf0Wg2qn1Jl1Wfya2rs/hQjsdzFyd1G
            +OVy/WZ+Kuhk8puVlk3wNdhK6qlbGmE6dVvb/G+wZ0pArEuq5XikCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-12T01:57:58Z"
    mac: ENC[AES256_GCM,data:2lGXyd1JETZ6igSzj45dxQt60tLYCeG2uUcLACJiLFIW6FtOxsAjA0T7F79PqyJElwuiuUPsiCkPewcOQYAEDE9FfiYoX8b+TA09RKzljqZgiN2JsGEjKoIzXwTTVwkxjBRPy8/w7PBG3/Ckabuvbw5UG1wjs/x1pdlKL9wmFOI=,iv:c5rqHOvRewZLnkw8u5qzCi0XW8ZfJ1rMatH7pTMzND0=,tag:RiAeIsEcK7P2RUHov/WbSg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
