apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: networking
stringData:
  email: ENC[AES256_GCM,data:wM8aiheK9DZTwDT5r4lADy/uxn2JYpMlM+mwUg==,iv:h3a5rzFNHVbcKC4iMC9T+FCeZlyMPhoN7GSF7g9YTCg=,tag:SWcp7DCkszWYKYmkXq5KRw==,type:str]
  api-token: ENC[AES256_GCM,data:rNRml+GFsIBylmB9rsLohrHs+YEMByqIz0DrFqTWgYnf/+ycrk3Jgg==,iv:ErXut0WBZSenmgEvJgDkWhdC0KAQs6Iwd7VB1ovRlNk=,tag:bNVuzDflcxua6fVBL0CahQ==,type:str]
  api-key: ENC[AES256_GCM,data:kdGtS2EaBwbxiIHOKcV7T9Piq/oKeF1lck9sWGPoinyX8QO/Rw==,iv:FxrNOdLphCj29amlD5A60GlMM/zo4kIR4fG+Ktw+ghg=,tag:8gR96IAnrRkU4zx1xrYeSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc2JYdEU4dW1BbzB1SVhS
        SDArNVBkc3VCOS9vN0ZhVVVidHlBS2tWR1NjClBoYmg5dVZNMDJkeldvakFpeVJV
        TllsRWZ1bnYya1RoZ05KWXBUdzZTM1EKLS0tIGZ1cEFFWkRIOE5xWnlIekllcVdB
        U3hBOWx1WG5sK09uaDhYQmJYUktkbkEKca1F+Td92Nm+sFYn9mxL8iHHhzH256Ka
        PsTMEMOrKvehLhoIQ5txpeMmcYGDRzEmNnH0GsxlOVatSEKtJrngPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:24:51Z"
  mac: ENC[AES256_GCM,data:8G1qL4KKLKiPfBnxobR1Ij7Vt3CGVYQT4c3iPho5ipk7T7ZjIGKMlQ4HU7OdbtQAubxcLCyi/ztdnYs7BrnQ/aTZDatBi8EEYbWZirA3YLaj1vy8+OamzMIQC2ojpgZz/DUf3mpNpBa6vq8Lf6Pfr41LdBmDiLJmWtJyjCfYjKI=,iv:EQRNGT1N5QszHRx2EAI+XBn6DFQe+CfOyldX0RjIih8=,tag:VLyh79GsSLfYsJtFk8slzw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
