apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: networking
stringData:
  email: ENC[AES256_GCM,data:niMQaSAIcQbnYKvgDqqfVEFmBNXOWRmoFMCTCQ==,iv:ioOuScDLCQZEqDU5fQmqOF/A2xxF5UYD8aNbTYKqBiY=,tag:ueSEQ3ol/PBPeHNm2SzX9g==,type:str]
  api-token: ENC[AES256_GCM,data:Rs5tpU25fYGgwRy1b80yTiMpWc78z6PIsld65kBMJk5PU7wm4V3yeA==,iv:E82rasqkgKQhMrwF+J3UWeSEhxWxRlud1Yj6dGN/niI=,tag:KcdvtmAsGrBo7Lb55l/Jaw==,type:str]
  api-key: ENC[AES256_GCM,data:GJFLFxR5iUMaDmOqCbmZY3jOw3sqCTZdXZQSdYB1jnn4PAk9Wg==,iv:JLCteTK5aprU4HDj2CppwV5aUU2p276ZtlzsCfT08qE=,tag:YaprNNOOx+5OhOd7hhu8YQ==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZzF4cGFMLzR6dStXMU1i
        TElFaFNWcm9lZ21pNGhEN0ZnZUZYOVptTDNvCitKUXNtcnpWNTd6ZHUyWTd3QjVz
        ZVNyVm5aVzgyQ2tGZ0U4THl3QmphS1UKLS0tIERLdjZCZG0xN1JGUDdBSWU4azNU
        cDBnU3QzYTlWV3UzdGlyQnhGY2FNK0UK9A4kQ6Jve24vHCYIvF5ivllszHVNJZGy
        hk02qy9Vcj8Ru1jHfgXbgzfWs6+61vdjPxUpHQK7k/T8djFoqo8NPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:40:56Z"
  mac: ENC[AES256_GCM,data:PPaotfD9DVCklGXl2x1mDwiwjh8TBlZtmchtr/cemMA6bCl8h6GMkXK5J85mcnGXtAyWVjvfD0Y4JgNIbEwMKP2a4qfpmHVIoUo/1zGS0zZ6vVFMamrcPcoldSw6WgeeC9LoTfL+NpMKRsvVntmXEZomJx3pNDe+p3uLpwyqlLk=,iv:mvnV0Pmbs2qjbMufzaJplr1R9zZ+P2rv8PVzureobKg=,tag:1sK+RBsda2AljDt21DxLlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
