apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: networking
stringData:
  email: ENC[AES256_GCM,data:dG9EmsS/S0Eh6qonJYyoRtt7fEkjQ2JwziJixA==,iv:ThrjU/SWnlC1cdZF4fWuPS4QRvA6gS3RUUtxIWb76rU=,tag:SAjfkPz/cengsFH3mAbIeA==,type:str]
  api-token: ENC[AES256_GCM,data:Bi+WA5Dbci4s9Rd0tnuQqxDSE3hVcFxqvhdPYpRe0hRJp8yF+DA5ig==,iv:ax91yDSzZTKTp94QjH1QAtMjaZFYdfOdSf6QSaOE9iw=,tag:/r3wc+b1pFoOXwdU2WjdJQ==,type:str]
  api-key: ENC[AES256_GCM,data:JdUXUmI/FvhA1rEFML/T8G7d/+Yr/plI44M62OlXEjq7fl5hMA==,iv:/1I7rdTGGQlrCESPDxUFDgloQijy43Z4JS7kbYdNrX8=,tag:LiHvJ4aspBGkmUQdgaNwmg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT2lyc0VndzNXQzV1RUl3
        WDVPKzZoQzZXRGVqQURtM25hZnNKL3UySEJzCklJWXREOGRsU1J6Z3RFZENrTUgr
        SVFJZThoMFlCczVsY0tPdk92Z0VwZ2MKLS0tIGJSeEhpYnFBRENGQVVwaGhxNXl2
        NnRxcGZFSnBRazU0NkVGOEQzWk85cnMKuti3UUuDQTkEvJS9CV3SVE+mHKZ6jsJ/
        nQsBspa/V01yyE8+uJ1Hkl9yj0d/+2OE1MX678xaHlmSRDHVOIs25A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T19:33:52Z"
  mac: ENC[AES256_GCM,data:fVakrXBMPzQitoWsMAhhr49Y8+XZAqEy9gw7MKkgLqdpFBTNDecbIfJX1lDj4y6ffjPOyzeAgDlGB0fIoof1NjF8agM5WL42FL2QFCpmg9jtelHAjs5nBBDE1g0/c2NSt7UpB3V5akp1ts2qQqvL3hAKdYEOAC5QYNzm1by+MsM=,iv:nfNTm73fJQGaPaZs1FAuS1snZF1CG4wDwlGDiTb6Xq8=,tag:A4LQs6ZyTlh1XMOJByC1rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
