apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: storage
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:b6kgp5iFPMU=,iv:Wgyk7ta62Az/aQdwiVkNVd7G8KyiliW7jW4uq6CVY1A=,tag:874ppPgAN4qB499x3I5a7g==,type:str]
  password: ENC[AES256_GCM,data:bEb/brexwtkc6J/vaEqBOA==,iv:IPkN++RWdzOvKLeo9XFuaBSZtHPtRwivGXDr5XAxMZo=,tag:DyX879Nmu9zg8/kKclEvJA==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:LvQFEHpoJkkXFOKRd0v7t3tcdPw=,iv:2zlBAV3/BeFCcQPSn4T1kjII5T2RDSEo/dnYz3jjsRI=,tag:AyTdk+3knAYNVQl6q3XSRg==,type:str]
  aws-access-key-secret: ENC[AES256_GCM,data:ky9u2wFxAeiakOzgTxCF6NfgbcZpseEHV1qdghn3w+R3D1s2BkQFTA==,iv:DbKZBIIiADPl3m3ru5clmwUM51qXnYPmydQYyZ7WkjM=,tag:pUonwwztKAdfeLrv9PiQmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMmdGdjBUczNYOFhUZnpH
        REJhVVgrL1E4aXdDMUVRalZhQkJ1eTJ1b2dFCnFvZFNtQ0dzQWpTa1RmMW1Rekdp
        djVkRmU2Q2t1eHVHclVvZDF6clVNeUUKLS0tIHkzS3ZZVWRORm5LMFEybExOdTRP
        ZGh0NUlVMExyb1AreHdUcVdMWFlyWnMKdN8AfayLX5RbzhN4WRbf5xopgXndOyU6
        V9R4qVXfeoBZh17nTmFA9ALro9EVm890LuorzR/m94/bs3lVSF4f0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T16:53:42Z"
  mac: ENC[AES256_GCM,data:KAngF+5LgI+ieSoywF3FPxUj64nst1TPzA0fMKZyz5z+SsZVm4A4x8wewiPBZyNVr6vC6H/YHdDrPyS8EA4WSeWH0I0o8+L3JY4BBfKymRIpaRA35GSN0WwS4IWjtxlpS1V8PMaYm8uqN9gOCsx1GSzGtwohGvasDur5C2OUQMg=,iv:xKow5ppk5x1cAdHAj702o+03/BnluLQ6WEgYmH/L7jI=,tag:jakd8qw2In2Hj0mNW4059Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
