apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: storage
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:EUq+GOWPdrk=,iv:WeARRuDZgyIvNxfB7x2/Uv32NK/rWb8Rd+zrNkEN8Xo=,tag:FnLjv3oCgg5mex7VvsCxTg==,type:str]
  password: ENC[AES256_GCM,data:dh0H0cfGu3Mbs6Tj/LRzaw==,iv:jzcpyR9dARxhza+S4VR/bK5ML7qnGh4PT03LnJ/btHE=,tag:rVi8irjwluDRoLgnHq1Ajg==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:cjOZMBZCGf60KqqiSMJ+Ysgf15c=,iv:F9dnT8+FFndkngFjGSWCQkKysijbFB0OgsmBA2W6xeM=,tag:+I6T5p90KhXqZ7CzeB/PKA==,type:str]
  aws-access-key-secret: ENC[AES256_GCM,data:3VQY8l2OKtivWub1A+YplUYBXNR1RN/6dPi6dMKNkg1WHakCBVCoEw==,iv:uQsYWEmREPo1/22EfqTyBYAAsP8g4DRK3O5YPlmMn2E=,tag:kw0s4f7RBRiDTKGgq85dZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOVFvUGtBVExKbFhXS0cy
        QnJ0ZHRhRjZYUnh4aDZGZWsvWDBobGVpLzFjCjVzTDVIeHN1eUlLNnlPM1krOXI0
        OE9zUTQ5WW5UL3czbzRETUxqdGFwNFkKLS0tIHpMRmUrUjJGdGxsQ3crWjNSV0hQ
        RjgxZ2ViWC84bWZYQ09oaFdLakhHVVUKjyjd8t+zuaj3LMYpsCfxfN1Ng/wJ+Hss
        bCSO9yGehJ3n4Z5w0BFGjO8EwndGz5a2BU7C3ok4rx2DD0sgAoSkvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T21:54:21Z"
  mac: ENC[AES256_GCM,data:dS949cD1/NvG2pUMgbke3py6BaGBaCYQs6fdMw2k+XHH/Wttx71hLi2a2C0ooTiHmcXGvwT496iVM2q6fGTnF8H7ON+NOy9JzTdbCg0jfalmHnQlJtREl7hGnochWhGOmvJOE0AfrVPhjGJQuL3O4RWV7WXnzDVqwjJda5khcnA=,iv:KG7Aa1QJUcXcAaXc9ogDAxMlb1XGAdv2K089LHFtBCM=,tag:3uSmFwcB9ezSvyNT3Xsqpw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
