apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: storage
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:w/r/dfPw1RY=,iv:KHKHsVEBn9ASmPQswRVzMA+1oG8Tc4nxSpvmRQClXPw=,tag:yjCWkodzuACgLls33GtL/w==,type:str]
  password: ENC[AES256_GCM,data:fi0rWX266P6vuPkr4TsQOw==,iv:lBjBFC783Majob6B9TNALJ7eqOuI85NUF0wF5lsyicY=,tag:DR8noWgPHjx0X9+YqlXEuA==,type:str]
  aws-region: null
  aws-access-key-id: ENC[AES256_GCM,data:viKg70OUC99YL7gzNHY0JdzTOrY=,iv:Rdi8QCtHOH9JG5HiezW7ARPGlndvVeq8Z6bFm+D4T6s=,tag:+iE4w0uvJsDwsWrzQewltA==,type:str]
  aws-access-key-secret: ENC[AES256_GCM,data:JCgY+p2h4PV1/MUnILz+mVp/qPas8toB9Db2mrOkNSV997z28iDB0Q==,iv:4WQUFROFSUp4h1i4a77V0ouKXTpLWsgLVFwluhIp1c8=,tag:QgURAA6SIdRl5pb02xJ6fA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaE9KUlZ4aEtTZEJpSXB0
        YmMxNHRJRTlZWjZRU2drUGRGR1QxZGpQTGdnCkNLUWdpd2ZYbk1wY1RTWXhXWFBY
        VGJZcjQyb2R5NjFhaWZFcnVmNENrWmMKLS0tIEJuRmZvRGpkTTJ5SHRabEtSbU0z
        cldTSGt6a0pzSkZCaWZKalR3RkVTNDAKnrLBLnPxNt+EikKxDuMt3PeNJaQLVlDa
        XYi8sfgjWFc7CKo7ydtJAv/MiuJ3PRyWORXsVvrbQGo3P5XTUD/TpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T20:49:06Z"
  mac: ENC[AES256_GCM,data:JPhl1QKwrVFQeEoZ4O3Ihk4SyuwHEzY2a63DAiZfC/a1WD+51bex/598aZPo2E7F3r7uBllK9yTKimw50M35oI7bqUZ5SPD67k+gIquqJeoA0QacFqMqToA6oEchNOuSWL6XF7lyoxGOyFmmuHMkjc/JIGjqO1B2z+B1yiLytIg=,iv:l/hHvaZeDM6D6KWZ4wIpQORLYai2UlQSIaaerJGdLo0=,tag:RVcQ5yXaqLgtl3Up/9E3cQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
