apiVersion: v1
kind: Secret
metadata:
  name: cluster-cloudflared-http2-tunnel-secret
  namespace: networking
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:oVfF4fiWbs9E2CB0+LGxxeArSMU5O70qMHXYxlLjX1lVgCtk,iv:S7JlAwcKdmiEs/vNUvq03w+rzDIJPR0yImDgSmmAvBY=,tag:TGT6AWziXK1jqcoFr1qaTQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:r7PHfX7yvMTIQMhg9OAOG1VL79BlsvtV8iIQkLwRnhXVdeO7+gClew6miqtCINJo9o4ab/aputV2fFAOqYVLrpn0zcfErC2gfQ5WUpPfxE+SqWnZbpGFg6dOECJdLAQPsmix9n1ujt6X5dPcilt9YasV4EJhz38Os0r1hVOfBR2sUbcGPf5CM7O4QeekaJml47LUPmvsH9dPh7RRA+HCLbLwmPOOCLzCdqktGtqXrQ==,iv:qwjS7KfyGXASnkUsA5z/g/PrRaC8oHTQR0c3aZ8KDp0=,tag:XGnk2kwxwist1Ids5541tQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUk9oVGtrNmQwaWF6cVk4
        WXNPYncxV2ZVZkpYbGVFVzRBdDhZRk5LblZvCjF2U21iVXJJY283UnoyRXlVWUtz
        d2xRajQvMW1ZVTRuNG1uL2FkZWZCU1kKLS0tIHpaZDlOSWRkRjNMRlg4VEtseVpp
        eVdvWHFibkplMGROeEVuQ1A4UFd2bnMKolchluupWLuqvnTkvGHJst9NlkQXB73o
        hlQOTA4MxnhT4qBWc083n49jr0dx/kTkFuhOGnxtXy/Lke/plWsouA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T20:31:13Z"
  mac: ENC[AES256_GCM,data:izEfQnUhMt7NRdAi+BRHiAAzzfSeE0Dk2M2owMyKOq5bRT7FOjiY68lKIn8LGeuob46gpLMlrHOoK7cDldGo7OIY2/t5Wf3bsfXR4+dfRvcNxqTYWlC/3mNO/NQmNM9uCvSphxhuVgtWzPg34FbadZ2cN9ZsHL20ELgKxnXsfic=,iv:+epAVIqgjnr7yUfMhBfnv6Z0KKhbXupOipYmP5JezkI=,tag:rcKB9KNjEnzyYwA3Uwa7lg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
