# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-generic
    namespace: flux-system
stringData:
    users: ENC[AES256_GCM,data:QJiNSaUC//bwLL89Nu3UavkZFQcTdZpRdZDE9NEFmJsxmDRXbGeJdQ==,iv:tPkGe4uQw1iMQAVbzDvLINd1IpYDOX04lxU6rFx4tIU=,tag:o5vOv0EQgjsnv67DA6vEQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZlVmZHdiYzBvSFRlcko5
            T3NzK2c4S1FPYTNNK09adTJUYURYWGVHMXlZCkRCTGxwcE9aYTgwRjlyOXdGeUY5
            RjFucytBajJJelpPRXd2a1dLVFZ6UGMKLS0tIGtvQVp6SkFSVHd3YVJTK3dLWmZu
            SGRiaGsrMVc3VHVDSFhLMGs5QUtEZTAK2PxV1ztV/Vz/dRPQ2Kyt+i/VfdQIsgV8
            hRMuCH7anKVekfSvbiLNHxnP1y5t5G1jLxrPtCaKfxlI+A3gR59xYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-28T20:15:07Z"
    mac: ENC[AES256_GCM,data:SgNH8ZpehwxsJ8jAynOq8IkjZ2IDb1Y00BHg/wad9Q/eCB5X8dB5bX11Q2L0IPsRQpgxjlPTb88eSBBwDjFNCiitdtutc+25yJB1uavGB7GeyWmMD2lmtK3OME9hf8YI9s7zu6p8r6mk30HYo4KiWV2lkFWpGMNxLpT3jgaxckE=,iv:y3E/mYTaInMJEMXLLXZ+D5WIBMt6xo6VSmhg8REi688=,tag:HgXb6D777SzE6jIGXIhqig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
