# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4c1amB7JcnDMJfYSMkV5LdwAiqE0Gg==,iv:QmlEfhCe7VezjCyuKIgg/b/Lc3Esv1PqS+23zmjY1js=,tag:VtKsM3A2INPmGvs7yGOxzQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZR4u5HG/OzabHPQIrc5ctT6O6rzx16fsBo6v5g==,iv:qkH9TqS1XG4Tq56EYjMWOCaoyDe5pbsaCDq5a3/ObXE=,tag:q3+MBRwY+KWi2xbcONTGtQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:gKXfGkcXheEJUljiDHSxz7O7JQ==,iv:HBbjiIaPP4ZXZhx/g5XKCGGYbGa3hz4+1Fxvdj7FTHM=,tag:mwyi2TFscq8AapoW8S5Y4w==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:jzGNYO2BKO/yzjI=,iv:ht4hc18plDEQWuQSlHZ1a33iGHMiWedBimDsjwPBwpM=,tag:d3HZZ258blE6OxUngRYNMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T10:36:29Z"
    mac: ENC[AES256_GCM,data:Kro671jFMY5LX4QdUBAgTxXKAK3YPOO5fpreuLF7pXKl885i2LAyTCY/8MVItn996bjl/7NqL/1VIoVuuSNEf0yTGVUHdIcFH79YsgBEEbmxFstUSw81OMM3ZVJlYKDbqYGNfP7VC2CeDvCljozuz0Rtut1Ai1O/BAXkHjRwEQc=,iv:KOyhuz9qxTmE6Qo6uOmuRa3WjcctS8cvZBMF9XBCB2M=,tag:wOWEAeH2mfHqct+OVGX7Fg==,type:str]
    pgp:
        - created_at: "2021-06-23T10:36:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5hYX5iUwZS/AQ/+PpLbmVrJy1AFe8WypunuhzmEIxMH0RatsirONp6x4Zam
            feGhnARfTLBm/8DEqsfUWeDXgNkLg2EooKL2VbsT5rKGYUykFzMZqgE1zW49a2q0
            UEzWYLWdP6ZRC9gxD/QqL/GWvMJMysAn1krRoCmP8DpmsldKRPAyRXNx85A/YFuH
            i2y7zjfBBAz3y04eScaAY7Vq5zAoQNHT6MqjQTfkDjEkHqVBe6LBqyKpkx8JViXv
            P0r88cBZFwiRTJBP7Od4tAxHfznZ6/qZUCVXjXuK54rHUDYBJ6+C2yKfatklfPH4
            GSkr37MdY++MMfINcjE12Wb7jMg/YMLOG31+jwjZFD+1tzu75qZltABtw/NCK8LW
            Z7C0pVi16A51hWjwsDN1fpuuuh4okIp9fpUWL4UnUJ8YgXrGD48CHOJxWxQWT8sU
            62Pl5FW4Y7CHyfrv1zO+ZVrMXo4Goc+7SJhjTbvxuFtAdwe6T6jFfk8RyfK3kvPc
            qhLc6kZ7yoYpywWKZ858TSOflqNnhVhqFO6GMqMgZUHAjQV4eD58/yvYBegDa/Oh
            oKVHu57/3Aa3JLypyjmeRKkdaUefd8sQgcx4Cje2C4BWfnLiYrEBWTjQOTPVdItc
            30unxuxl0xw6+9XLY3x30Py21Fx+ZA2lEcvnlrEjB0zLXWSEZ7TlT6HOW3IpWRPS
            XgHsUJ5nDi9P1jK+vnFbkwSUVX2lLiifvyL9YE7FNMHq/6Tz6N3e23hmy/gTfO4C
            GKqKvWKZWpoIhymOYRbuBB5xLwSR4IJLZaJANQLVY0c5elrPoQcbAiyiCImuBfI=
            =pv9p
            -----END PGP MESSAGE-----
          fp: CA0AFB08EFA5ADBE0A5E78DF6C8227E9B3F4C865
        - created_at: "2021-06-23T10:36:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LWf/ySlrMCAQ/+J/B7SEUgp4khVExzaZ6pPh96S4htuZR9oEXzVBn4BAI6
            gDQo0kvpVusfqt/7W6SZNdl21MiWIJVn76Z/yFJb1tnhbnA4FnuqDOBQdesB2a+g
            nWTMu3fkdlfbcpDq3qhq0W/T/qXQ10aCj0X+c6d4LRTYwhyXxEuWEw+GC7JbZoSk
            9AhFOioV/MdzCDMnNvMzwF/Scc5MGTf29t0EuX/shPAEIVa28dmLAYVfjtwbeSWm
            PQUWVGkwtsXsODQ17x1OueteNtZgKPV7wRsfQNB891ss4ekUQ9K3/aC+tZCexwO+
            VwUCFBiyGqA/rqoIz+ujq8EfjBsaaQar1kjIwYIk+rm2QoO13pLmIijuYruJsrVz
            c5VffrxgPOOyb9jRT8MWpzFaWilbok7hVJnlzgOoBCrs5byhr6xQ7iT0RmXY81g9
            zL0DPT3S56iVWknrP0KDFtgpiFcwiY8IERjPba9xiTIG6SAFWhd31I1HU+Autf2p
            5TijRh11rM8oHhcRkgb2/gYVphyGB04DE7Q1HwZ65+g3kkWT2MFhFjRC0l4HRBEU
            gkVRtP7opGOJmOGsk2WsbIhlY92A4MFGI0PCIp+AWuh03VRdvB+oNSxeRZ1CQYx5
            5TKgLwpGoUmuoRNnxcZmQ193UUvSViYOi9Rr5BLXlGGZdXrdXGtUVAlJLHdF5JbS
            XgHnl+UsApZl64fDDE7Yz/NvZbtFXCmzgnxUDGKJfDsXIxENuR+RaWrec5D7RrWN
            KHnhvUaAt3xaz0XvxCc2F4lvpXwb+RgnyahtAoX5h9WFHWV/rkRPlv61tTlnyew=
            =hRpJ
            -----END PGP MESSAGE-----
          fp: B6A28EEB718712C99403199C90BA7EC781CFA5AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
