# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FVaILDabHyCuzDCR93QFxav8TeXRIg==,iv:8G4UEU2itw0muWbgmG0YHbj2hNY7Cxnn2dzZSdo7BGY=,tag:4g1mXPLMMefQE6v6Ri1BoA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:jNtLLf/yqHA0K1btXTWyTN5H4aRjQnhSUzJO3A==,iv:6ga7xlpkNmDj2JSY6dZwKChmcc66z8qF7bHoxfuzffQ=,tag:yDgfKzOAZAWa0FjginLznw==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:PhwOX+19NgglWTs=,iv:0d5l+xKrVwtRfS4HAbUBaCXVV2yuZjt6Iaw0/S3iD9Y=,tag:L/+b3Eq8WLTz8UHLT6r2eQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:sfvNrTTSIZJINz/RujEWBw==,iv:wpYV0dhELUXpgycgQMzAPJtYHEkqMHCWG2t6C4+agsU=,tag:KbswBYWnjQSZFXu4ITzrTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRVNzRjd3WjNvU2VhN2F1
            Zmdsckk3N0l1Q052dHI1RmVzd3pwbEwzSndZClVua3h5TStxbXpTeXRRQ3ZJQU5Q
            Zk5iaWphYTJNMzlXOWhqZUcyNTZUYUUKLS0tIHpQOVhhc2htaWd5Wlg4TThHd1lD
            MHRpdHpNSVl4UHRZLzJ2UjVyU0VLRFkKlXZYw2pKJNomc1HcBxNl050UMAy9+iQ0
            MsCEszv8VuOxIsQXnw+rW2LSFP3YBKeRBu15bvqpCjtE1bhDWDO00g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-28T20:15:07Z"
    mac: ENC[AES256_GCM,data:AzfphEN1/5OeYZeBNFrV3jTeNz9YqlYRTmLZa4ttsT77k50Afxp5Wt9w8Ntr/dgM1sN2m6+2RoxyLoQ+83EH/p+GhEkUGzqoTrJ+qHqwN9Vk03j21SCO/QulzdhGcxg9S4H8oGS14ayFrnk2w88pLy/ufyNENQkFSB437xPRdxI=,iv:4KJdZ020D17sNcUb6ABJW72ymePD86utKrM3ZUbhoWg=,tag:QQTZvkHi7OhfN9sirpPFaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
