# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-generic
    namespace: flux-system
stringData:
    users: ENC[AES256_GCM,data:Bo0wa86qly0CoeSAvtMOw48P/JDgoDeeOLE7NZCz971YDTBqogq/ew==,iv:lEsgPeT2fUwr8kG3ZvkTOewKyriBMGyqp8vfn9yYJMM=,tag:SRN6AcH6ozgr9o9ihYlX/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdk1CQXlUWkFwWEhiLyto
            NjZQWUlvOFYxN3lKOEoyT0lLbUhNN1pYcUZBCkdQa0J3ZXl6aTlnT0ZNUysyWHFC
            QXBnVjBNRU5RYXB2bWdsSlBIRi9XNjQKLS0tIEJKZ0UwOUNjUzBWZnBRMm1DdUMr
            d3U3T2l6U1lNcU1yVXBkMHVrcTZkRXMKhJ0q3PeJrO9i5nlvJ8BX7FOVULh2sAl7
            nhyCqTxTSudW9PrjTM01crEUbcJoR2xc3tbwqbO1RLsE3ov8mDW3yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T02:45:57Z"
    mac: ENC[AES256_GCM,data:8kmsfrBWjNcQ7+rZssDSE576wIHtwRDnNDQ/4RlqPHRteAr1q6j98aYiNf22Wp3jh4nlDlWs50eZLC8nnXgSukSqDnua0ZJgB9LOZX/qmG7XvEE+3tYLQV2mfMAduj03n+0xwQgxwGoQTJJ6ZKbHP3n0hBxGoVpZq8gGGBAazFc=,iv:zybYr34S3CsWgssDayId62N3lSWAUquDLDKhyOF78Tk=,tag:lSwY4lG1Vha77pxxR766qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
