# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:zaGaa9HyGiPq2wO/BFqoqgjnj+4TjQ==,iv:eqC3NX4eYLlyCSmJO6ggr4S/Ws6elTxpsvGjcQdGdfg=,tag:s9nnhbo7P+4zZ9wnKRiySw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9U4njQgXDuSPq4jX9Yv64y5gRlwDVORCZiafYQ==,iv:TNAbbSBpXCrh9tdpaCtQJiF+Vcw1BpHw/7Gzz+s/M/E=,tag:t532sQbJOrhdOgvyg+qjWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-18T10:35:11Z"
    mac: ENC[AES256_GCM,data:+3NjylTa13a/UtmskyKZ5uRrTeSpoPhnn08LFYistujD1DEu4vDesyqwsbm+ml1fn12mLDfENFMVviTyf2X+r5cbKE5eZW8/LPS7Hy5aLqplR09Xw8lXlFyfRxEWc0X3nLMJYwqJOPBiGRUTZgOOrQGGnbsKt908qyxIqReVGrM=,iv:7wnV0oC2/fg7FtqKvGFTjch37dRq0Rf00vwIa+dSjAk=,tag:Yru6MEoVRMZpdQGzkzYV7g==,type:str]
    pgp:
        - created_at: "2021-06-18T10:35:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5hYX5iUwZS/ARAArNhkiud5XLrDeRR2KZq+wtENHyYYUBFGLZNx0KjVQ5mk
            zUR/cYidKTLnPhfQYu+ssu94UlPW/HdSW4BfHUfF3NxE6OBWfyP3PI5kWIsF/O4d
            RmxHx2P9Yy4ED7gzDVnD6s9LKNzwhOUJ83sqeSatRKcgWwpEd16jvdpOG/tvLMmN
            VDMUIeboSN9RsfOsioCj5ogSRh4LCeg4NkgCUYQyV/81qWUcp2DOXOz9xbAlJU0q
            rWEzziLqEiQXPssvLV5aY9CritDxbkG8qAj0mZLnorc37+xFMliMcFrD571kyQvo
            qpAgl+FaPCMO8AaWkNB2fgcNeEvHAs5rXDDiam2MbU3VuKwTbLcuPDDv5M5/0OFN
            XXVelmhvASxiQKcLoc4m9sd+ph+JDyjPF7D2AW7TZaYI939JxOMnalJSZSpz4MFN
            YttRBAocdfPUB6EuEREFH0kNZ/2CRzwUqQeb+XT6/wwXmWR6xUp2rWR6ZSkaARBD
            9/Y5+F0C8EyEfOi3b/z89GVBPR4WEr9jVKXW/OymLjZolTjsVJcZ01CDGXYmLX2z
            ELWWqiusI07Im6omW+CcoP2MSZxysZGismLjKthe9HED5mYkJMpQsKLOLfxopDqg
            A4n2Uxdar61xi1uJQiShBRWuI3pkLgb5NSNWfUuoZ3Yjls1Fgu19EGv8S9ygnTDS
            XgGJWBbv74Se3xnT0e8A7ttIK5qC+1/Qnv04Z9zk5I7VxCIpPUasGLcrcPiUD3PB
            VgRqc54I2XoOqm3A9a2+pug9/KkwPF1NtviO4KimemhZe+/48HfULCKficlrdUc=
            =e3IJ
            -----END PGP MESSAGE-----
          fp: CA0AFB08EFA5ADBE0A5E78DF6C8227E9B3F4C865
        - created_at: "2021-06-18T10:35:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LWf/ySlrMCARAAg5w4nsZfNY5Mxv1Qht3elTp837EPtSKoMGYVunF1o23V
            ZRfB/CHaVaQkUt7IjqoOEKRsnmKswsZ9s9QuJnHfh1R64hn1QBUOP6ET7/v53AZq
            Sg0+8WmjFQ3Bpel1uzv7HoDILlZhztLFPFWhvYzz4+QVBcyYU21UNqiJgFqJcqY3
            JDcuj+p44OHzyIHnyj7TFIB2stXTpo1ZCmFX5TYDE9CH3Y1jP9A8l7ABQbJ3GEnJ
            wiPCcI1fzuxwmCm4bvHZcg7Mp2nxX8hcjBcsGG4a8+fW2dlMFyHzqy4fLJ33ewvt
            dHvWF6NNxHa7jtGQzfWdbo/VV1nW4Vtmv6zLn1wrQ99n0/Mwea+3ndaOVB/o564/
            +4ivim0eUkHgZTOE4eGZNqki22oFEavOQpiaDxael7sAGQP3wcfwb+Eu+56IzmgE
            hafUq4KL0g9vzi9lcDpPX6NMj84SxZSjAbA3DgByj0IaKAEWl3aXLZMl43T1xfvv
            /OJSZ9+EkF4ih5CaHN7fNZa9meCM5oMcvZVyKEeoHI/EJlGop1pOWKVAxrnTW1DN
            sP3xPic+i1i4g9gw1CKNLjIc1Xu6oHADbB+QjZnh4MLlZeh5vVaMgy0mtCmY7q01
            rbM6cqoAVLSbJ6iEQ5Pz8nCI03FDX/tjRJZ6jfChXZvcqdbfd0BFT+gIAfGOLd7S
            XgGBEpEpa5X+nIDIo7f3iCIGmRCzEmupgdpLP1HWB0ZGbuja2HqCjujeK80eq5b5
            nk/3GoBq2jCpjUyZFSXbsBZASW3AncFzC6EnIYBfJ/CCilSdD2bhtCLP/Z16JJ0=
            =LlZH
            -----END PGP MESSAGE-----
          fp: B6A28EEB718712C99403199C90BA7EC781CFA5AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
