# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:w/rkFf+XiEvk8T3ZgE5fOLzRZgEGwg==,iv:fwwo74VGuUkeuPHVPo7e9iWezBQ6MNDMRRw5/fx3rlM=,tag:tGqmhAvID6KFKuBUEAZUog==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yE8GwjgzGUByO5lYtklmVS4ekEAlmtcFfYgVKw==,iv:g0sOAVHefru+UwePx72nzMlrnKweu7EUTCCobLzwO/Q=,tag:YuJKeH5B2cn+LJWzzCfeYg==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:Jxgr3SE+PYU5SCA=,iv:tRMuVj35+4RaexH2EAxbXUqH5VM1Fw2BRDQH4YTiC0Y=,tag:EK24Q72+ywW9qza/I8ungw==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Qpdj6I1yIaGnEd9qi1/NYQ==,iv:94FhRrupaRrh7zrIv+C9o/yKv6zx74hZSKId9bq1LT0=,tag:m9Oq2bDEWqi1m2IwPi9o2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUHk4UFpwaW9acXI1WUZm
            ai82MXZ0dVJNbldYSzBsUHFjTkxiMk51cFdjClU3aUo2Y1huUEl4NTZLNFJ3cHcx
            QzV2bmgwdTNIbVJSQUZ1SXU5OG5Ob1EKLS0tIENYZlNxZzZnMUNRUTlQa29kdE1D
            TVEwdEdOOWRaTEppZHNtZ0lVVDZCK0kKHHBl+h0aHnSN/QgzhGRnVU4KEEKpwgAe
            sjdTU7KoY5DGnhk2lOabPs4v6z8h5nygf6hhX6RgZ6gs+iDOHcb++A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:52:02Z"
    mac: ENC[AES256_GCM,data:phhRwt7td8+lxSjBP7Uls17XV5NQ+XkM2XZoZtspYhHo978c+Fww5Y+J1ACjnLD/ht7FKpap0x+TS3KGGv311NB44UVSjTvV2TY5SckiEvtVIQvTfWCh7Kbs+PtCfCBgnhPuKJCGLIPIVKyKxL7i+tWC4HW9hgnAz62NGQuWFQE=,iv:UZL7A5M0efL80WgHDqeo1Hr9lNOgHpLUDCKIA8/Ptxc=,tag:yLCVgbKQ0gUbw11p1q0yZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
