# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9htk/U6B9uGKLEoMB69/9pfFSFf9,iv:GhK3BvKUBdZumjfpeaJRWrconCXfLrIZ7IqGPkBQJmo=,tag:kbzDNHtLXPTxXsCIKD/foQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:oOdfmy1aQe1wuhKn6aEgdQ++sLes/ox31E7opA==,iv:hDLEyDfweHLgl/EacqQ/btA7ER5hHMnr51mnsem+WAA=,tag:lS7VtoVrEDf7qw60l0tKzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-27T21:44:41Z"
    mac: ENC[AES256_GCM,data:ebIi+5UleKyHeSV2ekkz5le7/WQSOFf5EWWWNQkdS+Gz2LWl4RBgTcj3pwGTWRhSwKe98quVrcaZY30MF1RmB30MqfeaHgRdMGRKTUxLRC7WMwt+qZPP8zOHhcsYalipsiDsWjhaeGDyvRcHR10AjuvC7vpRAbMH172Z05DQLRo=,iv:sAUqHgV8s4/D5/bAzSy/8f7vf3MnTTdGKhj2htKhKeo=,tag:/EVYousYrLmtURLrJIuFGg==,type:str]
    pgp:
        - created_at: "2021-05-27T21:44:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5hYX5iUwZS/ARAAjC42j52lLQzAh5fo9+4Sy41J/I5H81pr1xYuRnXAkwgi
            /vRpbZ2iuOsJP0C7zLhF1S6G3z9CIa3t+zF+SiieqwI/Q+ixlMPOB+RlngYjSe11
            z55hy0pCDwfQk0fHgnewWRsv4Gn4TLzDsoxymEFeJeojmIVmaFYzjsb9wgguM/ty
            J6bsBw0vJ5LWayCEewR5iRdSeucKUiVeOLm4QI2F/INGJAbjOxOzb4LWj9xwcrEe
            xqPHtHKW2TF9W2hW/toVNPWgvZ2ai9N7IASl40zPRxmeymKN1KcGH1RCfmshlJXC
            tN5ymB9IDPhqLpytZUh3TH2D1qDvGvykS/jWyDqmkZRbofPfT8dIDOeW4JLLkgUg
            46GtPw9GtSzo3x6BEHBi1fW5fl3Lhg5SyNcGkchjl4e4ZMgapZrPLWX0bjJuNQoT
            mSaMKKrYwJVlDoY0RKP0GXI89u7OnZrs2zMZtEqcAkYtiTDd0dYpWoKDUW3Wn0b0
            sXd1XNbgsLhCroGcZYHxTlFHOPhMO6nrJY82Aw4N5FC5eoe5YCo3hgnytiR+G7QG
            1mYOcOtKZy+Hqc1oLmN7raPJGQVqpU5hyHICFn+fFcKEaeQIlxQum57B/5IFl7Tr
            W5OsALtNVcPHHzobW4XQL6Tv6jdj2zsSOM85l74RhRdnBr/jODNdBIY3KCFEt+3S
            XgH2R/ZEZoW8GkYDrP1MHhvld1yuGJTnDM2dhI+ssqPceRIHIasHm8850zPKNwu8
            ClxIKJRlfHi8F3aQGOmHJ38px1N65Hv8QP4yuaaYJPUhNLw3Yu5t+Cl6fbA/hXw=
            =M5J5
            -----END PGP MESSAGE-----
          fp: CA0AFB08EFA5ADBE0A5E78DF6C8227E9B3F4C865
        - created_at: "2021-05-27T21:44:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LWf/ySlrMCAQ/9GkqV4b8MkCpoMPotczGzVyph/d8lBRffSUQhj/XFlh26
            F73xo9wcOcf3RJuP6rnJXTi+G5XemzNzGaQeyUNCCp8pcJbqOsO76fAEh2R0HF8d
            2oEB9WNV2/SkRpAtCmuK1DNCrSVE9kTV7Ek0Tkwvei8DkVVWPGGwNL+THRBeJrtz
            fir/eMPk+605yd+wgZxua9M0QiDDyrElut4V6bXLg0HAzrXrns5BG37wbsYsYm/Y
            7JSSLARN4klsB5WbEhujxefnXa9OKxTSu82+zfDa0Frs5//INIFiHzCixI1sCTXw
            KBtM+yZ0G5fDDAhXnkrl6x8AS3oYCmZmWStJM/Qf9bVmArBak6WBlvXPAExY21RG
            t3zp/KXpe55S3L4x1xpM/pKndDliIqfoSn6hUO6AYmIAVPDLPqUvcEm50jnu69rA
            pAmWWJHCesxmZXRP3KVXorOV+3TcR8Ybdqyf7Zt+3ASJ8etKVPnDBUlUU3vtUteB
            rLOat+zkjc/x7FuuJZnKhFscE9QYek+vTazlQXDs5iQG1VS1DRHApsvyuY8kv88L
            YTOF/dan6yFqKNv9KQ5SLfAKZO2nVqGKl6Va4yfe+UKIoUMUgZHb9snuYM4bjkoJ
            1w2Z7HX41qxXy/93CoDb9loHqVVxrD+CXUH9bbEtt1aChau8qsBd2Q+7jiiaP+vS
            XgG1yO1MGkJIi6ks2na8dMjlhqaQVhJ00pgNgnnulRnYYOjsokq7FjQ3ie6x+04R
            D7FGGd60kPPl6FqGbyt1WwsPGg8ZX6/d3dDEPM+zDOxqWnAGqqQS9emzPxLtOho=
            =U0FR
            -----END PGP MESSAGE-----
          fp: B6A28EEB718712C99403199C90BA7EC781CFA5AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
