# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:eZElZFrQ1phW618Lq+ChFOQUKDs6IA==,iv:tA4fCKVhjbSMXpbJa/sXPVmUvROLAJImNv9CTDpH9WQ=,tag:HUgR6U+J7Ilm9H6WC759Fw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Y4J8SjwR+Qi3G2JwhQiDQiAKT7gTcOvYgBPi4w==,iv:yr65GOgVPl/7GCK2sDshNjVdX2G96l+/Kge59vBS2n0=,tag:H536iWWaV3t1LoIQFFi7fQ==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:a9xuvFEOXB4nrrw=,iv:7uO4Kx3bXjmzllhy61rqmVBtuNcMZ/djMOmlPAc2GHM=,tag:ykLpRmmZRk6nSmOzkcXafA==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:1OBWXzb5XGri/pfYMRGcEQ==,iv:glZLlCTO6YJkOD2bHg+2hMueKSRTXsJshHnLm0hHrJM=,tag:wYZS4RpyksH2N67696Fb9Q==,type:str]
    BASIC_AUTH_USERS: ENC[AES256_GCM,data:IrxHnuOWGz8bnODCfDbxshFDjvdSuM6GL82XhM+SahuSMXZxxaYCWI0r10SNDs/4VQ==,iv:f/WmjAALLD+IbgYPwm7k648IaBFPpeEgDs/wKEyeCiU=,tag:1i8R0Z5FyvSi1r9BrL+QNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bUdwU2Q4NXA2SVh6YlNJ
            V3JtdFE5VnlnUEFOczA4aTN0YVZiMGw3U3lRCld1YnBNNEtIRFY5WXFZR1UxZlhv
            TE05RVNrLzdveVA5bVpCMWJFamVpTUkKLS0tIE9NdWJyS1BreFpibGlYZjJBRGp5
            UUZVNXNpVWV6Z0o0ZnFQYzRKR05rbEkKyjlMTYWSPI2B/McJ/bt0cU0/3JpkmlQ1
            9RutYkiZ6z+SlGWcxEJfVm4SSSqnbc+UpJ4xf60nQZRsYUNnGNe7/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T23:45:56Z"
    mac: ENC[AES256_GCM,data:EjFvhw6t9XFDaDXVi2k0wcYv+UN79/Up1iXTV0gJwsYponSqGer8RID/RuQ1oEA/BLcXR/3mrO34/6gHGYXO2mv+oGufDeEzQSjKZbZ9MBiwZwCNO8f8Qv0VcjpQDujYycDDYkcIYxz71XTb6/xQc0dTPY7JZ6dO1jctrB22/zM=,iv:Ml76CgfXHPsvewj5mLOUglDP/4lfm6q63vNgt3kR+hI=,tag:4FBL0/DBzskHLlEuoCFPIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
