# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: generic-account
    namespace: middleware
stringData:
    users: ENC[AES256_GCM,data:CrQ18zB9LBkSJ/UlhzldmCxNF+yOz3sQJ4ryaSCOMYio3JAHc//jKSlTEGS9Dhoeuvuatn27aIGK8ZtvYONbNA==,iv:cnZJyw8ZcfM/M0ABAOjg1QXz9Mjz7IAyNAML7MwZ66c=,tag:66cRnB4LL3HV9Ioo0Mvwlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Rml5ZHM4VWhkTkp2aDdP
            aFVmbjUvZjZCem04VERiWlUybCtBQ25aWHhFCk1CVXA1TFpsd2loYjg4K2lBZ3lp
            UkJlUUpzU2VBUFV5YXhIQTAxMXlJVnMKLS0tIHVTTk05UUE1TGRsODFzejlQRENE
            YnBXR1FOYkxFdTJZNTM5b2NjVUd2ZnMKg+fKE+qmdVFj7ELkiHE/2QS7WPvqtddU
            RmrDIGI1DbSoAlXYidkHmEB8d0JXN8BTKJz3lIcV39pxv6SqwkgXIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T03:44:18Z"
    mac: ENC[AES256_GCM,data:6xZmhkA38aycGJvdE3hj+6JnCl853SVLIsU7UNoDV/bL75iotDhIxaheLcF+tHyqP+1JrsgQ0ao6oLB3wbf7f8uK6pItZzvXPx8RG4gYKwSjU9M9plpxDvZMDHUY3BLkXA7DaEHjJA4u7BawPR4yK1P698UO+tjKrHvD61kef+Q=,iv:+fLOnHzWkaSbH2PQmQqQKPlWEg+UWXe+hjN50LQuy3c=,tag:2g0DMkiNLk+MwJo6bVqxdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
