# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: generic-account
    namespace: middleware
stringData:
    users: ENC[AES256_GCM,data:JUm6GQ4MUFctTcf9O3HaQvFQFLwERfaiTxKzXYipS/2qYpBtCyVbHUMXOjRR+Je96g==,iv:G1mZXJOeUktVC++uVAWxdtyQxubZVKURY3nzXmYv+Nc=,tag:yMBt5MWR+iBjWq2ffinVUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdjFSNmJFdFFUSTNIRDJs
            SzYrYnFGbkVTcnZvL1cxdjNXUzQ0QU9vcVNVCkVrczc5b2I5NWFuVlpLQXpBL1RM
            YzlZM0VkenNtWi9TQ2t5TFl1cW1ZUVkKLS0tIGU1Z29iVXpCNUN1SWtuODlUU1JP
            bHVrTnJCU0o5enJtQ2c2Qzk5MUN6SFEK3EU7p04VHRThE4DfwJiu29twNbE6WvWD
            0u/BP3iPq91y5ES8oyOxNzj10YdQWSmNp33TgYYHg58/uPBnHR36uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T04:21:46Z"
    mac: ENC[AES256_GCM,data:ZNgPCxH8PpUYBd/kKWJsEM5f+d4GeDSEZxy3yk5umvV945HdH5pqvAXSL2xwTTA9/T2Y4tOewi1tXN047QjKZxO+Gx0FPkZgowpk2TGcUXdeWmzsdHMdQ+2oLCiBi9qjAFg+PRHIttRwQSsgMVOZM3zJFhWlVogjaSM4TNVEyRU=,iv:qCZF3n11Ud7GzE85DBmsqRGtM2BA5waXCY6ntZmsz+E=,tag:qqy4SsRn7ebEsR5JJAOqdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
