---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr
spec:
  components:
    - ../../../../components/zeroscaler
    - ../../../../components/ext-auth
    - ../../../../components/persistence/jericho-nfs
    - ../../../../components/persistence/lordcommander-nfs
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./kubernetes/apps/media/radarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: *app
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: media
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
    substitute:
      APP: radarr
      JERICHO_PATH: /volume1/apps/media
      LORDCOMMANDER_PATH: /volume1/media
