apiVersion: v1
kind: Secret
metadata:
  name: netbird-secret
  namespace: networking
stringData:
  NETBIRD_STORE_ENGINE_POSTGRES_DSN: ENC[AES256_GCM,data:iH6sEsN1tZzze50SzrFMyQhOxsbpJUttBqdtFPuzwgISM7RtQ/BgeYarbrS9TO8n4hv+vHzHDztOJX2i7XK/MKLM+HBJUclVxj/o/cJrfxbULRjHdrPMDlXV7iVNOleNma7in1K0JOFDGEUezskwq4L4NjBDwwee,iv:ELKqDFFwAw3gbBUntmvhKTMRBMmWyqjwU0Aa4NCm9cE=,tag:4hW5KHF9GklZL+5w5yd9YQ==,type:str]
  STUN_SERVER: ENC[AES256_GCM,data:QRr0SwwGvSOaiGJUmiTZNkAGySFUz/klsT3s4GLWs1iri82552Mmqw==,iv:SH0VOABQVh5bLQgn7P7YLf8eXEdgVboCDgVpp/mE3s8=,tag:IUtza1tk0cGLMu6draKvzA==,type:str]
  TURN_SERVER: ENC[AES256_GCM,data:BLdubCtEHM+lfZv46ofFy6bqEQ2lQW6k6qwEk0WU4bDVjcWDHqXQ9w==,iv:Oljum3piBmhNA7cV3fpOvm3sIy1uGOlrPLUzdhdBiTo=,tag:IY4mTaFfs604k7Q+z6A2jg==,type:str]
  TURN_SERVER_USER: ENC[AES256_GCM,data:E1uFOmlnpg==,iv:uOY7zkBwcZUriDx4JqAYxmjSxOyht/rqjzq/IzamMxQ=,tag:i1fiWM0ga7LR6yeJr63Xig==,type:str]
  TURN_SERVER_PASSWORD: ENC[AES256_GCM,data:Fw+ZRZ0w/kswD6hlPfQ5OxW6NaY=,iv:udAAjJKkhwLVofMhB5LWpYyTWhRQ+EBEvA0GxiLEv8s=,tag:KExaQIK1XiCd9/FElFXgsA==,type:str]
  RELAY_PASSWORD: ENC[AES256_GCM,data:U7cTPrgDG0eQLIjKPviT/Zyjxu0=,iv:N0HkA7gcSjCfHMvrluOT6ujuRtCPPNtlJxKCSYUmhlg=,tag:lX+Uu9P4ciPfXmeck0x2lw==,type:str]
  DATASTORE_ENCRYPTION_KEY: ENC[AES256_GCM,data:yJkxJEG9C35Je0iVE9spLVmgyr+v43En/Z0PgeOycb0obPYstSLnos0j/Gg=,iv:QsXmLi+NZcdXrew1iByetHouaMqDuYUhS/Otr6oDDeo=,tag:TTnAwFV1zAou+JYNXYHRww==,type:str]
  IDP_AUDIENCE: ENC[AES256_GCM,data:cy4vWhi7og==,iv:6vT1cfPJ0SKY4VbLl4mI9EUqQruGsHVHgoejCevzypI=,tag:U6kT4Lm25mshgMKCBnznVw==,type:str]
  AUTH_AUDIENCE: ENC[AES256_GCM,data:E4Go4GfkiQ==,iv:YsKDdq3Rlt5IexJdIm8QIviMR2nMf87A4TvfLkgWEEk=,tag:LiyAmZjON/ZWC4KxPE6Slw==,type:str]
  IDP_CLIENT_ID: ENC[AES256_GCM,data:aQX8JXL91Q==,iv:VGj6X5P17Fme1hHQtOpA3KfZDmWyJdeEdZAe4URj9qc=,tag:IVdcpr6hc1lh+69enTXIVQ==,type:str]
  IDP_CLIENT_SECRET: ENC[AES256_GCM,data:HqePthglB7+XDGlX1LPKnRrVzn72,iv:Pthxg8nfd+tMM+fFZNFmStrQPiCOk5HlJ+NUugbiDdw=,tag:i9w5+wmhOlsahffYsvLQ7A==,type:str]
  IDP_SERVICE_ACCOUNT_USER: ENC[AES256_GCM,data:N5tNj8Yo+w==,iv:/k0+KzK/qhKrGUSMGObC1r3KRu5wWb2A0QRax46vU94=,tag:9tUhhocj3OFsqHJN4dax/Q==,type:str]
  IDP_SERVICE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:8SX9+3YuRyZdDACG8VvTDAGYb0t55EF8Gdbg+HQkmSEEzdILz0vgm5Ye0ljTWt18e0uScbs6ohjTZg==,iv:mirKSwK2cNJ3vV2zifuRTo2KEksqMp3CdvuJMCoRwP8=,tag:m0SUL5VbbPHuL7yf4wPNkA==,type:str]
  AUTH_CLIENT_ID: ENC[AES256_GCM,data:4eQfoHAJUg==,iv:rmFQpT09Sudud2Xjq0bLDSh8jv33FjzX3chgpQzCnnE=,tag:TPp4OIUmSHTtkNtfhVMHew==,type:str]
  AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:PcUjgOkobOeuZdTKS1UVnDtHX17L,iv:i0NwGtG4pbcQX/Ea89x2y4SaNKGQUDYfy9J5wymGYxo=,tag:xD70u9uLRTqlZP1UD1euQQ==,type:str]
  NB_AUTH_SECRET: ENC[AES256_GCM,data:jkevgwE4+MEY/OCsrdLSqHzxQes=,iv:ErpdBBxbk2IyioGU7EdriSMp8nw+NiTVGh03Jb5j9FE=,tag:V31h4uz5bO+mHRsiXcCbXg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:UGtSvG6EFw==,iv:2JjAcTmlRUcG8h3CMLVlxIqCCA/vvtJcp6XniwWtUOA=,tag:vOyiwuPAwQRWSrVGPj0pyg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:eEFymF0y6Sb/NgRzgshDLNjxOl7i,iv:MdPWrdm0ABTxoBbUgaUlv60QA96iWPAn0ICSifheQ08=,tag:MytzMN8yvQ/0N9E4Suxnng==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:CYZIhJQcwlx7oaeO76+avFmK6Mz9jPos2ek+qbkcFHV5SFBWzA==,iv:8/1y98X8D7rIajeso/YbpOlZU7DVag/cBFgYzoOd6pY=,tag:NxiR1u9M/Hek9bULK0tqaQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:uVDYP/s2Qw==,iv:l0KuXNg3i04/3CddBib0wH0kZnIV5NhTmBdI35EwWCw=,tag:527DmMV6olXLGbtk/yrY+A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:v6cQ00fxT2y/iVAsg8Txxg==,iv:fYRudFFED/j1q0SgIaTYtS4zNjNnqUbKSLKenqHIvhg=,tag:Fu1ryiof7iuWqPRBKAuROA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y0xycjcvOGdHMTJOUFpi
        ZThSa2dsbHYxa1FoeFJZQWlyYjBkM0dFNVRRCmNFWFNTOWdmbG9HZzZrVFFUUFQ5
        V2VBT3ZSQ0xaU0RtSXRLYklsMERIM1kKLS0tIHdvUkp2eHB0cVdCMXoyekhLQjVF
        MEdSeThURStLWlFGM3puWjhhNVR0R28KuqL8vsX3ioI2PAidpQnpctWq5D6S/YI4
        pSz6bMtqLJZSGOjEeADsxQ0Uk2Bzr05eGc8weqL4or1UYwBBoQ11/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T22:04:49Z"
  mac: ENC[AES256_GCM,data:s8vCJG8JoK0WirVv1zwdQkrGCjWopYa31F2h9qPqY9Bq8tOsxs5rYgLHcOY8vzVm0qDcJTNm4zgv2SiUeH6FqpdpR3rMBFPdPgN68G1zltOV5UwBYG4hRaFSsy+HYU5HXBeopYtd5rsupl9JuqiiPT+eXq/cdBt1TeOPeL1UKEE=,iv:ocJP26Ud9Eo74fRt5j4zHIuxWLMCtbnKzoOs6FWLCuM=,tag:kwsKXQvEQcRTdlI2aa5uyQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
