apiVersion: v1
kind: Secret
metadata:
  name: netbird-secret
  namespace: networking
stringData:
  NETBIRD_STORE_ENGINE_POSTGRES_DSN: ENC[AES256_GCM,data:15qrwj5H2ZqazOdvnWYQRQkA82aHHbtt9ibH2pAKH2aWpSI9F/j6zZ307JhixuZiR7YM4T1rJg0xMbEPCxSfRd36nrLy7xz7N45PCuVitpX1C3XstoUOcVKvGoJ4K+Lup2OV9lXq7FpfL5pLmO62F3KmbPvGOpzI,iv:Sz0jmYIFVvwlTJTo+A/by/3hW1bZXRQMQpIVlYRMmLA=,tag:5yKngFg9k7/HaHIt550mHw==,type:str]
  STUN_SERVER: ENC[AES256_GCM,data:x+HtXGEPAGxLLa3fk5quQRc8LbR6iRf4FKJCtoORABr0zp7ZUDwhiQ==,iv:sgqMEmiqtduUQ4xPge/rcVQUrLmGjdzzHcQDdAjjxyM=,tag:xweyz46srwJk4HXauUmvsQ==,type:str]
  TURN_SERVER: ENC[AES256_GCM,data:qnMsSl+zUt5n3etLN/tCXK6DLledVm/MmK/KTh5R6BB43cHhwQnYIg==,iv:WNNrz+NRdmkjZAfaQreFmgrrxyltXCCHZaG3KQF/484=,tag:4GNyHw3SKE8XdF8WRByxZQ==,type:str]
  TURN_SERVER_USER: ENC[AES256_GCM,data:Xpqnn05pvQ==,iv:ujNAPHBTf1jvU9O5/QlRYuMRZbsG2lyvZJcPvynch5s=,tag:Qci+tkWa+PJ0ntv0HT1jqw==,type:str]
  TURN_SERVER_PASSWORD: ENC[AES256_GCM,data:tKvm65WoRaxCKs67LZWao5vcIf0=,iv:Ozvu9+4++j5ZXV3Gh807LMugAC/lpenAfF+9JeonE1A=,tag:G3AvE0fiMKPr5Xrc/LfMEg==,type:str]
  RELAY_PASSWORD: ENC[AES256_GCM,data:XqE/LQKi+DLSEsFkqlL3FRXg1Zo=,iv:8OjdfwuAKZAnSOl7gKfRrenkupefycBEWkrU7yWxyhA=,tag:VQZvMLMsnHraJ5089RcFwA==,type:str]
  DATASTORE_ENCRYPTION_KEY: ENC[AES256_GCM,data:tRyUff2L80HCjCcTMYeKWaj/x7rMnDx9k8RpFiqLLTuchLGrSH4lV+XUXUk=,iv:Ilsi7sYX3PUvnEW4CHOSOSLePLuP3wDB5ATapcr+quw=,tag:tjo3wnt3tu7jmf4zwTpZ/w==,type:str]
  IDP_AUDIENCE: ENC[AES256_GCM,data:5gKxde+eTA==,iv:k5q7B0dPGo6QWWuOLDoRYEkfQOVrXC6BkG00MlxberU=,tag:u0eqDkhpJ8w5ZUwUx96WpQ==,type:str]
  AUTH_AUDIENCE: ENC[AES256_GCM,data:rlOtGCmwiw==,iv:yyAVRhjowUWc+ISOPu2v76Pecl4Vthm6fuK58XauI3w=,tag:+hNw2i4fFqWDlkg1snAwQw==,type:str]
  IDP_CLIENT_ID: ENC[AES256_GCM,data:M9Taq9Rxyg==,iv:T0++JwsB0HcN0bpH4Jp/Ac15qcbKJYKlx4N5aFYqyQM=,tag:RewQ15q6ApueTs9dA8J1hA==,type:str]
  IDP_CLIENT_SECRET: ENC[AES256_GCM,data:wa5Wv2b6lxnasvYLhGdzSCoOTtLg,iv:MmGtCBfZx4S9YF6EEYPI/ZTErZ1g/ICarIOIMsHjejA=,tag:26jWJKNw4K7wBiEx/3M/Iw==,type:str]
  IDP_SERVICE_ACCOUNT_USER: ENC[AES256_GCM,data:HBoiVfZOww==,iv:U4Vj+5KIswu4gmpWelE3k1HVmZNwSIhICSpN0MdNcFo=,tag:QPH7NCBUEKJSY63KH5aDeQ==,type:str]
  IDP_SERVICE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:v0jW0jmAHKiIYA6/6DE4ZS/rPWzZ+cstEmKIMuhWYZWXuUZZ5+GKrGW7vPvsexRZGFGriAURP8ollQ==,iv:VcDIiEtUmu/T/9NpHJMAnCXkuRdKrr3t+hfQbEkL4a4=,tag:VPhPw9rX79cD892TUKyhdQ==,type:str]
  AUTH_CLIENT_ID: ENC[AES256_GCM,data:UWZJkF5aXw==,iv:aUO+msBO9tAWFk7P5jH3hUD45L8FJfgT1V2Vn6rKwIk=,tag:A7ult/VVmBjGmtkoAzBOIw==,type:str]
  AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:r15Xuw/KtgPc3eyvvTVHI8SM3YZh,iv:2FrceLrRBj0jaAGZrIeAKWRem8GBHMIc/L85Mr/G3t0=,tag:6p1lAqVOGFLxO21OSEEHFg==,type:str]
  NB_AUTH_SECRET: ENC[AES256_GCM,data:mwiunDv5kx00zFzK+Exl9DmVJrI=,iv:rRBAZRQ+Yrla2ou8XgQrqiqVtv63ptVwBJIYqp/CW7g=,tag:sit2gCI+PihSViKbPrwxyQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Eqf5uutYvg==,iv:0F2SAsEocoHuKfWWm6UGDVdT8f3WLe/6ulBlkMLMQmw=,tag:WF7d51O8ac3nJ+n6xazEGw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ytmAv3kXjSnhyzeIbEohOzF49pwS,iv:9LHBX4UN5OZaDSrkrpCDkNOCN97T5juBlR+MtTXNdns=,tag:xeR72S439gYS2T6l2KC6WA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:01iPw+LqOs9IgeStrSgdN3xLyPyj9SUEdHb0X67MYwulHkSlKA==,iv:BN2luvP98NH2TQmPVrkRJ5U0tvXXBPOhW8LJIu/J/NI=,tag:AP/04aj2du5TGgvVU0cUeQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FgsTCs+w1g==,iv:srHNedrOKfsZwnYJt7h9PycBV8zc32mwil0Xlp1dPWQ=,tag:6vj7QMhZ0d+EORwEOS47Jw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:N+L5YQyG0BYoED2zrHW6uQ==,iv:jPejbLb6QDF/X4taCOKFxuU9UaipXlP26o/40NjKZSs=,tag:JP9Jo7jh+LUgoRrj4VQxNg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac3RuWmRhS0c4amhQTktw
        NTQ4dng4Y29iTFlMMXJWcldMbE02b2xBcm1RCjRUcGwvNzhqQis4MGdXalhaT3JI
        Z3k5WU44bXZ3Z1V5L0hMM2Z3Q2NxOGsKLS0tIGxDY3A0NWdQUDVSTWNLMW4rTngx
        VVd4Y2tnZDVhN05ZblAvVDlrT1JVRUkKjfJSAz0s0HjoKWkab0p5mqZ27JInPhzc
        nabZEfHs8KIDVUfjXN+hG96gczfYFcfo9H/+RnkxPMvOvmh5SYNjsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T18:45:47Z"
  mac: ENC[AES256_GCM,data:R7hn1o6plFyh+mM26XYa3BdOhV2DimM3UrMdfmHWg3qxACXZAaPRkOBao3jOEq0bVhD77NA16Cs1wX0kwQrF+DCgfZH0dZ+DpuKVh1RXkD2MhC7JPAQ7yAhDVyDYHGgUrnAKb6bImAtqzL2Kc/qZJnzG9m4lvZ7Q78eqH2EhP1c=,iv:+o4yDkCE8YsgwJ2vBDFeuQ37eQGw7psMEuEu/itM1g4=,tag:1rMA7No+UQkdGK5kgBoBLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
