apiVersion: v1
kind: Secret
metadata:
  name: netbird-secret
  namespace: networking
stringData:
  NETBIRD_STORE_ENGINE_POSTGRES_DSN: ENC[AES256_GCM,data:iq0sn8fD9AsaN/hdY4itCtQ7PbYcSiMFtvJm5X9j2eEEAuLjKSqNS4xX+s/tJuBG1fSHfHRTk5G8t1d1nGgDYzJZzXaIWdEvKZfAEWRZ4pI+PjOzK6GWIHS+bcBZJLhhMvfgVEh/njNIOibf7dXoYVs2aP6XKMX8,iv:zQSNSbMh0sckLbLuRabBAH8cNXVPwDH4f+dxUp0yekc=,tag:r5nfd3r9jwsJ8EqJ0Qw3gQ==,type:str]
  STUN_SERVER: ENC[AES256_GCM,data:trutIuMZSeQVl2/85ajqPgSu+1pU+ekEGCmaok3gLXphDV2NJB1U/A==,iv:vPkhdXcdxtwL7xzIzxzfCZnkhpW9KUoIdb1XCXiFAI0=,tag:WbEXf+5xQJ6Ppgeg1kVsmQ==,type:str]
  TURN_SERVER: ENC[AES256_GCM,data:A4KM7nBCdPg99C9c8zNFo4KIWy8NHG3d3KRi2RRjTjvCVrh33wyONQ==,iv:URpNLc7qqKRZ3/3+i1nd01h2NRbxFbSfAOzAYnJlAek=,tag:Wwwh8us1evV5imjmq3Nv6w==,type:str]
  TURN_SERVER_USER: ENC[AES256_GCM,data:zv7OYZjUFg==,iv:2Nl5U5ET8ZAvhPsGIL604HdAwPE+192aUc8SbWTn6b8=,tag:ogTYLZGEvTRQt4XeusvpjQ==,type:str]
  TURN_SERVER_PASSWORD: ENC[AES256_GCM,data:y7//jAzQwvWNAEsEqRerSDhQFx8=,iv:SXMS54Pe3ztJPlKfIFRswlI5EXwS+Nuw+BqAdsxqXn0=,tag:0l01yH0w8XEtf7aaHZEXxQ==,type:str]
  RELAY_PASSWORD: ENC[AES256_GCM,data:t4naP9j/BwxG1oU2JnP6SL9wVBE=,iv:97jywvMrK2oPZTKCj31YnuZWi/cEAUkMJCLL+HuYo4U=,tag:N/uJE+VhsJawG+9gAI1HWw==,type:str]
  DATASTORE_ENCRYPTION_KEY: ENC[AES256_GCM,data:vn15sdM7oQQ1c+XPubTdNK2kQqir+Oy2i9ahBRtFL6hj8PTOKICBaDOOIZo=,iv:9T4JDca9uuqdlWMhsr1HQk6SzQpndl6RQqZvSqaqt8Y=,tag:QkxadtwP98ILHHFU/LFQ8Q==,type:str]
  IDP_AUDIENCE: ENC[AES256_GCM,data:A6mORD22hA==,iv:X2/LPQUI5LeC3PQw2Q3lqhyKw2/R5UygxInRPA7DsJs=,tag:SDDdxkpc10UKqspAuVzBvQ==,type:str]
  AUTH_AUDIENCE: ENC[AES256_GCM,data:YcaQbgLyDg==,iv:4FysfxamYQ/i8h6mVT6wKxQJacIs5d0Kd5f5Yh+6urI=,tag:YVVUxUNu5UbCZUfbU5AgJQ==,type:str]
  IDP_CLIENT_ID: ENC[AES256_GCM,data:OOCNQd9bEg==,iv:+AObq3G+uJAnPuS/0DxE5DtAuM5o3TKCQrbf5eaGUoc=,tag:V8IXWI+Gq9iHwTcq5VArow==,type:str]
  IDP_CLIENT_SECRET: ENC[AES256_GCM,data:DN68bXvWSm/N8UxQnBLQN/P2y1kI,iv:59hNTNpNWnhaMvYqQvKidp8jGvCIXaaylsJSb8cF9/M=,tag:V3p7GmesV4iXuT4IhaZ0/w==,type:str]
  IDP_SERVICE_ACCOUNT_USER: ENC[AES256_GCM,data:1yDTmmHDKA==,iv:Ga0VzjX/W4TJD2agWEpjyPYCza5kilh00RBRy7a3A9E=,tag:heUJSiqKvxGOAXn0WD+SRA==,type:str]
  IDP_SERVICE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:DYKJwBUN5GE8sTVncffYC3Vzwdv6r+3vo9koN3/ZR+0X8RAn/Umm6/zhKfJ3+s7gzroNNDm2PMOOlw==,iv:CW7bUbinhx7JTglBuK4Jn9z3NEq/piBSgeOpZONJERg=,tag:HFKA8iO7ShXf+I3CG0PWag==,type:str]
  AUTH_CLIENT_ID: ENC[AES256_GCM,data:p2Dn7mN40A==,iv:t5hsk0LDQjA1hpGAsjtcgP1s51L1G57EaH0F43R2HYw=,tag:X/6RbwbpN1T7Fh+gFLrT+A==,type:str]
  AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:A0sQWjdNi2KreKbOP61h3K5dE2te,iv:H9XsX7mg2ohyUrq+Nl4TiaVIJFd1LnIhysZNELIJrZU=,tag:/Gc8PEjh1FwGv6057wMagA==,type:str]
  NB_AUTH_SECRET: ENC[AES256_GCM,data:Ng+C8yMGg2gvZ6qyIa+zBpCeh8I=,iv:dupmB/o10QU1NwjYkiustK6UVVftHdMYwhVvX68ipZk=,tag:QKXj0dX4RZ1Z9Z57bGpmVQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:JrTXg7tS1A==,iv:BYhmmeVFFy19FvhS4NETDhiUMpX8zwQY46TAY6NP9Ts=,tag:8czPjOBsXMwebscus+hFew==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LvOo6sAbmQW71BWIZTAkEXncn3fu,iv:RrrDHKYjKS8/MMzOMl2BtZtjVCWbhui+m44BGZP2S9k=,tag:EYLKkfjFEow35vD4YhZasw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3aVKdJRWf6i9Ao6Jp9rvBorq/YPsQhS+w3JypHXKEczGPy8MkQ==,iv:+XZ012ZOzUjPtvWOW8q39A4LNQfL8dHa9GX09U5me9A=,tag:QaEP0A5nyB8ZO+fRlhAgoA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9tBzINv7oQ==,iv:AIulVbFl29kqSvNAjrb4pthhiqbtcexEJa8gQAnqwZs=,tag:W57ZzyoTuLD1DnjPq+OliA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:HXpHnUqLYStGnoU9z2ZU0w==,iv:GkV7yM3nPQ6wIshC3G/wxaGxisLjlhu3Rr8OU9Zl+SI=,tag:Y1o0DxOVh2+D/1q6FV/WZA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb1QySkV3aGVHMmFIakhU
        VEhRa3V1RkYrTDRvM1lKSERDZGhkdjJLNEdJCjRhVHpFNmp2bStkK2UwUExCQlU2
        ZzlVdEVTUnkxRUJUOXhTTm4wMnZlcVkKLS0tIHdiVTBHYTFiQStSUHRSbG1RYWRi
        dFptQk1EOG8zSldWbkNDai9FemRGTTQKAPLHsBClCK8IBGj9cHAZMMpyT7mvUeZO
        YY6Gmg0eBgit26Edvl04L0TYok6YrzusLnMFIcujezsBrOyS1vz3Fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T19:33:52Z"
  mac: ENC[AES256_GCM,data:zg3opGPEr+NZ3ARytF7/EuDFkaC5qqZU89W8hGRhAKIx31Nrm7YAz3tUKue/PwiLCpKlz9hoVNkQVEsn8IDMZa+eFmxIyGDKBxX8hnLIpUlSPwaspLYrY8dWznLSKclGco1MqCkw/xi59XmeXGNQpA6l7/PhLkd23Cr1ivQAxBk=,iv:1/M4WqKeWNGSTj+IUtbAP7OK5oNozOQLNj4TSAO7XqI=,tag:uU7ky5K4ovI3ihPYewW63g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
