# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-ha-mcp-secrets
  namespace: ai
stringData:
  HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:+qYgJxWErs+HqxjhXEKEymTgt48Oj53J5WHQX63jQelfmOAH0kkwC8gMbJCs/LI+UiWhvNMxHtmYxsYZKEx33vjuqKl7YqECKfIDI68xNBK3Pft1x3Y2HT85p0Nx1j+4GuTD0uyFeOqd14Yt2s5HMUMSUkAsQ/vnKbjPJUffFQHPNQmZ2X8FEz+Q08lP5lDs32JbMPhFKMx18BJwga4jUvSZ5TB7ILcfLM9BrnOTJ8huyRpBJ/M/,iv:AoxaBu5F4u/NGEsOdBq1FJBNN+Z88cu35KiHugKh8ok=,tag:ZHK5dLUslSsffcbba+Zv+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4M1VXeUlsTWE4OHp5eGRR
        SWZlUjhpVnNCM3huQWVyeU1DTjBWUFNpU3pVCklUTVBVSU1vWDRsc1EvaUNicHRh
        VFZVRVBqb201cjNRRndLZVl2eE9TUU0KLS0tIDNFWkhlS0dyU1NlakRJczlwQ2R0
        bFVLSUVkNGw4VHpOblMybGJHSzJBNHMKjcOB5mLHuCJ05ABs3iA02s3OrZw356iH
        UL/6mhDMVGdO0OfViTf0wkqsEbDM9tgSVU5PSYsUyteTBHiTxn6mzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T23:16:42Z"
  mac: ENC[AES256_GCM,data:oalu3QZ7jtuP8szijOvyaTjQ6G4MdMRInUHuV0W8Cfp6hCVPVvx0GimTIkaENqYVjP6eul30znwzZeM/SWHgJM2xn9In4PXZzg2HppF6fUVfGuQ2z/JtvyK1o9gw33bIiJtfHOE87Zw6KB/AJeSUdXpm2mmEkJTzDjOtZmQzcW8=,iv:3O6KGQ7/Nq0xEOiHmsA3BeG9kHBRQvdlCQGSc6pfxmU=,tag:BmGYHuCkYxZsfGQHUw8Vng==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
