# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-ha-mcp-secrets
  namespace: ai
stringData:
  HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:sdoxS5yj7HpfcleN6PbutWI/avYm7JyO75Gofz+U2zz+TwuCfxxHHX5TgA92caFhrLkDKLZ29mvH4b5ogqXBY5K672iMhdy5svU+wUh0+ohb/kFPe+Lh0YtglDx5sePqoDbafLLTRZTnybLYn/GVrpuVCLNuJEMeOchOZbIiMCjxrSox0awXIPiJNs3HhShBW3Q5ggwx+fOCO3ccOePzglgMIbX7ixx53sOm2hhmcLam8D/KNfsK,iv:KwfhTd3xAQUOe9IVlL0iy6CQojSYImB0upTS5zNpIRI=,tag:66CZpVs5xKudVKSP4gH2kQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYlF2ZytoTnJlaHJJK2lx
        Ny84cG1RdTZrc0xiT1V4dnFQWUV0RlVQR1JzCnB1Sm8rNGJRTWRmSERqMytKb1dp
        cWdFOUhUNUNPeWlFVFhCUDVabGE4WEkKLS0tIFdoUVJKbXFYSlNtZUFSbmh5T09O
        UUdBYkFpZzBGdzExUnB1MWFMazVnelEKKpWLwVrBz22aTWbA5qIqQBNr/dRrAaiu
        227JBntS/Yr8b1UJ4IXGrN0QIVGQnBNiHsBaMEmwfQZrrkXeKxUIqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:18Z"
  mac: ENC[AES256_GCM,data:BdTO6/4EKqLDtiMABEeb69xXDC2GxI+UyULphk4nalA2ch1AsFmIaKEZhASJOCZcjTB2bTA5D37Wa392FkGtOCQtFZsIX6KaAb0xVchNbieU0JckoQYvInMMzjj2gaVhJKlOABQDr8K1LQz+GQXYLFZpS0mDf4GsntshCv6Csds=,iv:wGQilDkcWPbJQtKDJnzwnhDIZhfRCJqlQsKZkkdAcQg=,tag:+Zu0j4RpL26Hq9H7FnxZsQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
