# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authelia-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:6UMfI1b6CBA=,iv:cQAK3zOpF1Diq+8LnKOZf224/6qWHFCU0HnVleEEWAc=,tag:vVRUeIOnLD3AouYx60Hbqg==,type:str]
  password: ENC[AES256_GCM,data:xcR6lHWbcC2QHoT5qc+nYU2ZiiZv8hHv,iv:gvX+3VJtmePkhgATZXSwlE8+ffqwmB/XqAgJpfq2jh4=,tag:8No9aQcxBQwtU0umVpze9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TTlnZkJOMmQzdzk3U0k2
        eUtITlM3SFVlcy9XL0hGenJ1U240Y3RtK1EwCnJxUHFMdFRLWGhsTUlRbWJxcXFr
        UjhyVmxZT2ZLK2ZFd0t0Q2RDQW1RS2sKLS0tIFF1alRVNkFsMnNQYXBkWDlaZ0hW
        bzNndlN2QnRpejdLbVBjYjdQNlhDR1UKJpf7HOPkGJWtWCBVP+6F9AX0NWRDxEWJ
        HIKgVLJS7MNyXzdk9oOJ0Xt2OG6UHoL7ek0XITTBu/6tDDHlxnojgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:GU8205nTvKgpXgCfJaeAe5NYIVdAEHyijFGwXsyc4tiVI9mMS41KsbVnrASe/0WYIJm/dJ7hiNSBkeLh2MwJKHkHEKGgScRQvlGTkBcbPY5QKTe1t1TBgTeDVtvYqg3xCOZR97Z0lJXUsb73B6ezLvFtI70S+1zUcq6OcE2KSZM=,iv:vgtug5FFWNYmHsb/d7BzW5LbCsdY9PppfGpM5LfzUao=,tag:VX89HMI5G+O5sgHqgGOVtg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
