# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authelia-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:PvCienVdnp8=,iv:x+fP8r40fkqqsQvXhKXmVYiOuXlmzBOWP2kozAjsCyA=,tag:UlzFTajxH6XEeFkyFB/mvg==,type:str]
  password: ENC[AES256_GCM,data:/Rf0k1+DHqnSYhYS5vyrmtCKOo1eNdWl,iv:SF1rvBgRHSgRpe+EHv4Ce1/IgiOLT9k7OcrGXhg9JoE=,tag:ya/EBUs0cr93MDcjryY4qA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOG1vNjdVZmNSUEV0QnB1
        YU5jekJEOGxNVy9uWHB0R2VyZ0xHRURidFE4CkZqYjJMMEhETitJQWkyOXBUZkZ1
        TkNxcUF0M3hDOFo2WXdsdmZFK2paZzAKLS0tIGxoK3IxVGZHNHFPajdXbmdSbVo5
        TEd3cURFU240QW9yMjcxQWxqTXpkd2cKCjx7frAGj3hLsni5EULu+Rj/bmOSuCD0
        13BYZF0LaTDOROREQoYjEaTEH9MzHJKHtnTNUXIiyKyVN62G7QLbVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T01:24:57Z"
  mac: ENC[AES256_GCM,data:jCl5DkLBa47bmtouIYH9zYwSrmlhfYkX3C09FieLcC/K6QyT4KaXc+p67Jr3gMrJxn6hVXYfALzcRd+DhmFqmrM0hYDKH3XMN438q712oYOZOU27xaRNUxbBImuWG/Gt0Py0xRZgy5hKQBwCSvPlMduyZuUY0ybkKmmssI7C/3w=,iv:TUMFO/uEnr7dwfmoqpH+EOmOiv69+SV6PQvh6zirXbo=,tag:T8zbnZSj6THH3U0H49dz8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
