# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: autobrr-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:N055tuGuLg==,iv:Ttz5bdQClvkZza7KnrxLWj/+JW0T76fiYbZDgvJVoG0=,tag:qxLfc1ISWcUtgSAMTouFbA==,type:str]
  password: ENC[AES256_GCM,data:sP+xbLwfFVdRJg/3WQjD3UYWQt9n,iv:WkQ1BjPcHC6mzbgqhEAjaWjrKm8bvjp0m4/DWXEI32M=,tag:D1iWdaiYFRndqhlu5Mcshw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT1NTWTlZdm1WVUcyZ2Jl
        cGVENDhZR2RidWp6TXVOVnZvbFNXWHp6blFrClpRN0tzemY5RzRsWjBNbXoycjJE
        WFRPa3lSbmhOeFU2cHdmZUxXWFRHclEKLS0tIEwvcWlJYnJ4c0h6NWRsc1htZHFI
        RXFISlVHTlFEdDBlQ3FrYmRrOGZwdWcKy20QC45tJOShr1SWch9X746Hh8DCStah
        yEz1Mq0+tRUQWwH+QQnmvL+YH7tu0Ca6SDOST2esXY/eKzJcnKh10w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:GzWjhrTYtkC/jMB4PER0jNXJ44HOT6Aehgu4JWhwHJAiBQz+PolCz2VxkU/K8esb8CRJkIC2/98bpGnX6NyW0H8LtSl7VJJ311PsjyKL2A3fPdSfF9XvLz+Lt/ulL1a8wEMsPHM1oSXwehu9WFx7QFueMSvPhkYb7DYLcQwovlQ=,iv:XkB+8mkbjsH4I3tD/CAEk7xrcBnaRG1LvHUwCFBLXdU=,tag:yRXIYIrcCxSU82mv0vcozg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
