# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:L/14N6nV6g==,iv:LKRwfY5hD0kI0RzOVDXERwo41LUXv3y0s0PSAYH2VvQ=,tag:y9d8I7Oqp+votmIzSnz64w==,type:str]
  password: ENC[AES256_GCM,data:8h+daTYx4FBLNpzKuDgQhQrLgQO2XkoIQhuo3ilfwPTq6jtEioqSDBSfUTzZ2GYK,iv:f9/CIKiue6NjZtEBVPqcU3LWqMpm6Vir+p2cqOrNMZk=,tag:ifPGT8JadHsEMVsuQn+ntg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZHppaE1zQ0pDd1ZzSFRO
        NkFmRFdhZE1seEg1bFU4ODErZ1Y0NGhpVUQwClN5bzFadW5JQ0NFRXVMR3FVNzBy
        MmpCb0lVajc1YTQwdTZrckVIUE92NmsKLS0tIHBFWFNxeWZRcTZiUjNhYnYvRm1s
        d1ozdFU3R05DY21YRGtuVndpbXBqdncKxUVT6BHZoBndmOwtGb3oMqTDE6lozDHH
        h3RcfJj9ioJodyOk9WBLJm6Vit8henTJcgAe0gHX6tVOLCBMx27Haw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:8kUB/K10DFUXjemtU2VmcGCikUbadflpzZnkq8YWsAXQV3W9mrMl+Vp6GNeUhdDLMn+ehW71OiFCbTlqwL7SdI4ZERSSTGvNXEDVnm3aoTMlujKphwUR0zFsbUdgLtyyvwgqq1hmlxxQPlP2RZCyXGKYS28X6BM6ayib5L1crMM=,iv:9rkQnymoDu01bcN/065zFtyMnNaO2zhgOeLcqiUrJhM=,tag:bG2++Cb0mKS7t967YKdjkw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
