# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:oDzZAF6F,iv:N83nC4gVWDPC8gbykDGDcZMMy2G3Y1RkdY8bNWiRSFY=,tag:3VrGZPERafbvRY66r0r1qw==,type:str]
  password: ENC[AES256_GCM,data:8j/9Y2vqH+yZWzqhEMboaAsv6MIMORq6iJoPoxZtzH4=,iv:wX1vR+mIiIGeTk8eas1yARZ+roIK4TZVpSbHitlI/sg=,tag:1cP7XWyEznemMF/WeXutkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cGV3QVBjdWVXNG8yMm83
        MUhMZ0YrRVhhTEpjNnRyTk50Nnd6d3REdUQ0CmxkdFVPc2dJK2JUNGF2aUZ4ZWI5
        dFhSY2J2bEtFWGJ2OVFKZVZtOS8wNVUKLS0tIDE3UWM3MVpIRFVwdE1lcGFkM2h0
        dDM2amtESkNVVzBkRUlzY1JnbjN0ZkkKH+4pybSrC0zpJHpQ76wMgBGqVaThNALG
        jqbZq6xhba7TBWJcqBo2YBTQQLh8l4SlSp8rOxoP9fnfYTBggRBFGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:Jre0YvCjsLPVCxRx++mATGYpEMXvi4NsISrPDlrHHv4gVJnqXwChbRNUKQA0tNxfXk5uOtrdtFE5dbKSXat2KaiVPnB31QEueTrGv9SB+4pRSMIdd631BuXvs2QeABCeIy+JDY87LCLXxZs0mwhGbKSMzSrA54kzblMys5rzBFE=,iv:cMdJNApHJoa6n09qZmdFktj8Pp1vC34qPI3o7ldUVWo=,tag:NomDAh9FA/pVV9TGe+qJeQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
