# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: lldap-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:HUNQ8/Y=,iv:hol3MhsQpdSxrMQNWI47vUmUxF9wKvVFhcb0/CTMpFk=,tag:xdtLSvxWg6LJRpFClfqMRQ==,type:str]
  password: ENC[AES256_GCM,data:PaExQTALaE1jlzpvW5glymXrclRzCenC,iv:k+xlM7ujJjEaTQVR70kPiFYHU+9S0IrGLscR9xey5sM=,tag:DvrFJL9zh+CKdUq2+SfsDw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK1AxaGUzazdVTjRVNGVW
        ZnVhN29SMUMxVVUzcWVibmxlUEpPSHZqYkZ3CnpLZ1FMYytUVXVseERqSnl0UjVR
        bnNwV3RsZGJkMmtnU2NCQ3hVblpMeVkKLS0tIFo0Z281dDgzb0VrajZZbjJFTm1t
        d05YVFRzVlNrd1MzemdrWUtQVEU0OGcKnAfomiF7gDH85JalaO3Bfl/EMcam0Yz0
        yElAw9gZOSvDrqalwMuJBNHDzY01LA3P/6a8+sELVcx4scWIDFd5Sg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:iICWTu8GVaPrHeQaQ0le20KUi5V8jhGmwKlwzxUSDsIlwjJVi9OCTZ1KuadKLActLcmJVhIPdt8YcD3PgSPM/aCTx2lRh76YLgZOG4w8PvdH9+jqPncbo+IFUFTxHMj2I9WjCEwmZRCFzugO7lYSefkWebg5Dt8/LCYNua3bNqw=,iv:bMu68b8DCBrURfCKfiw5Q8xKjxeyQu0lA8bJTjyJ6mk=,tag:oM9d4paLw7/iGHApGdlGIg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
