# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mealie-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:u6og5//v,iv:Q1xaIwFVVSwgFrf1k2qDcFP8rii/ao6J+kE1PTI/Q/Q=,tag:FfThXZd2/yyHq9llOOvpHg==,type:str]
  password: ENC[AES256_GCM,data:MazB1SYj/7OtMUTeAbqPfbjpCac=,iv:849Mq/BC0nyhPMWkxHjAsBukRV7TJncq3IKW1Mq8Uys=,tag:6ryuD86O/93Hxzh69y4lfg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeGhoZVdGeHZFc3pZcmI4
        ajhXeWlYV2g5em1vbG1DeDNHN1hranpPTUgwCkdxaTloM3pmeTZzd01jNVpmOEJv
        cS9uMDNFNXlWRWI4ZndGYlF4Wlh3M3cKLS0tIFdtYldwZDA0aHkvaU1rTGxnTVFt
        V0t1STBTNHZ2NytMdzhUbHBYTnZ0aEUKpkbinT6UVR4HShaFwxoXVcoNrkmDjO2O
        7uSpjFPOk0sjL5VVexXw/+nzvL2fTwxY4T0pJYWRSJbWGTacD1dpZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:tu98LiGtfGHTlW6nP9CJKa0FOCORmu4eEZNDGFzA0juLIQhcHGV5fKAy1WyySkg76XVvfrvhtgsQxEGzWfF6Fhnxd5TGi8Sz6ktztmsFqedWD2YMIRG3hdCROk4FeUawRmTMEcgwFmLooqKOqcy2YMp7xLF6eX1fmsWLf20cOOM=,iv:zhQ4iWaV3tiAOLEyMjheFI6tkn7VPF8IxuY5AG17o8A=,tag:6zZHz5HRj0hIskWZdOA3tw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
