# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:kRPZ,iv:6kRNlLSN7AeSsNC6JlX1Uiwp8gz60Yc5LWn8pwpE3xo=,tag:9nxgj92Q7SLNdS23qp1B+Q==,type:str]
  password: ENC[AES256_GCM,data:Z1APBlfo9vO1pmFeFY3R0QCNUcp0KgQd2Tk=,iv:PeOjZmUj/ySsz6Yp6tKdJhebX0YgdVf6W+tMbpuMxjY=,tag:UQpbVsrfcNabCLq+F+iZWQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK2hQaVVJYVJoQnE0NWx0
        L0RlVFRubkdiQlVsWDNJdWRLSUR5QTgyM2dZClYvem5DWEZVUHd5b3JuMWFLQjVP
        TGptdDFFSDBMbllmQmpzRE4rR0lockUKLS0tIDU4LzE2clhCOGNGVFAzb3RJeW5H
        VU9PVmVYZjN4RmUzckQvYXkxN2p0MVUKnJxQNH6p66x4UIVfRExBijBFCctCDQbZ
        wnjlHiDivZmpmYyw+COwhDoALgWW8VNv7yXStnaRMHOPeQG5nR6CGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:QD+HQtBxQ0WP3MvS+lz6SAzTk77aVNEYhGDaf7Gks/Eb6VWpEqobeJ4i7kR0+alJQDYEZ4hIzPbIJIK3CGDTEq3fdmbbXw0xwX8fCG8J+qclF5ZkhS4xSbkPxeQPlErq4bVAfcwYdzY1ugy3HiBzn4MLQyXZh1y8NJn1jf4Dcsc=,iv:jolXz6umhxb7wPDqQOrFFa8IIIHbtRlaTix6o2CroeA=,tag:PF1G7n2Lw9kr56OOIgNOkg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
