# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: paperless-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:454DjZU9dcNZ,iv:Y7FWJ4Un120jtMZAQO3RHPps1XZn9xF5RJ/6//V9bRk=,tag:4dpgAMvFMfb4M/bbxGV6sw==,type:str]
  password: ENC[AES256_GCM,data:H93CMv6FYagPugd/wWg=,iv:sw9AOO+egATfxgG7Jgj8v+pIoUVSkpLrn81v/Zd0c2Q=,tag:Kzx0lMdM8am/sXtsVp+Kbg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbDduRHFCb0dMczFJbmpv
        Z2ZQSHAxUHZqL3FZOEdIeTdhSzFIa1RxZ1FzCk5qbEQrbjM5eGozL2JXTmYvdXJK
        ZWFjSWhkcC96Yk90S29aTlJvUUZvNHcKLS0tIDZJTFlpcEVjYmdqN2dWMzYreTF1
        ZzJwOE5USHBQL1RqSDY5ZnhJQTNiREUKFTOLzUhF8tf0D/g9r3wkET402hooWTuX
        +su04NqDNlYGsvebaiPxGqGTh7C76kepRhboZYjGC8kqEHLcbOpP/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:E1pg58yaqwCEYL+tWc09VhzObFGY6AyYEwI8MB+3lc9D1gLLufqN32xmf+Ls7vq/djIgISwdvkYzDLplMfB+XwN8KBlnj8HJ9pErrqxoSjnqoPqMeXx9S+qcOTIq8NzUAv3eObGLDw28Ux5BEEnHPQnfzPstB6RLCnJCJhWSj2Y=,iv:k65wzRgY++Y1NfTBrfXJiKhaHeuFTIQHO+SsHMRti+w=,tag:ghV4RO2E8eYQ4I6cLxMvCg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
