# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: radarr-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:o35eHjda,iv:9UE5HsszbuRxBfKtMHQjOEv34xt2651gIqvl1RhLVCI=,tag:MEqDdT4eT03C9AK3sIeXew==,type:str]
  password: ENC[AES256_GCM,data:6oka9N6gKs1nxJ3a6bMhIBIJ2fo+5Q==,iv:sU0K5n5dTkJCOZKEB4eMEXn49FmEmkLlnHcdfSPvKzw=,tag:Cu2smen+xtiHZg5g/b8CHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVXErUFl6bGVNTGFOR2Fp
        M1RLUGQ2RkpTRVZwejFBcDlwVzExUkJ5aFFFClk4NnBFOG5GdFFjb1JRMnliVWhy
        WHQ1S255R0szY0JUL29tN0kyWWxEMVkKLS0tIGhMR3hCa0lObWpxNTZudVMzU0xT
        cTQyNGx3a3k4anNxRVlPMis1czJCcW8KcgTfJjncTQJ1peKQQIRMjjI/JcJ3TelR
        4J1kzUBZiXDaF3kGlXo03+W+vGY0tggU/EtmaCzLDKYi3THiHs18qQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:ojtBVe1AXR1UAGrIGB8cIxw1Ft/S7ZtSM0IxrFOu1uSUMJfHxP9wXTXSuRGvEfbBQIc55DRXdK3l51r3ST6COZatMhT4JtGlonye5P6dRpk3qLgxkCInU5ZVxtWP0oCi0f/OBAJfrak20kS4QlFsreIt6JkCPES2lPVXPWxoGqg=,iv:vEsRdIT+DWOgc92ktytMH2+j+S/BpYt73aReh9bRrrI=,tag:+IbIY4pKgx773EYcAoodvw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
