---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: radarr
spec:
  cluster:
    name: postgres18
  name: radarr
  login: true
  inherit: true
  superuser: false
  createdb: false
  createrole: false
  replication: false
  bypassrls: false
  connectionLimit: -1
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: radarr-db
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr
spec:
  cluster:
    name: postgres18
  name: radarr
  owner: radarr
  databaseReclaimPolicy: retain
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-log
spec:
  cluster:
    name: postgres18
  name: radarr-log
  owner: radarr
  databaseReclaimPolicy: retain
