# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:fXWQ2Udp,iv:unAgi/D175ZR7MmGySgjun+uzuWG83BdWIu6Go8aClo=,tag:wRplNLvBubJbYiFDaBjrdg==,type:str]
  password: ENC[AES256_GCM,data:FSWroqx+qRF7OsQu5HA/4on5nRQ7KA==,iv:WQy0UWkAZDK3pTXu6zzCEdFpzMSthItH9YnDp2DZJtY=,tag:XD6aBl7/N3TltsCdNGpkjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreWNrTXRQM043cmx1cEQv
        TmtCQ3I4YUFkaTV1SUw5cWlVYVoyUmdWVnhjCndET3hQUDZ1a0JFYU5rMkdoYmh4
        R3A3R3VVMUd3M3Q2aGUydk50REdYRUUKLS0tIDFDaFpWaW96SEJRSHdlK1M0Vm9D
        aHZUR1N4a3lBeFRON0hmWW1GSHNrcjgKNXq4H8aeZVcwSl4DyUN+K/hW/x4QEGgf
        k+bdQ6ogRl2cFIG7aFKk2QyKyBWZ+9eOh82ZI+Vzx2zLSRLmiHexGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T01:24:57Z"
  mac: ENC[AES256_GCM,data:bh6fJhx+HtOA8Fe3Bkq0aiVXPDIGeqBqvx5d2A+N+RibG1XDFU5NVrePN1/wYxKPYCkWl+GY8qJmMNtusuxKf7phCeMgp9oWwouqHVsQ06oP2wRXA0GmiBs3I7qBzurxLMtkcLyvOsEvQ01mLFRWK3B1ZH5tAf9FO0SubzfJVi0=,iv:nxT46hlQtSc8jc92xT9CULPhjpuaRGLSKNNeRKJV8Ws=,tag:bYHbGGmC/nKuMNuu+dvfRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
