# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:tUhGsFtI,iv:7rRb78HcSAefJ+QJnCWUUW+/mz0GC6T0lxdFQaKlwO8=,tag:50NUmKH+5UdqXLSXfOzSVA==,type:str]
  password: ENC[AES256_GCM,data:U1R14gotfJEJ8uJxr8gq1Eh7LZqbGQ==,iv:sYyfmuiFHtmH1GzQpyt0ic6Ozq2BwrCYSF7O+UFgUCQ=,tag:6TnTAHoES1nhGO9KsvQvxA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOVRxdVpzbXJXUi9UalVM
        T1JjdE12a3NkTDJIWWQ5c3lLc09HSFcrS3hjCmlrNzhmQS9XcVQzbVhSNlI3Y1Zu
        Q1BKUUY1OEJ4KzJoZzE3eGY1L2hSSUEKLS0tIGNteG0xQVU1dDY4aTFRdTMzSUIw
        cGNNeEJkTzRLUEFNREFJdFhuNUpXU2cKii7Ifc9ySB4Jvizj77a8FtCvvkv0ZtS5
        mloDdBdX4eZxBDxlY8+IP9zLxOhTN8PU5+uanRgOVrEkv8MK2eAakA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:AGX24j/fVgaa/aTMgeylXPZVSgppFqZXSAoYA59FgKHkyvkSdCVhGrAYzGjLG8fh3hzYZ2CFGKYqUUPL5G1vJdMicEf8YD/dA72JYHGB9Fq3QKycuBXGavEeNx4+ZTyL26fT2o+utCXdyU7LlyVh6eAbva+GVMPkz+6z0J+zYyo=,iv:HOCWHHXO/lziIGoivJWVGrfdpUn+pPDz1X5+r+/cgyU=,tag:OimCmnkXfX4rJkReNEpVrw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
