# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: translator-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:fwefdq/lJVORQA==,iv:6hoWMKO4kDozWeMLsP/CM8RafmYRizLESyqQbggkF5Y=,tag:+HwLZqQ10nBy4h+VLHn18g==,type:str]
  password: ENC[AES256_GCM,data:4WQMBN/wYFlrJo8aTDd0AOGc71RZGjC4kBEdAij0UA/n0EjuJsyyTpBWlit4TPgW,iv:8/tzCnQUdVJ4vC4z4IqojJEQXM2BQ24zWVCmT+gmj0E=,tag:Gzt9cqFnayZXOt4qJrUviQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWhIanQ5V2Q3eHgvWC9u
        cW5TM0FiMkVMbDRpdU9YSTlUQzl6aGM3RGxvCksyRTNxUDdVYm5VanlWYWNjaUtu
        S2RJZFhudGNoNnFJQ3FSVjgyV0dUYk0KLS0tICtyeGpmOFlIeWY3akFNQUN4T0FF
        UFRRRVluMS9vYjZpRDFXQVhDQ2IyekEKBYM5zrl1YH8CSMnIcP6cFQRdrYC4L30g
        UVZiFtH+y3Zmkt2hSSqwfvcIa99sPkbhYhxoVOUjSp/gh1ZtoZ4eLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:od2a2f7OPjwpPCMdxKEwKKHQvRfecjyiW3lZSA7QW7UC0gEzXdyIWdvo2AbLrvgwwTlrjynSN9mHy2M94/i976e2c9945VfPaaMgggMld7CpwYJu608JK8Fm3TuUIHZYG76NyuFAv4y51jNinvLmnwgXEKoQCMNi6mIwTj2iOsA=,iv:Pb85YYGh9TOW9F/Zbsay3LTD/NVDkXxq4Dt90xcYUb4=,tag:v5KoxPTqxVDZYzVLBMQfgA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
