# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:4yEhpg4S+GaqhZ0=,iv:hma+mL9Z68qwj0Ob96B2c/aDsN/u4lShV4hYC2btT1E=,tag:lbev73upYJ1SXdVE5j140w==,type:str]
  password: ENC[AES256_GCM,data:RKpmIWWfoV3vzUT1ZoutDH5d3VCF6CgI/g==,iv:2fRX58Q4yk0pBophrBF7Kpz8/4LWaSHCBSnLFaSv6KE=,tag:9ZZw1QI0ftvtaXhS97s5qg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OEhFdTVsSWNLWlJ6UFk1
        T0pJZG9iRnVuTE1xYXQwa0QvR2tUenVqMVZzCldsUUp3VnpabDltdHlOQUE1ZFhy
        NG8vSTZrVldVSm0wbHhkdks3eVBCMDAKLS0tIGJCR0hjL2lWbWVJYTFBYnFhZnkv
        VVd0SGwvTVZIYm9nM3IyRjZnd24xMjgKizZsMdn/INxIA2ofLFnoZmqs4nJPWIYI
        pfTVTo9Cu5fXWZjHoQtD8w60UwQZWH6Q819zJOHqxTVQNEJPSGcM7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:lbOpNkmWQpkwty0ayGsv2RmiheiCOz/sHBRFe0usLrHYUtSzTcEWQUjdDf4RkjaOQNRnXPqEf82+sCcLLVTOIPZMzs1x5KQkAHchz+pxPz+WHgsP4pVNW1KFVzDSqYNT5FJwHy0Lgp/RtK0lO2AxTt5+rXcklo43synkBNlYVuk=,iv:He5gQDUqnO5aU04rObUocXxrqQ/Y8oIFyPYiLFYqhxs=,tag:+R37JdDPjLJx13MurSDEeQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
