CREATE DATABASE IF NOT EXISTS ${LETIBEAFRICA_DB_NAME};
CREATE USER IF NOT EXISTS '${LETIBEAFRICA_USER}'@'%' IDENTIFIED BY '${LETIBEAFRICA_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${LETIBEAFRICA_DB_NAME}.* TO '${LETIBEAFRICA_USER}'@'%';
FLUSH PRIVILEGES;