apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent
  namespace: media
stringData:
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:Keuw2aPiVFnxncYaKWaS,iv:A2a+jqo+V5f5hfX9gVEvzl0637F1IxrilWUNc4REDpw=,tag:WzGFKYvRvAqaGq7YtrWNGw==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:6Vxmrt8vMQYn5lwNbHF6Q1xjv53Glf7/ecXrJp15+vH41RwAo3xTnM/TX78=,iv:voA3Xe6w9R6lHyCZg1clo8jhsV84fqw/1aCAzenJLrQ=,tag:q5vApym1jHdLzXPwSqt6WA==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:/avMDzKzf0DnDJ0ItP7MWpkgWY0itOhM3TzAMCmVu9FvuyR+woU4Ebd4o/4=,iv:iQxAcSih5x/8YqtKlKycBsx9OSKhfaOhyTpV7gDyXIs=,tag:ZyLFwdQJnyk8GOVLtE+08g==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:5+vYhssKmj95MQs=,iv:QBWv5xLx6hSU7DN1lGCSFT2vrKHUc3xEoxgbDmLWyoc=,tag:VWioMxxe58u/xdpFxnBAug==,type:str]
  GLUETUN_CONTROL_SERVER_API_KEY: ENC[AES256_GCM,data:rq63xXQLhfuVYjt2uU1N87keq0g/UVk9dsn1JzYASAA7Tg8T3Tvvqe6eHtWCTHk=,iv:fzf7kcVmelbzQ3vZc5cDK0TsUZy4PLv8JX4X+sXI5oQ=,tag:qWriQgEak50EE7f9oZI2oQ==,type:str]
  auth.toml: ENC[AES256_GCM,data:MagZeaxMISvOTiSbGo1SYJkwsJgTfaclNjNmt9j1Z2vBtbmlr57sZya47IT4kT/X4TGRX3xVlpPkEfOlW+GIam9upXWZcQYG5rDYe6reNVlTONs4APFUnR9e/8lZ3ooHwigI6xV/kYEMJTyte9Y3J0gZQzPUnKjJDGqYS13xX/lVj7yl0ZKWV+zlsIP3YRA7n2MNZ8rE3GX45ULfVO5tu51+s/0lsBqSPs225XhQVPqJI7mjT4rtHjVX5w==,iv:cBNgk6nmoAOyYzi22IfZygcTLkN3fL/ampqEtwH99Fc=,tag:oczrN9Ge0NWoZfS7x9Dajg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRWFaVTRPN3U4OTVJcXpB
        QkJROTlnTmhaYVc1OERhRFhnWFAwSnFEdzNBCkdOOElUbVl3c3U1SWpOU243QnFq
        L29lZnM0clZsdUNWZGFFaE5FaDBkV1kKLS0tIGxnT0RvZlQ0NzRGTHpJYTlvMGZK
        MG96OEd4U09CSlNtcjd4YjNPbW15OEUKziGQWhlQf29AzzJB4YDJYiLlbcGOe+bo
        /6RD+RK2IKWhQlr/uX3NtCiHCioJReOTiynonaXCmwiVznGReNDazg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T19:03:11Z"
  mac: ENC[AES256_GCM,data:BtkZxc/b2Kavq76ECGVfkeZ8c/UXje+vdw6CHjacKAmPS45qA9Y8CAsbVJ6QESlFPCsv2uNFeBE6O+QIMozLlPWg1ZoKo4EWXD3ewK6CvIW0mmO/a6iyE4Z6ILLusyN9vWacUmtc08n+jjW2eaFyO/cKy2NhRboK61rBZREuHXQ=,iv:MmHk3pw9R1k3IqN0xJuyhOJ+YHQ8SkYDLC5GMvgu5fo=,tag:wsn4DeDgmizNhL7TZS3hXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
