apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent
  namespace: media
stringData:
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:i6K0XoBfeKG7+hXnj5dK,iv:9PurkUtaqdgepaZVC1zgjXBUUo5gRdr7rvgez8jFGpk=,tag:KAxcZG90auqsmv113rFOMg==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:ZuEO79qee1SLHZL1koUCaub9kQjfGDC+MTtnPfbqdKmfIu40bzfkI2P//j8=,iv:bPdBxsr5IVUBzYiob7PhJ14inyrPpbM4gv9zV7bjuI0=,tag:9WVZBQrTUWVFyT3R/i+eTQ==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gKU621C/H1Tt9YCxxlqiRqAhu0CLThJjkzqjxY5gEzjWSfYD8LH6OUsokoc=,iv:g367JPhgTyOotXmBZricw5gs4ID1wZrHsHzcO+RyFk0=,tag:22ZH5D8vfb36lhlqPD0TSw==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:pfCDRy4tdCbLZY8=,iv:61LwPRszGtYzYs354KZ4Z0gdMO+a1DGj6Dkjl3QhxnQ=,tag:aJyO4WxhYZv2nT3HBiFuuA==,type:str]
  GLUETUN_CONTROL_SERVER_API_KEY: ENC[AES256_GCM,data:zPL+6FpHbZgCPlUbGz1f1LGegGN6ZcT3f+ySKMOlAM0HCRpLtoRVbTQYaS0hmds=,iv:/snDpLh/ls5LzE0MsKpMtb2e16wozI87a1v8J0Pa+II=,tag:ouRqvlBGFKq1qfteOJq+IQ==,type:str]
  auth.toml: ENC[AES256_GCM,data:c5Kyeps5cm2SKccBwH3EZpIavc0aUj2qxvguQcXiSihxfqKMiRcxPGDupvzRJoAUJyoJnMUpMOIOB1YgsSX8kLFdYzZ0wx0XgXTjtQ0+JI1hVTmiFhKv1d4LQW9ziRUI3z5xDMK+uqf3cVpIBYX9eq/cRnMyBHhGePmqnJ+qYlKEGw2WSc0jVRMmMOPFvOAJQaXpIhu8vibRMdDWRUNH/5B6+yolUlW7gUYiUAajBU7FE6KKfSSXlPgYhQ==,iv:KI8rvPgfLAE8OcDJI+og8qKIp937PPJTaqMc8vlcQfk=,tag:oY3YfzXFWCXycLOiMzeSnA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTThkOEZmQVNGQkpIdGNr
        dnlSRUlmaUxOZERLWm5WR2hPQXQ4NnJPRTBjCkJid0NvZ0dpR21NdkZSdFVGM0wv
        VnB2Z0p1RnFLMnZhSDZzbVRnOGRPbzgKLS0tIC8xeTJWVjEwUm1aMG9YU3p3Myt1
        MjJCLytod0tFM0lGcEQ5VGQ0TGJycGsKMu/Z7w9HVJXgee/U8RVA7ulKoPsxXTAQ
        azElwrCM4M9uRGkALljDUGnt+mXpUqNWK3cdf2d7jYnnqmfyDKO/Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T00:43:43Z"
  mac: ENC[AES256_GCM,data:ub6NMsdbP5Y6KAhBJFepFS1CkAxpjxyigSUTa+r+Tgh29fjZv+zNvuRkVwmX8GKOhTDjBBwhBQKjvffCumTbOj0v3L4qb/20fIw0iDnN7mSf/o2ntlrMN+TPGhaM0m+kZY1TP5RKrMxE3nhSsL/S8qGzV9EUWLIVbP7oR8aPCUs=,iv:5ZQQ/ll34beF0BQfZSxVDwQ6yAGPMjhzpzOx6eEZarg=,tag:QS4yxo/X6w8ihJ4iJBglEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
