apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent
  namespace: media
stringData:
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:NXBwcX6fozeyNxlcyRjg,iv:8GPG4C41OPUXSDhVnJN4fKg+y0/Gm3Jib4n+zhy1SRg=,tag:JxqsJ4Cplayry0Wf8p/hpw==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:HzroomMyyefkIduh+NurLcYK5BbWvO4YMqtuwFpf/VvT7cWKcLuDIR/LW/w=,iv:vAl/scsy3p8xRV+YLzFFGzxdom/mcosT04KRFycUSrs=,tag:/iOziSpHyxD/gzwnpc7T6w==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:f5Gjj8MQ2fhEuKbsFqgDdIM2XtMyI5QRaiFGVPyENVH3zPQomJnduBuXI4c=,iv:nzXsJPORhhjdRzGirFTA0bCn76mjTHY8I+Li1x9KLzY=,tag:b9kdVrsgBjg31n2L/z90FA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:RscNMyfX3halZ+E=,iv:yfL/e0XlHFJEsMiU3R6qOxOZ7dCkCiSCv9NttsRlhrc=,tag:08cgG02ekOK/5Bbsa/0VMQ==,type:str]
  GLUETUN_CONTROL_SERVER_API_KEY: ENC[AES256_GCM,data:cDLm8Ab0jJCRibmBmNJgAAW1aZeN+wdRggPjjV349c/VM8944g1K5arO76Msq7U=,iv:VAny9S/cFE1C5Coe5s5XqguAwZ13QSwPgu+cZ+Oi5dQ=,tag:Pkc7KF5XJH4hUklC8syJcQ==,type:str]
  auth.toml: ENC[AES256_GCM,data:gXIsVE/cWmYB+wMfIv9K6U65Oob21D5UpEepj1bnQygoMaH2AeGCKtGUv9lRDWrw2qOibEAuIVjT2a/8CPWXGG510KKP0eiWXnzq/gkB0K3gW4/ra5kbhZIwHoBEp0aCR1GwTQ57wy53jFXuHXms733oAOrv8ezhSCAJP3pjzDkTnL9/TLEGEbbCnreMKMPi7j1yZfu6KpGfR6+52mhEW5QHYMwrSD8chGc7tAX4bf9sWoPR6HkALl0RLw==,iv:THaBPh8eK/lhgs8ti6aeaU7LGMpd970T3XKKda6uSlY=,tag:3CXX0tnVf7kgCI36ux3byw==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL3YybVZhYlJ4ZlNNbEJk
        RGVyekZPK3JKSTZ5VG9DTWlJSktZWHJXR0N3CkttcURHeW1qUHNmZytpejZ2aXkw
        OExxQ0doTDAvUGpLVUFkR3h3Vk1qLzQKLS0tIGU2US9iZU9hM2I3T3Z3Tmd1bC9r
        bjlIczgyV3JZRk1UOFpUbmVhWE9JOHcKHWQSCq6nQcTSomL+OF1UdVOXMMepx/3C
        ahr2UvUKVfyeHpXg26CTOn6UX2AWRsQLNzTH1B42+d6XL2RGLPTpzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:59:40Z"
  mac: ENC[AES256_GCM,data:t/uOoWNzth0MkcFy8W1LQhqUpxu9ckL0++oqTgb0QvU33Aj9Yl01s0z4oLaOHzScEv0iY4wNgbO5mfIHd0/m7xYIKz2BJAPGEoCfKKYc91S8/osVTZ9y/wCXfTs2lLm92XT1MXnGDAjT7fuTKP2S2X0G1zUj5nzXaHt4PjSJERU=,iv:3Q8BV8p7qiuTizOFeH0eyX7Rk848uOKcgUS+YXieWsY=,tag:9qpUG3Rj61c1nTdqKwUS4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
