---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: forgejo
  valuesFrom:
    - kind: ConfigMap
      name: forgejo-config
      valuesKey: gitea.yaml
  dependsOn:
    - name: cloudnative-pg
      namespace: storage
    - name: dragonfly-operator
      namespace: storage
    - name: minio
      namespace: storage
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    extraContainerVolumeMounts:
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
    extraInitVolumeMounts:
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
    extraVolumes:
      - name: signing-key
        secret:
          secretName: &secret cluster-forgejo-secrets
          defaultMode: 0440
          items:
            - key: ed25519
              path: ed25519
            - key: ed25519.pub
              path: ed25519.pub
    image:
      digest: sha256:e7a59d193ad5e8bde19cffc68f26ee00e77a5b0014e95433eed5038f0c3888da
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 16.0.5-rootless
    httpRoute:
      enabled: false
    persistence:
      create: false
      claimName: forgejo-jericho
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    redis-cluster:
      enabled: false
    tcpRoute:
      enabled: false
    valkey-cluster:
      enabled: false
