apiVersion: v1
kind: Secret
metadata:
  name: cluster-forgejo-secrets
  namespace: devtools
stringData:
  key: ENC[AES256_GCM,data:+nO4YOW9Og==,iv:dNfAjHO2ETp+1L0QwL85nCSNGjlIKUgokiHBIgZB9MI=,tag:ZDYek7iS2KzV914pKt+hCw==,type:str]
  secret: ENC[AES256_GCM,data:85djMmBcqdUTLN7XhSnfqK9CvsxF8kGc5EBbG49tRjXqDv77QWHO1B/MWKkh+IeSGMl275gCb1KuwVyWniaChQ==,iv:+oq8v57O23fpNgDmUcw3LnoTXT5NgoIKupfZcaW7qKc=,tag:kLiLfCcgaaD/fhorYuAVIQ==,type:str]
  FORGEJO__DATABASE__USER: ENC[AES256_GCM,data:tjUqfnYbqA==,iv:gd1ZI8D5PHjxVwK2Y0cEbBbrigHaMHk22V+0zXbjMZc=,tag:+oY1Pkld8aLzH/JLvAyDPg==,type:str]
  FORGEJO__DATABASE__PASSWD: ENC[AES256_GCM,data:u2R6g7wsvDCuL0jFOPJSE5LukmaDBbaHtQFMYrNqOWjSX5hBeKpp67fJKOTdHVoW,iv:F4R8icuO5Lv2Heyy7FyVwOKz1bGzRBg4CJJtrUgZNf0=,tag:Hazxf6xBiHWL8oz0gF0I8Q==,type:str]
  FORGEJO__SECURITY__INTERNAL_TOKEN: ENC[AES256_GCM,data:ULG1V0FoR8oMMiHgwXNPg9PV/1Aqv2qu98JZmOnHBqwWf1tPbaJDtAfhPov32Ju52su2YGDDugoJFM/wN18otf4qZtzAktbv1/sByMiWNnNAWx2hsbzy9Nk4RiFDYW5g,iv:aAC1ZUpvSyrvb4XG4O1iuP3zrNsjrSnBqliHRsO//RM=,tag:6F/08FSLsoQIcifSCl26MQ==,type:str]
  FORGEJO__SECURITY__SECRET_KEY: ENC[AES256_GCM,data:es6Bqb3mFzbjHUTAgFlFuDpfCqUosoXOBh/rEaMHj7+jkOXPqOB3bhtjzz4=,iv:K84FUcpYxOB4Xqh/tQRNFYvVSoFw0Y8LdllcwCBQ04I=,tag:U7MAI+rFape2YLCWR915JA==,type:str]
  FORGEJO__SERVER__LFS_JWT_SECRET: ENC[AES256_GCM,data:NMKyY3xHogNUtUd+1LBk+vL9Wfk9dtdagCSXyA6ZiwaLqQTMhFJFF2NDdTY=,iv:XLeVTl8Pwvajse1cFvVxOeHK+Ie7xYYUoDC4kh2gNQU=,tag:aWcim8a7YdD0RxOT8bgPDQ==,type:str]
  FORGEJO__STORAGE__MINIO_ENDPOINT: ENC[AES256_GCM,data:Fydn9ZL4LiY+u9UZRv7fQVxzkpR9Iv+og2DYYuOsi7h0FI9C,iv:GMxM1tS2gJRP4sfwEgCMxRCVIT6DFvbO4PgBUoYvF70=,tag:+e9b1I0vMJ48gXdrTYeaAg==,type:str]
  FORGEJO__STORAGE__MINIO_BUCKET: ENC[AES256_GCM,data:VHFFMWrPtQ==,iv:XhrVTsPmIJuBir5cOEBUpVkmYd+O6Ro96lwL/4wtvuw=,tag:jmOQC6DK3+Nelk6lI7/gGQ==,type:str]
  FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:Eu6TfEOFTlvxfv+l5hVxE/3deIM=,iv:7orqgiNsJZtlA2eBgpPcLZeHexHog/bVgY1F+pPuzEU=,tag:Jmh/BuclfsZBZXcj1W1riw==,type:str]
  FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uQEJUnOhh38HZyCfYAFB2G3tlPj8CPwxX5Q6ms/nP2i16G/N0UpkVQ==,iv:k+G1tmPCH+YAG2iTpiDHcYe/kgQkSgLIoaaL9hTyE7Y=,tag:jBQ20X8I8zsdzTzGPgxVRw==,type:str]
  FORGEJO__STORAGE__MINIO_LOCATION: ""
  FORGEJO__STORAGE__MINIO_USE_SSL: ENC[AES256_GCM,data:waS6JG8=,iv:H7KbLMUJ2dJGsvqWepjRn0d1psdXEWFRK3zwhDWmXsg=,tag:D3irbTeshIroKPvyp5D6hQ==,type:str]
  FORGEJO_POSTGRES_USER: ENC[AES256_GCM,data:f2n1BbAz6Q==,iv:xN6vl9/Rp4eG02vPV9bHSzqmMUJ43d1YaT2VWMsY1fI=,tag:QnRc6RnRSpkxELdPLnBg0g==,type:str]
  FORGEJO_POSTGRES_PASS: ENC[AES256_GCM,data:WEHtkLdSGdcCuVXEYG8TT8VFaA6mkEfgql5VaYE915zCDJXrlwFOTbaoucSb7wYz,iv:iXRwUuoHr3YUWfc2nS8NC/p5S4l3VbX+1EimvbFVXy8=,tag:5PjtGnPKaJ6aIhS2Hjc1eQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QVpib2NyM3c2M1AwNGZM
        K052aWxRSFlPbHV5TUZTOXZ3QklTbm9lRUNRCmFRcDFKTjJsLzNFb1lERit5MTdh
        UUh4dDA5K1Y0czNIdWVpT1dWcmc2TWMKLS0tIGdIcFdTdXFESllyaVlGVWhUL09Y
        c0lzVmUxdUJjY0hFZVdiaE9WSTFSbFEKCm5oCGKGlgYC+65kGfKunm+BP0MUhX8f
        0mDz8QT2zJQv22iO1AzQJoFobqw7iW8wYB/ma4fiET7KRZuAiw2/mA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T21:28:41Z"
  mac: ENC[AES256_GCM,data:vGmbq5m8QhlpmQbTvh3NnfDu0WA/sD68xwtBpiNu/weh6JbjADXMTfysoJ1IbrwYtvJN4utFDY6CY+dUEbkoMHUeNFeSZnk9bqYdvR1gCi317lESGSZUJhidFqclRH7eNbSA8CWL3un2f9l6zJkLyM31Mt7MLdugbDC+PD9f60k=,iv:Vdcb9oKbXnnDK24qN8hS6spZC/NxaqNtP65ki8o5gig=,tag:pFFApnRBrRuY/tZR5E4cVw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
