apiVersion: v1
kind: Secret
metadata:
  name: cluster-forgejo-secrets
  namespace: devtools
stringData:
  key: ENC[AES256_GCM,data:QTVl169vCg==,iv:loL/S7UEjskkuJ/WGva0bahNUXO/M/dMuNGvCgLBKWA=,tag:ZeuIo5277r/pvrAsAHZVPg==,type:str]
  secret: ENC[AES256_GCM,data:5CRxxdOcRntKpu5uTEp7ZYtxhk4lMf3WV0vgc663pHzY5FvVLqpUX78uFpj7H2wmK0xWT0YK5nunAlrxbeSQOg==,iv:TEeJ/Msmt2C1rk7Ja28Xpg0+FCVMjoOvz9EP8uJjZh8=,tag:EibVXx2gd7XNsFXNDWzpeQ==,type:str]
  ed25519: ENC[AES256_GCM,data:Rop/yhNEvzhrRy5KyX6t0nzMS4ScKzXmgVOl9zmHFut5JCw3cJVRjinR6oYNHWzJLP0ktUNTWzB1eKoN6qS5BQeem5i8ddCTmEQBKHjHlUIy+bUzeJiB+a9gzXxMlgLm2CiBlcN3AGzzjp07sCeFQrZmhgUJ9OmAzLySUZngllNyo/Cc79/R0NEk8enUR4XU9ANaF401UJGqcN61sT7gLc3rIE/yEtcdp0zRGHSi0Q5c9t33KQIweSoB7gyS0lhhQr4x5grfAjCoWM/D4Zw+xJfJW84EWRZp1vZN/zWSmOQMQkWf+6lj4Tw263q2iLySqKxyrxX4IMcitScHAd6Uuw2gtA10Bwkgeu4f5SnPjcAa2RIS3BAk1iFPLMNks+fKRcBHZsTPe9fiFFwq4eBFeZ3DdDL+i7HApYAOP78jZODzyrLDrCrKdWfFh3cv4OXrCtblTPT0bOQgB5iEaYfG69X6gWj7qQWRweft0NChgCksFKXdwhZc0OpGgCnERqnosuUwn7ZO91UDa6EiokfGWp5SYXoqv1B9ztecBDqgY1gq27OtKkC4abczZxiqG2jk,iv:Ddzgpdstj/+KRIrEUxxDFNMA8AX0cCNkacwgcNKULF4=,tag:Zhq1RP0u+KscIc4Gs7pkHQ==,type:str]
  ed25519.pub: ENC[AES256_GCM,data:xQj6mkqcgYT/I3ITjAuFnFN0HIps7O2yvj5hlkiWRGq8aRwRTW3UKhJt7qkKI297/QWEdkZQrDuBvqtHSf4JkQg+nqBEYBM/oAgB9UILFwQkoQIbtlEmAMMDtXHn8kO0oBVf32f+OcB1Jhh/Sg8u,iv:q1LoWQnhYka4X+b8k3swCKiNYostTlIfK/lX5gSszgM=,tag:V5kUrQ0k2/rb21EEl4J95Q==,type:str]
  FORGEJO__DATABASE__USER: ENC[AES256_GCM,data:ZBDeLEgqbQ==,iv:7tARc0YRQLmwOQjUTjrBTqNkJk77pGvXxmMVD7Pbnuc=,tag:YdxJKdlnP0DjnthV1yOhvg==,type:str]
  FORGEJO__DATABASE__PASSWD: ENC[AES256_GCM,data:pdDEcShAoz3DM9VtRLXEy6BTDxOCTgKyrjSrk38mu2kjXTSIBjQYAJy1+mXEQnJv,iv:rY1fpFpEQ346Bp+q0dWsYTHeG5TBcaRJcIizNR5ibIk=,tag:vNSP6AqeFbGRSII7EEHKNQ==,type:str]
  FORGEJO__SECURITY__INTERNAL_TOKEN: ENC[AES256_GCM,data:tHAO6hNaMhMPYVgoMcbTZ70AZmeE+JKmqy5ryLViVRhMdrmIngbkATgOsU88Wb92X0AiyFBmUcjx1MI+31PzWwuz3ZnZ8+HUA+BmbBB1CUmrpSB+Aw4fzgkRu05wbm+k,iv:2Auh0+7fEdxjvt0hkHsESX9RUD+/rl5ctIQ3WWE702Q=,tag:BXPn5+tleyA+8/xSYiXaVQ==,type:str]
  FORGEJO__SECURITY__SECRET_KEY: ENC[AES256_GCM,data:KIXYQTYO2xSmhbnSGCExIWWpho9esBq34CTzTVk0opuK42YyKvNu+DJfaFI=,iv:wo8v/JFueL7kre2IKQM9HBjq1uxVm9pTb/R2lOlyi0k=,tag:LWd0DaDQi9GlAErjCny8hg==,type:str]
  FORGEJO__SERVER__LFS_JWT_SECRET: ENC[AES256_GCM,data:lAOv4URhYlGL9xek8oODHPeSuLU77ibSfJc0HEcEPb1eIsxL9N5SKqWGjSE=,iv:ljEQ5XwUhM2NW5GgivD/W9xNyLaOD9BLsZpexKLG2Y0=,tag:zMlqwSGmHP5ZDP/rPl18Ig==,type:str]
  FORGEJO__STORAGE__MINIO_ENDPOINT: ENC[AES256_GCM,data:PF1SLjwcD/CFA6z8J3HFYQchUTVMbjeLrTtrv5v20O/h9hMb,iv:oVKnQz8UDKD+dxR01R8FS7rnFlIW9GGIcYdcyA9KSNA=,tag:qkRtsb0slcc/TRFnvmxLmg==,type:str]
  FORGEJO__STORAGE__MINIO_BUCKET: ENC[AES256_GCM,data:6mqh7MJZpg==,iv:pPSb1POEdVR7dkt72a532AqCUWO1GU9GDp3NOY82Wzo=,tag:j9phjndgtVo//698coT4oA==,type:str]
  FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:F2efBjq15bU3nOzohu+IUlmT1WU=,iv:KcZyc7iTBFPI7cexlCEYj2IzuidpEcI4sr8ghUg8n4c=,tag:xXFnGoVKQxTxelqBqSxx8g==,type:str]
  FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SWXGwBbVdU2RhlxChb6xNrNOU5Xm+mBDuh81f1Rtsg4i2qhp3QdOQw==,iv:EQtPfemkou53zbMo9CwIeqwcI+C6iL9ZIzdHYDwpFYI=,tag:tQiwP20Gg5Pth5Gt6t5W/g==,type:str]
  FORGEJO__STORAGE__MINIO_LOCATION: ""
  FORGEJO__STORAGE__MINIO_USE_SSL: ENC[AES256_GCM,data:4SGUwLo=,iv:HbyIyOnIm8gzpK9EaRMsBIKcH2u8O90iQ1FTrjFGg7w=,tag:vQBNqIU0NltNAFVbzjWkdw==,type:str]
  FORGEJO_POSTGRES_USER: ENC[AES256_GCM,data:ZAjIYQXZ5A==,iv:3YWY3F4cJefDDYzEkibJzMYuvRquM0Y+wT33X3QmVbc=,tag:Sme1RSn7lvRgWk93JbU1Zw==,type:str]
  FORGEJO_POSTGRES_PASS: ENC[AES256_GCM,data:6JhJ105C09H0wda0NhCeR66ds2/Tf//1rS4q1v/9mvkWXQVahqITJIDnG+kv5lpm,iv:4T6FyfL7eOYnqKX4dgPFMy6ooospczp7xQufBri46Zs=,tag:TyIx9LVQZs12RvaCcqnhSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeklEUVY0TGEyc2ZzOXl0
        a2NtVGJHNW9KYXFDdDNvNTRwY1V3TUJ1MUFJCjFYZ2gwTmh1NVh1VGc1eXJOTnYw
        dVp2aGF2Z3RBdnVoeGd5U3lOZjVOMzAKLS0tIENXWGNtNGxVeVdsd1V5b2FqeDZw
        U0pPVGtWNU53UzNZVnNJMDlQclJOMzAKic2WZ3lj7PRJE/c7VKYAr+bIXBvWXwv5
        ZsdyvLC2pcYdAU2iFn1OdIXorVCcVtslvFwE2JdOpk1Kkuv9sV1oyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T09:43:48Z"
  mac: ENC[AES256_GCM,data:prkLyPhtR6zTOxbT+h28aklSiLdUHIoKAAce76mZgWdBlS+LbEDD35v03O9XFG2LGCeEYVGSJHhaK4wUrcv6iynBAc0u+B4HZ/SX/dJ6GlCnNKyxP+mKbeMyoLFYoTkSfOE/vHXexVaL577aj3eYE9U6x0TJ2oAu9Dfw3HtWIlE=,iv:qn5lPh3UrtKNaB/htoe2MlxDiqw/K+MwFfCu3a2JvK8=,tag:KropbtWH2yJpN/h8brBxhQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
