apiVersion: v1
kind: Secret
metadata:
    name: cluster-forgejo-secrets
    namespace: devtools
stringData:
    key: ENC[AES256_GCM,data:IuJNjqazHw==,iv:+UiXdjf6J4B7vQNxE/Rkq2Q0eHSWb4XP8+R3yyXVpdM=,tag:C6Q/lZ2wN81AQrGU608WuA==,type:str]
    secret: ENC[AES256_GCM,data:PV8PY+ul0NtBQ07wW57D2cWG0TalcYl7gmcbBnypQKgwgHRiPZarCOnwsd2g0mxiD3Lsvdt/w/RQUnVm3UnIpg==,iv:Dh7QQBnYa4p/HNQ1R7UJao7GZdhjwGjHJB63rgLrISE=,tag:X1Hw50mR5A8x4iTeOfUK/A==,type:str]
    FORGEJO__DATABASE__USER: ENC[AES256_GCM,data:o7Ha0ZRycg==,iv:plyo1nyx57f6R4WAzDe3D0O1LM/ZmomUxwyVYTC6Aes=,tag:9daTvIYhxcKp9IbMBK86Wg==,type:str]
    FORGEJO__DATABASE__PASSWD: ENC[AES256_GCM,data:QY58kczlmjIEpGrkTsl94waGOfV7t7ITk5EGM2D81nr+BQSy0YHBHzXtj4t5Any4,iv:es6rO28s0wVUnmqYow3meCJd8fqpJElxYNuT4keQB1c=,tag:EaBXrwN+ozY3oxFk/QxzHg==,type:str]
    FORGEJO__SECURITY__INTERNAL_TOKEN: ENC[AES256_GCM,data:6LvigkxhWy+5MvWwwwZFOjP0RZSEYim0uI8ohNqWq4XXmPgURgk6iQKuQnEVwzN5XG+znBNGfpHHaJr4IVl5Cs8H9t2abYLvnjruAtm64wlhrv0JLgo+0y8Rg+itt349,iv:VAJr6WWi0Jk5IiXmBVAzEnIi3LNUw6mReRnpzmgXWPI=,tag:0OFVTufhRKKgp5Z5e9FC0A==,type:str]
    FORGEJO__SECURITY__SECRET_KEY: ENC[AES256_GCM,data:UoWjhLJwnThuc2Nz2naSxUCAXRnDyrLrOJzgM4qvrm9VJg1F2iIe6PJP8vE=,iv:AKU5rrRP4S/6bv/+dLh+Cp+XK1+wcHNfcVb9PbHan7c=,tag:9kTwL1DnSjFOeo2ivnHGMg==,type:str]
    FORGEJO__SERVER__LFS_JWT_SECRET: ENC[AES256_GCM,data:gl1EydECGl+MsTj/XmzZZzHrlYcycCW6BKDKHlFT+wHyVYIZ/ex/raNnIXw=,iv:q3QAh4hQx0uFLHI/BzSRQQRpz7xS06YZrqTRBwCiRd4=,tag:+xFfE32U/SKuCC753xaURQ==,type:str]
    FORGEJO__STORAGE__MINIO_ENDPOINT: ENC[AES256_GCM,data:qCmUqSEea3mxopbIoldyr2lLN5mL/SGNFeOBqJNGaNLxUPHj,iv:3Y+8qp0BnHFovrDt27PO/t3n9vQ2HoKJBvwbZGiA4DQ=,tag:htON59wmptHDzi6RLAw3JQ==,type:str]
    FORGEJO__STORAGE__MINIO_BUCKET: ENC[AES256_GCM,data:+BCrSEFdFw==,iv:e+aPCKZeihYvW7uippC/NQQQM/X/wqC4c8wLPsewNCk=,tag:N8mWA9fXAQEizxHgSs+J/Q==,type:str]
    FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ss5EF+9RsiqAuX7hCBWPObRpyXg=,iv:rAOLfjGFZMIoaNrijDEiIFTshqMFWUqCCNBaQBdhCPQ=,tag:OxF6n8dU3OvWfWM/40Z9Aw==,type:str]
    FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pJj9NIZRajO1B6/Iab4F8LRDiSFPR3LZ4a5A9PlbVuSQA9lecEtRDA==,iv:Sa/SexWXWkHhb0b1zNXp+eVeXbD6QSlogQ1tMPI6vFI=,tag:2kGshYJVR2uJ+vVaRBCNTw==,type:str]
    FORGEJO__STORAGE__MINIO_LOCATION: ""
    FORGEJO__STORAGE__MINIO_USE_SSL: ENC[AES256_GCM,data:RrX8ufk=,iv:Psju2GCgjed+n5P8HBSPmanSH65cn8bXj5k11q5A78Y=,tag:nG+HfNDZuUrJgQxalDf+wg==,type:str]
    FORGEJO_POSTGRES_USER: ENC[AES256_GCM,data:8OBy9/yjpA==,iv:NWOhKG95xqrPLKRGnyoRJQ0tkQn8p4yf9tYWUvtpYlg=,tag:ZCcgpxHn/cqews1SfDfC9Q==,type:str]
    FORGEJO_POSTGRES_PASS: ENC[AES256_GCM,data:HKgX9bxpqA1hlKJtr6URjslDNKtp1h59PjtBuWBcDRqMa2Vpb6ESFqY4Gz2lztXi,iv:+xO3RTz2pH/lexyWsNQhbPLy9UDJ1uqgY7u9vNWdHyY=,tag:2OPtxGvN9xgOQ+7xa1kuaA==,type:str]
    ed25519: ENC[AES256_GCM,data:N7XFshzLChzbW0ZYDx3FAUsmxwiJ8Yi0HVLId+PbsHo1bljNJ9vsi0wKnfXFk82VLmF28RMBmbohUbBXxCpc0zdeujCuGRXfQemC9o1HymuwbIduwHYJe5bvi/xasAX39quF8xw/CN+Uc+Hovcb6djK/V4Xi298XyiYDpvGDUcERRuucz878sAj61ALmCJYEY4ZFQ6lZr+rR1FZDn6RJuP0hmKuuqHYd9Lo6O4lW/DTlswlgrs7jrs7ET4X6wyw+Ug2FfYVqFbpyxDAh62RUvsKAEzyfCmHaMUL256bDBTwFObCVkNwSWgA2VodzCoxUSGayIfx8UmVtccg+s1G33+1GVPUQM2A/x8M8r6JXMM6Q6qIJ+zAi2GpzaaVY8WiHhxL9WUGvoDqaD7oCkJ2wonZIfH9Jmk7771mqg7G0npOqOo7zXrr1XhJoN+ee7XRE3cX2RDTZpu0lLOr3JC/FR63N5jp5Bwa13CDqP7aTWVB1sytiUDUDlbimFfAavEOsijP5/LUcxLeAFJIpvsJEfaslt3RVdRjgEjw=,iv:rmihH1jg3ZXvQRbuabxObsnVNaCKg3DBgF2UujfwO6A=,tag:K6jdQaBjM6lOB+3AXhw58A==,type:str]
    ed25519.pub: ENC[AES256_GCM,data:a96fVdGiVaRm20X7R/9u2JjYOfDZrBs/8/wcdyNjrcf7SE9Cgu9DVt8sEwrukYCbLPvqH0HgxCJc4ySI9Z7Jw6gEJa6FDIV0u+4WBHrdMuuHlwOybAs5rClRduSviajgkQ==,iv:U+oqzeGQNWt2cjzXgQs0sqQVkx2Un8UjXLj/GUZ9VbM=,tag:FeVZB9WKZom51icfSFk/ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ukx3a0lUSXFmT3BIV3kv
            cXdIN08xWXg5RXVZcThrZ3BkcDF3RVNONWxVCnFXUkc4bHZ3NXh4R2trZEtPdFc1
            clZhODhuYkdHa1NtTERZdEVDL2dWQU0KLS0tIHpJZTNyRW5HdjN3NW94YVJsSjUv
            MEp4aW5MWnozYyt5YVNRR29hQUpjK2cK5TT7Fc4gpUllLNPXzLLAMWLaF402h/3v
            glT3wwOhsGrGvwAo7ZfBis5p/mpFjeOEbyzcrO2zrvi4c8kGP+OF8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T08:10:22Z"
    mac: ENC[AES256_GCM,data:HWF3VzhmkPEcA3MM7vkXttJu8AvDUMXknSVwU3DIgKejOND+gQzHT3OzeSkCVgNR2BMpg/74iHcS2FN6/4Ow8KCV9wH7w6tE3C0yKbH1u6ati0aMzzvi8Udug/a3ZTkLY9/hClLXqGEmKup7+6T9pnMu2UvyaB7hiEohSmyzxk4=,iv:LbdMfXj5+HrsSfTXKefFVPI7hXEBKPf9SooRqkkeCB4=,tag:I0AwItyk7qz9q1KRe9YwEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
