# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: translator-secrets
  namespace: default
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:IgVihrJDL7ExIv/6kC7iWU6ztA9iwtrQTJldcx25240IqblLowbp0fUIP3SDuk1BQMVVmZWKEsrkOi0XpYMNcxt1bbBvG1uao/15QLsdh0Zx+lrJ6XxSA2ubK3YS9ZetytyAtQGHZooq6eFN5WoV636PGMgQB2Ppr/6koilv21X1oT6V6Bo=,iv:qiqPSOJXFWGP2a0xaILD2rbIvbOIo9geuUh/O+A0loE=,tag:dfeKVR87Jsa9Jp0j4em3qQ==,type:str]
  TRANSLATION_PROVIDER_ID: ENC[AES256_GCM,data:YBITs7zwV+xcOfxEN8+4DWOBaM52icMXQxWPe9+y042ly2Vf,iv:36qMrfRKA/ShD6WcYY32yk4qeTela6Jm/dUUmtXTWE0=,tag:IIEmJMz2tPvihgeNCcuCCw==,type:str]
  TRANSLATION__PROVIDERS: ENC[AES256_GCM,data:q7JcNePRRfyLC+32juH3qgms3cJVNe++NgcjxmiJKFchSAQne4MhZ8LKmIN5DWhtk6ioo6j2qrXBiSDRm2MrjarQUA328H2B/2HasbWs+k/PFC+UMHv+nqTEYN0kfFz55fY3kfDzYU4WyQELzEIuZXalSu+i/rWeym6Gklah3ZZDN5eWNmTJX3Xr6sp4Vwo+EJXcRGjVve2Ym0BiDgEGncSftX7hqP93lWhnO0owd8FNCF6jrK8if1QDQokLkaa5RnqY662dWj135fWu06hwZ8G3YxMhX+LuDRy1pNclh410iydsSfbEhjlAuvHBjRJeqpOCdFIc/fH6x1PFM6CKdXWqR2mtu96W8TCW8zTLyvcFQT2BzFRGZG/Xa7bG7L6Vpc1O9JhlcU/tW6Rhear7K2BjAqyr7089t6bGuN0WU7URS/JiOjVVoZh8xH4z587jMEjUwHgJmeXFUkUrQlJ2qzH4x0w3vx0IAy5ws25y8hEHIveeJzdTEj5nHASdPOuSPhZJunTrZGTekhUkNGNkeF78uf1qS+jPEMcJdCklhjymU9XHbxkeq35gfml683/wpelVxNy3n4vgvc+mYCtn8fCm35h/lt9y1SnYlq49Nxz4X7Qab0br5LCs5A2l8dwecbpEBJjwwGo80JilafE3vboG+k3g+SfCCy0QgqSxwwYPra10qZgdHLbzNwji2m+W5AMwc7w+rI4A6U2gXD9T0o8Nmto91JvSP5cCDgFB6Qh1Qet3GBGXQNXVS7kbCUFA1Vub39hcJMqokiRwbUL3mVajwdLH6Uj6dnu/uaFWVy9yYnrI0SzZKTU8EiD9wBAbQAWmFezOUaJYzz9NUQADPf2fx+O0ODTbeIc=,iv:E3/QXAcdjVIxenk3TgSEDWanhF+bSZVSbx1Pxa2r0Q0=,tag:A5Q+JaG0Z25PwafXJhPGgg==,type:str]
  INGESTION__S3_BUCKET: ENC[AES256_GCM,data:yZF0Tzjry0zVFw==,iv:d2vea0N2jCG0FAOH+6ukSxrRxtUs+H52s9CBR4yzJjM=,tag:UhpomwK1S3m6Phw10OYDBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cEFZWkJSQ2JBbDlIdmtm
        WFlMOUNwMkJCYmM4L0tSa1lzb0lCZkhJVmtZClBVNlhrTkNMSFk0RFh2c0Y4SWVW
        UklnQUVGZmlRMWRxcHkxckFLQnhTdGcKLS0tIHZJT1NzL21YSXdnQTJyclJFaFBP
        ZmhrUEJSM3ozemdxeEpjaGp1Q3lPRDAKlfd0dZeIwdKXDDV5JDPQ1zZdpdJC6nQC
        PiWzg0adozH2bWvB/SzsUGgzAWrlOxB8A7paRLeUdt5B2Xn9rBK/TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-01T00:22:52Z"
  mac: ENC[AES256_GCM,data:pSkjGWBOfl4VZkUypSMgr4lwTsW2bBMyfrXovDlma3ZypfE5th6UDRBA1IJaAH8QpAIaLmX13dRG++5Nc9gcB8ujEk6HZ8rrkcCSumf75Sgj7WvNvAxPDQ/Lp/8q8qsZbe2sNRkxp2dCyxyxbBDqbxje77Jf1lcxLiQhKpNib/4=,iv:M13U8iDNan3tfJKm6Cq4je8SljBgzPNN3TFKvuiJp9A=,tag:sR0zR1X5+Q/JJCpalcmMuA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: translator-keys
  namespace: default
data:
  document-master-key: ENC[AES256_GCM,data:6K7TGcQ4KJnN3VDk1JbsvSVjIxE7OAwEvwXmK9Q0r0ysbr5zJtFTtLEoVHY=,iv:XGBDWcXkpUo1UQZ9KHL/fdRuB8ZNcqWWFFC80rfLGIo=,tag:X51/EnQHd+SUjDoW+Q8w6A==,type:str]
  provider-master-key: ENC[AES256_GCM,data:SKYBPzu4j787Zqt3G1hkI14n8FM1E0d/X9Nr/Try8yVuPDId83P46RA8Sy0=,iv:6TUNZpmPUAIMrgyMCeQ3WeT0IgRqWdK02CrMGdtvGSk=,tag:7uQIKXtGawOoJGvD6v4A4w==,type:str]
stringData:
  s3-credentials: ENC[AES256_GCM,data:fw3GzAG0RwisnNIumLc38wNDQH7gbVCL5dsCwxDjc85az28luMJ1DPl9ZGYI9HKY2D1FNSggWilXKxWVjFerlJvG9+gtpD0d3lOcZRfyquGtcJLzfAT6WKR1sRVWvNYeGYGGy6mgT8Hnjg==,iv:WQcUOWJap1EGyYj8k/O9j8GmqOJz0Aomkq9HwYJ7+VE=,tag:ZWSHxmMiw7BnDB5UGwpRRw==,type:str]
  oidc-client-secret: ENC[AES256_GCM,data:sa4EVlPzF49X2QekL12ag5o7CfpnP0L9QUvhrsrliQn9/eO7FH9s1xBuClvzkMYIsTA3e3fzuJPjAwz2zjtn0g==,iv:F62wM4n3EiTEErslfXxV9Ixis4r3wtZ1bemtkhg5bmU=,tag:9k6VzSNoa5PT+CI6lFHgCA==,type:str]
  litellm-api-key: ENC[AES256_GCM,data:r410nRWhP2unrMSm7MC5yEn1p5YQV6K0tQ==,iv:UQj1TpN6XTf1IZHBQt+viaTgwZZiVNsOhLSe4Jgfx+I=,tag:ybA7HC4uHkd3J7Q2Wa2t5g==,type:str]
  public-litellm-api-key: ENC[AES256_GCM,data:eEGDrcY6hd6kTClDlPG32VF3CI62R5oobA==,iv:5jh+uHc/w+uyR36l7n4LiqI4f6QS9/lOLQ5TweN94xk=,tag:hUCUw3zdG8DHCz7tTbUQ/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cEFZWkJSQ2JBbDlIdmtm
        WFlMOUNwMkJCYmM4L0tSa1lzb0lCZkhJVmtZClBVNlhrTkNMSFk0RFh2c0Y4SWVW
        UklnQUVGZmlRMWRxcHkxckFLQnhTdGcKLS0tIHZJT1NzL21YSXdnQTJyclJFaFBP
        ZmhrUEJSM3ozemdxeEpjaGp1Q3lPRDAKlfd0dZeIwdKXDDV5JDPQ1zZdpdJC6nQC
        PiWzg0adozH2bWvB/SzsUGgzAWrlOxB8A7paRLeUdt5B2Xn9rBK/TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-01T00:22:52Z"
  mac: ENC[AES256_GCM,data:pSkjGWBOfl4VZkUypSMgr4lwTsW2bBMyfrXovDlma3ZypfE5th6UDRBA1IJaAH8QpAIaLmX13dRG++5Nc9gcB8ujEk6HZ8rrkcCSumf75Sgj7WvNvAxPDQ/Lp/8q8qsZbe2sNRkxp2dCyxyxbBDqbxje77Jf1lcxLiQhKpNib/4=,iv:M13U8iDNan3tfJKm6Cq4je8SljBgzPNN3TFKvuiJp9A=,tag:sR0zR1X5+Q/JJCpalcmMuA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
