# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: translator-secrets
  namespace: default
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:FeoktpcGyb3rfJ0dmVkurAvYt7jAAGLUWWbDt4Ti2rMtYZIiD0GnnjJO9fRvDs0dghwK/BXpcgEJbGWK5GFVHVBBUae+AnYgVIAW/OSUpRe+mlg7hLeUA1NKmrxTwCKJyQ8JFcnDHJxBkmyjOSOt9EVlHCcjkroDXZWOKV7bvbqqVBoVYrg=,iv:Ne0DuesVuUtv+a1EDwxqElmSadWAr9Zok9+H4SHkNUE=,tag:zxge+qtOhvUKLPMpVE/jJg==,type:str]
  TRANSLATION_PROVIDER_ID: ENC[AES256_GCM,data:D7AiLlhljt9HkLGx80NNL2ZWxEtmRQgw+fQ7YEXYFlqGrqHw,iv:ZfPoggPYYEnxxEv0IxMeLniFCIENvP1BYFN1dfD1rLA=,tag:BuoiJKS9Neu4bHNlR/PtXA==,type:str]
  TRANSLATION__PROVIDERS: ENC[AES256_GCM,data:tdpaKJKIapr/yvH4Qkg+roL8Rb72V/8f7Pkf/y6TXQLAfaVZjm8bxCz42iK4dvc+QkrckTT2z7sdLyEz+pXqpuBOEsKpz5HBV1NUTFzrKQHtePIbmTOOJC8PT+UHHKw1RNDJk115WyQIgPjc+HFGHYDhjQ7MBHbwaRGpQ3LqziyZbNe2PyUGPrPYG3zmivkDH4egNDHTFFtnB3HcnUOyEioFvtXQbBYcnCiJxiDpA6/EqLwihVM1TFM4IBcPEU7ir/eQZLUEFzRyd6HFZhew2+pJPm194Op3rUIzjVuE8oEtniUox0PwomH86ORHrP5D0NK4TgWfwzAwqhDcmVLfPK+syHwXDxS8K00ulvzpLQsbmUqwpuxApX0oJ8WL2wSFrhZnNq4ihzpM0u8Wy5dcXnxclQZ3grp9kyxqcpG0I0PleInaRPWMK+MscSBr8PmhuBcRFevBcq2ozYbnLKx0k7Qs5B5cKAD0am9/6TsCn5cKp1vw/qvuhHnrUfDQEQoNryh3WHarGGy2D2lKsNI2ca3Ge5azod2fnInTGAVdJL+y7GJotDDjta7m1fIeb2zF9iR4M2T45xI4cfX/Bn9BKJb0Am6jiF3c4rIeXkGNE7XET4Si5S2P7Z/G/F2C9WWbOWCb2MA8pQ9Xo+nshFSoAHNgepGY2lrPCk9bzsRhqyIKwlnjpxso8rKCcAkeholpgZxM0DjyMuk0faxyilzGUhfgIAoNgd88iWLX3PlAjBHXAagaLp4q85QG1pm8LUelc9emAjB3rr/LJuCqmbzjqXHiieDXuNLRJmCOrgQPYXI8I7nhbYpRgX5HKzK0bGo78SKIn/gzumLzRC2g9UfmNvZ1OzWn21LmqAjbVROs4J8FKwWg,iv:ui1W1MeivoUT6LlcgZnrjHUFB8XFU5+afcB+aIPSaE4=,tag:lbmVoT3Yn2GrQ2TqZDfpIg==,type:str]
  INGESTION__S3_BUCKET: ENC[AES256_GCM,data:KnQRun+8FcIbQg==,iv:jLP6fkwfO50e4lDiliXF90dYk4Y2Ji++jqNOiWr7yP4=,tag:71Bo/ssd2mVqewNFtLtn3g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTVrMXRUU09haGxVN3Q4
        dHBqNmExMmxCemxHamxramhBR0N2dlh1WGtVCmo5UHhVdVhGMjVHSHdZR1g3aUg2
        cTZYVkplbi9JQ0dSN0grdzRrUE5DYU0KLS0tIExHQW95TmozcXE3N2Nrd2J5MUkv
        VmtLM2F1NWxuMFBrZTBtVmVIa1RMNHcKvpyVFzML38dFuhYCzc1MaKLGAy6ItxVP
        aa/dbAvexmoX8PfZnbXS6Qcd7vZhbD9EKvb6vHuheyYhk/R845I/Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-01T21:33:09Z"
  mac: ENC[AES256_GCM,data:IrllCnC2K33LGkeQi4gzNBkNk0bDrorqkDP+O6FP5SCQt+Hmnk0lYBy1yT8CIdkVRjNXfywWHLQptgNmMIBoMg699m/U8FCSlJq0AB9JSHGr/uyR/mNDz/6U8NphqbM4eU9Q2COZvLmw7bzdFAv4gWZHQXhnyJj6A9Utl/VXB8c=,iv:zc1ZbHpD+yyGQVe9kWRUg/kkaTPu1iS0H4vdWV5oi5U=,tag:gHIOblSDjN13VvzvgTexXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: translator-keys
  namespace: default
data:
  document-master-key: ENC[AES256_GCM,data:yDjQvCsIMeGmaJdTvjmpFaS6M0uzrd2KVLH9nXGkIq8cBZ1bafkSmFKufFY=,iv:DKIg4XNqIfB7GzJ+A4wIQ/vCRJAeMdn4eUW9351Ut+I=,tag:Rx+E5Uloil1xaMjEwr/lag==,type:str]
  provider-master-key: ENC[AES256_GCM,data:kWpcFq733s31OMs1y49c0sl7rFWsZfvdB0S5PMxdrdSWIoOblAI3tAWvhws=,iv:+GXYcnm93CG/Rth/ESINJt6XajBNvGsR3ghFLTAiuqg=,tag:TRDZEA/aZi4ji1gm0IyJWg==,type:str]
stringData:
  s3-credentials: ENC[AES256_GCM,data:O+vx8axifTpvRY/vDzwFmOHDyAfAMWT+W1i2LQg3TfN6Lf5ivU+6swIekIoy+1KAu/t+phnwt06HBNZjdWQxh4z8LusTDeCIbIhBv8hnF1g3bG7t0DwueJmyExDmocrUNWbVtpuSmy4n8Q==,iv:Hzi8WofC5LrVVEnxBU0BqqL3qnYj5BaAaour8uW99N0=,tag:7eI9fR0eIcrNOOXReSAgfw==,type:str]
  oidc-client-secret: ENC[AES256_GCM,data:Hfq5jTqO0GGMWpZQARyPacu28TyUowl72SfNDrpbzr3zzxAStNxiYxrhax8IkUlJsZ3l+/rh3+zhnYIfdhjRBw==,iv:PbG5+ACn7Wn1v16FWiTXL2pgl2Ve2h+DUGibFII7it8=,tag:4xHX0JRlSUrgGMJxFVAkrQ==,type:str]
  litellm-api-key: ENC[AES256_GCM,data:TGWwacR82NkPuEiQYUXdF5mPR3+g22c/Pg==,iv:fawPbEzY3V1o06u0nWEZFCDgFIFT8RoOyizcYwaeGg0=,tag:vqSUsMdFLVXZJCW/Duhh8w==,type:str]
  public-litellm-api-key: ENC[AES256_GCM,data:b9jtAG30AnWwovco6JaAVRW9t4So0ftXrg==,iv:vkRU4DRu5aehU3Mwmw6f+v3sA17wERcdoTOtpajli7M=,tag:qFUe6Bwovo3hLwQGNyWm+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTVrMXRUU09haGxVN3Q4
        dHBqNmExMmxCemxHamxramhBR0N2dlh1WGtVCmo5UHhVdVhGMjVHSHdZR1g3aUg2
        cTZYVkplbi9JQ0dSN0grdzRrUE5DYU0KLS0tIExHQW95TmozcXE3N2Nrd2J5MUkv
        VmtLM2F1NWxuMFBrZTBtVmVIa1RMNHcKvpyVFzML38dFuhYCzc1MaKLGAy6ItxVP
        aa/dbAvexmoX8PfZnbXS6Qcd7vZhbD9EKvb6vHuheyYhk/R845I/Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-01T21:33:09Z"
  mac: ENC[AES256_GCM,data:IrllCnC2K33LGkeQi4gzNBkNk0bDrorqkDP+O6FP5SCQt+Hmnk0lYBy1yT8CIdkVRjNXfywWHLQptgNmMIBoMg699m/U8FCSlJq0AB9JSHGr/uyR/mNDz/6U8NphqbM4eU9Q2COZvLmw7bzdFAv4gWZHQXhnyJj6A9Utl/VXB8c=,iv:zc1ZbHpD+yyGQVe9kWRUg/kkaTPu1iS0H4vdWV5oi5U=,tag:gHIOblSDjN13VvzvgTexXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
