---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template
  - ./blackbox-exporter
  - ./cert-manager
  - ./cloudnative-pg
  - ./descheduler
  - ./envoy-gateway
  - ./cloudflare-dns
  - ./intel-gpu-resource-driver
  - ./k8s-gateway
  - ./kubernetes-dashboard-charts
  - ./nextcloud
  - ./nvidia
  - ./node-feature-discovery
  - ./openebs
  - ./prometheus-adapter
  - ./spegel
  - ./tuppr
