apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
  namespace: networking
stringData:
  email: ENC[AES256_GCM,data:jZb4TiJRYneW4wSB+WRc88hmNegx26euoaVrIA==,iv:zd2XJE+kWbQuwmaSVTccuRXOiz8hXFr6tAgpYMF7X48=,tag:OgE7i06dCBMndhnmZ9yeaw==,type:str]
  api-token: ENC[AES256_GCM,data:Hxld/6nJbIi+jDB6LWgYHuFFRQUQ7j/tY9pLmZSussAKJZL4PWBUbQ==,iv:grAtGefYYAkG7KNY56HJNkihmtMBjxUflH4kxeOnPaw=,tag:ejXJEubUjS43rzZDhRMqSw==,type:str]
  api-key: ENC[AES256_GCM,data:QiOKqqaCuyS8jJULexJTrNdtvh7FwWcfc0IGCX3nhBGHxYQRWA==,iv:CthlDhR3po+kQnzSh+7UeGJ29OjRgc+DSugQvgrKMns=,tag:1Q5h+fNk9GKapOeM7QPqjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUmRINFJVQldZOGsxeGNT
        cmFUV2dFMWlDSTRQK1hCWGdrNlB3ck01djM4CndWcTZRSHJDRllVM3ovM0JVMjNk
        eVQxdGlua1VvRGFLYldjTkxlUGlCU2MKLS0tIGROdC9wRU9wU21xUSs4L21WaXda
        WkVMaXZUUkhqc0pITlIyTWRWVkN1Y2MKD5spZApIpU5pNrZPvnbB5zCWidcdnfHG
        ZxDa8Ub9MJi2jQmMkckOEOI6JifLy+UZBmO+Y7Yn1r1MzAqs4mX9Jg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T09:33:31Z"
  mac: ENC[AES256_GCM,data:SB2bmHa9ZgNFj3Cl27TqaO+MvsQB1NaXMliOft+c/Ze5IAIPsyFX193vzR4lBCQ+mazZI9Q6uyCWIQVCIhdlOYMlIRZZLqA5540RweNL+jh5vxgQWflw1QpAlZt0wPZ1pIxsDf/7W/B2qXxlKOVwGI3MdgYzydykP2UQjGt+PDM=,iv:ZG5QZJQrwLpo5CQtanvPEFjLi0EQzcLU7XwBfj/pyuM=,tag:qZITtye0+R8TZMXDUQ6QCw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
