apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
  namespace: networking
stringData:
  email: ENC[AES256_GCM,data:SO+4Wndw1o28Gg0Pbg6UYJxZoEUfCPoo0pvQMw==,iv:B3DpUQS8hZMk81OuIzPkTDd9bBUq6Vigi5R/isK1luE=,tag:mLvIrzlQUsR+JnszkFbWag==,type:str]
  api-token: ENC[AES256_GCM,data:Ba2evU8R/OniQxpIOvjN4u66/oxq0NLHcvQUZ0XEJ98BXL59ksJiYg==,iv:J18kPBFneOGhxlbFBSFXD+vD9Ew903ZJV5RYDC38N0s=,tag:gsJ4dIYY89Z55QKKEiClIQ==,type:str]
  api-key: ENC[AES256_GCM,data:Ozu6P0q3PXDbUrOXSW8hffpBKWbIPZ2pxWRztTJbSbm+3UgHwQ==,iv:MUxNOCD9GMLIo3l5aEZ+4RmUUqbICLbaLLJ3rsJpJyw=,tag:LE6Ff2wnHot4QJKXaNnXIA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbWlrVFRQeFJ1TUVGNDF6
        UGhwVmRTdmc1ZEFBNVJkSjRheEhqUi81QVVzCkU0UHYwaXdpQkJCNENLdHVpVHNV
        b05HQS9JSFVQbUNkOWFRWmhNNFptbHcKLS0tIEJFQmdQV3VXL1F0MzJHSUlsbmlW
        emV2OXRBWXA4V29HUkI5VlhYVlZhZncK0O4Q4I4oJYYJgSNPsEtdB4ubXsdfvE4D
        8TYUoNzWU4Et35sRtgJtpW1KlPf1e1XXqtJkp3Q78Y6t2WY5GUUhkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T22:47:33Z"
  mac: ENC[AES256_GCM,data:OD3Bxqh+WIvt3fePJay7hlx809nNN0w27QK4n6ftfu6GGmpdwlf2OJ1RJvthxY8/RZLA39ymrWx4ihqIyaYozTpuNySMFuBVk0uRkXwo/71do1nB4bm9xSiQeOFnz111pk8ssv5zr/7Wwk3Tsx/4cL3SvQNvX3jsRtrggrME+Mk=,iv:nSziEpnu8e2O6K4MUglWnmhF1YsudsAOB5u4G4YjFbg=,tag:m2Km6Y8W9HDejkgbHvL11g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
