apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
  namespace: networking
stringData:
  email: ENC[AES256_GCM,data:R1XqoZekoi+2CMFhZqPDfg4TLu8ur8jjPy2ZzA==,iv:u8EXl0UELofS2+XIxtBhfqjVyiH7YwxMM39uH1Bn09g=,tag:wXiTpdxoDnftxz2TurWf4w==,type:str]
  api-token: ENC[AES256_GCM,data:W+ksx5h4bdNVT8MVCLf3q+GJvZTVdB5XFZzeLOX77TQf/Lm2WggDsg==,iv:v217j/uOcYI1C29LnYx69z3XXeQSOfrQp+V8Cfqr1ic=,tag:AGWBgjdPlt0oWsHgZXVyow==,type:str]
  api-key: ENC[AES256_GCM,data:ClOwa1TcG1LBO7s5bscLFIkCcpLciDAb1nZRIc1g1s0Ts8FBqw==,iv:lkoRv0A68iZsiZ9D4/Jvh6GsF0tk4jNWqx7rrb8Fws0=,tag:zS852YPwH+MfRK8ni8LxWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaFRDL1ZIM2pJb2l0UUpy
        YkxPbEhnOEVVMVpTalFHZUFEcjM5TGozVWtZCnluWjdSSEtsOVh1YlZQZVlKYmNz
        QTlxenhJTmJaVHNPOGRLMWt6SmhVWlUKLS0tIGhHNFVyZEtZRmxUZk56NDYwcXEz
        R3NkbXYzdTExbHdHeWlkNjNPaHpJOUEKAiIyGSAA87RnwqfWz/5pffXriRfiUePM
        IG3B3sFfDckFhQnjuytEUkzPtsdEMR6G0gj/82Fg0hi4lUZ41btm2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T23:39:23Z"
  mac: ENC[AES256_GCM,data:ncuQwADGBmJQ4NIrohT3ms2XI0DW1EDRNqkr7Ig73dLGlgf49dLTTjW7+woRRpUb/VHF2COursuY2r1IzkKePqfYmy05jLQ+NJN1oHFu/DltZ5vKSIGMCP9pk1+yMTncn+s0cy+KDsIU/MJY3WUX9X3sxfxwoBwbpai3T135t6c=,iv:jraHwoCEiBVyPsJ5Zz9RIhHh+cD0NkjvDFW2JhF7USQ=,tag:JK5Fqyu7p2vXJ+l33HJqUQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
