# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.155:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.155"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-3"
    ipAddress: "192.168.0.122"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/gasket-driver # Coral TPU
            - siderolabs/i915 # Intel iGPU
            - siderolabs/intel-ucode # Intel iGPU
            - siderolabs/mei # Intel iGPU
            - siderolabs/nfsrahead # NFS Performance
            - siderolabs/thunderbolt # Thunderbolt NICs
    talosImageURL: factory.talos.dev/installer/f16b35938c5dc3de653a41ab2db6b1f9a60f9af1a86bc3af4fbcde57530a5683
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "94:c6:91:1b:f6:3d"
        dhcp: false
        addresses:
          - "192.168.0.122/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.0.155"
  - hostname: "k8s-4"
    ipAddress: "192.168.0.123"
    installDiskSelector:
      serial: "193423D5BED4"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/gasket-driver # Coral TPU
            - siderolabs/i915 # Intel iGPU
            - siderolabs/intel-ucode # Intel iGPU
            - siderolabs/mei # Intel iGPU
            - siderolabs/nfsrahead # NFS Performance
            - siderolabs/thunderbolt # Thunderbolt NICs
    talosImageURL: factory.talos.dev/installer/f16b35938c5dc3de653a41ab2db6b1f9a60f9af1a86bc3af4fbcde57530a5683
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "30:bf:00:62:90:95"
        dhcp: false
        addresses:
          - "192.168.0.123/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.0.155"
  - hostname: "k8s-5"
    ipAddress: "192.168.0.124"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/gasket-driver # Coral TPU
            - siderolabs/i915 # Intel iGPU
            - siderolabs/intel-ucode # Intel iGPU
            - siderolabs/mei # Intel iGPU
            - siderolabs/nfsrahead # NFS Performance
            - siderolabs/thunderbolt # Thunderbolt NICs
    talosImageURL: factory.talos.dev/installer/f16b35938c5dc3de653a41ab2db6b1f9a60f9af1a86bc3af4fbcde57530a5683
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c0:3f:d5:64:95:ae"
        dhcp: false
        addresses:
          - "192.168.0.124/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
        vip:
          ip: "192.168.0.155"
  - hostname: "k8s-0"
    ipAddress: "192.168.0.119"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/gasket-driver # Coral TPU
            - siderolabs/i915 # Intel iGPU
            - siderolabs/intel-ucode # Intel iGPU
            - siderolabs/mei # Intel iGPU
            - siderolabs/nfsrahead # NFS Performance
            - siderolabs/thunderbolt # Thunderbolt NICs
    talosImageURL: factory.talos.dev/installer/f16b35938c5dc3de653a41ab2db6b1f9a60f9af1a86bc3af4fbcde57530a5683
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "94:c6:91:10:d1:2e"
        dhcp: false
        addresses:
          - "192.168.0.119/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
  - hostname: "k8s-1"
    ipAddress: "192.168.0.120"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/gasket-driver # Coral TPU
            - siderolabs/i915 # Intel iGPU
            - siderolabs/intel-ucode # Intel iGPU
            - siderolabs/mei # Intel iGPU
            - siderolabs/nfsrahead # NFS Performance
            - siderolabs/thunderbolt # Thunderbolt NICs
    talosImageURL: factory.talos.dev/installer/f16b35938c5dc3de653a41ab2db6b1f9a60f9af1a86bc3af4fbcde57530a5683
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "68:1d:ef:29:89:29"
        dhcp: false
        addresses:
          - "192.168.0.120/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500
  - hostname: "k8s-2"
    ipAddress: "192.168.0.121"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU & Intel iGPU
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU & Intel iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/gasket-driver # Coral TPU
            - siderolabs/i915 # Intel iGPU
            - siderolabs/intel-ucode # Intel iGPU
            - siderolabs/mei # Intel iGPU
            - siderolabs/nfsrahead # NFS Performance
            - siderolabs/thunderbolt # Thunderbolt NICs
    talosImageURL: factory.talos.dev/installer/f16b35938c5dc3de653a41ab2db6b1f9a60f9af1a86bc3af4fbcde57530a5683
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "94:c6:91:12:ac:c1"
        dhcp: false
        addresses:
          - "192.168.0.121/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
    - "@./patches/controller/cluster.yaml"

