---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
  - ./grafanadashboard.yaml
  - ./httproute.yaml
  - ./authentication.yaml
  - ./scrapeconfigs
generatorOptions:
  disableNameSuffixHash: true
