---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 16.3.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/postgresql
      tag: 17.2.0@sha256:cf63048c92092385585b1ca8237f47d565c08c7b48693f47a6e8013d3c98f361
    volumePermissions:
      enabled: false
    auth:
      postgresPassword: ${SECRET_GRAFANA_ADMIN_PASSWORD}
      database: "main"
    primary:
      persistence:
        enabled: true
        existingClaim: storage
        subPath: postgresql-17
      containerSecurityContext:
        enabled: true
        runAsUser: ${PUID}
        runAsNonRoot: true
      podSecurityContext:
        enabled: true
        fsGroup: ${PGID}
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
