---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 16.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/postgresql
      tag: 16.4.0@sha256:b6a35d50efe5f328e0944a32972e73cbb3196612cb633ee62b504edfe64cd323
    volumePermissions:
      enabled: false
    auth:
      postgresPassword: ${SECRET_GRAFANA_ADMIN_PASSWORD}
      database: "main"
    primary:
      persistence:
        enabled: true
        existingClaim: storage
        subPath: postgresql
      containerSecurityContext:
        enabled: true
        runAsUser: ${PUID}
        runAsNonRoot: true
      podSecurityContext:
        enabled: true
        fsGroup: ${PGID}
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
