---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app searxng
  namespace: flux-system
spec:
  components:
    - ../../../../components/ext-auth
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/searxng/app
  targetNamespace: default
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  dependsOn:
    - name: dragonfly-cluster
      namespace: storage
    - name: authelia
      namespace: identity
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: searxng
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: searxng
      namespace: default
