apiVersion: v1
kind: Secret
metadata:
  name: cluster-n8n-secrets
  namespace: devtools
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:YYTRJvlSStNoW/cp4RaO4YOulKhnOShSd/Q=,iv:abEvgODzZO2ZXrwYf/erI0u8KCkbvH1EcisKFWMNuwM=,tag:U8WRDxIZCXHYPKw5LsXbUg==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:LRZL,iv:JX70dPt/cPN5q+YN/z09pChYRaANvXesHBV651KXKgE=,tag:tNonvL84/YteIjuJ7+CHAQ==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:c65/ZLpWSfjzSb1ChkHS7G/X8m3Q41MyIjg=,iv:DebufHu1AJhpwAU/MTWmPK8aeg9XdbMPMWLPPDMSzL8=,tag:yU650yEcefmSBtVUAT72cg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU1FiQ0pUTllSajI2aE5W
        Q1dyNU9na3lreUd1UVZDb1Q1MUIrbVlwUnpFClZMbDdHRkF0a1hvb1NYcjQ5UVU2
        aEVoeXdMb2JkVHIrOVFZeHowaFpQc0EKLS0tIDdPVXlkWGdUQnBrSFROZ29BaEgz
        MVNDUEQrMTdyS1lubktUVVB0WFpwM1kKqqLpIRSiwJ3R5ZL3nTWnSbHxhYR0bLC3
        LR9KKaHF5Y3lVnVVq6f4Z3g0s+B2doGO0X2Ks97SfpIqDoNz6Hz29A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:2eXS6eptPR/Jq+7Z5LJZO9KB/1HsUKio8eAfEPdAaGrJ4YdgwAhPUSQUmLj32QJ7OojOITXoMoPRnA1JNY0/P+p7ig6q3C/jnJQ9wE8//swsGf+u8Qcwpf0NJijszRLZ9GKoRdgoKf5mM3DZlk4DMMXfHQNsZQQU/qyEoJAiQYY=,iv:ZpLnDKR7ngJYoV5+EbLi853t1KJJHaMDKtmgxzC1Gyo=,tag:YRfpbVWoTklZyf4LaPGl7g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
