apiVersion: v1
kind: Secret
metadata:
  name: cluster-n8n-secrets
  namespace: devtools
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:lJnIgZRemMKfbPIyzUGh5f6vnrSRb6OfqEY=,iv:+i09MPzMWGVr9+SsMik6Ju9FBGrAxRtzH+Op5/HUhOw=,tag:NgwBlkCPL8aKxigXec2OpA==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:XQUO,iv:MBqf1yleTy1j27wQdeqVtSYDFVRwq78bXIjkY/uUzFc=,tag:ZZyvDvb6fS3FfzhcUUp/LQ==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:pcoFiLnnecOjbv47UnuSc+djbjE6krm/3D4=,iv:E8zZIOwYBfvsHd5i+IgilOnbwqnbLRwKbbSaDeV0dnI=,tag:8S9B1NhFIp9lq0PUNqHq3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNE56bmRlbjd4akRCYnkz
        MjdNQjhwS1hmWVZqeDJ2NWZ3MUxYaEdmeFFRCnpkWEIxUTZ4TVZ1YU94bHFXWldE
        TEgyUlFKVWM1bWJXV0JqZGNjVFNIYW8KLS0tIFVJd2g3aURtZEJyTXkzUG4yWXZS
        aHl5SUhZbjJEZ09Hd2R3ZmJtZjhLMGMK2G+7vuN7YPcA5lwI+iKEjLGBuDLEqJi/
        qenW7eaZeUfgyKHLy2Sb/o6g3W0z8BQsvwyVro7GvzsVZ+jUsoON4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T16:53:42Z"
  mac: ENC[AES256_GCM,data:HzKxjTWrxVxFsFSKvSrZitd8jjipSbYBWZ/KDZyt/pEX1f36L27M7HB1A+svMUZTUlQCe7dH8wm3wZmOShgPFkPuIZpDWD5ZRmjFhZLVc8FlKIrKgv6JYbOBodbp1RxU0y0uc3YC1vToErrAogNOJORD23NEi+8o3QT0drGb/iU=,iv:y3i16/mKIY4wy/VdEH8Ec7CzZR84D5LIOXsc0Q4nK14=,tag:4Sq3ZNhNiH5AYZYky+wMNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
