apiVersion: v1
kind: Secret
metadata:
  name: cluster-n8n-secrets
  namespace: devtools
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:gdciFpQLsMtHKnQishsu800RCBU5ZLxU16Q=,iv:EiNDP1xl50QsifQn7FaNMnC7VSqeOa1FwRJajc3cH9s=,tag:WDnQ8I/QuczeBBdRarnEzw==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:1BY5,iv:zikmKQqWDNkTfWlZukkjxlbcxZ9iCJrFNghgtLbkqe8=,tag:5SpqyTJc571sCKgWrM7qZA==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:q5WLviNv4jpV+pyKUwSQjDfVslUQVnWsCaU=,iv:F1oXTI2xHWcCK3blpKmHXpQByrS9NrplY4H8fEv2Q/k=,tag:EuY3WVW9yPGC0UccDH9d8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcGpVc3IrQWNwZ1RtOHdi
        Ukp4NmI1MTlLWHB1dWUxWnhhM2JSemxGaFRzCkNIa2RyVG5Jd2JMaXpRZzJISnBW
        RzEyNXVHdUhyb29Ld0RWWUo0TXNxQ2cKLS0tIGl6TEc4dTdQQ2NkRm53aVhJVlNW
        b3VLcU5LWUtRcWhKY2Z4WktCUUh6OEkKw7h9QJDN93HuI5OLOz30EtAOtfy9gQdu
        mGZW825BKc8N/t1L8dCgMe/68sLvRH58fHdiVdYlQ4CDrPt/NecAjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:17:20Z"
  mac: ENC[AES256_GCM,data:aBIiCtZOQ9GifJ2INQrM67RG1U6LgLxT1BQSZJmUb4SlpmuMDkb+YTMx0waVtMFqLnUJn2p4CzabeDtdqil4BqEp49ZXM6H283UZrbaOrXhDcoLpVpwqvSNuaN+Ji6U2baYTWOljfBi2wFCh8Dfmn+iplvJHkuwH+b95Di8Xor0=,iv:R8lRsyvWc7sdE2+megM/G+UwWBILm2XlL1kwfXMhPyk=,tag:6mWxvLC1n90Lp+83No1hsw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
