---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basicauth
  namespace: networking
spec:
  basicAuth:
    secret: "cluster-secrets-generic"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: basicauth-route
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Path(`/`)
      middlewares:   
        - name: basicauth
          namespace: networking
