apiVersion: v1
kind: Secret
metadata:
  name: cluster-open-webui-secrets
  namespace: default
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:oDnIh4gVdY7tuyjj8FnynSkBf3S2E839eqOchP+k1EjDwjY4ESAe9IZ1J0Eoh9pQ0bDNL6vdhgbusnAqyoe7rcgDXUoT5HIaqFTWJde9jNBA7sWzN9RMlUqYXjyagGcrbbFRB5znf/Y4wIjoeHm00AgajRk1VjFPFrJR4cd1RResBunvOoRa1fA+aMj6Og==,iv:Qfi898KJl9jgTFcSlqI+F4uT8O8Xhqlywnun4Q/iMgQ=,tag:7LRoLa+gFDw/ocLt//3e5w==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:sdSiWOfxGoEbY0ur4xY9a0cSVb71P3YlSoPaPFlRvzs90mKNV96ihEhxGW596FmNEUMua7io0bJDkpstA55x6w==,iv:Qbp0ePoBeA8sqj930pX+6WdnFOIVYCdQijxiJCUfJOc=,tag:HVfzUJ4iK4Pcj1AyKehiKA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:lGdu9BPEb8P6pvYvgEKh/X99Tu/K14NlRnBJVN2tVjm4SIS6frytQKFWELXmq1hsmfQh4oYKYEl3iwQSlS4yww==,iv:gqSOZRzxEH6vCYF1paUgwlwg0w9yFA8e+/tfEXmRxF0=,tag:vrvNyI82x6YUUEzd2EtD9g==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:8QsvvNLwvEeZmA==,iv:LkxeMApNP0hkKvEB0Ee8PAdFZ/7AtahUFCS3cKHAW/Y=,tag:dMkeW5eZMKIrdzLWok/BKA==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:ZDHZM9/BXjgGKRTWHj1RYN12fwQpP9ht9asSPa4GSwRgqCzKFx+icYpMW6We7aWVopYUJCC3GTK5mscWEnMeSw==,iv:W6RZ5Zc2lyj7ys9SCNDVsKp3cN6PSi6bxCz97tOOVDk=,tag:qGY3bkYvQORhy9eV5kpzwg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMVBRVEJ4Wi9FZ052anZE
        Q1NQYlFRUmJ0Q0lNbFQ2djlwbE9lYW9IMmlBCnRlaHdUYmVkRk5BZnNLbEkwVEha
        NFpaK1NvTm9OZDAvem8yYUN1ZnVNWjAKLS0tIFpVaUN3VTlaRjRPUk9lbWZwQm40
        RzJmMXVRdklpVTBJUW9mSjFKZGdHZ1EKpO70krvdeP8DwdKR5BwFTOE4zl3K+yPg
        JOrgmpzHccpRycE+kdp2J6aLbDByQe0QbE8JDWXGnjjg+5cxd3Ah2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T21:54:21Z"
  mac: ENC[AES256_GCM,data:tjAAPTw/XP/r2oKy/IIleZrhclDBmChV91ZRv/7+EQJbJlia/Qgaoir2niz+Wg40Rnxhr2192+/e3yd5Ccz6Rs8PP+Jp5AKifieBrdr/CgvWlrSY996Fg6LAfK0PPS3Ge7Bw5NaleQ0MrZm2LD7Zc8lPkP/+XphhMCfx9qgN+5E=,iv:gdiWOrVTDKWWKxzT5MsjIOxZDhU4oZfhHF2VvyJcRfM=,tag:qDY6zLYV60cmXdof1let4Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
