apiVersion: v1
kind: Secret
metadata:
  name: cluster-open-webui-secrets
  namespace: default
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:N2URqqqQwwyvQ3ujeC+Ap14RizGmL8ewWUycjCh/FVPqQAohcl2kVKEvruViM1bsMtRCv1yMqNHKqIS01UQQNSIxng/Pc3YwMUBCGz6k5MfolN0u5PGH3q6dbmDQG8KOnTyVW56MpO8d2Z6eqBfe1rSHM5WPTR6A2nbK6EYtsOddrfWF1OeRo7Ll62o7ng==,iv:ZwGiho0kqM6EGHl9GHtcyNF76sZBqSwE8z8zI9WCgxI=,tag:uA2igWpBiUog+RReN8z+QA==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XClrRU8SLCVXo9a/AbmjHu1M7Tr4LU9xpexW7ySUB1j4bVUFRwgIZ9DVu0ZtUomhOGq3FMARZbMpfCn3GPqI5Q==,iv:8GHJPwDwlLrKe1kzDodoxYN8yNGSstHdl6wTtTTrgac=,tag:Qy4UElTDUfJJp5JiyKfpJw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:dxbxQ1fxtm4nal1oIsPKgZr/e9hnGTaXakoCqTcBnC38e7PUFwZgfvjWNOGpTvwFqmqmmdqqKqhO2N3D+lK/SA==,iv:ANiZxenIJEzVFqX7qGgOyG7aZirSK9fwsZcv3ssPaYQ=,tag:drG9kmip8O6jAMaKA11v1Q==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:hJGvGDYkSr28Uw==,iv:A6HejsYEtIyvRbhgmKejS8epfI6+s3ladYW+/M9q2DQ=,tag:Hn0vKn4gXp/IDVY6ZMvOJQ==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:a+zS5A52gXKJFyx3w2SG+qRLOQUPmkYUap0dubEnDlwHDAO+hptZvhZUCmnFGR556+OqS99PJnU5mJ2RAJ2RRg==,iv:npGw3X4SIcYTLJ0rg2Oj0qZAzTKUSG8M6L+mP1GDW9w=,tag:qNN+S4kK9n0noS/yNw9M9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL2xkYnA4ZFVLcERZci9i
        cUlaTTZCQjZ3alVkdHA4MFZzREU2K2R4eEE4CkZkTjlLS2hmdEh6QldqcXczdHg1
        T01kdGRqWXJ0MUZJZ0lnbXhhUVRidm8KLS0tIEZQRWpxQkRIelFxcHVpVGNyWWxZ
        QUpwSXg0eXEzUUtMYWd3Q0IyNWJvTFEKRyNoXjTMmzRK4jHAtKOfXjAKb5iI6+dK
        +zop5UeSpHwdWMppJ8Tx7oZcser78dQGTzZWZ5hVZzYu43SrYOh5xQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-16T15:59:10Z"
  mac: ENC[AES256_GCM,data:1p/b0EO1Fx2ewM1e8BxhDuAsIgPKIJQ6rR14mm2NHc2LaIeYzxx3Fqvr5oho0iE9Nxhg9dL3xBSlBkfrgLUj9mac1Ll7P2FWnN2hrwmxn2q3AR+L4sYa/EL5W3T2z0XSo3UhKDbRKQWcb+JJQjzpSZAzblJdtLaj62wKifsXsvE=,iv:MkeOljDDjXHB/EIUL0534iDGBQUWBtPwExsb92gEi+0=,tag:xSEt1Ky66SsW3DHRLMWIRw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
