apiVersion: v1
kind: Secret
metadata:
    name: cluster-open-webui-secrets
    namespace: default
stringData:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lWyEZQMYORVwR20BrmSCw2BlfSB+XPZnRaml6vOPLPEXVCaQoKL7L+BoyO3vAEX1hcN5VoxQYFwL8VlyV3cQ/Q==,iv:nQBx1rqFFxC5xK9YxUxnlwvpNcpNFtsfY6Xiak/gD8c=,tag:RHP5OXivQj7QB4BjLX5kNg==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:2QZmw00nk5j6LhvcoazTKKH8DpO5awqVFCR0mI7uR/NTv8VaVvkeMKYzjYOsuPW/SPoLPIMD+9ENrW5SDQZy2A==,iv:n0+9mycnhUuTZmKVaBBWUkPdWDT/WP1YBeJjK4pcFl0=,tag:GvoUjBkyrTGuFf4FpdwwzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWERJOFdTNlBvdm1Nc2xl
            a1J0clJ1ZExWSml0TEZVQUxKVC94OGlwenlrClhmVTNobndQOGovclBIVGhlRVpU
            NWtETFE1SlJla0k4SGhPdXF5dzdoQmsKLS0tIDRNcTZRSzFjZStmcHY5R3BSMjR3
            SW5XcVhreGFlUmdVT2preThjcVVYWjAKtdI/ZE3Adje0znptGC7DwgdfgEObbVe5
            WDcoBbLt0Z7+dx3AItc21wHMs9dx8FIm0XP7rYvelDHQerezv0C3OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T14:38:05Z"
    mac: ENC[AES256_GCM,data:w/eE7sqoccN68wS2uRHnnrM2QBZ9fQLY1FlEoExxJSFGUREbuZuObSHhsL5JeVbb1X4UzCF4jPBbhjiu/xVZdLZwMwgm9o/6MLtqTe/eX2V0Nfb5xCWSbLzcd9bD+ctN54w2K9WQWs+LUdq/WL80nGrOeJNbVXTXRIlQIgXJQg0=,iv:oa0rKzR/357PSnIuB4UYZwQS8N6it2Dtn8SlGyyFG74=,tag:3exao/lGyuEillOHcM3FZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
