---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devtools
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: vscode-defaults
    files:
      - ./config/extensions.txt
      - ./config/settings.json
  - name: vscode-dotfiles-init
    files:
      - ./config/init-dotfiles.py
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
