apiVersion: v1
kind: Secret
metadata:
  name: cluster-memos-secrets
  namespace: default
stringData:
  MEMOS_DSN: ENC[AES256_GCM,data:dyNngPstYxA5tpWO1F7wUdBlzN/advpykZ4wgAHksRLaI40tCpXDdt/dX32B2PEZzmUDKZ6gnOAzpJejoPDKEw14uSZ4/oEND5l27vjXQjVWIhLoXrl/Dx2xHQ==,iv:0zo4DelcDP1m6cWe9PU4zNOHIxz0fjeb3FO5tZSQ67c=,tag:kM7V5TLkRqg9OjUWBxnS8Q==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:nzl3HWA=,iv:9126pLjNMsDGJ+iPkL9Sofk2yq/v6C+xjHlqRcEvIDg=,tag:EKEemJkTYsKh7WGPVnAIiw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:tON3l5VYfJyJZ2r2TSdZRd/0IMKF6LNhBg==,iv:+/GBfS+k93K/oMvvPi8njb9yCfV/89PP1upPhi66skM=,tag:ApkGqjcZZK71RMZckt+rqw==,type:str]
  MEMOS_S3_ACCESS_KEY: ENC[AES256_GCM,data:hYKZrIr2pCavx++PySWBwZq6FS4=,iv:Wp1ddjJChzOECgWzvx+2Za/XFaysX8rUFXQuXV+b7xI=,tag:G5rJ7YIso9GXf7vW/JmVnw==,type:str]
  MEMOS_S3_SECRET_KEY: ENC[AES256_GCM,data:T8CZZVvge5a0RKQ4ahLBL4+MdktR2to1LqiBZ8aa3qGywBYjsgNAZA==,iv:YXbaqO5vivKmEA3K029AV+/3gZ5mktJn4RHPEL5sbug=,tag:Hz6niU+dMJu08qXpHj8nhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TmcveW1EaFB5N3Rnb3lP
        UENSVFlMQTBEREk5VFZNMU9vZ0pGVWg2dDFBClFZWlhVbS94QWlIUWdmU0RLWkR5
        cmhibkNhdDJPM1U1L0RQSUVsVWFOQ28KLS0tIGk2bnRKZWgxcDhNekk3eHBDM25M
        TXI4YndpMTJjb3NwVUJlNkhYY2tNSXMKkJMhohh9I+F6WsYLDlxi5cBryGgZ3UuG
        JyD3UGwrQ3dx2Dc3tcbQ7e4/zcrly5IEqJ9KauS5Gc7QM94puG8XJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T12:49:05Z"
  mac: ENC[AES256_GCM,data:uWBPAd2uMnL/MaImBB0a4RKTII9uM4fef85PkprNUN5di6/R1AOqo8L9FJFGepW0awLbYAHxKQ0mHbvCPzW/Lz5//9tpyGGHcl/XVs3P03FVDuaLXoPeBajIt0WFo/Oc3nHGkZUgwWTA6OduE9A0w0w3JcWQSBjA1uxz8LbrTSA=,iv:ygmRtifE2ySCFmCJXvqRqS4OmN23HDwi6NblH6opTKI=,tag:JxawuDCtzuiq+pASiNYTlw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
