apiVersion: v1
kind: Secret
metadata:
  name: cluster-memos-secrets
  namespace: default
stringData:
  MEMOS_DSN: ENC[AES256_GCM,data:KlvxUHGfy/iBw4hkXdDlvDF/1PZkkT19cKNPCgRivDs4Xp7y09NiNCwApjZA8PYEL1QTH+mEl8FJpImZpgmmSWg+38y+XLnD1hIWycMr0ZVQV+VyonxKZ+E0Fg==,iv:2DeUBVlvo/wDF85mDVZNIqUxVCHXWG9ZdI/VXzwQn2A=,tag:xgnZ7szGlScZk1dLPximlQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:WvPTF6A=,iv:SYcKD4TCjExGZrXnuYL9nUScmHH2A2hNR91K2h5uXwI=,tag:WU0jrV/aGo3kOds3PUwXgQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:ryC4kLbkBEjMgfA8dnUf7PpB6L6L8xRmhQ==,iv:ReefypYET52yLcOrUFC6rY+h6zyGJUx5ahTqWDmRV/0=,tag:kOpOv0u8QqNqC5IE8LlIJg==,type:str]
  MEMOS_S3_ACCESS_KEY: ENC[AES256_GCM,data:ZcQvsAxR9Gs9b3948c4v44TcXco=,iv:tIQJyF94Q/IVUzCkQN6pI5z2bK8qchucjwija57PUyc=,tag:JNhbWasLeB9WpwC9P/6/PA==,type:str]
  MEMOS_S3_SECRET_KEY: ENC[AES256_GCM,data:nNIv+dvk3pAW+4CZA7YffofxADiHViBzEuqayYxmGDV55D/USdyLmg==,iv:CTntCAYqqRDFeINu/uQ1XhAG1ajTAsSDyNtt8oD6oGs=,tag:c4rfZZrQ8g6mfWhsOVcaxQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQXl1VWRuNVRpQmxTUFRh
        V1VJdFZWWmhIZE9WWTZRMzYyak4wZnREaTBFClhKRStEa05DaDBQeEw5M213dE9o
        OVk3bTEyZHBYcWlnOHRnTUU2aTFpWnMKLS0tIGJyaGc0Rkdldktucm91UGZLTERj
        ZGxlRmlHMldGTWxBWVFhVzFnclY2TUUKv5Ip2ZiVaRzwC1gghk6dT/jGanaF5YiU
        8ELhdF3rmft/i1N21qeSAxHEUPzPIGYy9WVcf17fh+btwoanaMViyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:24:51Z"
  mac: ENC[AES256_GCM,data:HdKQb3oWlM6JDEy89SGZL0Gy1COD1Ac0zMtYCUGuCe5tov7qiUKLxMYCWckpFqPGtN7EPDZsio2A9/0cEJV7YauAI6PKBHAE5ejDRYoWpFcxXNw0wJPVtrxZzE0/YUSUoCwlfUR409XQhsW5HeftTLAPTszWkjwqaZaSH01lKnE=,iv:lyP++eaTH6zMtICP1BMjJQLvZHupqxlfjWAkszqeyVY=,tag:sBdWVmg+fimhWnaOg6n/cA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
