apiVersion: v1
kind: Secret
metadata:
  name: cluster-memos-secrets
  namespace: default
stringData:
  MEMOS_DSN: ENC[AES256_GCM,data:24ZOpNN1n4xIbZTxq1nNR4kBKCHHNCfMeEC1ADdZLZHoze/YEK/b3nY0nZQEn96/M/Q7OC4lGOknGqyiJrQkhNWA5fGf8ap+m6wLl7iGmVWnwFXscOikxT9ddg==,iv:tJvrFtUpxQCHfyevcMwaESpYJhkxBWYxNmO+Vii3oCQ=,tag:kOBUIsR4diGAQsoGoJDGeg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:FcIgAnU=,iv:3eLHAD0l4BjHfLfxN+h+8PP76yshtJiZGNYCfKDsjSs=,tag:0gDx7dDLfj/NzmHHLnaA1w==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:hGs/9e1HhMdwpbl7WUjRXsL7A//VSpZJuw==,iv:v451IZgqt5VF9eKfd4EI81meyIkewMow7m21KfJ2e24=,tag:oQoyMQr3/lfc3Nbce/Z1MQ==,type:str]
  MEMOS_S3_ACCESS_KEY: ENC[AES256_GCM,data:Yq9VmLqipiaM8VolM5e8XpodHcc=,iv:wcoI3q6FERD35dEBiM2EKpeKHAiSF/6LkKnPr2Cjk5Y=,tag:ePr9fBPZ/z3SICwnjoXcaA==,type:str]
  MEMOS_S3_SECRET_KEY: ENC[AES256_GCM,data:90Jm/zjBHfbIzgmBphg+JzdHScWXjFAYJzVMF3OKlvpc3jJB9NEMxA==,iv:0lHyx8ysjgDcIY2L11gwc5HLVKmspMK/5vbKBF5rjWA=,tag:x7J71lGTQ4B02Rd/Jm44nQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV09kMXR4YS91M2ZyMUtF
        bHBtaWdwL0lDQVJUdWl1Y2I4aUlWNFM3ZjB3CmFKeWpEYXloNTY0RXg2cDltK0hG
        bHRjVXVhc0RGSTdHWTM2cWlaMFhzMFkKLS0tIG0yY0xXTjNFdHd6ZG9YT01VT1Fp
        eDVHa0JXUlBIb2xzR2VMNkhlNXlpZTAKe9xfY9e1T8ny+uP60cOduOiPz/8M63tU
        38mBczgEXN9Pw+EVo2QauBz0WUrWEolHMsuSCHujPrvBWH9rKypBjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:42:48Z"
  mac: ENC[AES256_GCM,data:US6gVrNM1wUrjOHmR38/6PD+f2SG3PtVqaf1obwyb5nKCCs2gzl1OvK5Ro1nvB4TGhRejx/ZtUYQowH2FVvHfmAVE6QLHOKvVu3sVvVx3drE/mHd86rFIoz7Mw9a6uSpbJwCTViREMfLimXMOdgJU/nFeYHt3rVzZQohjfIIf5I=,iv:yW6ssHr9YzrsPsUmSEWnbdshoKQK6r3flsm2Gek9Am4=,tag:Kon1AklRxAZ4a4nahjb0tQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
