apiVersion: v1
kind: Secret
metadata:
  name: cluster-paperless-secrets
  namespace: default
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:6gV3qtTo2EmRF60=,iv:B3SfKErDnPUc+PMXJ9gXcxC2fS7BmKKCn1vsDoPZ70s=,tag:NSSapvUXlSV7q8GN3WGkKg==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:MpBCnHvnOS5S5f1inJ/Ucw==,iv:YyuLtkiRJgIYHe0rixUDOcdFJB9Pjfrq+MklpS7dO98=,tag:mxGj3WEBfwLReGGAPCgl6w==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:X/fakJLXeKtsth6o0baCurUlLp9yimK57w==,iv:7KDC1p25devY4xCmt2wG9YsOpOLKkwpm7uFtRJSBg/A=,tag:4QruF2FrEiAuo8MStv9HXw==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:QXG9dMxwzD0GAuQBlV/Ilcp97eO1iMRD3QG4shk4f09IGWtySJd+bqNBgr09+mE81diRSYKSc2yqVAgjWEx63jaYO8EUdKaaBvpQEK0BnGga3BxH5QA1I06TSiUod73IJ5wx4Vl5DzfirhApik16gfcDyMq5bhZXrGY61XaiiS/oQWMbbJ4dNJKriWf9F3+a8fYWbz/i9fWK2Su6mpDIQLq5rWRxlFZm6rV8y9u11KjIM59y4jDyIyTAxTC0ML99cNYw3pbA61+2OK8AXsuXp+ma+9d12JF7TL8VpobisePANqji465eJZSFD/XlxABeG8airOtj0H9iPhgMBojrEsM68kDdJrdFmZWGT1OIGoXGrHjZn1If+fFxA/a1m29Ym8mrnLoluHQKRQU+L91Mu/Fv9hQWtbk4BQw=,iv:mooihnGsoc5D6W+LtZn0fFh7gcg8k+iysP7iH1gfHFE=,tag:xz+NALrdezr6d4esJgqbTg==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:dxF3GolvhTJ7,iv:QjAxWcFqbU6i/o0dPxdmQYbbKEUEATElcP7erIiBLwQ=,tag:T6mOZJDy0YnSXsqfB//utA==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:livaphFpmD+CQwmDTsE=,iv:ENhm12yKqJPmb3BRU5+TSjR1ekUbRNHUCKjs26Q5o2k=,tag:maN4zNzxkpflktFWu8VUew==,type:str]
  PAPERLESS_DBSSLMODE: ENC[AES256_GCM,data:knjmSJpo1w==,iv:NHq0QpyUfqBfj8M8dQdTZqpNheRzG/Xsc4Rd3OKpijU=,tag:zwANyxLM+iIAOWkTdJz9zQ==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SlQrU0hWRzBvOGxmSktO
        eXNIbXJmY1I1RHBOQTZxa3NHZjd5VjdZbEVvCkVWbVRRdDQrWkszOHpLM1pLRmFq
        eDVvbUdZbDhpaDBWcHF0Y0RsNHl1MTQKLS0tIFdmcnl4RzNLbHUzNW1MMC9yODRL
        cTZ1aEFwS1V4QmRZUndMWE1jdkVuYTgKyRd6oG5RbCoDjluAViEatWQWlWsS66L3
        WdUriXsDEf5SM+PY46CTjX80EKkMPAxEV/yEbh4tl5/fBK5lPbbLhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T13:04:59Z"
  mac: ENC[AES256_GCM,data:X019gLFvHibNSX2x3ezfIt7TB8rx3JY7yaRMcUt/A0ljAIz9sOB6gQ86vDQvEl6yb5vEmUJ4XleV+EINL7BIIE5cem5QdieDuvX03h/cjvuCh/Pnl6RiqqJzAAAkI7g1QCviizgKXHAJD+YEVXUv7u8x22+f6rMDc7sQqHCceCs=,iv:ySKX0GYdEV1xLHr5RWzUxrXgBK3HUuN0FYoiHYjUfsk=,tag:QRt3Z6q76bgrXaQsYeFt4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
