apiVersion: v1
kind: Secret
metadata:
  name: cluster-paperless-secrets
  namespace: default
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:vqbmminHFRPFhZA=,iv:uHbcDuciVBvqYZBmBuv5eLORuT3nacVZarSzkCms5rI=,tag:rKxtZYZFmMq/DnhIGZmkzw==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:bIRqknnKi8rcJq/f7uZPvg==,iv:bU6ZbhZd4vApqiEkixEtyAYOepRRx4B0jhMTIQmhI8M=,tag:MG+DwpCuRRk7Zmww4F+j1Q==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:8a8R76ivSnhO0sz78cQzG5ClPK/T1E2g2w==,iv:b9Dp3wnY4eUdlzAU14CGT5jycvbx8+6Gd+D/WKlXnVM=,tag:vS7Mc5Dis8Y9nik4LEqsIQ==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:zvq25x0r+RsAjjPBItLe88aTTZqa4WYIolbuP9JDSCQuDEJnfX066xhHEYK6CrhZ6enPkRDYZx0AV+DXp/cRt9U3Eo8uh2+G6b7uQRRnHLuTkhG6J0y7a9RuQl/UB6nlAwh65qUDXQkjFUBeXbejws0wl1gxCqnUrOOc/liVXoklllt8j7D96MFfob+qIgKdm6BvVo66GbX9aOEaMUVl98oq0g2ZmaemFA6RdDWQJhlvGLtK+aI+HA9d5KKI/QeSjgiLSnx40Z8SweN6ZQgnlIuuJc25A6qyeetK2Fj1Mqzw5qP2ZpXXxFqkDvVnfCsiJMuWn8I/hDfTakmDIk3HixPgwSNsHM/3xOX6Ysd+Zf9uybkZzOC7EQOr2UwkQnwDUYbcXgQbif77qx3ZS1i3pe3K31PkVW486MQ=,iv:cxtBH2hj7c9VTpCh0rTxD+B2V4vX7LOvhaefvzQkSOc=,tag:rIIHTNbIGXuA/8WAJJFLdQ==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:GCYLamew9Do+,iv:EPobo+lbTO3jCrsFd1JOWb52vbgpNv8ffZcyQ7Pe+4Y=,tag:eBM1lyoakR/HQYsnKGsDWA==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:kSDDfOX4Ids8IlDIFjA=,iv:AL8NxS91hPwoPNU4cIWyU+XkVD5wwOZfRZgqfLJfMdI=,tag:BYK4r0zlOo5qhieCJwarAA==,type:str]
  PAPERLESS_DBSSLMODE: ENC[AES256_GCM,data:UEEAyHT19A==,iv:KUp11kio4+2GsjqMF+75R9rKPZh+VQnjLvqHyNZeM44=,tag:PP1iScB4o4SK4DqiwHrSYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSlNhUEQ3VzRUQXFsTXBR
        TStMNmhIUVRBd21tcC9sNzhtZ3oyRHlRc0N3Cm9iY1Q5Q2JhYXUxK2ZpSGhXbEsr
        SzBWbktQMVh0Yno5N2diOGcyaC9jb2cKLS0tIEppMGVORkJCVHAyOHIrSVNiVElH
        ZVc5VTlMN0IxTHNDVkl3TkloOE1obE0K/HsHW8LT3ptOkRdKku67/t+Jnbsl9x4U
        fnZzU4tQcbQAxqTXkZQqG/5FLfr64WXWT6qEJIAPa7VoUBj2L0TIxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T17:17:14Z"
  mac: ENC[AES256_GCM,data:WPfzqg36MWPbJnN9dtvbmz8GIFZdfsb6uhdFjIt5qxNJ4m/qmZlcLqpxhPzJkkYWIaZPsr2X2FOv+eeU6Z2FtVI4e36878R3dOnWUK5W0JXjFO7yYlarXBfmAcljI5EqdralroIiv8h2xkrY9vsZdlHimzn43LVznnwYgtm2NsU=,iv:a+qOCNrL4O0BYBxT1NwO7nh5+l+JY/Qr+FbnTjXVS/c=,tag:o0uB1+dgObnRjfuHwbxWSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
