apiVersion: v1
kind: Secret
metadata:
  name: cluster-paperless-secrets
  namespace: default
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:kSMtbiPb2Q2RpEo=,iv:Ho98HzQnHC1KeI3kbKlj/AeRU+CShyiUDyRa1ehtfcA=,tag:7kXUoQi2G4wsv8WDqkUO4w==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:3fgLCQJr+++cAHwsfk1SLQ==,iv:h7lxNkbsBzMpRIhtim9eTnZhkLoTi4mkjOUQhfCpO2Y=,tag:nRy0cPMZFIdEdpT9soVPAw==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:0PFJG8mA4J+e+kowiUoszjmx8eeuANqfSA==,iv:ljkO9hUT867fFFfZPfGOOUIqiD8NwdjP7Jpjqh+qM5w=,tag:Pqft+SPqkIFNqSJcikjSaw==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:g1nT8EwiO3Il9vuvxTpdRneiYHlinZyM0YNWf/tRWjB/0hgu9dFzHGWioqrG13zjw6jJgGK27An1oPXkmxez2QTJdWVg+HW8aQM8zXS0Y1D+GMvOgIdg3pum5YzUIApguux9GKpI5A75YBS6Rjqmvmvjf2PtfaAu1ZCMHrJc9Ojvd7UOoQm+W0f2/LhzdVgkXu6xdkpQw0fF2ydEs+kAYcuvb93fMDn+rkdcc3251mRZM/AXXbhr3do98MWQVJF2nlasYE14nVQ5NLTlrdwKyzvbfO9/PNv6wlwQAOVlpoo5/L/znSrL71NB3p/RhRYI99FJ9zVh5qEB39tUUVczuB5u5DpRP1fBlruy978lGR90ou7rfJNGpQ8RvTYFTQDxKmXG9zFbCQoQCpY7Vov7ZGWz5tZdvj7uO5Y=,iv:EosYVkA5vuj47sssyixzCiiZlG3HgBB/4t1+5J33CtY=,tag:Hp0v1r/mBILWUBX/2A7T/g==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:AG8AUJ+AhZ30,iv:Ar9uOZNaZ/UGK44aCf+TcafjENdfLL/jqq07TtcOuUM=,tag:F7pUHIWei+kcuHERafaNQg==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:RTshAzb6SqaO8vhQo1g=,iv:o3tbac8eu0b0QOakOAQlrfYMZrWoOq9hZzseHTPJl/4=,tag:Fmh3uYISfy2uT1oqmpRgwg==,type:str]
  PAPERLESS_DBSSLMODE: ENC[AES256_GCM,data:pno92PDJ2w==,iv:NqVwviBtcWsrsjHMg9092FXZokqBtN9bpvSf8iMTj0o=,tag:3sy7Enq5Pn44lQghXg5smA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWlZSckZiYTZjRytTRWVY
        dHgwbTMwVnoxclhkZUR4MVVwTVovbkhOemw4CnBvWW42QXg2Y3BqK2lnenZWQndv
        TWRHcXpSYVV0WXRadlI1NWxrTTFlTDAKLS0tIFNGalUycGMrTUlZbjdBanVtVVp1
        NWJsKzFSWGFEcnQvQ1JaaXN5Umd5cncKc0gujPy2mPv6r16Gd601OUbQzghs8BOX
        qT1yTpQ8zTQQ5c6U7FERMkrL6Hv1Q3a+Qi3ksmy0vBOqzu7WGiNHCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T17:29:32Z"
  mac: ENC[AES256_GCM,data:rGLQ801g5V2hs/NvWz0UQqbtJvK170aD9rYzhFSxGr+k8U04J0Fa28wyr2sHkL9GE07n2eVx69aGlN9IReJjCJCx8Pgt9zyC3gYqF6sG0zJ1mp1PwK6USRz6YIguMfgK7guev9diL661hhQmNVab85yjCJo69/HnPSOnaw2W0Zc=,iv:IOmuqHcvkBvLgLsVK93RylagSl0Ht7Oa879T5sj/dEc=,tag:SZkP56R8to5Srs5NA5voXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
