---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: home-assistant-gate-notifications
    files:
      - automations.yaml=./gate-notifications/automations.yaml
      - bootstrap.py=./gate-notifications/bootstrap.py
generatorOptions:
  disableNameSuffixHash: true
