apiVersion: v1
kind: Secret
metadata:
  name: telegram-token
  namespace: flux-system
stringData:
  address: ENC[AES256_GCM,data:fMInJ3ykPK1tXetmU8CpR++RUcStlcpH8w==,iv:seZUaXQCU48rf32/TuOyDuTWiocFfzvw2EiNwEDKZck=,tag:52fGK8DQPaKjhexP4iQhtQ==,type:str]
  token: ENC[AES256_GCM,data:S+c24SVo5x/0dHQxuKfiKbIpixs2dfIoxbpW8r7qfis5UHuDL/IEjoJqDJKbXA==,iv:ih2wt9+dUAffO7lxkmM+4uyEfVG9uXNNvt3qBvxZQFE=,tag:kVAmqXwXqBLS6cAVDaAjNg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQk5pc1Q0Y2dmeDkvWUFN
        c3FRSmx2TDBRR2VnT0FMbUdFTGErVU9WVGlJCk5uNnBVTlByYnoyTUZHa3R5eHlp
        OUdMN2paM1NFY3hLdzBxSlhPc0dIMFEKLS0tIGsrTUx5NnRMQkZWRVlndmdYdDh2
        RFB0SHN6MjJ4U1RuL2ZIQnRlVEhMTVEKUuEly32/O/5dq7LaCAkOsNv7aMqZCEbR
        bHrKRQt4Kukh6VSCDUQdZIqQDNUZ21NvPgYRlB7WRZSqv/lcWQyrgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T01:08:28Z"
  mac: ENC[AES256_GCM,data:KXuX28Y49iH9N8rssJDfVoRiagfrOZVNlvY3NXLXT7a2qztngcotvEVouormSjD4o5TsLfzDX7rOhsj1cGwMaG4eoFKnP+qNal/aMBwnfFVhh8zAl0DUFsTrwt3+pe5Nuyj/v/D++lR5o3tF7XRXdJ8Y6rB3IAJmvzYE4GfCb2M=,iv:m4hcU7gofgzuPbSUvUxap13H++QkfGh0fxESfzRgX5Q=,tag:tUuz3FE1nlBsI8VLI1ffRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
