apiVersion: v1
kind: Secret
metadata:
  name: telegram-token
  namespace: flux-system
stringData:
  address: ENC[AES256_GCM,data:kzd4Av4aMKo6tm4c1nb96gY8p9V8hCmrpg==,iv:Jt2bgoCfxY+ObMcSohHaqQNLLwGbsq9LoAx03MySwcA=,tag:ITCeudqrmm2reuJ+Bhft0w==,type:str]
  token: ENC[AES256_GCM,data:EJrpkZk3odz55lnTjAdM5cdefc0e6Oc4ryUmQzL9GhZSoYtQNNoo51M/3etXAg==,iv:QaYTKeobKO9rHLjdPLnmeuTGTNi5P1MW49JqEDN8ZgA=,tag:MKmXVUaj1MxQTBICLvHgEg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTFd0d094S0ZXK3I3ME1i
        QTdLTXprcHFUTXlKZU1SZ1l4eUFlMU5HNldvClpsZCtkL2dxR0xiOFUzeEd5TkJo
        Y1dyck90QjkwWnNZOVBsOEFNQUhuRG8KLS0tIFVncUlXa05ac2xXQmhMR0ExVkY4
        VVIxd01tYkg1Wkh6a0hRN25vYUtNbU0KY2+tCIgoFKxPwrv2/YKQ9t9wwuv3HfK3
        oeXRfcnFdYty/MS4sVnzMe0iSyeFbPvmP56qs3f7FWLpOQr89rwzmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:40:55Z"
  mac: ENC[AES256_GCM,data:DrROWrZ+FnC5MaOIU/iJP8yHVuUlvVS+nXvFQ+OirUcZMBTN77BG16swTksluopk9zGjVhYCtEy9DTbnpakBm5osZkgPIp99JLN3GvOM4gaQc2s7OvR5ddCSGNQMz6F/zSgokE2uqfTSJ1jYqWMSvrrNPcKtGzi5i2FC7Fg8m2I=,iv:3mnmHUeNdnLTWwrNzDv+HTvB2B0cHY5tltFxEJ3ktV8=,tag:GHf75HVbzNwZQQ4H4RVZmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
