apiVersion: v1
kind: Secret
metadata:
  name: telegram-token
  namespace: flux-system
stringData:
  address: ENC[AES256_GCM,data:MWRhT5fsx1ct2m0J6iogfjDTD22xv3hzMg==,iv:OIv7KS3+09n2hYWmgktXwyAk+GLB5U8J6FB5VxOx0iM=,tag:kgGVx5/dmC+Ootl6obGvzA==,type:str]
  token: ENC[AES256_GCM,data:/+uUJO1Sv0LH+LmMHbeVn4bDoQ2wvyYxq/MK+jOgVqS6st7ym3gOaxP6P5TDCg==,iv:WDW2CibraVkVwhLsiLmv751xbujvUN4M8lBdr9YaSa4=,tag:hL7D7jPc6kXs0CARQ2V7qA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dFpyaGVwZnJHeGN6bTVR
        cXM5R2Z3eTczZTJBZjJwVmt5L0FkczdpbTJvCk56ZWZ4d1NoYW13aTBseEhKbHN4
        WW96eTM4c3FaNjR5VlhTdzVyQ2NrNmcKLS0tIEZCT3lsWG1EYXg1M0o1djcxeTBz
        NHJxblJSZmlFVlkwSEM1MGNiU3RwRlkK9JmIxFWIYmuAT/a4GKry4i+xImyMGNb7
        +A8iCJeBYRbT5iUrHZImcWIJCKKY8w5sXaF+mY/Ya4YeNmTvLiScKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T22:45:52Z"
  mac: ENC[AES256_GCM,data:0yCPr/v00lxhNnW5hkT0fIJiwVnTp3BiRvOX6XDUse79CvMWuOeV44kmUn+1zXgq0OaG9SuWNPt4m3yeLckSvdBTcCaMnJxfPLe/vqrK7N4afeEOX074IWEev6j4wUZCYjOvgIQb6Z5Zc7bHUrspGVgg24JAc2ugfWc8hdJzNe4=,iv:zwH286PF1u/VvbTC71wac6T2WyVfLZBCc87/YA+9w4Q=,tag:4Zi6n7DHsCQaR9iE6pnizQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
