---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate
spec:
  components:
    - ../../../../components/zeroscaler
    - ../../../../components/ext-auth
    - ../../../../components/persistence/jericho-nfs
    - ../../../../components/persistence/lordcommander-nfs
  path: ./kubernetes/apps/home-automation/frigate/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  prune: true
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: frigate
      JERICHO_PATH: /volume1/apps/home-automation
      LORDCOMMANDER_PATH: /volume1/media/cameras
  targetNamespace: home-automation
