apiVersion: v1
kind: Secret
metadata:
  name: cluster-mealie-secrets
  namespace: default
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:uh9FtVSY,iv:zQ02IG2gZTpul+3TkFmxaYxSltxQkTgbZMedNApvQ9A=,tag:lKA5a7/9K/a6J1MGHQ+Nkg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:m12ZLoN8OWsE/xdaQ6HOHEFiGsA=,iv:XccmSBd0c3GyrRn5CmLlE9dC/y9y53/Fi8D9CZidUHQ=,tag:g5JDd6MktgwkzCmmpnWn7w==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:9GQKf9OdjmAFebldlDSxxutQSH8maT5puUnjYse/Nb7L0oONDCWBMGRrsabGQz1fGUsXFgWfedCBdjPcko+e/A==,iv:xzR+JpCSG+pSjyk9q9/vAcefPQxdh047u5FBfOlJL68=,tag:36KcigJkXRMUEuzIOE5z/A==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:BKy8vjO0YIYVzmzjqxrPm+lcm52Bm8x2qO6cd/XzDx1DSHpajefNkH9Fe1jkZEY1pt1/smlu1h6rxNZ9yWftZ2jt0P8V59xpzqbbh3N1Jx/Y28mGB/xi3UhDpg5dyiGndUWMxM4Y7iIbLhuUOyROlnQK+Hb8tibp2xoEokDJ7BZvrry7ChLccJHC6cEm+Ve0wo8oP1SXLJt+qOt2mUeoNhUlX8k=,iv:nQEEbTe4Ek65+32tUWo8fqL4s69G7xfnrJqn3JLXy1o=,tag:zn3EEUz8jzL24KVXtDiChg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cGJ4ZjdKaGswL29IQVhs
        QlRZSG84blcwNm9KVHNxcm5VMlUrZVJ6ampJCk5KbjI3SFNrUlRybmFsLytwVDEy
        VnhQMHcreDl5NjZpOFluYkZGcVArdzAKLS0tIGprT2RuMktMeWhyQ3FLWjZiQTBq
        ditmd3hITWVXWUZRdU1adVRqQXg0bWsKB+rL5Li0A4x22XwAz1CJSN1/qxjk6X8M
        xXHWHcg3/gcfFby31zCwc/5nZzRsL8bn9Xqsh7csXBKwDMQnWAdx9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T22:47:33Z"
  mac: ENC[AES256_GCM,data:qxXqkljAZMbPT7b/UMVUTHl130VT2LgwZGtt/A9RBn/9PYWC9h2rEgjHBaUCoDq1+DlVHpZm2VYdcRSZHTKlNY/XKlq1jpoaprdbS3n4SOwuUeRPjDGRUaONSOrSP1ViMVkjyy9Y+MmXy+9qH8RigA3UDsGIzu7UKV27FJozQ0s=,iv:+jqmNta+C4iiCTVUtU1Si9RwyHz+JwWL71jPfN/bfJs=,tag:VHZemBujVMKF944hQfFyCg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
