apiVersion: v1
kind: Secret
metadata:
  name: cluster-mealie-secrets
  namespace: default
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:6P1Nn8Be,iv:qLCVKSQx46vKIfa3d2ZiKU/mbByJN0rWwF9Pa5yGKrQ=,tag:WGgNcYNsdyz5Idu44hrJ0Q==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:WW4mqaPt6er2tkvid4DERYFcjJU=,iv:WX30T/xLJkMz+bKpXLwE4rfBQpFmFj5gmDLj/XnEnu8=,tag:z7iEpJ8QNakBNDJh9fp0Ug==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:COGGR53NUIa8+TUSVibAcqQGbYixHpsV8Yy8xnEY3tbtGXJAlSl+zMeiVuhofiqy3L6ubMcV2G6JyrPUeWryQA==,iv:Fjndzu7vuy8MeaktT1HAg26Uu/zU4QSmGf7a7kF+f/4=,tag:jlN53nIR2S1AHrkQxVzwpg==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:sdlspDT8JuApuCl1mQ5A7qrXPXQmmKMu5znrEDPLdRqU+fH5wFIGoxUrp6B6r4aRTuyO0hvSI3kmRDUZHe1QCWzQ2LqLCF0aypt9Ha7SedgmS8F7+sZgTV2+4anVD1DZ/PNfIZq8yr22R8K322AqO9zZJ2jFDgZfl7kirl3Lb2swFsqomx6MnzZNa3qbwEP4JKjxs+81URMtLs4cwgn1+iV9UUI=,iv:tKpW9aKjTCJmU0C282UK/WsO1cMOAut+eTFGuSxkWts=,tag:49NmJlsS9aOxQApDy/uNgA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vy9WMVFqQ0ZsWjNDTzFT
        Qmp1VDRZSzIwd2ExQlEyMGJ1ZmZVUG83UjF3ClRKLzFObFdHVUlrWkRLU1pWUTVa
        ZXNSNjZBMElGUTZ6SWlhRkN5NXJZblUKLS0tIGNaTTFDcG1vbjAvbXU4dmdXL1Uv
        MUpPcUJ1RXFuQlNONGZUNWFmTUdBYkkKrJsy6je2zk+Y7emcihG76eclvCR+7L6T
        YqgSeJjowHhCB3PEL9lFnVeTlHoLDq5djIR02rNFMgySrSQ81N8Q7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T22:51:30Z"
  mac: ENC[AES256_GCM,data:oe17yLca4W8XdgCgBPOI/MhS4osjnZgBU913yOGF/A8gg/KPy21kbgSGRgP4VZ22KMidD4MyDuxOIyiG3nbJ4v9uN5aYRZN/MuCTo/I3eklnzeWNxcWFXTQr+cFgRse6Dd3kV8f0+mqoZehqgjcTdN7zQ09/qnVk79R8LWrKy5s=,iv:161Wqe0QdwtJEP6BOvpurvDDdys3wGDipz0MCcZ+cUw=,tag:SSiU8fGTD6KXLfVmHqo6Tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
