apiVersion: v1
kind: Secret
metadata:
  name: cluster-mealie-secrets
  namespace: default
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:qire/ljC,iv:xXJS5Vc5Oz051nDR1Qaz08D7Sk4Ww+wCF9fQPUlPopk=,tag:XAdSen3c1m3o3h8hVgolgw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:yumxmhUioE7/xIrH6BM4G8yn7IU=,iv:zItKwQBN5W4qMm8fZZ0fHw+4Zv+kHRZZTmDVPvpeYEk=,tag:UcybocJe5qZiR6Vnts07+A==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MJ1FQ2kyl1FQkjfEt/R4qx4KAvjjgbMWPcf3lPDMqGDctVp0bPkNDMB513ucROTkqRA5FIV8Y+oMiuUSnvvzHw==,iv:WKX93nrpqDfUz10N8qIX6/PcTjKXkQaflOLIP9+MEcE=,tag:9sDrp6K2x9eMFM8Cc6v8rA==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:4isjyNaxLidrm28hwVjGiP7sbXCy/dFTdAqRd0ThVZSGHuTxr47ilCgqf08zepWLJP8Zot1vpgdYsw5Zyr+RChn/8m73gRhijSyYnbRTPWcOdHMM3tv05n4QKhQP/XfnY+IV8BwFQH2t9qrzTBqMUQlt1C9mK6ZrtlMZkoT+Eu9l8TER2GhXV4HELLjBZaXsPGtiY0sodJCZcsNfSfxbbFsfj84=,iv:Rw2qdjEjrDlsuBUjmi1PfklT3ChA+TpTTdANiJ4oQOQ=,tag:29+L0SupXA9RBtmH3O+9wA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R1ZuUWFyRDJJL1liV1Ez
        SHFVU2Ixb3psZGl1SHE5MnltMnMrcDZmeDA0CmFZNlR4U0cvWXJtMEV2TUVucXpB
        U3RMMDR0WHd6TUNJcFlHelBUMW5Nc2sKLS0tIC8wM3JWdURwUWRwYlh4TEt6ZTZo
        WDVzVmw5dVRQV2M5Y28zNi9SbllXcGcKZ7wmIYmBEKeHuT1HY46JfvPnHw8puPuY
        7rUoJz5D42CcXEmBNioRnOK1y+FNu8ANF6E9OCdkIxU8sNiFr2Aubg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T23:19:00Z"
  mac: ENC[AES256_GCM,data:iYLC1ONJYY03nGPkoKZr9mKMtKSrTY1KXNTO5F3/OX5rIf4pn+YAIdWjgFAB4qBNIbmjS9SVQNAnDmA5xXBZ+1d82p0XulMephia7XyrviipZekl6BPByPbSSjlyBJgTxqifWuqFJIAQ8JI/fV3ecktSBLnLlerwVbm2SweCI5Q=,iv:yG40+ber/Iahfehi6IErPAlyT1CRJDuy3A2XI72t6LQ=,tag:kEA3jr1RvAAZ3lH6ZbxVdA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
