apiVersion: v1
kind: Secret
metadata:
  name: cluster-immich-secrets
  namespace: default
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:gvtn537a,iv:uCy+yRDN9oUGyciSdbHiF0YoPdx2d8NoNa5P1na6hC4=,tag:jH2xHDlqG9ITVyE9Yr1LPg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:fnGHQIuYtzEiBdRWj6ZrIFWYT+DTjW80gM2LikfLKQ8=,iv:FkpQRG4Lw9CJBVw5QSc60PZVMO9CptGEsARPTPgZS8U=,tag:rCbbPs6ubHAICEkfoA0eew==,type:str]
  immich.json: ENC[AES256_GCM,data:zzm4HGyXPoiCxmf8guXsva1qiPkxpzWXuZDJyVaB6yRxnbPa7SAyWKsxCGsOCCqccL8o3w+OAfonlcO+i1r6ULiBFWqmsr6mjAhFVqpa5NVbsm9HsjMirH1XdvFgTCVrV4LN3Wt/dDo6zK8nRXIMTc8EHYGLScpyKQlEtaIjsIyAdKm9BwDo+weoFTIuJUV1rYDu9zBQZGzZ714TX78+NpIwF2kFjWLGYqc0gHB183dioFayhG6pcMWqifp6mGP/6h9Rq1F+g1AFPNR6WzfXCq0HFtykzVJaE4EtdJH/pcw3ADFMVpm7IBbPQM/RVXX118kM4f25gXEykOTXiwN1CNEdlMcdkRG6wflM6TVVGE2Kb2VEHQyMAB37A5N/LoTqd33DPymkLHfC9OVkc80pDwEpsDOGR2niLALCSJewGIjBNbGwJ8VP7oWZ2idNTFu+BG0iXcDAE/PJ0xRXWUGsRMRihDdmYq8rIHFg7NnQ1eLFjRQo9GjNXTCPULQsRbH/VBHcByNvOcrNTFBTQsZCQYEmuScVHhxE1RchFOmN5WkbPfLBNlfrLwVPSOsuJNvaL9w+7LksKG9ibwlSzgHPFblc5dL3K5zepF7Xtzd/j6h5pZ23MBzaFI+CglK6ef50uV3jEUIEfX5Y7Bqr3qWxU1lSpb7Bbnf18VTZMbpDB6yfypFjsRl2RYpv1T3OisCbh0eEJZHG1TfGwgpuGciHxTPnsjJZqKtO7HXjX+rDrlfsOCF46FXJdNexHK3dhh5TPL27tRBSt24aocajno0vANoYw2LA4YiD51zxDi4EXDn71DILZ1Md74gJHXlu6EqhI1NNNgAJ3uj/51mB3KSd68s+kkPKwGC+R8HHPGv/0fr4SRrBiyGxCfXMUdRm5gtmWy7qenrDPOesi5Ady95JjX7UdqQbNpqNJ56QYj7jpC2aydgRr4eQPhv36tRwXTcF7luYfdQPutxXYNs+HjAAoFkQ4JAKEdQK263+xbvDIu/KiSmrRaiiBTMqF6Q4qI5Xq9vT/4lCXfBrkwZpzuG27QJkloBKwxU1eZmh3R0ojjAFULwW2grio+Ar+9K6lDiiKGrx5S+uUKM7MMCasNpBoKvJwNV/ol3iURd0kbu3/gYPt28j5oTibSCpm+tKozNuK9x6t+NquiGaFtVOVtBZCj2v94Y12UBsG8++hblkx4Olm7CCetGHA2BP4C3r5kD7OAU2LUYjZcBbMxOz2UIy8m1cnnW0SuBjUOgp7e0KjbXcsiLE9KzMyudMuwVr7Wa7Jsz1NIrDjaEiN3BORlupoW23ww3BhzAjegrjk5/xet59Q8O8wop2R2rldANtoqIGydXHhIgraiJ522DAFLFiQ/aDjnsxItR1L+aAH7bPUYsvmHKMGwdJ5HJvCROK8Urdy11VYsG5UnnBKLf24l8sHCt4/hv6iabqPPPw6wkrupoeT+T1vF/7Z3y3yPOy2U5PWDbjB7CNUBVpCE5sn1qa+mUDJ3PjDbu6fi6dwOOsUiZmPaW5UeJ2TFJsV9EQ7ABccaSQFKLUwzXDZBpF3Q3xwaUb9fE=,iv:gQEoZGQvtazjJUC97Bc6sJ/X+ZnRGFwrEY+ysABH1RU=,tag:eEfvH1aJgWpOsNBkw3LaDg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dis3NjF3d1NrbVdEVU9G
        YXJtZ0U2WXd6c3Izd2ZORVhVTkJjQ0s2dUQwClo2QWRJL0lEOWQxWU9PbW1EemNq
        UmlJN2FQcDJZV1NqWUJ4UXNqcEYwdUkKLS0tIERrbS9Zc2pBeEtiQ010b3NwNkgy
        RTVBUnVSY3h1THhFR1kzTFN3NXlVOEkKKRO1ZMaxJUjHWkuWPOmFeAlIx4A27qBp
        AnZqYpAApG2EUMgjrgAS/8gzaLsJNxCEQvNIiXFmLSaWzhaCzWuiKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T09:12:42Z"
  mac: ENC[AES256_GCM,data:/VMG457kbYp//7ELzj7HW8vWDu9lcgWClhksJxenuXaEJ+fqBNTm5rNRhpu4guLS+wACy3VPE2oQi5UVmFw4sDkswhXo76inq6sAbwstBQR4DC43+/PDNUe4JOrSFsPXw48d6r6AL3JuyarCv/AZBBSdc5Q/uoQNm8OYZMdsGrY=,iv:+sfh2wbd61GuE7c9j2iy1YTgzAWtFIfV+amws2iG6Xo=,tag:vAX//iWwCKnTgRQI9s42ew==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
