apiVersion: v1
kind: Secret
metadata:
  name: cluster-immich-secrets
  namespace: default
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:/obCn2WT,iv:NPDsXvBxBZxmTGYQmDPgcR1PD279S41LHsq69kP421w=,tag:jRIl6cOg4qjU3c1Sqybkvw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:ESzpf3YMnawwbw7roTwDvMq1cM022WZ2HMtuHptiwMU=,iv:Kizu9ijF3GJs3Fsssc3M/+MFUrxg7t0mx9gUsVKfJRc=,tag:Jx69M3OvqFQ7hem+Wps6aQ==,type:str]
  immich.json: ENC[AES256_GCM,data:4daofOeiUNNnOMpKzxxqZ85skqukBQMhaYZ/WdWLMwq96/TiS8fpQAaStBp5Uc/EAwTLkb2elFL9rrYlRFyyXO46SQbtqhTvYhKw+U4xrkGWyfVa/lf/emiAdIv0hG3Ehs8xYGrGikgIk/aaUncuFm29xV/DfAOnMQa8dRUZLfVbMgXxAZ+4vTd3y3kWv5q/amOKWj1uuY24hAI4AQDg4nU7T/GM2s0cIihhHPGt0SEnrtF7cCnzktHG2DQo545V9mT6WE+0nYvG3hvIAfHRTnSu8XvIRixtFPI/Vk8RktDX/tT4zlEFJrdbXeA8yjm27fCc0gyHZ3TAtcARf1aHyDviyDHrhd89UTIoVSZ4i5G4wivS/RoNoJGG+2aNVf047oiZUcudP0QJnUsqgaqepzxjOL3hEWmSJf2/EuM+GDdst6YN3V5A+r5VgktI4kNsTWkS7BeJoc8VOJLUTeNKz96EzUua7+7hGEZ4UsG9ziZfDZUardqszhsFVSjW/IA2VWdpfPo9W3VBCnLBPOyfg21v/nsAw6o1iHKT42Iy5N5gg+9OUeZoz+8nRNlAGOJjaIwCbpGaJh0F+LXNMLfV30jQPMB1bUVovYhSj8frCSnCt5xNIR7YF7jjPTbfClJ8yfYholeynSyGS1Dv2LQ3BWHekVN0TJd6w8j7uD8IyRRx07cmrbzpuaoeVwsI2Accplx1nHGLbYzOxwPYi27ixGcV442dlmEMER+LQWL5OqE5j5u8L/Z4isWqiQcUrONdSJ16+j+s6KoVoDTnQUnV+lOIn9cbw8ZL57jPu+FRKGRqr062mRfXG3DanZU0tMpPrBAg0MTKm/SkkrvFxFPikidFp8U8oGqIBewT3Ydl4tF5nAU0IDqnHgKta1T/l9qlknnaeRs5dcMXtgd+KNhw207Oijqb/Z9Ezo673TGBtPrHM8r4N0YrTlgkpEdxDMs0HnBSfbL76KAZb+Nt2UmX49DA44sdqabhyxGb1u+p3+uQpVChXSeBaD83tdA7F78Utd7vgAbrjlSSL74sY9TanKFlurdhW8Iy/nu1l6PQEr/4Vn1A23ml+tKqqE+IscMl3vCLvNfBr1e4EqNLTWin75saVuh9Q+Q24hT9h8x1cTtrAN+fZIOlWBkeYVErImDV7Kdhjapuv5FBOdNjsZXaR63Ity/SvtwA7/MdZ03HWLsf6250N1Wt5p8tXyorLHzJ0escupNiWZZQRr4cFXkmVPbf5LFEq3S039ObScCP9JXT+L8z5ttK0DE8WEjPsNNNZJWTakS8u+V35HsiVtTTAhMXWta0uNZElQ3lgZoVGeC4DFQKHQ9sdQ4oTUpW6H9JQCPtRff3QQAmybWWRMcSJLuLOIkt299Ewo89k0HrGY8JnaL9kiftWWT45BxQc/J5tjuxvZr0eSKcG1uKhFm/mkx+qeWGXJeVbC2Gpcff5iPOqp16e/ja3hmrbnwNZQ4tazfn4tUMr+8ON0nWxjQ7x+PHyUMRPs47adni24mo60MPw1S/UpBJvjLtlRacKBdjYKHUeWVtyV66MT7QKClM0J6j4eI=,iv:3zY7KPxeEnhoLGhIcrEkJl1MofqF8DOHvHuP5OHGT48=,tag:n0oUy/VJwefmc/ZLIajPGg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYURncFo5RWV5QndpbmJj
        aVhEV0NRMXN2OWRPMDdzQWxvNHFVVEFTdjJVCkZUcXVSQlZta2prdDAvMlRKK0pG
        Yit6emRvbStWNHR2bEhsTjRkTHp2SGMKLS0tIGtjM2tTODZoS1Y3SWVIdDFQUCtX
        YXRHUnJwK2VPL0x6dHMwNGFkWXp1VDAKhV+HE0ivG0bJ1EhCOK6GsaRUeyZwvart
        IoFBYirzgN9c9V9HRUNUr2UCZwHMIJ6r8pHgUwJEbwL9o1zwNSnsrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T20:31:13Z"
  mac: ENC[AES256_GCM,data:22tLb2qKd/nvapiBtPuoNyQlf+MgLcxwfe8tL3mRPW6je9mnm3GkAfNUzU9aZhDyDM2yw6MNzWDiofNPhPOjiyKJk7lVQ1vDT4fzhNaBO8dJBsgMtWch9Rse3/4X/WLFFe0qM8diyhskVVhViHenPE11XvB3b7cYHSGBOjRp52o=,iv:GtZz9PrlfZPr425QFyt6eQuLZBBtvd2KBPCPSdWJ2Eg=,tag:YbsbZjLiNhlxrGGWWZAPJA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
