apiVersion: v1
kind: Secret
metadata:
  name: cluster-immich-secrets
  namespace: default
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:WhiKN9gC,iv:sGLe5CZD4sDg37nFndN1ezR9qrgdm+NCbaXFG5be2es=,tag:A0JF2pTEr7BNofpA8Eh5zQ==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:bNqMVhh0FdlCMUWtcOi/fbao+6xnyEhnDajyloXVsTQ=,iv:XqgtMtwrHVNRGdEZdFduJN3EarKVMgT+FFZcq8VVuRo=,tag:Lf+devzM8cxcytHdeYbPOg==,type:str]
  immich.json: ENC[AES256_GCM,data:YQfGZ7mDzssDmZN+nmSmzCeWhTeiV2erO6cMVKIhuIba5lr+HE6uXRz0Fz1mG28MWljXfkUm5OlqI69uC2aTHj2mdqhwbAqkr4NwA7qDtHvC86jMr+s16C7sG/lRny84bmMvRvSL3IhTDrseEMr5/UAdjN0NAdz4B/Pq+u5PF8x3Xu6AqeruwOFNwsbjuJWnvSwJ+A1Yd6xG0GJ1QHR52mgZoTRt8IRF7ukzRo6aOhDKag40YUVMPfZoSZzzlLccku2FzMrKKOnU8Dj+yduB9CJNfI3/rDsdZL9Up+IpyDGGXrKy6zCNpMrUQECrIml4LMPcYTJ7RFzpxRwLfqiC+h5z15swh2xaeS4xthxKOov5J0gLboBGiKykI3RRozDu0mfCpa8mhaqMLt9sQ9pBuXXOGPWdBHfzAHPBAFNGTEK6e3TSXAdHns9ZgB/eANcZvfT6fhGQLd9PgZNBlzhMGcPr2iJGTXqT1kKe9JgYdQ2N0lpalDkKxogen4n5hrho0usl1Iiv2sFSHJM93LH4SyQrVwL/OWJ8c6KAi5Ap5YmW1mRA/XDr04g085Qhdkmr55xOvPJ+FrpSku17JGlmjft2X2exaqgSsA0lpLBfqlFw4m8KpAvVu7UHnnt6jR+dPGM2kVfDE+wmIahJyphKWIxyJbNXcqIZjLhLoToo1GDrJk9GJfU76e/jvg+Xsk1O7JY5KmkRKZ1aVC0INhJ+t0VMiXkELu4kyemjqJ9+AX/AjQ+388cR1+EFAcwyj5jr/40UgJMGmFdBzmlIhak659GObLU7g4fFYX8gZbVwm1iGPkTwTqarvsfJhaBpTBqKcBfBeaevCJVUd/5RmD0WvwblPvP9B5Z9GI2nxA+S5I/TDtacLd8s6YKk/YiBX2s2cY0cYfousVUmLv5LGL2eTp7coAPvYNIwD7UjpSL8vbhaflvMGpvKV+IEk4MMYDDjIHXkRLMXE7PjndHdqpCMF6/PYE9jw2JamPqCqhs0xLYwU7u22+/EYSVyoeBuuMNglDJ2IZlRDtd6s2gadJtaGUH5l4TvhOLGCXZx+XnHwo5LeGWafHZKQSkQ61jRActmjs6qc1iAMg3m8SZurUuYtYtYxHkVGl0MTDvLX3VHRJ+AXNXR8olqM7XQXyK6a30ogWqhentjOgSzDq5dndiipqwDh5QhrPQtzSuyOARkV0DJ8TDjxTSkTqDO2zSJKFTx3FFe5NXTA5AakmXDYDceBtEs0atpCj8rFBSmL3tjKuvVYhed89w7hbcZ1IKHD+90zHYquGK96PaNpP+EySWx3Zdn6EqQvTHRTVHyyDb25Jghifs7fU0MXanLqaExd61oip/+bsDUogD7QZ8jks9NCXWLaX5o3A6CCsSELeJtrV0x88lQ8VZW5wzoK0xYpDHC4oJcbnBHSIp6ST3ZyFoo4vbJ6L0g+B/zYGw48ufThSXFdH4dYA2H9IUwfzOoAEqz908MC12JzqJ8nL+47PU948dbIJ+gLIctKzFOt+B3bN48g6+TszmsBHbm24HtQpKQtFdPEuWjv2ldRbpsZ2hsKU2jl9I=,iv:owp8YJ037RdMYSP92nsJ7m0DmYpPijQ4RJulRZeKHLc=,tag:yBKXpgqmmLlmRyJx+73jPA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ulo3d3lyZzRPM2FUa0V0
        ZnA4NVlnYVl1ZWFBaVM3Tkx5eVFVN1Z6VXlBClQ5b2kzU2tLWjdDN2xkeEk1czVN
        RHVVRmdXQzREdmQ5NWk1dDduenN0YkUKLS0tIHIrczJDbFhFNC90TWNDc29xRmlK
        MnN1RnBIaFRWcW1IR0FDNm9PRk9OUzgKHwzAqSMFCbdXe4w89w8sL/YWP5Zg7jh0
        E/oWVSsxdQq1dAg+n7dihyN+RquN7v4e9ogoNsTov4zOSZtUluHUjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T17:17:14Z"
  mac: ENC[AES256_GCM,data:rTp3UcygsZXEiqbFxO4Yck4lHkKwsGgT7B8tYTj1U3y/UsssBkoRReRxQrOQ7ONU4bUzhQX6heMKLLSMnDARFFT0vZmOiybTacfNRxueWAHlNjobDAjVjjhURt8cgDwm3j3Ax8yQOtaTqMh3ojn9g6qfepFPZxy8m87ASuqfhrI=,iv:qiiDh2vjGHBu9foV3EM50yS/syIIxg6IZru4mF1DoEA=,tag:IUupf3kwOATeBr8cQ18wKg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
