apiVersion: v1
kind: Secret
metadata:
  name: cluster-vaultwarden-secrets
  namespace: identity
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:YWkYo01vZOOwP5SpjN+M/U98PsuV3fMXD+oWbx8vTYAxlnmfHdrM+SpMxwi2c3YegoTgqaD9REGivl5275j0Fy32+yYQQL8vjzFcuBtv0cnvFRL+DgxNMEHMsAP3I9TysQJUd/y8tZpY,iv:RfRajiBag8sSx4L8UEsFRYigGxqEJZ7QeMDEyriHyF8=,tag:ucESs1In0MFMJWsVOg/d0A==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:33IuFsxXgRxHWmdRpvwfO3YLGOHBfrbAXPFj3IgjprYhpKSSeSb0ynK6I9BbgFOimvOdMphtYiuRS1TXYm7IqiW315qhXTGa6usv+HbgjXo+bmxy4Qb8bMqImRwV1r3PB7XcRDbrz1u1LX5XREPPaIYNjj5NalXvWLPaQsoGOSAdtWiEqj0=,iv:pJqkrlfJLp9tLKx8QzWyJ3NMaRSF9/1kNl7CsDB6Hng=,tag:3+RT8XUsLC70N8D6bBBYEA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DmuW5TqYgQ4D36I=,iv:TM/UrSb6GcMa0DgnVMlQkZ2jFBCz5Ii4GzpuiTi9Bn0=,tag:2mDw3kCqwUUcbj8cJaLu0Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:sG3ukP+SxsiLXM0dJGK3T1ZNKsAFQHlUCZhdbPNnBwJ10SI3aw==,iv:qSbASFI0zpsVrQUGdrbwmr/ZjvqjC/weFRlBTAOLzw8=,tag:Du75DWcrWPpiUkn65mxK/A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:spm784uXgXZLcWc=,iv:fzS0TLjjZvkuPM6FMxavjSSGJbeMVUoHAGLqbEukzVY=,tag:EoqnR74GEfojw85cjKBJbg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:tuPpDWOJw0P5OLvO8eplBFk96YB6k9DT1Q==,iv:G3H17Vma20oLh8axoFds1ix4SOGGhpYXSNhCJB1krZY=,tag:afpkdI+p+HFFxwLBIULjIw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:KOKxGENBNctdwaIfKskLwA==,iv:onfg6jcb3uz58uttyZg4F0lp/S4qqYiMTA/lV76ieXw=,tag:tRQZQZOemlCKozx1RQvKwg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlFwRjBwY0JXWkJxcWZV
        N1pMcStxcGhUcklFRnRGNEgrelFvOS9pREJRClIyMEo1U0d6Z3piZzdmcEZmVGlj
        clhTTHFZQ3lDSEt2QTZXTDg1S2ZLVlUKLS0tIDI5bWtEcTZnVmZEdFZCSVNIa3hZ
        Zmc3UDEvdzAwRERVbUQ4a1hoSHNkaWsKpmqDRWzbrRLfpNZVEtnbJby85P/F+w76
        E01Yn+7bP22xbxolOteT2quk526amBXhgvgx/JbLxhfPrRz4mvChMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T18:14:17Z"
  mac: ENC[AES256_GCM,data:jUWx7HmVXpdLan5G79ZIySIeTa3QfEDfk0T169wH+AfjwZxp/U9kk19HFvyI6IKlEztXvqta3SoZIPMnoUoUwHZXvpqf1AHn/V9fbuuWYNyNRhxqiRQITBHNf3pAMgeWBlPLJ/xnKaoqMOgAdLupV5UffTu1Dq63UDeumuPoY7s=,iv:eY1j+iZoOHcADrLFGwIgRNOKnScKWJQMOqRvyEbvcmw=,tag:ldDjdCu3P0d5V/Gxi1tGmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
