apiVersion: v1
kind: Secret
metadata:
  name: cluster-vaultwarden-secrets
  namespace: identity
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:6hwn3lSRGILv+eDQpWYG6DaFscXXIfBIpgyq02p/wl5F1o8kdERFMuhugRKW0NvnZrvFfcFOq/35WpK8NEIMAozKCXVJ/0tdrQD33Zetluigs1g9a2RvpeUbdMSzDt038mBZIbi7mYHF,iv:ZfiyYjfy42VfnBDkg9wuwRixC5NeV83BrU8lHGxde5c=,tag:qp6uSOmXO1Rlgtv5mQ1H1Q==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:Fk+9vbed2fk3sKEub4WGHai3OnWTHwrpP+mtPAeog58ypU7wN1EhmG4p2cj3t7PHz6udF0xkwFKNX3ySSNPkPQ37KFfgTPZbDgoUXZBjb7syu2hMHXL3u321B9RzPbzShlqLUaQnZP+00EcuV6GwUuJRS3XVgmX9+GfDQKE/9DdKgaxj05w=,iv:kF+36PYYMNlmmGbca+XIN16PjKPX3ggUDT8IJ0sdaug=,tag:FI2LNNVkmQoJgGHGP7295Q==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hkkA0grjRd+u0hs=,iv:xFSlvdYM0pLN9dJvHNeuqfl5NiWpGMyZVu3Wh4mqaAY=,tag:8yz/5zEBzlGecZZH7Cfk3g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:GufhU9n+mE2Oofdga6IyaRNyV68WO44EA8BZooTyg3xvOA4ZOQ==,iv:IMXa1uvfUAVOfyPEeR5KySwvYu8n7ofpfyATmAuu40w=,tag:h1zwG3vci1RxLVS/rpXg5A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:RuKbNMaMJi2irpI=,iv:yOpLKNyBJkYvSF1ZKpISKMBf8zbVpG9KcUApwRcADoQ=,tag:RCq+r2npb4P9kIghUSdbjw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:rbdCxRaAIdrtNmP89gIH7YER9iMWxlV8tQ==,iv:1B58SvdkllPuzUKm/EOS034WTT/yoacvxAgQMEdYaSg=,tag:0XOjBc3ljzUKMBEdiEU5/Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:f4/4Bk0QZc7dG9IG6eA6+A==,iv:sqySl1ccRglSW7lEUTL/H2iyS7d15bgUbfk7DF4TkFQ=,tag:h3h2WlMLJ39OE3VEQYIFmA==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSUlPRlVuMVpFZ0w0RkRm
        QU1Fd3c3K1N2eXRuWk40eG9tMVIwZnVOcXg0CkV4bHhXQ2JuOTFrNjR5MlFNa0xL
        bXcyZGVCbEg0MENwZlpJcnZJNHRuaUEKLS0tIExISzN0TmNSNkZRZUtJdWo0UXJj
        WVQza1NVNktSdHRZVHNKb2hkZDRmU1UKzLsQTs+nBJSXVPSUL3Lgv/W7W418wUBV
        a7+KXnpuW3XPCN9F6c+wsIt4afAKnVYl4FYHfRY5VkT5GeqUhbdP/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T18:45:46Z"
  mac: ENC[AES256_GCM,data:kcbK2PrpF1Ps7v+8elkPn35+f3ZqGOQB24X1i4Kz730DcIzbIdMns+7Tey0RP+z1hGLTlN0F5MEsndge3hZiQ27OCViEW6VGeXejfEa/i/NAfVJ7C9YQ25FO6wzlFaXBLtdUgo0aF9N0o+zwNuQuFD1vrg35TIAYPk0eGBMdPFo=,iv:VCeL/W6qdu1qu8UhuZW4qaeEn1pJbbxuwy+TLpFzONs=,tag:kTAGuruUNElNexJuLvT1TQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
