apiVersion: v1
kind: Secret
metadata:
  name: cluster-vaultwarden-secrets
  namespace: identity
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:Tln3NfPLZ/AnMWEg80o9fBlW2hb6KH1ClXWNxXGAa9kN20YT0DnGCGVH1cna60D3oiGt/TQPuo2St1qMe9gq3Kgoa1A2buzbxps6NncQTYF71E9KAxxuP56mdD3uljnd2UrcL0L+6N6n,iv:qcFtNvEuhc2Bt/C2FlKDtjy5gg5tnGr63kHSP6lxZ7k=,tag:dqsdI3Psokm6qQBVT8y9kg==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:Q1odz5jW/+Y6orI8ksSx5DZ1AhzU4Wd6pHgsuWK87QrzDrV5YVIpj1tbCE4QakLO+14eUjL5TMl/Ba7cBYxOi4f6cRqqI4sKJBiz18G1Kj5MK6iY2B71iX40tRv6OULmFgFVKdOXQJvUqyRHlCN1CC8+r46oGpJ04x922aO+V1wrNabaQAE=,iv:iuF/QNxOzspY2tFHqqXBquCAlVXkS+I9YnzPPLrJreg=,tag:XaoLxqilEkdD/gtOalv90g==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Da7o7pyBA+hFWzc=,iv:LUP+oAGyrja/FAEHtEECn267OTXDobDQoIOkDoTxmEU=,tag:0AXyue18nUnX9Qy1wtYKIw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:k4NetNrpu4PTqA29FnLCsL0cDfZ6ucj4I4pOXyrs8YnJ7ypyCw==,iv:xWdZpIh1hF9gLratd0zAWfuUp7nrXkXcSY4R9siyiXI=,tag:lSl/lZfubp4I0OKjCNwPIw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:AsH48QD3AeuNap8=,iv:iLZt+bcj3+b9V/5v1WkzW7aRqSWPB8Oi21u6eLeTiAI=,tag:fp/zWVXHHewOx6q3i6/0Tg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zFHujSo60/Hj5h4zxb/55QIUdpvsIoAkbw==,iv:4/8B7JtWu9g2BajInTUK0lWOtHEpST/wGlJDXabNcU0=,tag:RH+9nDySKxuRcZue7ocjpg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0xKdym8woTpEZWEOpPSKXA==,iv:L28dB1ZA0E61k3wYhyiFzYfF/XC/f4lFAAH+pGlG4Lo=,tag:sp2h9Gp9aCRR5sfYgekPXg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhLytJN0JLRVkwTVkyS3lU
        TW16bFFUKzQ2OVdqUnFsc1c5bXQ0dEkyYkIwClNTRXJYbXB2eE5hb2dHRWVNc2Ro
        ZU44eVkzSkF2N2xxTHEraEx5NFREd3cKLS0tIDIydUpNOVFIaHZkMEs0NVBJZFpK
        T250blQ1QVRkMStkYkM1a2lUdXU2YTgKJ1Pzg4SSv2XynCKuaJ76IwNIUzjwMwbt
        M93alrax0jxN4ZhFfC9Adwm52x01f9VUPVztexZAIGIE2COBgNuKQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T22:51:30Z"
  mac: ENC[AES256_GCM,data:9QAog5Z+jShBQ09rJUTYFdRQeybg0/OYZ4QNShK3l+PZRx+cI2elWYd7tj4BZbzuQ2gXQUfchgLXgsKzFUpfNd4eifLIy9H3jiTzI4hHFopxW2NlxpY/6hsSqKItQzK4qpISPF/UaxzTnxKRk26UhkcbzMwIc3zqx6pJ1oU8gao=,iv:1tTNqwqWoP/3REMVSM55/tDxw7+4vhlt7d1Y91zbLkU=,tag:L1Cez92zPzNUX0m275flwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
