---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app entrance-camera
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./kubernetes/apps/monitoring/cameras/entrance-camera/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  targetNamespace: monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
