# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:LYxD4uLUjvijaq5gPZDKWpDqLrNMdcopjqZfLlz1UIWezBivDnKifg==,iv:V9Rk2qmlVTxnFbek9KnTN0V/7jj9m4SchihsdG+w6oI=,tag:UPyUMean/FD/Y4JW+b0bgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-27T21:45:10Z"
    mac: ENC[AES256_GCM,data:o5XFfsySd1LPbtSLmy1JuRcOPPs8iVkZTh9xVQB4KdTRkbBGPqBa57wqaQ5u8uLOZ1pYKnmV7l27HNI4VJ+xBm8gmWcudkeffiWlBrH4xriVIcz4uqRN+HU9vYpXwkoF6gRAa4mSi/cPc+WK+QkKv1UuB4Dy8p7YDSACrRtxE1A=,iv:6CwoRcBpBMuWlghqGYRTAh8DoMCfKZ8P/tTjp+wjrvg=,tag:xdZt+ZXRc0GLI4z2Jpb8yQ==,type:str]
    pgp:
        - created_at: "2021-05-27T21:45:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5hYX5iUwZS/AQ/9GxOh7+pCBCuEH4m2APFDJxbDbflBtpnziDRb0/mUN2yu
            LWt8RH8IlXOn1+cZ2N/kpEWB4KjgL4fM7T8NoWwe1SOpKRzjwv/WelXdmqoYoY3h
            CdpKtA3CPJj8+mRwmXhHJFqc1LMC5WvMsdk0qc/pDjl4yrZz3xKUluxCZCsBmJ/M
            WuyBfvjWlV5PoR2eoiGvk9hvY89pSyDq3C6uqswmpn1mqVdWfEPMHtl6fFsXu1NZ
            HIhv72FbcTnK987ej9uEe1bYymaBtkFx4Xu6fAU/EQZmwwTL6S8acPTAp/38NyqS
            iqhJcuI7rjTMABcJP2jsyZZdrzidxXS+8lNrHr8YrmKDADPW8TEw9GJPNQzvsvZU
            8e9UfJAm9g3rFo4ksZ7qoIOvSceaObMU/EPi/6PRXgo41LPxNUzYnefrl3qRL62+
            1khZWv5aPMLY4mbjoRQUkxYgPrHtGQW0L8jF/z1lp85ab28Q9PSz9f/LnDCBZUFc
            rainWsfhfMcoDtL1O7yPp5+3Z9EvzXj3YxpEjYm5SpV9nqWnTD4pwmDojaSUy4zL
            Xke6C0OzYSOKqikOwYHYFXbSAcvAp8DU/7jje5jK/wXYnasrlSb3+4VkluJGyZSL
            p90pRsfVPG9xpuiwGU9nUnHWlo6PdXr7Qv2/yrTT+YkY+1k/VerUfcxlIK/TPnHS
            XgFtPkOwTmiM5sD7M+1H/bmM21FjZYNBRl/mVbZFAe7t3B1vHwvcCG/z87o/teRE
            9vhhIqSLhsg23tg2wkTVbuHsoK73wJccTFuSffm/qCARZnkWImmGbHPsduLjkVk=
            =qGk9
            -----END PGP MESSAGE-----
          fp: CA0AFB08EFA5ADBE0A5E78DF6C8227E9B3F4C865
        - created_at: "2021-05-27T21:45:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0LWf/ySlrMCAQ//SepT+QY7gG8wC/9qQCYU9uxVZGWQE9Mec+V0cM86KLm7
            i+Ifzm2zVrnE0W0ReaLepj9h0Hjm15a2COmwecKuC7oSJwZ76Uy5uYx1D+ZAkUEL
            srRnlOGEaoAKDpkjszr7iKUthd2I1vSDN92NU3Qfu1zvuRfO0UmUvSzzBXJ2c35j
            JGXEe7n05R5GVI12BWOvTAZGS1SwLk6tSAyqOw06Mj8pZOMVDZwJ6d2GpLSx79/O
            ZPSi/w2GY4FgGssnK+6o03/iqHwm9vHOeIVfrVc0v1U8D54VLtL69C5ohp2AEMBa
            8auBBHSW1SQqRJJpRtTzW5EF9JPll8fdDMbcU7RyzN7C+3PAXJgle74kjfhkvdZU
            ucy5ybJXxyO8HVPNwHlfIkhZq+M2196f2X9Z9jHzxFncx/n2BHQfJpM2LfsP1VUN
            84aadBuZ0CNiM+zL6cMZ8EITWEBEqE/rUCDQpNUw1zm8fuoVjUqPBmF7PGK9Df0H
            V3+wSwifLwj4UXbJiEOg/+PiMBnUi1AxebD3pMcJDU9v3tBmWI7TOMEJXSV6J8ZG
            2AQftEK95wUdfotsRkTgmsY3eowu41+mdBTpMH9Zsz4ckOYFq34C5daXzWrLHRSK
            Q8Xd79bOV6uR1VOAy1eEoL4QZ7Crzy7uzRnmpQoK5FCI5WITGjLZw3LoTfcc/zbS
            XgEOoR2Ji8QSp9ZIJ69OYGt0d2daBT8mcrzvgbJQHfm/d9rc9YVF47NTFy5aVe7y
            XRptdA2BeS26uUij7fpSOzG07328ZgeFgw2OH7hbUTvntqHF3R7+aQv5ZYRVCUQ=
            =dLgH
            -----END PGP MESSAGE-----
          fp: B6A28EEB718712C99403199C90BA7EC781CFA5AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
