# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:HCImWTYi2md/e6PLVjBTqyeMxhJV0h5yeHtTYUU1CvC4rNp2Qw==,iv:dr9BEP+WoKPH4cXNk15Z45RJwRwPiREA9alRSi0DgBk=,tag:884bZtG6qZk5a1qnJac82g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dHNTZ3cyTjkzUEFDR3Jq
            NGdIMDhFOExmYW84VEc0MWJxdUsvY25sU1djCm40dW5OVDR4RVpzejc1VUZCWGNS
            czFNd2ZCTVk0Y3ZTdHlQQ1l3R2RocjAKLS0tIGRCOThVMlpTSmY1ZEJwSkt0Qncv
            K2x3Ulo3NEQvUkh3by94ZkJZcUlMZzQKfWAJIGsR6l1rcXuLtQQ/l2RD97GvNNXm
            mQQa5IJn+2OkgqbkalYNUCoyTGkHKKQhC+aobT8vYCWE9+OOa43IAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T03:51:31Z"
    mac: ENC[AES256_GCM,data:3r+BnFUUa3n410LloJvbQD+/izaC+xFcwZOItlhueBclJLuv/pkaggjcicXT+UiRcy49hrR5MwVrF2m6J/xnb8ytwFmTb6JifHhAeD+HcOiAOy5MOhKR+3cQeGjHq0Pf3uX4s6NFiLDyjXFE3s4qO8n8+UJgLs4C0+CgsEqe00o=,iv:yeZ6mxRzroYKsWyPrPBeAg8L/RFu4yuuddooDoebgYY=,tag:8TzXcEMAdyW9+VE1bJ7tcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
