# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:OoR0hu3UHVcCnpDBkpxDiom0dncmjzLUkVzdiHZCIpUh7r5Kqg==,iv:batzZfbq+Q9L8IVW+TziJxVKA2G8otyJC0NJnpCm92U=,tag:zKUhsG6oqIECNipdZdPeaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRWJ6Y1BwYzhHbVpiUU9Z
            SDMzTy84S3pOZWNUdnhNeUNaWEVZVitKMWdjCjUwd3ZnZDRkUm5DU0I1QTVzYnlY
            ZEZOTEhOK2FySS9sZGVITFpoK2pEMUUKLS0tIFBDZHR2ZTlUMkM5WkZrNVhiTVlQ
            aTBDOU9jcUZNNU8vdlV2bDBrczNQSkkKOtvb/lDPK0uJ4I5g3ml89MeShCXPpk65
            oIxGigAqC5l4GoTaV2nqHrs2wXiGehO/7Ko+WDmVvzg62frr4SsRKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-09T01:17:17Z"
    mac: ENC[AES256_GCM,data:8mojnrgJSDUhUBMvVEog6e6Um43PkhF0zuNJOd+LejLtm9rnW/zvWPO1nwR6iIvwMCYmqmoiFvs++4IrJ7Jw2px2VIjEsqibG/bpSegx01/V5G5JGlsBKBbKK1lWawMAvifb6TiWelf53UDIY283bRiiwfLI+azWuklTMZds2C4=,iv:676fqYsDwoo/iKXwcPhSzkNDV+PU9rAdT3jNY14kPNI=,tag:XSAYeSkwhkL3SYWYDG77vQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
