# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ZPSQ5seZvCpb+jEPRRF06KGSJV/BEZ1FC6EzSf8hwFA4++pLIA==,iv:BkeBtWyqqNAKQMnU/Qs/YuIEaQQYvgA7VlRwlA1gc90=,tag:pMnMfTdL7sBQaN9Idr7bTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUXBFMFdiKzVnYjRZZ2dm
            aWI4alAwdk5mNC8rY3lUdkhkUVBLT2pQd3lZClpEcVNNQWVXb1VFbkV2YmlRWHJN
            a0tXZjBSWGJZRmhPNmEzOEZSeEJJL3cKLS0tIFFNWndmZ1hGWHh0c2JlY1BUMDdn
            dVVmMncwcE5DRmhXNmMraDE5aTNhME0Kj9iKmfBXB2fMInwAZsssQuqlSa/zY8rX
            t2ZRZMgH7/7Q7XtsGLBbirc5fz5Yw0f8SdJoXwR/ddLzWE57f1iEkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-09T01:13:06Z"
    mac: ENC[AES256_GCM,data:8zd+GYxJhWYc63tyXMyNcKSR4yGyDkkfx3H612ZGUiwl1h1OjbJjzxOMR0JS6KuvJGQyFgOFYiCjMvBF+EEf8EAW7t8RjUPqiGHlfzO4FFgoW7JQjJqxdUZP5l5WepMSHzuGYVu1SgiIM0/IalfVImBoq7dQ5e2vMJAx4zTOgqY=,iv:YT4vRuUkUGhxKbPIpkz69e1vqch8iH3sT8FsQghX83w=,tag:AGpZ3r4zSroK21FqgdXtyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
