---
- name: Test for raspberry pi /proc/cpuinfo
  command: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
  register: grep_cpuinfo_raspberrypi
  failed_when: false
  changed_when: false

- name: Install iptable packages
  ansible.builtin.apt:
    name:
      - iptables
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_iptables
  retries: 5
  until: apt_install_iptables is success

- name: Flush iptables
  command: iptables -F
  register: flush_iptables
  failed_when: false
  changed_when: false

- name: Correct iptables version selected
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Correct ip6tables version selected
  community.general.alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy

- name: Test for raspberry pi /proc/device-tree/model
  command: grep -E "Raspberry Pi" /proc/device-tree/model
  register: grep_device_tree_model_raspberrypi
  failed_when: false
  changed_when: false

- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot

- name: Enable ARM 64 bit
  lineinfile:
    path: /boot/config.txt
    search_string: 'arm_64bit=1'
    insertafter: 'EOF'
    line: 'arm_64bit=1'
  notify: reboot
