apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:QiPFS76MXIzKBHVGWnnCHyAeK2bfvA7s0QuLUDBAQZUFveMQqi/v4C4Y2/SMOXWLvlvlIkiiAH57VoXe3tvaJwxZDpLCXHg/lts=,iv:Jkz95LnHqCbXYYOuRlBsm+7cBG9iJTF91SwxCVTXeI0=,tag:YAO/TypO49KX6tkQzv8MSg==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSk4wVnBhL3VlaGtDalpV
        SkI4WWg0ZWNxcENlN3I4azhRRmg4Rk53b1ZvCnVSMThxbFdNUVZ1bnRGZnRUVmdV
        Z1dQMjJucldrQWNkakx6QUFaNG5FTm8KLS0tIGo4SkVxTitxQ1NKeFNyL0dVK29Q
        d3EycmVaNnN4T3V4MWxlZDk3akU5MWsK21Q5890195JbkaJdGHlt1fRIdmAOOTa/
        91MrbHlk4sJ1zZgmkwRBnKPmA97sp7Ro2ZEX7NZYDhppZYzJrR/oTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T13:04:59Z"
  mac: ENC[AES256_GCM,data:ROjoRKcNTuSk8gTDKvKeooK15AXQaRoK4c/l8mlXsa8FVQ0a6l29bXS5fM1oRhidkwHQ1tY0R5il0ce5rM33pBbU+7dDtpcaJUBR78P6WM2OQRNfYm6/hniCJgNXdHmWg6/ccHpG41RMm9zI4saCkoDcg6ZjL1Ns3t5tnfErDJQ=,iv:fhE/uYs3GPN5BAXKyowQzJccwcocNNrHnKkI8cLEMSU=,tag:btigmmNujnxjIfboy7gzvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
