apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:dyOSLLdMlB955g1oqxrKAJIXj1dAkadmoQarTm+5vyILXOpVZ0CFxGabTnOsCWfHagV0563HS81CnHluxqpEjhC+y68cRCWyUYM=,iv:ZUwXA1ydT3Wl11QOOqn090Vp/RNrooFaLytJTkGkuOo=,tag:FEN1TVOtI55wcEjyK3GE0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveHI5V0xJNWpRVE9sRUZq
        NktRSXh5RE5Vb3VScEw5T2h4dE9Sdmp5czAwCkdyeTJLZXJBNjN4L1E4UitnS3U3
        U1kwQjV0cS8za3ZWbjlVamowNkZJRW8KLS0tIEYxRU5GQXdSemI5alB0NWlJSm1P
        RlJydml1Um9NZExBZ2xva2piRG5HWDgKBrbKB6xFEPP54wcKIBakrauRarr69M/9
        fsOkLVCZSWyPYMUIg5mh4DHVgYVHDGS4vsWeKMkWau0uOdpViOQyyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T16:53:42Z"
  mac: ENC[AES256_GCM,data:DwR/ipcwJpwCPaD7mxAl15I4oxAOYR2waN/FZ5z8a2vBPyFNoALMb16gEvU5REvv1Ho3g0R2QD91UhYpMeH82635cJOKPWI+r1dnAh7TBQZRkmv48pHbY5hjMS0WlfwJ8wK+tiogPv28jYHxk1eCEJCJPLHYWiipj5oVP80xWj8=,iv:LrCsDpcj6nMIijBT8rpMvwCULmg26GoL0rIEJPmuPT4=,tag:jCLa8nuVqmilS4iUNVfvsw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
