---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mazanoke
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      mazanoke:
        type: deployment
        replicas: 1
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        containers:
          main:
            image:
              repository: ghcr.io/civilblur/mazanoke
              tag: v1.1.6@sha256:92cc7474deb789af6549318563b7a9ee750131f9f7b297cc9c87ab67e656c22c
            env:
              TZ: ${TIMEZONE}
              ENVIRONMENT: "production"
            resources:
              requests:
                cpu: "10m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: 1Gi

    service:
      mazanoke:
        controller: mazanoke
        ports:
          http:
            port: 80

    route:
      main:
        hostnames:
          - "mazanoke.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: mazanoke
                port: http
    persistence:
      temporary:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /var/cache/nginx/
            subPath: client_temp
          - path: /var/log/nginx
          - path: /run
