apiVersion: v1
kind: Secret
metadata:
  name: cluster-gatus-secrets
  namespace: monitoring
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Ow++gno=,iv:VWK7RfMky7I6ZKMyC+QCSCEvUDhfvlOvGjK4vn49Q58=,tag:l5dvRTlh2CfCFZje0I4LXA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:i1KWvJ2m0xYeXesOZnsMAnBNjkjiDBnzK/AQxIuc4XTDYelqlg==,iv:j3sGVF+ATnd0I+u3xAZmNqHenoM/nT5UaVlbmM4iuQI=,tag:yeE94MH5T8iB+J5J+1q4ZQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Y1fC4LM=,iv:5DpD/XxX88nAV9qR88tTNmxj0qLkcuY9im+E3DQknRs=,tag:GoBlhszdzerVbehH2eXi6Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kr//6o+4NePVm+1b8QpSrloghyE3lMhkFxUb0nA=,iv:Lt8AJ11RX112TzN42Yjv+1zdXaZg5bGDVO9r/CBmaHc=,tag:jjBBsCyC7UZASvG+eWYJeQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sKF8kGOESBOXoYWTQty0VQ==,iv:r72zN1yQjh4sDR/grSevfGdg2nW9zOtZbkKe3qoBJnQ=,tag:TaDbAWsbYYxd1tGcCIkM/g==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:a4MV7wQ5zFqrwdcS5ZAgI0cLzqd76zp9Ae5GzDcU4W9dAXOVtye1Fyt+EmqH0pXcJaXpHFU66FdYMkXggIARyXHvDJ22UERZQtSexwpXYrT5/PW5XEWUoMvILPsdxgnx33pDGWhRBq0AaXFU+efh3ONhMJimNv2f8w==,iv:+Fe2dOxV2tjBY0SbOhRGeSSMSej6H9mo9uE+8yXXNuo=,tag:ADrx4Jf+oKSj6543lionUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNGZ4WmRFTVRtRUhTTXIw
        b1ZiaGdsOUdCNkhiRHpmdWVBdHJTdkU0S1ZjCklmQTh2anRZeUJ3MkhXQmVReXVt
        UktmbXFaN0hjYm15K2NoMGhxZ2xFVVEKLS0tIC9NTXVEd3RRVWFxVTNvUXpranZm
        bG9HSE9IMzM0U0JTMS9SdkZoSDR5MDAK9zsH0L2F7wquESCGQ5x3VX9lAhC/0rxZ
        ILH8eHaeSkDR1DDFWY41gdxNsK0CL3CIcrCbF3zoDon9j9aiemWq8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T22:45:52Z"
  mac: ENC[AES256_GCM,data:qDLm1FvltW202TCJNDCFMu/6965/Bde4cyz55M2EqBVfMcAPCXA4S2jtIH3yHMixYLrVbqXqbFKm8wlQJOn0GFyPyhL4gcSS4iqh1psrcVjCWjHr1Jpi5YNk08LLWJx+Q8eXQCgzmbW5TjKVOFUkd/8HXI3+vwrkY+znqN6M+hg=,iv:2JyfYDQz6YMRqBRzNKWyJQ+TqqRpjP974+UI5Z3gAVo=,tag:VaTqiny2CfH5UmMsYM8d0Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
