apiVersion: v1
kind: Secret
metadata:
  name: cluster-gatus-secrets
  namespace: monitoring
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:mO3H93I=,iv:hi0gRrOx1QNzMXuwEcTjMuGTjPRXTnqSpOTZZBnk/UQ=,tag:aD7os8KZ1n7EbxF7jvRCeg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:GJJcs4fvv/clv3ihvn5gcpJGrybJVMd9qbNTOTgNnQME4QonhQ==,iv:2HDSAn+kiwmi4TWvOZcsksEvrtS7R9Q+ZE5RIayJ5d4=,tag:mZbsLhJo7PDiWQmNHoB5Ww==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:o0gX97c=,iv:Lc0pSSQCMKs2LuUN82Cm1MLU1tXq1Lc4eQ/FMqxikcg=,tag:Cz7ay+eO1iXZtnsKYmW3CQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:2kGjszLfsXiq2/1NRrQxeoj+svmNKZGuXXM5o4Q=,iv:oNZLRTFlDHjLJ9W1y3gubmz9EJSjQE2dXHAbATkCVFI=,tag:ykelwg2tt9Pd/X4q/RDkng==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:4qzKSuqkHcmoM8P7ndDrGw==,iv:xvHEJU+5oZa6ZANO46Bsj2hI7vg8vSKNQCytx88M0oQ=,tag:5h4ZtNiGjPK+1/xjKGM+4Q==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNFhHZ2FKaGlvU05LVXFt
        TDRDTDhaM0EzYkovWnQrRVFuMDNBT0o5dlUwCm9GeU9xNWhUR2J6RFV2SUdwWFR0
        YnZib0V5VTM2aTNaNkJuczMrTm9HS1UKLS0tIGJJdHNiMThmSTF2RCt3ZEd3Z2xX
        NmRaZGlyZld6MjhFTjlZaGdRS2Y0MmMKSZ2rOxPw5Gzaz8D+4RP980IUGjr4PyJJ
        Lquf2cYcS14Pzxjk7PHPR9rIv69ENtAbCQZppQn40K60HM69WXN8nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T00:09:12Z"
  mac: ENC[AES256_GCM,data:j6jWTNz2GopN6usyCsKaqQPOsq0Ri0YfBFIUGipzFZuJPC1XM3tgLBfc+Q0k5yAEcNmxdKTXTkIe1Bu2M+psKj8r9rQP0Z1xyGzNh9Eccj343TnYd18wkEylr4gGptkrkhuJcG/K/GHj/78TT0YD9c8OLxGT+NWzCVyicWd7q20=,iv:rUpY1froYXeY7qYXX5vIiYyopTNtH0oXuesj2ePlAqo=,tag:konLyQ9uJipd2CFlg4bVHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
