apiVersion: v1
kind: Secret
metadata:
  name: cluster-gatus-secrets
  namespace: monitoring
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZOonuOo=,iv:eUP+90YS3R2ZpabqXcK/L90oV7FhZiOHkBbgaBdCwD4=,tag:Pg1eeAbNVa3ihtaPPxuDGA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HNb0GEjgvUjUYOucB8Xs8tfmskbkky8khM2WnZmtfwJJbPodKw==,iv:YjD7MxfNn0q5vNCHmGSF/TZB4oIgi9IutBijyDrb69k=,tag:wRSZSGRR/gNHeOShBl+Ieg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:aripTCI=,iv:93adoOjs6BWUZrmuf02bBw4uvNHZ1/gV8o+L/I5xapw=,tag:CM/RDV19D/fJfRL6I7k4yQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:I4p73TzLyYS9rFlUOn6A0rRSXkultEsVbaLU4p0=,iv:T0dsBWeDfs3IJyeyns5nvuRudqcuAhUNdqJPm/s/4gw=,tag:/uBwcuhvAb0XjG+9Af28Og==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:FjCFr9TKhu16eOqXwu3COQ==,iv:jiJQlfEa06ydaBK3DA31HDBwv/3bB56eY8K8N3AMBDE=,tag:IWInkK9L8P09Q/rMuyigSw==,type:str]
sops:
  age:
    - recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY2xWRHZoeXpzK2s5dVhv
        bDhFRDkzYmplR05lZm9haDdjSGZnR1haQ2lzClBMVXhiY3YwVUFuemZ4M0V2aWFq
        K2FncVhJVEx3aFpaTVJlUmFiVXo3TEkKLS0tIHZKNlN0MkZwdGF2TW1OSFR5eWs2
        YVlmK29oUTR3UGtOQ2JUbUJiWXlOTGMK2Z3L+t34N8g/sU6e4xsoCCiyMJkIhm7a
        hauUkIcAKlb+vgUCqFsJDJTDk1ZDldcAb0Ylht8OIx5X63u8Zs5VoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T23:40:55Z"
  mac: ENC[AES256_GCM,data:e4/Xv3AW4hdzAqpyUgiDfJjQfaz8vc63h3Ga0FJvindTtc5ssU8NagBut/q4YoZmgwoqFYPxOFKVtyX+eJo38SUcv25b9md6+RsnLK+KyyBtICdO8CR4vgyYhfMIZ98DndPl9p1X/ExSfKaxFfPC35KrsN4V4yqZJ9dUq/LWnkg=,iv:ZY0FBZGBo6TbMmlQrqEofmmuRQdGhcCO1lcfEE2cOPw=,tag:ValC3JFYg9aLIZmoT3Z8xw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
