---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app chrome
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          automountServiceAccountToken: false
          runtimeClassName: nvidia
          securityContext:
            fsGroup: 101
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: ghcr.io/christfriedbalizou/chrome
              tag: 148.0.7778.215@sha256:9c091a84e95836e8087cf9e50a537b4c9da8725795c849b2fd5cf7dafcb0ddca
            env:
              PUID: 1024
              PGID: 101
              TZ: ${TIMEZONE}
              AUTO_GPU: "true"
              HARDEN_DESKTOP: "true"
              NVIDIA_DRIVER_CAPABILITIES: compute,video,graphics,utility
              NVIDIA_VISIBLE_DEVICES: all
              PIXELFLUX_WAYLAND: "false"
              SELKIES_ENABLE_SHARING: "false|locked"
              SELKIES_MANUAL_WIDTH: "1920"
              SELKIES_MANUAL_HEIGHT: "1080"
              START_DOCKER: "false"
              TITLE: Chrome
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["NET_RAW"]
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 120
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 3Gi
                "nvidia.com/gpu.shared": 1
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "Tools"
          hajimari.io/icon: "simple-icons:googlechrome"
        hosts:
          - host: chrome.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: nfs
        server: ${NFS_SERVER_APPS}
        path: /volume1/apps/default
        advancedMounts:
          chrome:
            app:
              - subPath: chrome
                path: /config
      shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
          - path: /dev/shm
