---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app it-tools
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  components:
    - ../../../../components/ext-auth
    - ../../../../components/gatus/protected
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./kubernetes/apps/devtools/it-tools/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: it-tools
  targetNamespace: devtools
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: it-tools
      namespace: devtools
  interval: 30m
  retryInterval: 1m
  timeout: 3m
