---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-jericho
spec:
  storageClassName: ${APP}-jericho
  volumeName: ${APP}-jericho
  accessModes:
    - ${JERICHO_ACCESS_MODE:=ReadWriteMany}
  resources:
    requests:
      storage: ${JERICHO_CAPACITY:=1Mi}
