apiVersion: v1
kind: Secret
metadata:
  name: cluster-open-webui-secrets
  namespace: ai
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:pat1I0OsFh6AS5fA/mTnrsfMd8fBvEy/hPm6gtsLcc57TvYuGSBJ/wyomH1FMSV9LBHiRlS8hB4xBZN2Yv8Yh6xTwz0EvSQRC+3ZK2gWI2jGdfF8zyA73jt+NID4carBpYZXxE7L7G6ZhsnYnkaUFf0ZEDlctQd46N0nk6pmAfM11FouV9R1hRTIieQp1A==,iv:b5wy7/lDJQN3Bp7Jy3IGle37ZHmU870MgCk1quE9Q+k=,tag:0iA9Im2vNsa1XakhOr8PVQ==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4+Q+AKqvKSZ1BTknZScXFZpT354mL7RUcfpNdspaW0ipU+FOMTje/UnvCAnpxvvue4vqkPWoBazbHBM6EwMqvA==,iv:owfi/v9/S6OxImJRonQJ+A4wuV22pWiEtH5GqzJ8M4A=,tag:xaUl2MZ1XX2uXTsa9GKTQQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:dh+x4j1/rIU4YVzoIeysGiPQnDio63jeIEhLpVIrVJgc05cgVh+Mse4x7QgLyDHGgEQI5Qhzc7/UWd+RC1V/Xg==,iv:NB0sEHX7DcyvavP7VzXrcBX7tZADFoRZvBdos9TwPM8=,tag:sAgTG/cKnK4epIOnTJCq8w==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:EaPT9kGV1QFBNA==,iv:JXwRjmo9wTnWl4uG25PxxS9J9Wwq0dirPXjvGSXcmTo=,tag:geBwHh63WbUGOgu8WZ2akQ==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:4xrdzEmN5LYBPlwtH7cSwM8KkCj2ykLZ4wIZaYeuHQB3lg/u/oGqhs91lGAttXJm936ak0ijvjiAtzo6zGS8cw==,iv:i0UU7VAXv9SXAbumvlcXI/UYcUFWlgXAl5VoY6mhhpE=,tag:1ANOOqhp9cXwXgbXLGrGfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdVBOTTJTWUFCKzVYOWM2
        M2hTa2RsSURnZmZuWEJhNEVEaGZnUHpQWkg4ClBTWmt4cTd1MzEwL2FHVTBWSkFh
        a3lzZ1RpL3lIV2FrbERvKzB6Z1dZYncKLS0tIGwzckdKdmVqMjZZZktKUjJxbjlY
        QUVVc0lkWUlkOXRpdUFGbFVwa3VvSUEKEq3Z4g20gicS/1pU6Qk2JPqoEVUUOaA6
        eTHkTWWw+9eab2poYzh72yFdZVoiutEXYzs4o557Es53yhzxnWV9+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:42:47Z"
  mac: ENC[AES256_GCM,data:mZKY+UI9MnRR3ZCSRE+20yIRLVPae4saIsNReyB/KCzvXS2BvT9d6lw9dCLQKGVDwhs0mlVEz8buYcXv/NR44qP0hBu/nSfIYqiFytfBrnX66O2fBMgKV/B7gjrH4wPGDRt1oBI0mAD4rFMtDSmfri4ONGp3v8HJw1aHqtc395o=,iv:3jJwf/8OoTCEXtn13Al79P/kWPT6/BYEJDxSOPc8bKs=,tag:4uE/CIQf6vos9G/qEq/VHw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
