apiVersion: v1
kind: Secret
metadata:
  name: cluster-open-webui-secrets
  namespace: ai
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:OoOwV9CFlwY1V+V7Tw8R5XjCa8C23ph2rYjJogW/U/+o/HtlZan6qa8cAqDzlck3CH1oX8gAiWepdvI00x3KBnzaZJBn0hDU5WS5C9XKGQLTWd5ReRPaqt2HQ3sTKZIW7bA8vHCppMiohD8OzWDKfZw7rP4RRh0Iz6yCuGLymONqmAwJFcWKMY8tzlw3ZQ==,iv:Taf0xyAXqKiqX2yp9ASqLE+Zppz5FJKaso0xsuH4PoA=,tag:8LdePlujGtobZqIxpkvFLA==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:2LsOJyLDzuIHfuYWnxf1itmALxO+IvT9Tjo96PCtzemXkNBjsFTkfH4hc7nwhoZr19L7FJR6J9B6KO8LrHGawQ==,iv:RbzrCDlc/9Z28lpLuW0saVDZUCcimpn+ZBMFkacrpqE=,tag:J6Mz5228NWN8cTKnzl37Mw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:QbPydsP02Rj2E9jM7dysXMAOFhfldKoyCyZnvnsPCa/AXNxpKfwsRuh3WmdXnWZbusPiHGlSpssJHzbpiJT2Ag==,iv:StFARPSz7bIlKT14HPVKbN4DX3XcGPgULYpUnzxYd9A=,tag:dYuXy+UQ59zmZ/uCrCI2CA==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:8OGEel64gWKrkg==,iv:u8wXq6jr+qB/wj8beG0ZNT6fm5IEwumJhLD9W+UgTbw=,tag:UVi2futJgZZswH5Z50yCkA==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:VSIawtUcPtsXz0+BXrueRSDGgg9v70axU5euwzac78+WF9AzE8T2eRg1CecpnmoqzYw3Dit8vVfwtMjhimHxNg==,iv:ButaEUh/hkc52/C/0CHHuoZTrcnNu3fXLC8TCEGknuc=,tag:VA+Bs/cMpvRuM2spjREspA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdmhpWkVmUXdDMUpjWUNI
        SkQ4aUFzREZ5RWJxWU5aY1k0aUJJKzVDNVRNCnF0VFlMY0tnN0lOVHlMV1JBUHYw
        d0hWSmJ0NU1ndjVySUpyRDluR29HT1EKLS0tIFQ2ZGorU3RaT2Z4MVNMRWQ5eTdY
        MG1LTXROVHVnM25PSGFqcmUyU1lJWnMKJeIsQjVspYCIGJsPho5A3C6GuJxpLCMS
        H1HhNNNIValo2Xt+uZj6Ap/EMA7I/SqgTrkbGPhcWP0gGOgMvO1tWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:17:19Z"
  mac: ENC[AES256_GCM,data:5bY0tWw3CijwdYut8XKbWSBtakE2jNEdUAdYCiSJnIcWGBJtWygfHa2Qu7Vxy//4pEj2iRUI5HT1JEzweZ9vg0ao2jdKOKR4O6jJfGIaw6Xo13RzIIwnpzwXITMzIn3nZRE9Cjm8Vxiz1IDlBo7YsbRjN3XymcvByWY5GezZS78=,iv:LFzEX2SYICaRE4jpNcbp+VoU1BSYcVgOpRGT/ox7X38=,tag:oNxxxDzhosf80p6c8RzN5Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
