apiVersion: v1
kind: Secret
metadata:
  name: cluster-open-webui-secrets
  namespace: ai
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:LjSKeKgTGveLYExr2lRUtqyhwPSKBYa+VER3DaMCaazgGjF+g9TtUK1YPXMofmqPfdTltTvCpy3HHwXyPn69vqiPHUosXfvA5to7VVpNoBVzAH/E6aUQ4Ixbl9noUcEB4zs8udl4lwkERjyL80p3MvRRN39EsRu1GPXX8qLVOnjGlbq5o48Xki11o8NVbQ==,iv:ackcg34MZj3jVkrPclnpv7WWNv9JU3WfKfTh4+FtsSQ=,tag:+xv89S7mjKn2hscbOhMK/w==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ARwIpDPdmKctmUhTN54kP+rYjdVvy9dPlsvWNWEbgznnd1S+Y1eMpH1LTtWOfFfklVmfwbHIHk/eMLNolxjNqw==,iv:t/tGcB4ujgoJvvadLzrSu2Yu0EA2XXzIlECL8VMr1Pk=,tag:S32hY66txQ1MAqBuDyRpVA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:vGEpAcHnQk5WjTVU/w7CJFyfX9RmrIDoArL3/IiFDM0mLKiVsz//gy0V1/dTFDjW06Cr+eYjjWjcM3HvvKhn1Q==,iv:Hr+I4uoDtk65Pfcqr8nHoHzwIPlXI0KZijcM/l5Vn1A=,tag:zEDLF+kcpPOnfIpNLv3x5g==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:yPUjcOSzTtfPMg==,iv:eAbEAfVHBoAtQMWMJ1uQTYh4FiQJzq60JvlF4ktQ2ao=,tag:Gr1z1lnjLz130GwFvJT3PA==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:TzbHt95qBg0PaCGuH1ri8F3QEo5YeBwEmXUCVxVIVVlFpXInYQpmxSx2Z+yUH/c4Ql5U7LKre/vo9nGLmXv73w==,iv:m4VDzlVCw37tIEi+73TEhMrAujlx4kMPKRNPF1mYNRw=,tag:+A855q5vbV7/RIziEX0kCQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS2duYnNGb2VkTkZXTE1x
        Qkx4VmVyWkZIdlJBV2RCR0lMRDNNMHIvS1FJCjBCOWdJWG03VnhaNzV0c01zbFdP
        ZFkxM1Awa0JvSWVHcU1NSUdxMzJ2VGsKLS0tIGNDS2dxb21vU3l6Z2lrNmtDd0Vo
        Tll0N1c5bFp6NllGU1U0bDJaWUs2dW8KMNbsgmf74qqzehXkFFANbYZDg5Ulem2k
        4kOsrlUf68TI6GftRJok92sNnBSvFI+S5GETuFynjP0w9pBoITTsyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T20:31:13Z"
  mac: ENC[AES256_GCM,data:ZNk0Vy4RBEwGi0KXMEDmbyzz6viIhlCNU36Ep9hmWwakI2kn5zPLXwvbYX6yO7sgCvOSklYZ+d+SnN8CmUHTVtj7xcwupYdHdU0CAI+I0s+EB7Pqm6r3OeqBLdNwIVzxjsDw2DtxXbJBuYV/P77ocvUY+afaFDFVfa2+MZ5RgXw=,iv:vqr4A3Jrlu78g2q4rbjMZiIowE/mnNXjTkotL11T6KI=,tag:p8JhKJHPVttXKHDZ30miKw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
