---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devtools
resources:
  - ./helmrelease.yaml
  - ./rbac.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: forgejo-runner-config
    files:
      - ./config/runner.yaml
      - ./config/podspec-default.yaml
      - ./config/podspec-dind.yaml
generatorOptions:
  disableNameSuffixHash: true
