apiVersion: v1
kind: Secret
metadata:
  name: cluster-forgejo-runner-secrets
  namespace: devtools
stringData:
  token: ENC[AES256_GCM,data:830hT3k5X9WW2bVgZK23WYTwp7eWxJI1OYjaeDYkZJnxGEt5MI72ZA==,iv:jzK2xQlfvb9ZFHg8S0cQ/aHDrpnqXlKIY11ysz65WpE=,tag:57FyRv8Z6QKmFACeneBuhA==,type:str]
  uuid: ENC[AES256_GCM,data:tkwdzmmp4Ht5yf9TyP7y+KNKUngxm+03YedS37BJyDXRJq6N,iv:6otB0ClHp1qYmC5RkYh0Riwi+zfHW4DKbGRD7c8JL7g=,tag:1mwzPsM50gMvp73cwK5saA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIam1qRVRGcVpJYVdPTDlD
        Wnhuam04T3FDVFdReDVaY2ZXK0NFcS80dVFRCnY4RDBHZ1JSaytITm1DK25iWkNM
        dEdOV1VXZklFYVJRUWQ1MU9RTkFoRTAKLS0tIG03djgrdVBnc3FNNnREa0NHbENn
        L1FUMkdsS0tva2djanlCMEIvQ3VoeXMKZssbThSHen9Vz2TK44GOy1M09ujfeLto
        I7YYK4GF+ykmHE0qZXnQJy4gEvEMm+I9DIn+LKU//Ew6TlPdC4K4tw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T20:58:19Z"
  mac: ENC[AES256_GCM,data:cjAV3FfHaPTmCad29eNbKU6/XlVqy2/Gog/0j5q4IfM3vjphN9LY/1dTMvrHA0glqc5ijmKIgBn+1LbCRIlFTG6qYsjIzVrO15vMNTy1d+owLQXeHUZqnh7+uhiq0XIm5UbUcS7BrI9UpEjcN+uDDILFQKT1ZEfnpw9mFPqCd/I=,iv:ClgPqhO2HovgOrApZjUhbZnsSG0itR6oUXT4eD54sHM=,tag:lkgxy0DMQxFSOrlP+xLwZQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
