apiVersion: v1
kind: Secret
metadata:
  name: cluster-forgejo-runner-secrets
  namespace: devtools
stringData:
  token: ENC[AES256_GCM,data:cBUHzP5Z6KZt6pD4Y9wLwvz0Og4EYR+2V0PISbmtUA==,iv:jFfZTIk0k57qvZvYILhhhsQI5+mSdyvYdbVVbBtV4JQ=,tag:TVj8NmtCGPs4PQRQoXi08Q==,type:str]
  uuid: ENC[AES256_GCM,data:Xw9/FQ2+zIWFkEun802dfU0EXe8wKlRHZoWdtk7Fc83+UkjB,iv:VmxXXws6fY4WG16wH9BSGUyOEAhR0bfhBazUdQfobhg=,tag:mzIhJj2zYtMdamzlzVf04A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd3dhVVg5bU1Wcmpwcld4
        eUhzQ1lJbVNqcXBWOHhaRVlKZ3lPbEFIYlVNCjRTOVpSNVg5WjVWNkJVNEtVRGZs
        MVNQcHhsZG9mS1NOVElrbFJ4cTQ1WTQKLS0tIEFRa2hQWVdPejhBb1cyS0tkRUw2
        N1VmVnlCaWpxRTFJQnFNRFN4eG1pWjQKsdp0YhGdcM2qn9SDbYORfqXuX/oEap1J
        RA9Od/rwpHrsIp1ERUqh9hK4KqTDdCuUuPY82WyieYGEgIlH+6ni7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T08:17:20Z"
  mac: ENC[AES256_GCM,data:+yNMdeR6JPJsMX0fbSC8aQJx3AMyw454MDYfIpY7hT/XJzyPLTgX0NjvemR4vEnNkt9SKZ8H3gpINNoK9+iH7kGscBhpaiBaDZ8IFm4d4am9TWnGI/kRD6jckABxiAIo3vSguL+v67kqjRQETBenR95Qp3PXjSaD2YFAleSXOwo=,iv:TqnH3tn1zyIR2g5Z7cGUgJG4dksqRczQIRH0f9KxXQE=,tag:5VJyykAGfFpG9xRF6/7Vrw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
