apiVersion: v1
kind: Secret
metadata:
  name: cluster-forgejo-runner-secrets
  namespace: devtools
stringData:
  token: ENC[AES256_GCM,data:VIm6oCYxd9cxJzz6wzIQz25i0EEaAfTjlFJ6/IqtwQ==,iv:8rE219+IJ8e9bZ9lUdKhElXluc9fSaaPgB1wIwSa1qk=,tag:Sp5A0ncPGAm018eHzW3mlw==,type:str]
  uuid: ENC[AES256_GCM,data:SemSTrapfUiuuow881PpPvkGIAxvz5ImK4D0/nV3HXTq/ghO,iv:7En2+w8Wpg+Us4Hbw8wOoP/6oO7tONy29srWKmdHV8A=,tag:OXK47Av2K+rKA4Rnl+4A/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlLy8wa25LM004S3MzeE5h
        VDE0c0U1Z01ybSs4RjJDNXZIUTdEYjM4dEIwCmdtSW04LzVYT0RJQnRObzNhWDZ6
        dHhkNFZLcmtBeDZ4TTVxdkpVWDZtOU0KLS0tIDdOY0dyVHhQMmZTS3ZRR2ZnOGZh
        amlyNEpONXFweXZuc2FHVXpMRXVCbFUKZUWtQ6g6iEJnXj5T7WK/jja0V5wGIG+0
        BECohV2hJ9G+nb/NOmOkUwxDvoy01gbsRjNYHnfi73tzkPNBgdhLmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1undkver5jqs36xk2djfjemx8hyq4zl4wkfkrq3yx36zmedmduvkqkgs0rg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T22:01:00Z"
  mac: ENC[AES256_GCM,data:D8OaYB4VgKfjpBdIFxwE9zl961d46rjJnpUCTbCX9ocA6zU+IOrDIZp4/RqzqrO3Yx73U5cYSzcjSwRcJkMCPHEZPNOytat6Mc4TOrK6wu31L4dYb2FluRn5w+zqTovcWUUc3i8Qhduhp9a70IhnT5VUMeEjLxWQ1RhOsNX4Xx8=,iv:44nIjc+dNBiziry4KjvQGAn84gTR4QkoCyu2Mhce4xQ=,tag:hueFW55mYiHxUcayCH+70g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
